### ISSUE TITLE
Clicking "Recent Items" doesn't empty section.

### ISSUE THREAD

**Issue by phyber** [AdiAddons/AdiBags#100]
As the title says, clicking on the "Recent Items" doesn't move them to their proper sections.
No Lua errors occur when this happens and the UI must be reloaded to have the items go to their appropriate section.

This doesn't happen all of the time, but it happens enough to be an annoyance.

**Comment by phyber** [comment]
Furthermore, sometimes when clocking "Recent Items" it will move some items to their sections while others stay in the "Recent Items" section. Again, there are no Lua errors when this happens.

**Comment by Industrial** [comment]
This is old. Doesn't happen now.
