### ISSUE TITLE
Shouldn't print deprecation warning in Wrath Classic if BetterBags doesn't support Wrath Classic yet

### ISSUE THREAD

**Issue by fryguy1013** [AdiAddons/AdiBags#1001]
### Addon Version

1.10.24

### World of Warcraft Version

Wrath

### Describe the bug

I recently updated my addons and opened my Wrath of the Lich client and got a message telling me to uninstall AdiBags and replace with BetterBags. But the addon page for BetterBags claims to not support Wrath of the Lich King Classic yet.

### Steps to reproduce

1. Install the latest version of AdiBags with CurseForge
2. Log in
3. Notice the alert telling you to uninstall AdiBags and install BetterBags

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
It does -- that's a misprint on the page. BetterBags works on Wrath.
