### ISSUE TITLE
Adibags completely broken in 10.2.6 retail

### ISSUE THREAD

**Issue by kcoderhere** [AdiAddons/AdiBags#1004]
### Addon Version

v1.10.24

### World of Warcraft Version

Retail

### Describe the bug

As a result of the 10.2.6 update: 

When attempting to open the bags, I get this LUA error and you can't open your inventory at all.

Date: 2024-03-19 17:11:54
ID: -1
Error occured in: Global
Count: 1
Message: Interface/AddOns/AdiBags/core/Utility.lua line 355:
   Tried to build a section key with no name. Report this to github.com/AdiAddons/AdiBags/issues please!
Debug:
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119:
      Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108
Locals:
(*temporary) = 0.011000
(*temporary) = <function> defined =[C]:-1

### Steps to reproduce

Open your backpack

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by SpareSimian** [comment]
Confirmed. Errant object is Tidespray Linen Bandage which results in an empty ("", not nil) section name in category Equipment. 
https://www.wowhead.com/item=158381/tidespray-linen-bandage

**Comment by SpareSimian** [comment]
Two more are Fire Bomb and Winter Veil Cookie.

**Comment by SpareSimian** [comment]
These items have an equipSlot value of "INVTYPE_NON_EQUIP_IGNORE". This seems to let the bags open properly:

```
diff --git a/AdiBags/core/DefaultFilters.lua b/AdiBags/core/DefaultFilters.lua
index 7e8a608..d579e7b 100644
--- a/AdiBags/core/DefaultFilters.lua
+++ b/AdiBags/core/DefaultFilters.lua
@@ -254,7 +254,11 @@ function addon:SetupDefaultFilters()
 				if rule == 'category' then
 					category = equipCategories[equipSlot] or _G[equipSlot]
 				elseif rule == 'slot' then
-					category = _G[equipSlot]
+					if "INVTYPE_NON_EQUIP_IGNORE" == equipSlot then
+						category = MISCELLANEOUS
+					else
+						category = _G[equipSlot]
+					end
 				end
 				if category == ARMOR and self.db.profile.armorTypes and slotData.subclass then
 					category = slotData.subclass
```

**Comment by SpareSimian** [comment]
It seems like a lot of items that were consumables (food, potions, bombs) are now treated as equipment, putting them all in the Miscellaneous section. Smells like a Blizzard bug.

**Comment by Wevah** [comment]
Yeah, and it's making AdiBags slap an item level on them as well.

**Comment by Cidan** [comment]
Hi everyone,

I pushed a patch earlier that stops the bag from crashing, but it does feel like a Blizzard bug as @SpareSimian noted. 10.2.6 is riddled with bugs left and right, and Blizzard did not give us a PTR to prepare. Sit tight while this is worked on.

**Comment by Cidan** [comment]
p.s. @SpareSimian I was also able to trigger the bug with 192955, a gem. It doesn't seem to be specifically tied to consumable. I'll dig more here.

**Comment by SpareSimian** [comment]
I installed BetterBags, which doesn't seem to be affected by this. I wonder what's different? 

(The lack of the N button in BB to clear the new items flag is frustrating. I usually hit that right after looting and reviewing what I got. I usually loot a bunch of things at the mission table, then go to the mailbox to redistribute things to alts, and now feel like I have to wait for that flag to clear before I can see what needs to go to who. I also haven't figured out how to drag items into categories. I click and hold an item, drag it to a category title, click again, nothing happens.)

**Comment by Cidan** [comment]
@SpareSimian right click the bag icon on the top left to clear new items and sort.

**Comment by rodalpho** [comment]
Is this bug going to be fixed? BetterBags really isn't quite ready for prime time, IMO.

**Comment by Talyrius** [comment]
The initial errors have been resolved. Please consolidate further equipment sorting discussion to #1007.
