### ISSUE TITLE
Adibags+AdibagsConsolePort+AdibagsPawn

### ISSUE THREAD

**Issue by Tenuiis** [AdiAddons/AdiBags#1006]
### Addon Version

10.2.6

### World of Warcraft Version

Retail

### Describe the bug

При добавлении аддона AdibagsPawn инвентарь больше не работает

Код ошибки при открытии инвентаря:
18x AdiBags/core/Hooks.lua:78: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@AdiBags/core/Hooks.lua"]:78: in function `GetContainerFrame'
[string "@AdiBags/core/Hooks.lua"]:161: in function <AdiBags/core/Hooks.lua:156>
[string "=(tail call)"]: ?
[string "TOGGLEBAG3"]:1: in function <[string "TOGGLEBAG3"]:1>

Locals:
self = <table> {
 AcquireItemButton = <function> defined @AdiBags/widgets/ItemButton.lua:156
 FAMILY_TAGS = <table> {
 }
 UpdateFilters = <function> defined @AdiBags/core/Filters.lua:83
 SecureHook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @AdiBags/core/Core.lua:437
 ConfigChanged = <function> defined @AdiBags/core/Core.lua:357
 GetSlotId = <function> defined @AdiBags/core/Utility.lua:57
 Filter = <function> defined @AdiBags/core/Filters.lua:144
 IsEnabled = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:451
 Reconfigure = <function> defined @AdiBags/core/Core.lua:190
 SetupTooltip = <function> defined @AdiBags/core/Utility.lua:114
 RegisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @AdiBags/core/Utility.lua:188
 CreateFont = <function> defined @AdiBags/core/Fonts.lua:122
 filterProto = <table> {
 }
 db = <table> {
 }
 OpenOptions = <function> defined @AdiBags/config/Options.lua:671
 SetEnabledState = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:424
 Hook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:274
 IterateBags = <function> defined @AdiBags/core/Bags.lua:183
 OnEnable = <function> defined @AdiBags/core/Core.lua:122
 HookBagFrameCreation = <function> defined @AdiBags/core/Bags.lua:306
 NewBag = <function> defined @AdiBags/core/Bags.lua:150
 GetClass = <function> defined @AdiBags/core/OO.lua:129
 RegisterFilter = <function> defined @AdiBags/core/Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:235
 InitializeFilters = <function> defined @AdiBags/core/Filters.lua:64
 IterateFilters = <function> defined @AdiBags/core/Filters.lua:116
 ReagentBankUpdated = <function> defined @AdiBags/core/Core.lua:348
 CreateBagSlotPanel = <function> defined @AdiBags/widgets/BagSlots.lua:437
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @AdiBags/core/Hooks.lua:137
 ToggleAllBags = <function> defined @AdiBags/core/Hooks.lua:86
 OnProfileChanged = <function> defined @AdiBags/core/Core.lua:198
 GetName = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:279
 name = "AdiBags"
 OpenBackpack = <function> defined @AdiBags/core/Hooks.lua:168
 LayoutBags = <function> defined @AdiBags/core/Layout.lua:102
 Disable = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:314
 SetGlobalLock = <function> defined @AdiBags/core/Core.lua:405
 Unhook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:418
 Print = <function> defined @AdiBags/libs/AceConsole-3.0/AceConsole-3.0.lua:54
 OpenAllBags = <function> defined @AdiBags/core/Hooks.lua:109
 L = <table> {
 }
 safecall = <function> defined @AdiBags/core/Utility.lua:81
 Debug = <function> defined @AdiBags/core/Core.lua:61
 CreateAnchorWidget = <function> defined @AdiBags/widgets/AnchorWidget.lua:37
 ITEM_SIZE = 37
 DEFAULT_SETTINGS = <table> {
 }
 CreateBagAnchorWidget = <function> defined @AdiBags/widgets/AnchorWidget.lua:218
 FAMILY_ICONS = <table> {
 }
 UnregisterEvent = <function> defined @

### Steps to reproduce

1. Отключал последовательно все связанные аддоны.
2. Помогает только чистая установка аддона Adibags+AdibagsConsolePort, без AdibagsPawn

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
AdiBags will get no new features or integration fixes outside of the base addon.
