### ISSUE TITLE
Login/Reload Exception with ACE-Lib - bad argument #1 - same exception as in Betterbags

### ISSUE THREAD

**Issue by tsracing** [AdiAddons/AdiBags#1009]
### Addon Version

1.10.26

### World of Warcraft Version

Retail

### Describe the bug

Message: bad argument #1 to '?' (outside of expected range -2147483648 to 2147483647 - Usage: local debugLevel = C_Debug.FrameXMLDebug([newDebugLevel]))
Time: Thu May  2 08:02:07 2024
Count: 1
Stack: bad argument #1 to '?' (outside of expected range -2147483648 to 2147483647 - Usage: local debugLevel = C_Debug.FrameXMLDebug([newDebugLevel]))
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: (*temporary) = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:57

### Steps to reproduce

login/screen reload

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
This isn't an AdiBags error.
