### ISSUE TITLE
Lua Lua, hey baby, we gotta bug. Yeah, yeah, yeah, yeah

### ISSUE THREAD

**Issue by Siofral** [AdiAddons/AdiBags#101]
Date: 2016-08-20 07:12:28
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\ContainerFrame.lua line 1008:
   AdiBagsSection7:SetPoint(): AdiBagsSection5 is dependent on this
Debug:
   [C]: SetPoint()
   AdiBags\widgets\ContainerFrame.lua:1008: LayoutSections()
   AdiBags\widgets\ContainerFrame.lua:1064:
      AdiBags\widgets\ContainerFrame.lua:1040
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155
   [string "safecall Dispatcher[2]"]:4:
      [string "safecall Dispatcher[2]"]:4
   [C]: ?
   [string "safecall Dispatcher[2]"]:13: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: SendMessage()
   AdiBags\core\Core.lua:445: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
   (tail call): ?
Locals:
None
AddOns:
  Zoom, v
  Swatter, v7.0.5662 (TasmanianThylacine)
  NPCScan, v7.0.3.7
  NPCScanOverlay, v7.0.3.4
  NPCScanOverlayBroker, v1.2.6
  Ace3, v
  AdiBags, vv1.9.0-8-gd7305d3
  AdiBagsConfig, vv1.9.0-8-gd7305d3
  Altoholic, vr171
  Armory, vv13.0.1
  ArmoryGuildBank, vv13.0.1
  AskMrRobot, v39
  AucAdvanced, v7.0.5662 (TasmanianThylacine)
  AucFilterBasic, v7.0.5662 (TasmanianThylacine)
  AucFilterOutlier, v7.0.5662.5459(/embedded)
  AucMatchUndercut, v7.0.5662.5585(/embedded)
  AucScanData, v7.0.5662 (TasmanianThylacine)
  AucStatHistogram, v7.0.5662 (TasmanianThylacine)
  AucStatiLevel, v7.0.5662 (TasmanianThylacine)
  AucStatPurchased, v7.0.5662 (TasmanianThylacine)
  AucStatSales, v7.0.5662.5598(/embedded)
  AucStatSimple, v7.0.5662 (TasmanianThylacine)
  AucStatStdDev, v7.0.5662 (TasmanianThylacine)
  AucStatWOWEcon, v7.0.5662.5613(/embedded)
  AucUtilAHWindowControl, v7.0.5662.5575(/embedded)
  AucUtilAppraiser, v7.0.5662.5653(/embedded)
  AucUtilAskPrice, v7.0.5662.5599(/embedded)
  AucUtilAutoMagic, v7.0.5662.5587(/embedded)
  AucUtilCompactUI, v7.0.5662.5629(/embedded)
  AucUtilEasyBuyout, v7.0.5662.5576(/embedded)
  AucUtilFixAH, v7.0.5662 (TasmanianThylacine)
  AucUtilItemSuggest, v7.0.5662.5651(/embedded)
  AucUtilPriceLevel, v7.0.5662.5633(/embedded)
  AucUtilScanButton, v7.0.5662.5631(/embedded)
  AucUtilScanFinish, v7.0.5662.5588(/embedded)
  AucUtilScanProgress, v7.0.5662.4979(/embedded)
  AucUtilScanStart, v7.0.5662.5347(/embedded)
  AucUtilSearchUI, v7.0.5662.5657(/embedded)
  AucUtilSimpleAuction, v7.0.5662.5654(/embedded)
  AucUtilVendMarkup, v7.0.5662.4828(/embedded)
  AutoRepair, v
  autoturnin, v5.1.1
  Babylonian, v5.1.DEV.332(/embedded)
  Bartender4, v4.7.2
  BodyGuardAway, v2.2
  ButtonForge, v0.9.44
  CinematicCanceler, v1.3.3
  Configator, v5.1.DEV.406(/embedded)
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStoreQuests, vr36
  DataStoreSpells, vr27
  DataStoreTalents, vr54
  DBMInterrupts, v6.2.0
  DebugLib, v5.1.DEV.337(/embedded)
  DraenorTreasures, v6.2.4.21343
  DropTheCheapestThing, vv70000.2
  GarrisonCommanderBroker, v2.13.6 6.2.4
  Grid2, vr789-release
  GTFO, v4.38.5
  HandyNotes, vv1.4.8
  HandyNotesDraenorTreasures, v1.19c
  HandyNotesLegionRaresTreasures, v0.6
  HandyNotesWorldMapButton, v2.4
  HideTalkingHead, v1.0.1
  ItemScore, v
  KibsItemLevel, v7.0.3.6-fix2
  LegionWardrobe, v25
  LibExtraTip, v5.12.DEV.409(/embedded)
  LowHPAlert, v2.24
  MacroToolkit, vv7.0.1.0
  MacroToolkitIcons, v7.0.0.0
  MinimapButtonFrame, v3.1.10e
  MinimapButtonFrameSkinPack, v3.0.1b
  MoveAnything, v16.0.7
  NugComboBar, v
  Postal, vv3.5.8
  RangeDisplay, vv4.5.0
  Recount, vv7.0.3e release
  SavedInstances, v7.0.2
  SellJunk, v3.0.13
  SexyMap, v2.4.29
  Stubby, v7.0.5662 (TasmanianThylacine)
  TellMeWhen, v8.1.2
  TidyPlates, v6.18.Beta20
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.7.4.70000
  TitanApexisCrystals, v4.0.001
  TitanClock, v5.7.4.70000
  TitanCurrency, v7.0.3a
  TitanGold, v5.7.4.70000
  TitanRepair, v5.7.4.70000
  TitanSealOfInevitableFate, v
  TitanVolume, v5.7.4.70000
  TomTom, vv70000-1.1.0
  WeakAuras, v2.2.1.1
  WidestAudience, v
  WIM, v3.7.9
  WorkOrderTooltips, v
  ZygorGuidesViewer, v5.0
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=e1e)

**Comment by VulcanTourist** [comment]
This appears to describe the same error reported in ticket 99....
