### ISSUE TITLE
War with beta not working

### ISSUE THREAD

**Issue by Axejess** [AdiAddons/AdiBags#1011]
### Addon Version

1.10.26

### World of Warcraft Version

Retail Beta

### Describe the bug

Try load the addon

### Steps to reproduce

start beta
load addon

Errors:
1:
Message: Interface/AddOns/XLoot_Monitor/Monitor.lua:445: attempt to call global 'GetItemInfo' (a nil value)
Time: Fri Jun 14 13:14:47 2024
Count: 1
Stack: Interface/AddOns/XLoot_Monitor/Monitor.lua:445: attempt to call global 'GetItemInfo' (a nil value)

Locals: 

2:
Message: Interface/AddOns/AdiBags/core/Utility.lua:342: attempt to call global 'GetItemSubClassInfo' (a nil value)
Time: Fri Jun 14 13:17:51 2024
Count: 1
Stack: Interface/AddOns/AdiBags/core/Utility.lua:342: attempt to call global 'GetItemSubClassInfo' (a nil value)

Locals: 

3:
Message: Interface/AddOns/AdiBags/core/Core.lua:312: attempt to call local 'InterfaceOptions_AddCategory' (a nil value)
Time: Fri Jun 14 13:17:51 2024
Count: 1
Stack: Interface/AddOns/AdiBags/core/Core.lua:312: attempt to call local 'InterfaceOptions_AddCategory' (a nil value)

Locals: 

4:
Message: Interface/AddOns/AdiBags/core/Bags.lua:161: attempt to index field 'BAG_IDS' (a nil value)
Time: Fri Jun 14 13:17:51 2024
Count: 1
Stack: Interface/AddOns/AdiBags/core/Bags.lua:161: attempt to index field 'BAG_IDS' (a nil value)
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:161: in function `NewBag'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:205: in main chunk

Locals: self = <table> {
 modules = <table> {
 }
 defaultModulePrototype = <table> {
 }
 defaultModuleState = false
 isRetail = true
 hooks = <table> {
 }
 isClassic = false
 enabledState = true
 bagProto = <table> {
 }
 isBCC = false
 defaultModuleLibraries = <table> {
 }
 hookedBags = <table> {
 }
 name = "AdiBags"
 orderedModules = <table> {
 }
 EXPANSION_MAP = <table> {
 }
 isWrath = false
 L = <table> {
 }
 moduleProto = <table> {
 }
}
name = "Backpack"
order = 10
isBank = false
bag = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "AdiBags_Backpack"
 orderedModules = <table> {
 }
 bagName = "Backpack"
 hooks = <table> {
 }
 enabledState = false
 defaultModuleState = true
 moduleName = "Backpack"
}
(*temporary) = nil
(*temporary) = "BAGS"
(*temporary) = nil
(*temporary) = "ABEvent-1.0"
(*temporary) = "AceHook-3.0"
(*temporary) = <table> {
 modules = <table> {
 }
 defaultModulePrototype = <table> {
 }
 defaultModuleState = false
 isRetail = true
 hooks = <table> {
 }
 isClassic = false
 enabledState = true
 bagProto = <table> {
 }
 isBCC = false
 defaultModuleLibraries = <table> {
 }
 hookedBags = <table> {
 }
 name = "AdiBags"
 orderedModules = <table> {
 }
 EXPANSION_MAP = <table> {
 }
 isWrath = false
 L = <table> {
 }
 moduleProto = <table> {
 }
}
(*temporary) = "attempt to index field 'BAG_IDS' (a nil value)"
addon = <table> {
 modules = <table> {
 }
 defaultModulePrototype = <table> {
 }
 defaultModuleState = false
 isRetail = true
 hooks = <table> {
 }
 isClassic = false
 enabledState = true
 bagProto = <table> {
 }
 isBCC = false
 defaultModuleLibraries = <table> {
 }
 hookedBags = <table> {
 }
 name = "AdiBags"
 orderedModules = <table> {
 }
 EXPANSION_MAP = <table> {
 }
 isWrath = false
 L = <table> {
 }
 moduleProto = <table> {
 }
}
bagProto = <table> {
 isBag = true
}
bags = <table> {
}

5:
Message: Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:839: attempt to call global 'GetItemClassInfo' (a nil value)
Time: Fri Jun 14 13:17:51 2024
Count: 1
Stack: Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:839: attempt to call global 'GetItemClassInfo' (a nil value)

Locals: 

6:
Message: Interface/AddOns/AdiBags/widgets/ItemButton.lua:234: attempt to index field 'BAG_IDS' (a nil value)
Time: Fri Jun 14 13:17:51 2024
Count: 1
Stack: Interface/AddOns/AdiBags/widgets/ItemButton.lua:234: attempt to index field 'BAG_IDS' (a nil value)

Locals: 

7:
Message: Interface/AddOns/AdiBags/widgets/Section.lua:54: attempt to perform arithmetic on local 'ITEM_SIZE' (a nil value)
Time: Fri Jun 14 13:17:51 2024
Count: 1
Stack: Interface/AddOns/AdiBags/widgets/Section.lua:54: attempt to perform arithmetic on local 'ITEM_SIZE' (a nil value)

Locals: 

8:
Message: Interface/AddOns/AdiBags/modules/FilterOverride.lua:57: attempt to call global 'GetItemSubClassInfo' (a nil value)
Time: Fri Jun 14 13:17:51 2024
Count: 1
Stack: Interface/AddOns/AdiBags/modules/FilterOverride.lua:57: attempt to call global 'GetItemSubClassInfo' (a nil value)

Locals: 

9:
Message: Interface/AddOns/AdiBags/modules/Junk.lua:50: attempt to call global 'GetItemSubClassInfo' (a nil value)
Time: Fri Jun 14 13:17:51 2024
Count: 1
Stack: Interface/AddOns/AdiBags/modules/Junk.lua:50: attempt to call global 'GetItemSubClassInfo' (a nil value)

Locals: 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
AdiBags is no longer updated -- community patches are welcome however.
