### ISSUE TITLE
11.0 updates

### ISSUE THREAD

**Issue by glassleo** [AdiAddons/AdiBags#1012]
### Describe the feature

I know the addon is discontinued but has anyone been able to get it to work in the new patch? I can kinda get it to work after removing the interface panel button and adding a dummy function in ItemButton.lua:

```lua
function buttonProto:ENCHANT_SPELL_COMPLETED(...)
end
```

... but I'm not smart enough to figure out why every single item button is just blank with no stack text, cooldowns not showing, and textures only working with Masque (and not at all without).

### Describe the implementation

Anyone smart who can get it in a somewhat working state?

**Comment by kcoderhere** [comment]
![image](https://github.com/user-attachments/assets/5213bc00-6034-430f-b4be-2eac308f6dfa)
I tried this and everything just looks like this after reload. :(  No errors though.

**Comment by glassleo** [comment]
Yep. A very hacky and bad temporary solution is to add a delay to ``self:FullUpdate()`` inside ItemButton.lua

replace the line with``C_Timer.After(0.01, function() self:FullUpdate() end)``

Search still won't work properly.

I don't know why but I think the main issue is that the item buttons are just not updating properly when they are supposed to, or they are being overwritten right after doing so. I also have no clue where this blue overlay texture is coming from.

**Comment by glassleo** [comment]
Solution in @Pegoth's commit [99ab6bb](https://github.com/AdiAddons/AdiBags/pull/1013/commits/99ab6bbc7359a5ae2effddb8fdc0d02de105d02a)

**Comment by Alevpi** [comment]
Hello!
I tried to fix the addon according to the solutions described above, but it still doesn't even start.
Could you upload your corrected addon to third-party resources?

**Comment by Pegoth** [comment]
@Alevpi I attached what I have in my AddOns folder. It might not be exactly the same as the PR I made, but it has the bugfixes.

[AdiBags.zip](https://github.com/user-attachments/files/16388015/AdiBags.zip)

**Comment by Alevpi** [comment]
Thank you very much!
Now the addon works fine for me, it does not give out errors.

**Comment by Axejess** [comment]
It works indeed thank you. The only thing we will miss is the warband bank I guess. Would be great of someone would figure out a way to add that too once blizzard fix it.

**Comment by Koreanuser0** [comment]
감사합니다.
Thank you, Thank you very much!

**Comment by Koreanuser0** [comment]
감사합니다.
Thank you, Thank you very much!

**Comment by Soromeister** [comment]
> @Alevpi I attached what I have in my AddOns folder. It might not be exactly the same as the PR I made, but it has the bugfixes.
> 
> [AdiBags.zip](https://github.com/user-attachments/files/16388015/AdiBags.zip)

Thank you very much for this. AdiBags is still better than BetterBags since it has anchor point as well as better layout ordering and compact option. When BetterBags offer these, I will switch, otherwise, this project doesn't make sense to discontinue.

**Comment by Orbion91** [comment]
hello, someone know how access to warband bank with Adibags?

**Comment by Wevah** [comment]
> hello, someone know how access to warband bank with Adibags?

You'll need to disable using AdiBags for the bank in AdiBags' settings.

**Comment by glassleo** [comment]
> hello, someone know how access to warband bank with Adibags?

Disable the Bank bag in Settings under "Bags"

You can also do ``/run OpenBag(13)`` or ``/run OpenBag(14)`` (or 15, 16, 17) to just open the bank tabs to deposit/take items. They won't be sorted and they'll look like regular Blizzard bags but it works. Not a great solution.

**Comment by Talyrius** [comment]
These issues should be resolved in the latest version. However, the Warband bank is still unimplemented. If anyone's feeling ambitious, you're welcome to open a pull request.

**Comment by zalidthebur** [comment]
Current curseforge download v1.10.28 is missing the AdiBags_Config

**Comment by zalidthebur** [comment]
Tried to sort it, but nothing works.

Keep getting:
Adibags: Couldn't load AdiBags_Config: Missing

Tried to download zip from the code dropdown on github. But this one just gave numerous Lua errors as if it was an old version.

Tried the releases version on github. This works but config does not work. Tried placing the AdiBags_Config fodler within Adibags with same result.

Moved the contents of AdiBags_Config folder to Adibags folder. Same result.
