### ISSUE TITLE
[Feature]: Not disabling the god damned addon completely when you don't have feature parity in the alternative.

### ISSUE THREAD

**Issue by fatalicus** [AdiAddons/AdiBags#1014]
### Describe the feature

Why the hell would you create an update to this @Cidan to just disable the functionality the addon had, when you don't even have feature parity for it in the successor addon?

Bad fucking take mate.

### Describe the implementation

no

**Comment by cars11** [comment]
seriously? this last update breaks the addon? why don't you just let us use it until it stops working. now I have to go through the hassle of rolling back.

and betterbags suck.

**Comment by Shinjpn** [comment]
I've been playing for about 19 1/2 years, and this is the first time I've seen such a terrible, ego-driven development attitude.

They push poor and inferior addons as if they are "masterbating" to do what they want to do, regardless of the convenience of the user.
They are corrupt and completely lack user perspective.

I would never use BetterBags that are useless to begin with.

**Comment by Cidan** [comment]
@Shinjpn

> terrible, ego-driven development attitude.

Hey there,

Come on over and join us on Discord so we can chat about what works for you and doesn't -- I'd love to get some more thoughts around what works in real time and collaborate together. :)

Thanks!

**Comment by Talyrius** [comment]
Let's keep things civil, please.

With that said, see the latest release.
