### ISSUE TITLE
adibags equipment manager It doesn't work.

### ISSUE THREAD

**Issue by Pgmlwns** [AdiAddons/AdiBags#1016]
### Addon Version

Version: v1.10.28

### World of Warcraft Version

Wrath

### Describe the bug

adibags equipment manager It doesn't work.

wow : Cataclysm Classic

<img width="1545" alt="스크린샷 2024-08-04 오후 6 28 00" src="https://github.com/user-attachments/assets/fbc43632-674c-4978-ac99-04584b860834">

### Steps to reproduce

default blizzard equipment manager 

Equipment configurations are not categorized when saved.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
AdiBags is unsupported.
