### ISSUE TITLE
Config seems to be missing on latest release?

### ISSUE THREAD

**Issue by fronbow** [AdiAddons/AdiBags#1017]
### Addon Version

v1.10.28

### World of Warcraft Version

Retail

### Describe the bug

Trying to get the config options to open (by right-clicking on blank bag space) results in this message in the chat window
"AdiBags: Couldn't load AdiBags_Config: Missing"

### Steps to reproduce

Right click on a blank area of the bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
AdiBags is unsupported and not maintained.

**Comment by Talyrius** [comment]
I'm not sure what went wrong with the packaging, but AdiBags_Config was indeed omitted from the Curse release. However, I manually uploaded GitHub's release to Curse, for now.
