### ISSUE TITLE
[Feature]: Ability to view Warband Bank

### ISSUE THREAD

**Issue by AlaskanDruid** [AdiAddons/AdiBags#1018]
### Describe the feature

Currently, when this addon is enabled, it is impossible to view warband bank.

### Describe the implementation

Please add ability to view warband bank.

**Comment by Talyrius** [comment]
As per the announcement here and in-game, this addon is no longer being actively developed. If you or someone else wants to put in the necessary work to add such a feature, a pull request can be submitted.
