### ISSUE TITLE
Warband Not showing

### ISSUE THREAD

**Issue by Devonity** [AdiAddons/AdiBags#1019]
### Addon Version

V1.10.28

### World of Warcraft Version

Retail

### Describe the bug

Warband does not show up in bank

### Steps to reproduce

Opening bank

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
AdiBags is discontinued, this feature will not be added unless someone decides to send a PR.
