### ISSUE TITLE
Issue opening the bag generates error

### ISSUE THREAD

**Issue by lipelipe2** [AdiAddons/AdiBags#1021]
### Addon Version

v11.0.2

### World of Warcraft Version

Retail

### Describe the bug

20x AdiBags/core/DefaultFilters.lua:377: attempt to concatenate field 'expacName' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags/core/Filters.lua"]:148: in function `Filter'
[string "@AdiBags/widgets/ContainerFrame.lua"]:849: in function `FilterSlot'
[string "@AdiBags/widgets/ContainerFrame.lua"]:883: in function `DispatchItem'
[string "@AdiBags/widgets/ContainerFrame.lua"]:943: in function `UpdateButtons'
[string "@AdiBags/widgets/ContainerFrame.lua"]:514: in function `RefreshContents'
[string "@AdiBags/widgets/ContainerFrame.lua"]:499: in function `ResumeUpdates'
[string "@AdiBags/widgets/ContainerFrame.lua"]:479: in function <AdiBags/widgets/ContainerFrame.lua:471>
[string "=[C]"]: in function `Show'
[string "@AdiBags/core/Bags.lua"]:96: in function `Open'
[string "@AdiBags/core/Hooks.lua"]:121: in function <AdiBags/core/Hooks.lua:118>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
(*temporary) = "down"

### Steps to reproduce

Just by opening the bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Acrivec** [comment]
#1022 fixes this. I don't think dev will merge and push update because they want us to use BetterBags, but you can just apply those changes yourself.
