### ISSUE TITLE
Suggestion: Prevent items for rearranging when you have a vendor open

### ISSUE THREAD

**Issue by Oniji** [AdiAddons/AdiBags#103]
User Story: I find myself accidentally selling items when spam right clicking items in the "new" section, because the bags will dynamically rearrange themselves mid-sell. 

Is there any way to prevent the above behaviour from happening?

**Comment by VulcanTourist** [comment]
I second this suggestion.  Further, I have encountered frustration when I already have personal bags open with "new" items visible and then start dialog with a vendor only to have that action force Adibags to reconsider the new-ness of some or all of those items and then move them into categories.  It would be nice to have new-ness be a bit more sticky than that....

**Comment by VulcanTourist** [comment]
This "suggestion" may be related to ticket #36....
