### ISSUE TITLE
Item icons don't update on equip/container open

### ISSUE THREAD

**Issue by Taliyah9** [AdiAddons/AdiBags#104]
This is similar to a known issue noted below, but I don't see an open ticket for this particular issue. When I open an in-bag container (like the current "Small/Large Legion Box" reward items), the icon stays the container (instead of whatever was in it) until I close and re-open my bags. Same for if I equip a piece of equipment, the icon stays the old piece.

Also when opening these reward boxes, some items don't appear in my bags at all, even after closing and reopening the bags (especially the belts for some odd reason). I have to switch to the "separate bags" view and hunt for the item. And finally, items with the same name but different ilvls are visually stacking rather than appearing as separate items.

**Comment by Talyrius** [comment]
Are you sure you have the newest [alpha release](https://www.wowace.com/addons/adibags/files/)? I've been opening Legion Chests and this isn't happening to me.

**Comment by Taliyah9** [comment]
I have the most recent stable "Release" release, 1.9.0. I'll give the Alpha a try, though I generally prefer the stable releases. (1.9.0 is what the Curse Client currently picks up, too.)

**Comment by Taliyah9** [comment]
I tried the latest Alpha, and while it fixed the issue of icons properly updating, it did not completely fix the other issues. The belt and shoulders both wouldn't appear in my bags until I closed and reopened them. The belt was just missing, and the shoulders visually stacked with the chest. A close/reopen corrected the display.
