### ISSUE TITLE
Suggestion concerning learned and unlearned transmog items

### ISSUE THREAD

**Issue by nanrector** [AdiAddons/AdiBags#105]
This is just a feature request. I'd love to be able to have armor I can "learn" for the transmog system to be able to be highlighted in some way for times when I'm running old dungeons etc. Just so I can quickly see what I need to learn before selling it. 

Thanks so much for a great addon! Used it for years.

Nancy

**Comment by Talyrius** [comment]
That's exactly what the addon [Can I Mog It?](https://www.curseforge.com/wow/addons/can-i-mog-it) does.
