### ISSUE TITLE
Error @ 110

### ISSUE THREAD

**Issue by Sotuma** [AdiAddons/AdiBags#106]
Happening since I've hit level 110 and when I open my bags. No item level appears on the items in my bag.

`[23:38:49] Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:339: bad argument #1 to 'unpack' (table expected, got nil) -- details: [Error 00000218CCBFBA90]`
`[23:38:49] Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:339: bad argument #1 to 'unpack' (table expected, got nil) -- details: [Error 00000218CCBFBA90]`
`[23:38:49] Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:339: bad argument #1 to 'unpack' (table expected, got nil) -- details: [Error 00000218CCBFBA90]
`

**Comment by zarevucky** [comment]
Thanks for the report!
This seems to be quite easy to fix, so expect it to go away with next update (just as soon as someone with commit access finds five free minutes of time).

**Comment by zarevucky** [comment]
In the meantime, you can fix this for yourself as follows.
Open `AdiBags\modules\ItemLevel.lua` in a text editor, find line `[100] = { 615, 695 },`, and add just after it a new line `[110] = { 800, 875 },`

**Comment by Sotuma** [comment]
Thanks!
