### ISSUE TITLE
Categories drop-down frame (V) unable to handle large numbers

### ISSUE THREAD

**Issue by VulcanTourist** [AdiAddons/AdiBags#107]
I've been enduring this issue for at least a year; it's not a new issue.  I have created a very large set of custom categories, having been dissatisfied with the generality of the default ones, or in some cases the incorrectness of them.  That works very well - and thank you for enabling that customization - except for one specific instance: having to click-and-alt-drag-and-drop to recategorize an item.  If the list of categories is too large, the frame gets pushed off the top of the viewport, obscuring and making unavailable all but the bottom-most ones that will fit; there is no attempt to columnar-ize or scroll or otherwise display the entire list.  I have managed to work around this by selecting New Type from the bottom and then maneuvering to find it in the Manual Filtering section and drag and drop the item.  Secondarily, when pressing the "V" button to display the list, it is usually if not always incomplete, having only a fraction of the total categories; is that a deliberate condensing to only the ones currently in active use, or might that be another issue?

This is of course quite inefficient.  I seem to recall having noticed that the dropdown frame seemed to be one created by Blizzard code and thus and API call from AdiBags; is that correct?  I hope you can find a way to alleviate this truncation problem.  I would in all seriousness consider abandoning the game if AdiBags ever became fully unusable.  If only it could work for guild banks!

**Comment by VulcanTourist** [comment]
Why was the issue silently closed with no explanation?  Obviously the issue was never addressed.  It no longer selfishly concerns me since I stopped playing the game years ago, but what of those who still do?  It's disrespectful to first ignore a reported issue and choose not to investigate it, doubly disrespectful to then quietly close the issue as if resolved when it was not even addressed.

**Comment by jgwallace3** [comment]
I -do- still play and this is still an issue. Why the closure?

**Comment by Cidan** [comment]
See #645 -- this issue isn't being ignored, but it was closed as a pulse check. You are not being ignored :)

**Comment by VulcanTourist** [comment]
> See #645 -- this issue isn't being ignored, but it was closed as a pulse check. You are not being ignored :)

Ah, so the closures were meant to trigger notifications to anyone still watching the issues, who would object if still an issue?  It worked as intended.

**Comment by Cidan** [comment]
That's one part of it. The other part is there were 180+ issues of varying age, and it would have been difficult to verify each and every single issue at this point. We'll continue to make improvements as time goes on :)

**Comment by jgwallace3** [comment]
Glad to see someone taking an interest! Use the addon every day.

**Comment by jgwallace3** [comment]
Another pulse check? What release is the issue resolved in?

**Comment by jgwallace3** [comment]
OK. NM. Read https://github.com/AdiAddons/AdiBags/issues/997 and see better things are coming. Will this issue be addressed in the new sw?

**Comment by Cidan** [comment]
The new addon does not use any code from AdiBags, and will not share any of the issues that AdiBags does.
