### ISSUE TITLE
Incorrect itemlevel

### ISSUE THREAD

**Issue by OmniBlades** [AdiAddons/AdiBags#108]
Sometimes, but not always, when utilizing the itemlevel plugin for gear in the bag it will show the default itemlevel of gear that is upgraded or modified through some source, like leveling the artifact. Artifact can be 762, and icon in the bags will read 750. Other times it will read correctly.

**Comment by zarevucky** [comment]
This is a sad result of the fact that the itemlevel plugin uses hardcoded list of possible upgrades, which needs to be updated for any additions in game. IMO the proper solution is to read the itemlevel from tooltips (which is not as bad as it sounds if we cache the result).

**Comment by Talyrius** [comment]
Fixed via 2d532c8.
