### ISSUE TITLE
Just an annoying little bug

### ISSUE THREAD

**Issue by oldbuster** [AdiAddons/AdiBags#111]
1x AdiBags\core\Filters-Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.

ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0-12.lua:270: in function `NewModule'
AdiBags\core\Filters-Filters.lua:126: in function`RegisterFilter'
AdiBags_Bound\AdiBags_Bound-v1.1.lua:52: in main chunk

Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists."

**Comment by Talyrius** [comment]
This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.
