### ISSUE TITLE
Hearthstones are not junk

### ISSUE THREAD

**Issue by oldbuster** [AdiAddons/AdiBags#112]
I have all of my hearthstones whitelisted yet they all appear in the junk section

**Comment by D4n13le** [comment]
I've only had this issue with the Dalaran Hearthstone, but it's easily solved by dragging the hearthstone and dropping it in your prefered section.

**Comment by Talyrius** [comment]
This is a duplicate of #109 and was already fixed via 0aac3e8. It's available for download [here](https://www.wowace.com/addons/adibags/files/).
