### ISSUE TITLE
Remove silver border from all item icons

### ISSUE THREAD

**Issue by sevelev** [AdiAddons/AdiBags#114]
Is there a way to remove this border so that I have nice clean straight edges for all my items?  I have tinkered with the addon and have not figured out a way to do it.  I thought maybe I could enlarge the icon and not show the edges somehow, but I don't have the skills to do that.  I use ractionbuttonstyler to remove ability borders from my dominos buttons and it looks so clean.

**Comment by kacsaindex** [comment]
It's the only thing I miss it from this addon. :(

I hope it could fit in the basic styling features the creator mentioned. ;)
