### ISSUE TITLE
question

### ISSUE THREAD

**Issue by perrins21** [AdiAddons/AdiBags#115]
how can i get the addon to show like in the picture? i want it to be 4 across and grow up to down not left to right. any way to do this??

**Comment by fioo** [comment]
Having the same problem. Half of my bag is completely empty because it's stretched so far horizontal. I have the max height bag height set to max and max column width set to min.

**Comment by zarevucky** [comment]
The probable reason is that there are too many currencies shown on the bottom of the bag. Go into AdiBags settings and remove currencies you don't need to see. The bag should then adapt to the smaller size of the currency display.

**Comment by fioo** [comment]
That was indeed the problem. I remember going through those before and checking them off...I'll save a profile this time to be safe. Thank you!
