### ISSUE TITLE
Allow right-click to sell for other bags beyond "Junk".

### ISSUE THREAD

**Issue by Kruithne** [AdiAddons/AdiBags#118]
If a merchant window is open, right-clicking on the header for the "Junk" section will attempt to sell all items in that category to a vendor.

It would be super useful if this option was included on all bags, either by default or as an option that can be toggled.

Use-case example: When I've finished clearing an old raid, I generally have a very full "Equipment" section that I'd like to vendor everything from without having to click everything at once. Being able to right-click the header to vendor it all would be a major QoL improvement.

**Comment by Elschnuppero** [comment]
Would be awesome

**Comment by DejotaFreitas** [comment]
3

**Comment by SpareSimian** [comment]
That would be dangerous. I wouldn't want that to be the default. It should be controlled by a config option.

OTOH, I wouldn't mind something like that for transferring a category into an email message. That would make it easy for my gatherers to send their metal/herbs/skins to my production toons. Or to send unbound greens to my auction house alt.

**Comment by yangxk15** [comment]
+1. Maybe a toggle option that enables right clicking on the header would "right click" everything in the category. This would be a huge improvement for use cases like selling all low level soulbound items to vendors, or sending BOP for different alts for transmog, etc, all with one click.
