### ISSUE TITLE
NewModule 'Bound' already exists

### ISSUE THREAD

**Issue by Bang257** [AdiAddons/AdiBags#120]
Error in AdiBags: Interface\AddOns\AdiBags\core\Filters-Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists. -- details: [Error 

Interface\AddOns\AdiBags\core\Filters-Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.

...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0-12.lua:270: in function `NewModule'
Interface\AddOns\AdiBags\core\Filters-Filters.lua:126: in function`RegisterFilter'
Interface\AddOns\AdiBags_Bound\AdiBags_Bound-v1.1.lua:52: in main chunk
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists."

**Comment by kevorkien** [comment]
I am also getting this as well as a similar one regarding the Legion module:
here is my bugsack grab:

1x AdiBags\core\Filters-Filters.lua:128: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Legion' already exists.
[C]: ?
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:270: in function `NewModule'
AdiBags\core\Filters-Filters.lua:128: in function `RegisterFilter'
...ns\Adibags_Legion_Filters\Adibags_Legion_Filters-v1.1.lua:24: in main chunk

Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Legion' already exists."

**Comment by TK51508** [comment]
I have been getting this error for a while now.  Tried to uninstall and reinstall.  Thought I would post it here.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

220x AdiBags\core\Filters-Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.
[C]: ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:270: in function `NewModule'
AdiBags\core\Filters-Filters.lua:126: in function `RegisterFilter'
AdiBags_Bound\AdiBags_Bound-v1.1.lua:52: in main chunk

Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists."

**Comment by Talyrius** [comment]
This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.
