### ISSUE TITLE
Causing "Retrieving Item Information" bug

### ISSUE THREAD

**Issue by ericscal** [AdiAddons/AdiBags#121]
First love the bag addon and going to be sad not to use it until this is fixed.

Yesterday I got the legendary http://www.wowhead.com/item=132444/prydaz-xavarics-magnum-opus. upon recieveing it my game crashed and when I restarted this item and 3 others all display "Retrieving Item Information". I deleted my cache, wtf, and addons and that fixed it. I have since been enabling addons one at a time and it looks like this one is the one causing the bug. Let me know if any other information would be helpful.

**Comment by VikingSven82** [comment]
This is a known Blizzard issue, nothing to do with Adibags - several people in my guild have had the same problem in the past 2 weeks, and they're not using adibags. When it happens, just quit the game, delete the Cache folder, then open the game again. It takes a little while to build the cache up again, but it sorts it out.
