### ISSUE TITLE
LDB not available for Elvui datatext

### ISSUE THREAD

**Issue by Weissrolf** [AdiAddons/AdiBags#123]
Hello,

thanks for this great addon!

Curiously the LDB does not show up in the Elvui datatext configuration (anymore?), while it does in Bazooka. I am quite sure that I used it in the past instead of Elvui's own "Bad" broker, because yours allows some configuration (free slots left) and clicking Elvui's only opens bags, but does not close them.

**Comment by Talyrius** [comment]
This is an ElvUI issue, no?

**Comment by Weissrolf** [comment]
Turns out that the Adibag LDB keeps coming and going when used as Elvui datatext. When is freshly configured it can be used, but after some time it disappears. No Elvui issue? Maybe, but if it only happens in Elvui, while the same LDB seems fine in Bazooka?! It's reported.
