### ISSUE TITLE
Ignore list for auto-deposit to reagent bank (Feature Request)

### ISSUE THREAD

**Issue by zalidthebur** [AdiAddons/AdiBags#125]
There are some items I would rather not go into the reagent bank automatically, eg Felwort Seed. Would it be possible to add an ignore list for the auto-deposit ?

**Comment by zarevucky** [comment]
Auto-deposit is a Blizzard-provided black box feature. It's not possible to choose what is deposited, unless the entire functionality is replaced by the addon. At this point, doing so is not planned.

**Comment by zalidthebur** [comment]
Ah. I thought it was part of the addon. I will send the suggestion to Blizzard ;-)

**Comment by SpareSimian** [comment]
While you're at it, how about getting Blizzard to auto-deposit to profession bags before the reagent bag, when present?
