### ISSUE TITLE
Artifact Weapon iLvl not showing correctly

### ISSUE THREAD

**Issue by iamswish** [AdiAddons/AdiBags#128]
I am having an issue where the artifact weapons are only showing their base item level, not the upgraded item level of the weapons while in bags. Here is a link of a screenshot for proof:
![adibags_ilvl](https://cloud.githubusercontent.com/assets/23019325/19630225/ff388dd8-9953-11e6-8386-8e43564fe9d1.PNG)

Just wanted to let you know to fix in a future update. Thanks for the great mod!

**Comment by toanqc** [comment]
As of today (patch 7.1) the weapon ilvl is in black color and display incorrectly.

**Comment by Musouv** [comment]
The incorrect values on 7.1 artifact weapon appear to be due to a double addition in relic level. For example, on an item with 39,40, and 45 ilvl relics that should be ilvl 874, it shows ilvl 998, which is 750+2*(39+40+45). I've confirmed by checking all my alts with multiple weapons.

**Comment by Talyrius** [comment]
AdiBags retrieves item levels from [LibItemUpgradeInfo-1.0](https://www.wowace.com/addons/libitemupgradeinfo-1-0/), so report these issues there.

**Comment by Talyrius** [comment]
The latest version of LibItemUpgradeInfo-1.0 reportedly fixed the issue, so I tagged a new release to embed it.
