### ISSUE TITLE
Item Enhancement! Section since 7.1

### ISSUE THREAD

**Issue by redxon** [AdiAddons/AdiBags#130]
I have this pretty annoying bug, where many of my items are just in one big category called "Item Enhancement!"

This is pretty annoying because it defeated the purpose of categorizing them. It is not caused by any other addon, because it is the same, even when AdiBags is the only activated addon.

What's the cause for that?

Screenshot for understanding:
![2016-10-29](https://cloud.githubusercontent.com/assets/6185397/19830214/1bf158b2-9df3-11e6-8bac-f3e9b2568b3f.png)

**Comment by Talyrius** [comment]
See #129.

Options → Filters → Item category → Split by subcategories → Check "Item Enhancement!"

**Comment by Jaerin** [comment]
There is no "Item Enhancement!" option to check or uncheck

![Image of options](https://i.imgur.com/oNoVWJz.jpg)
