### ISSUE TITLE
MInimum ilvl

### ISSUE THREAD

**Issue by SpykerX07** [AdiAddons/AdiBags#131]
Can it be made higher? Possibly 900 or 1000 maximum. It's currently 600. Thanks

**Comment by Talyrius** [comment]
> It's currently 600.
No, [it's 805](https://github.com/AdiAddons/AdiBags/blob/master/modules/ItemLevel.lua#L323)...

**Comment by SpykerX07** [comment]
I updated my addon today, the minimum ilvl scroll stop at 600 for me. I'll try deleting the re-installing the addon.

**Comment by Talyrius** [comment]
Sorry, I thought you were referring to the quality colors. I significantly increased the minimum item level range via 7694f4a. You can find the latest alpha [here](https://www.wowace.com/addons/adibags/files/).

**Comment by SpykerX07** [comment]
Thank you
