### ISSUE TITLE
patch 7.1 crafting items display as "item enhancement"

### ISSUE THREAD

**Issue by Myrroddin** [AdiAddons/AdiBags#132]
Ever since patch 7.1 all crafting items (not finished products, as far as I can tell) show up in the Reagent Bank as "Item Enhancement!" when they should be shown as their categories as defined by AdiBags' options.

Filter overrides do seem to work, but it seems like AdiBags is not getting the Auction House categories for these items correctly.

There is no BugSack error.

![reagent bank](https://cloud.githubusercontent.com/assets/6456346/19834128/63f9c58e-9e18-11e6-97bb-2a88fc584ebd.jpg)

**Comment by Talyrius** [comment]
Options → Filters → Item category → Split by subcategories → Check "Item Enhancement!"

Please make sure to look at both open and closed issues before opening a new one. See #129 for more information.
