### ISSUE TITLE
Item iLevel displaying incorrectly...

### ISSUE THREAD

**Issue by BenHopson** [AdiAddons/AdiBags#133]
...but text colour seems to be correct.

I realise you are using LibItemUpgradeInfo - and that had some issues with Artifact iLevel but this is something different:

Items are displaying as the base item level - ignoring upgrade and scaling.
_However_ the colour coding (against player iLevel) seems to be correct, suggesting correct call used for colour coding, but incorrect call for actual display level.

Artifact getting it wrong:
(https://cloud.githubusercontent.com/assets/6533428/19839750/61c388b4-9edf-11e6-867f-00a22ca9ab5c.png)

iLev 750 is close to player iLevel and text correctly [yellow] - but number very wrong
(https://cloud.githubusercontent.com/assets/6533428/19839751/61ceff1e-9edf-11e6-99dc-2d64a6b2cf8c.png)

item iLevel 735 lower than player iLevel and text colour is [orange], which is correct - but number displayed is wrong
(https://cloud.githubusercontent.com/assets/6533428/19839752/61d116b4-9edf-11e6-84c2-25777204278e.png)

I'm not sure I explained this terribly well,
Any ideas?
B.

**Comment by Blitz54** [comment]
I'm also having issues with ilvl. All of my gear now shows ilvl as 680 when in my bag. The character screen shows the proper ilvl.

**Comment by rbowen87** [comment]
Same issue here, and I've included a screenshot below. 

I can confirm that it is directly related to Adibags, disabling the addon resolves the issue and enabling the addon brings the issue back and this is the only addon in use in both scenarios. 

Issue did not present until I upgraded to latest version of Adibags this morning. (Release v1.9.3)

Have not tested the Alpha v1.9.3-1-g7694f4a to see if it has the same issue.

![ilvl example](https://cloud.githubusercontent.com/assets/23161451/19844787/b1b2697c-9f06-11e6-8b99-092fd2a8eafa.jpg)

**Comment by RBowen87** [comment]
**Update:** Just realized that AdiBags v1.9.3 uses LibItemUpgradeInfo-1.0 Release-70100-26. Manually replacing that version with the updated LibItemUpgradeInfo-1.0 Release-70100-27 resolves both this issue, as well as the Artifact iLvL issue.

**Comment by Talyrius** [comment]
I tagged a new release to embed it.
