### ISSUE TITLE
Too much space on the right if set the column width to 4

### ISSUE THREAD

**Issue by toanqc** [AdiAddons/AdiBags#135]
See the screenshot, not sure why there are too many spaces on the right if I set the column width to 4.
http://imgur.com/j5b1KAq

Thank you for the great addon.

**Comment by Talyrius** [comment]
You cutoff the bottom of the frame, but it's most likely due to tracking too many currencies. Disable some.

**Comment by toanqc** [comment]
oh you're right.. thank you! I closed the ticket
