### ISSUE TITLE
Non-fatal lua error upon loading in game

### ISSUE THREAD

**Issue by Jaerin** [AdiAddons/AdiBags#139]
I've been noticing that AdiBags has been throwing the following errors.  Usually it only take reloading the UI, but other times it is when looting corpses and the like.

`1x AdiBags\modules\Junk.lua:76: Usage: Hook([object], method, [handler], [hookSecure]): Attempt to hook secure function IsJunk. Use `SecureHook' or add `true' to the argument list to override.
[C]: ?
...faceAdiBags\libs\AceHook-3.0\AceHook-3.0-8.lua:164: in function <...faceAdiBags\libs\AceHook-3.0\AceHook-3.0.lua:118>
...faceAdiBags\libs\AceHook-3.0\AceHook-3.0-8.lua:283: in function `Hook'
AdiBags\modules\Junk.lua:76: in function <AdiBags\modules\Junk.lua:73>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:571: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:551>
(tail call): ?
AdiBags\core\Core.lua:104: in function <AdiBags\core\Core.lua:104>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85>
(tail call): ?

Locals:
nil`

**Comment by Jaerin** [comment]
Note that a removed all other Addon with the exception of Bugsack and Buggrabber.

**Comment by Talyrius** [comment]
No longer occurs.
