### ISSUE TITLE
Items in bag have their icons replaced with different icons.

### ISSUE THREAD

**Issue by Mumush666** [AdiAddons/AdiBags#141]
I'm not sure how else to put it.  Random items in my bags eventually have their icons replaced with completely different icons.  Mousing over the item reveals it's true item information.  This is really a dangerous thing when you go to clean out your bags and you end up vendoring stuff that looks to be trash/greens/blues but you end up selling epics and other important items.  Please see the pic.  I am currently moused over a blue item, but the tool tip shows what it really is.  The only slight work-around is to /reload.  But the items eventually lose their original icons.
![untitled](https://cloud.githubusercontent.com/assets/22685801/20211145/06c1f5aa-a7b2-11e6-8191-f0a01e3636fd.jpg)

**Comment by andyhunter** [comment]
This bug troubles me a lot too,and almost makes this addon unusable.I just disenchanted a 885 iLvl chest armor because its icon is a green ring.Thanks to God I can recover it.

**Comment by Talyrius** [comment]
This no longer occurs, AFAIK.
