### ISSUE TITLE
Apparently random splash error - ContainerFrame.lua line 949: script ran too long

### ISSUE THREAD

**Issue by Maxiride** [AdiAddons/AdiBags#143]
I sometimes, and apparently randomly, get this bug screen when opening my bags with B button.
When this happens, only the "new items" row is shown and I have to close and open multiple times my bags to show them all.

`Date: 2016-11-17 16:10:04
ID: 2
Error occured in: Global
Count: 2
Message: ..\AddOns\AdiBags\widgets\ContainerFrame.lua line 949:
   script ran too long
Debug:
   [C]: Show()
   AdiBags\widgets\ContainerFrame.lua:949: PrepareSections()
   AdiBags\widgets\ContainerFrame.lua:1055:
      AdiBags\widgets\ContainerFrame.lua:1038
   (tail call): ?
   AdiBags\widgets\ContainerFrame.lua:447: RefreshContents()
   AdiBags\widgets\ContainerFrame.lua:432: ResumeUpdates()
   AdiBags\widgets\ContainerFrame.lua:415:
      AdiBags\widgets\ContainerFrame.lua:407
   [C]: Show()
   AdiBags\core\Bags.lua:89: Open()
   AdiBags\core\Hooks.lua:112:
      AdiBags\core\Hooks.lua:109
   (tail call): ?
   (tail call): ?
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:

AddOns:
  Swatter, v7.2.5688 (TasmanianThylacine)
  AckisRecipeList, v7.0.3.8
  ACP, v3.4.30 
  AddOnSkins, v3.38
  AdiBags, vv1.9.4
  AdiBagsBoEBoA, vv1.5
  AdiBagsGarrison, vv1.6
  AdiBagsHearthstones, v7.1-release2
  AdiBagsLegion, vv1.6
  AskMrRobot, v48
  AucAdvanced, v7.2.5688 (TasmanianThylacine)
  AucFilterBasic, v7.2.5688 (TasmanianThylacine)
  AucFilterOutlier, v7.2.5688.5459(7.2/embedded)
  AucMatchUndercut, v7.2.5688.5585(7.2/embedded)
  AucScanData, v7.2.5688 (TasmanianThylacine)
  AucStatHistogram, v7.2.5688 (TasmanianThylacine)
  AucStatiLevel, v7.2.5688 (TasmanianThylacine)
  AucStatPurchased, v7.2.5688 (TasmanianThylacine)
  AucStatSales, v7.2.5688.5598(7.2/embedded)
  AucStatSimple, v7.2.5688 (TasmanianThylacine)
  AucStatStdDev, v7.2.5688 (TasmanianThylacine)
  AucStatTheUndermineJournal, v3.3.0
  AucStatWOWEcon, v7.2.5688.5613(7.2/embedded)
  AucUtilAHWindowControl, v7.2.5688.5575(7.2/embedded)
  AucUtilAppraiser, v7.2.5688.5666(7.2/embedded)
  AucUtilAskPrice, v7.2.5688.5599(7.2/embedded)
  AucUtilAutoMagic, v7.2.5688.5686(7.2/embedded)
  AucUtilCompactUI, v7.2.5688.5629(7.2/embedded)
  AucUtilEasyBuyout, v7.2.5688.5576(7.2/embedded)
  AucUtilFixAH, v7.2.5688 (TasmanianThylacine)
  AucUtilItemSuggest, v7.2.5688.5651(7.2/embedded)
  AucUtilPriceLevel, v7.2.5688.5633(7.2/embedded)
  AucUtilScanButton, v7.2.5688.5631(7.2/embedded)
  AucUtilScanFinish, v7.2.5688.5588(7.2/embedded)
  AucUtilScanProgress, v7.2.5688.4979(7.2/embedded)
  AucUtilScanStart, v7.2.5688.5347(7.2/embedded)
  AucUtilSearchUI, v7.2.5688.5672(7.2/embedded)
  AucUtilSimpleAuction, v7.2.5688.5654(7.2/embedded)
  AucUtilVendMarkup, v7.2.5688.4828(7.2/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.2.5688 (TasmanianThylacine)
  Clique, vv70100-1.0.0
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  EasyObliterate, v1.9
  ElkBuffBars, v2.5.0-188
  ElvUI, v10.29
  ElvUILocPlus, v2.21
  Enchantrix, v7.2.5688 (TasmanianThylacine)
  EnchantrixBarker, v7.2.5688 (TasmanianThylacine)
  GatherMate2, v1.38.1
  GatherMateSharing, vv1.10
  Grail, v083
  GrailAchievements, v011
  GrailQuestsitIT, v001
  GrailReputations, v007
  GTFO, v4.41.3
  Informant, v7.2.5688 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.416(/embedded)
  MacroToolkit, vv7.1.0.0
  MacroToolkitIcons, v7.1.0.0
  MasterPlanA, vA
  Omen, v3.1.12
  Overachiever, v0.98
  OverachieverTabs, v0.98
  Pawn, v2.1.8
  PersonalLootHelper, v1.16
  SexyCooldown, v0.7.0
  Skada, v1.5-14
  SlideBar, v7.2.5688 (TasmanianThylacine)
  Stubby, v7.2.5688 (TasmanianThylacine)
  TheUndermineJournal, v4.7.20161115
  TipHelper, v5.12.DEV.405(/embedded)
  TomTom, vv70100-1.0.0
  WeakAuras, v2.2.2.1
  Wholly, v060
  WorldQuestTracker, v
  WoWPro, v7.0.4B
  WoWProAchievements, v7.0.4B
  WoWProDailies, v7.0.4B
  WoWProLeveling, v7.0.4B
  WowProProfession, v7.0.4B
  WoWProWorldEvents, v7.0.4B
  BlizRuntimeLib_itIT v7.1.0.70100 <none>
  (ck=bad)

`

**Comment by Talyrius** [comment]
See #213.
