### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by TasWho** [AdiAddons/AdiBags#144]
I have been getting this one for a while now, might be conflict with other addon but cant seem to figure out if that's the case.  Wanted to post on here in case its something bigger.

**Comment by TasWho** [comment]
I thought this was a reply to another msg but I guess I created a new issue?  Anyways here is my error log...

Date: 2016-12-18 18:31:50
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Filters.lua line 126:
   Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.
Debug:
   [C]: ?
   ...AddOns\ElvUI\Libraries\AceAddon-3.0\AceAddon-3.0.lua:270: NewModule()
   AdiBags\core\Filters.lua:126: RegisterFilter()
   AdiBags_Bound\AdiBags_Bound.lua:52: in main chunk
Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists."

AddOns:
  Swatter, v7.2.5688 (TasmanianThylacine)
  ACP, v3.4.30 
  AddOnSkins, v3.45
  AdiBags, vv1.9.4
  AdiBagsBoEBoA, vv1.5
  AdiBagsBound, vv1.1
  Babylonian, v5.1.DEV.332(/embedded)
  Configator, v5.1.DEV.406(/embedded)
  ElvUI, v10.33
  Gatherer, v7.0.3
  SlideBar, v7.2.5688 (TasmanianThylacine)
  BlizRuntimeLib_enUS v7.1.0.70100 <none>
  (ck=152)

**Comment by Talyrius** [comment]
This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.
