### ISSUE TITLE
Feature request: Artifact Power section

### ISSUE THREAD

**Issue by SpareSimian** [AdiAddons/AdiBags#147]
I put all my Artifact Power items in a separate manual filter section to make them easy to spot and process as they roll in. I keep one 10 point item unused to make it easy to drag new items to that manual filter section. I don't know if this requires tooltip scanning. If so, I can write a plugin based on the 3rd party BOE/BOA one.

**Comment by Talyrius** [comment]
I added an Artifact Power category to Consumables in the alpha release of [LibPeriodicTable-3.1](https://www.wowace.com/projects/libperiodictable-3-1/files). To use it, add "Consumable.Artifact Power" without quotes to the "include" text area of a new section filter in the AdiBags LBT plugin.

**Comment by SpareSimian** [comment]
I threw a plugin together here. It handles Artifact Power, Relics, Champion Equipment, and Ancient Mana. https://github.com/SpareSimian/AdiBags_Legion

**Comment by VulcanTourist** [comment]
Another filter plugin also exists that incorporates artifact power items: [https://mods.curse.com/addons/wow/adibags-legion-filters](url).  It was missing a few items which I added for myself.
