### ISSUE TITLE
Large Green Border on All Tooltips

### ISSUE THREAD

**Issue by SaskyaChangeling** [AdiAddons/AdiBags#149]
I've poked around quite a bit looking for the option to change/remove this, but I cannot seem to find it. It is far too obtrusive for my tastes and i would dearly love to remove it, if possible -- or make it 1px if it is not possible to remove it. 

Any help you can offer would be greatly appreciated. Thank you! 

![wowscrnshot_120216_090421](https://cloud.githubusercontent.com/assets/24318941/20838465/5d045c88-b86e-11e6-8216-1c7676ec9dfb.jpg)

**Comment by zarevucky** [comment]
This is almost certainly not done by AdiBags. Try to disable your addons individually to see which one is to blame. My guess would be an outdated theming engine that is missing border textures.

**Comment by SaskyaChangeling** [comment]
Interesting. It didn't happen until i installed AdiBags this morning, but I'll take a peek at my tooltip addon. 

Thanks for responding!
