### ISSUE TITLE
Suggestion: option to dictate preferred bag expansion direction

### ISSUE THREAD

**Issue by VulcanTourist** [AdiAddons/AdiBags#150]
Currently AdiBags seems a bit random when it decides whether to expand the bags view vertically or horizontally.  It seems to somewhat favor horizontal expansion.  There is also no means to set a finite limit on expansion in either direction, which leads to overlap issues with other frames sometimes.  I think it might be helpful to have an option that either constrains one dimension or prefers the other, to allow better control of overlap issues with other frames.

**Comment by Talyrius** [comment]
If you're tracking a lot of currencies, it's forced to expand horizontally.
