### ISSUE TITLE
WoW 7.1 gear upgrade indicators not appearing on gear in bags

### ISSUE THREAD

**Issue by VulcanTourist** [AdiAddons/AdiBags#151]
Apparently WoW 7.1 has a new feature that displays green arrows on gear items in bags that the game determines are an upgrade for the character.  There is a new related API feature, **IsContainerItemAnUpgrade**.  I have not been seeing these upgrade arrows at all with my use of AdiBags.

**Comment by rflack1717** [comment]
Came here to report this, too. +1 for this feature, please! 👍

**Comment by p5hema2** [comment]
👍

**Comment by p5hema2** [comment]
add to widgets\ItemButton.lua

after Line 305:
```
self:IsContainerItemAnUpgrade()
```

and after 335:
```
function buttonProto:IsContainerItemAnUpgrade()	
	local itemIsUpgrade = IsContainerItemAnUpgrade(self:GetParent():GetID(), self:GetID());
	if ( itemIsUpgrade == nil ) then -- nil means not all the data was available to determine if this is an upgrade.
		self.UpgradeIcon:SetShown(false);
	else
		self.UpgradeIcon:SetShown(itemIsUpgrade);
	end
end
```

**Comment by VulcanTourist** [comment]
Martin ( p5hema2), I noticed that you have forked AdiBags.  Was it for the sole purpose of implementing this fix, or do you have larger designs?  I haven't done significant programming in decades, and hesitate to make a self-patch that I would have to reapply to any future updates.  I'm already doing that with one addon, and every time I forget precisely what I did and where and must revisit it every time the addon is updated.  My tools and technique are terribly primitive.

Personally, I have been playing the game a bit over two years; I came to it quite late in its evolution.  From the beginning I was frustrated by the poorly designed and inflexible default UI, and sought out community solutions to it.  I have been using AdiBags ever since, and could not play the game effectively without it.

**Comment by p5hema2** [comment]
Only for this feature. I am not used to wow addon development at all.

I implemented this feature only to have the green update arrows in my bag and want to share it with all other.

**Comment by p5hema2** [comment]
use this funtion, the above crashed on resource depod

```
function buttonProto:IsContainerItemAnUpgrade()	
	local itemIsUpgrade = IsContainerItemAnUpgrade(self:GetParent():GetID(), self:GetID());
	if ( itemIsUpgrade == nil and self.UpgradeIcon) then -- nil means not all the data was available to determine if this is an upgrade.
		self.UpgradeIcon:SetShown(false);
	elseif (self.UpgradeIcon) then
		self.UpgradeIcon:SetShown(itemIsUpgrade);
	end
end
```

**Comment by VulcanTourist** [comment]
I hope this gets rolled into Adirelle's next update!

**Comment by VulcanTourist** [comment]
I'm beginning to wonder if this will ever see the official light of day in AdiBags?  Time to fork my own private version using p5hema2's insightful patch....
