### ISSUE TITLE
Non-Critical Issue: Splitting Stacks

### ISSUE THREAD

**Issue by Dannii-Darkness** [AdiAddons/AdiBags#152]
I have run into this issue a number of times so I decided to write it up.

If you have the option checked to combine multiple stacks of the same item, splitting stacks becomes a bit of a hassle. For example, the other day when I wanted to send X number of an item I had 47 of showing in the stacks via mail, the only way this was doable without resorting to temporarily disabling the combine stacks, was splitting the stacks into separate slots in the mail I as sending, 3 times. Until finally the stack number I wanted was left in the bag to be added to the last slot.

Obviously the issue isn't a critical one, as I have shown there is a work around (two if you include turning off combining of multiple stacks). If you're able to come up with a more elegant solution to the problem than my ham-fisted work-around it would be very nice.

Thanks.

**Comment by Talyrius** [comment]
See [this](https://github.com/AdiAddons/AdiBags/issues/134#issuecomment-257309170).
