### ISSUE TITLE
Non-Critical Issue: Manual Filtering into Existing Sections Prohibited

### ISSUE THREAD

**Issue by Dannii-Darkness** [AdiAddons/AdiBags#153]
Let's say you have a bunch of things that AdiBags sorts into a particular section. Say for example Class Hall Items, it puts into the bag section denoted with the same name.

At some point, you realise that there is an item which for whatever reason isn't included on the internal filtering to put it in that spot, and it winds up in junk, or maybe just some other separation that you don't feel the item belongs in. You think it's better suited in the Class Hall Item section along with the other items, and set up a filter for it, telling Adibags to put it in the Class Hall Items section.

Adibags doesn't recognise that the section name entered is an exact match for an existing section, and instead creates a new one (with exactly the same name) to store the item in - and then sorts that new section according to some criteria, not all of which can be altered. So in the end, the Item, and the new section may not even be next to the existing section of the same name.

Thanks.

**Comment by Talyrius** [comment]
Drop the item onto the existing section header and it will be manually filtered there.

**Comment by VulcanTourist** [comment]
That will not _appear_ to work, however, if there is another filter that is taking priority.  This has happened to me a number of times, especially with regard to the Outfitter plugin and the filtering it adds, since in my configuration its filters have the highest precedence.
