### ISSUE TITLE
Seperate Filter Section for iLVL?

### ISSUE THREAD

**Issue by 1Kurgan1** [AdiAddons/AdiBags#154]
Is there some way in which I can set a filter to put all items under a specific item level into a section of it's own. For Legion I would set said filter at ilvl 749 and lower. That way when I'm out Transmog farming everything's separated and not a jumbled mess. I tried looking for quite some time, but cannot find anything like this.

**Comment by VulcanTourist** [comment]
That would require a filter that doesn't exist in AdiBags, though it's possible that someone else might have created such a filter as a plugin.

**Comment by seirl** [comment]
I did a while ago: https://wow.curseforge.com/projects/adibags_lowlevel

**Comment by VulcanTourist** [comment]
> I did a while ago: https://wow.curseforge.com/projects/adibags_lowlevel

I would have wanted to know about this were I still able to play the game.  Now I'm struggling with the less refined equivalent of AdiBags in another game....
