### ISSUE TITLE
Artifact Power numbers not reflecting AK25

### ISSUE THREAD

**Issue by galaarelune** [AdiAddons/AdiBags#157]
So since I've hit AK25 the artifact power items show ak24 values on the icon but 25 values on the rollover.  

Other addons:  ElvUI and BagSync

![image](https://cloud.githubusercontent.com/assets/24950156/21707016/8671d0be-d399-11e6-8694-558fffe8a725.png)

**Comment by Talyrius** [comment]
AdiBags isn't responsible for displaying these numbers.
