### ISSUE TITLE
Can't sort items in sections

### ISSUE THREAD

**Issue by Connorjevans** [AdiAddons/AdiBags#158]
I can't move around items within the sections. When I try to swap two items within a section, the tooltips change but the icons don't change, and then when I re open my bag, the items haven't swapped. Is there anyway to disable that?

**Comment by Connorjevans** [comment]
It only occurs with virtual stacking on, but even when I try to swap 2 items that aren't stacked, it still happens with the options on.

**Comment by Zarggg** [comment]
As far as I'm aware, there is no way to manually sort items within subsections.

**Comment by Traummond** [comment]
hello Adirellei,
you've written a wonderful addon for wow, and I've been using it for a long time! the sorting of the bags works so well! I have a question or a suggestion: the "shiny pet luck charms" are packed in the section "battle pet items", all right!
Now my suggestion: the new "polished pet charms" is packed in the section "miscellaneous"! maybe they would not have been better off in the section "battle pet items"? :)
Kind regards
rainer hönel
wow-user
translated by Google

**Comment by Talyrius** [comment]
@Connorjevans
I can't reproduce this behavior.

@Traummond
The sections that items are initially filtered into is determined by how Blizzard has chosen to classify them in their API. However, there's nothing preventing you from manually adding the item to your preferred section.
