### ISSUE TITLE
Game freezing and crashing when I click the sort button

### ISSUE THREAD

**Issue by kelisikelly** [AdiAddons/AdiBags#159]
I have just installed this addon, and I like it, but whenever I click the sort button, it crashes my game and totally resets all of my settings upon restart of the game client.

How can I fix this so that it saves my settings and does not crash?

Thanks

**Comment by Blazernut** [comment]
I've been having the same problem since installing the addon in patch 7.1

**Comment by gi2k15** [comment]
Same here too.

**Comment by lorddev** [comment]
I have this issue as well.

**Comment by josephtylerbrowning** [comment]
+1 same issue as gi2k15 mentioned.

**Comment by Talyrius** [comment]
Duplicate of #137.
