### ISSUE TITLE
Random Items Filter to New Items Occasionally

### ISSUE THREAD

**Issue by misterjoshua** [AdiAddons/AdiBags#16]
Every now and then bags will sort all items into the "Recent items" category regardless of how long they've been in your bags. I hope the attached screenshot shows why this is a problem. (It goes off the screen.)

![image](https://cloud.githubusercontent.com/assets/644092/5513737/14ad895a-87c4-11e4-87da-558eff31392f.png)

Most times you can work around it temporarily by closing/reopening bags, or by clicking the "Reset new items" button. This doesn't always work. This started happening a couple of versions ago, I believe as of 1.8.0. I'm currently running 1.8.2.

**Comment by DjRicko** [comment]
Indeed still a problem in newest update.
