### ISSUE TITLE
AP in Currency Tray

### ISSUE THREAD

**Issue by norsehealer** [AdiAddons/AdiBags#162]
I had a new currency popup on the currency tray and couldn't figure out what it was. I asked in guild and found out it was AP. I don't need AdiBags to track that as I use another addon for that. Is there a way to remove AP from the currency?  I've checked a few times in the Currency section and couldn't find that icon or name after knowing what it is.

**Comment by CHagenlo** [comment]
That can be disabled in the setting of the addon its self, under currency settings.

**Comment by norsehealer** [comment]
I looked in the currency settings of the addon and couldn't find any mention of Artifact Power.

I'm looking in the Plugins - Currency - Currencies to show area. You can view the image showing I have 18m AP but no listing of AP in the currency section. http://i.imgur.com/1UDldIL.jpg

**Comment by Talyrius** [comment]
Does this happen for anyone else? I don't have an active subscription right now. However, I did from patch 7.0 to 7.1 and I don't recall Artifact Power being displayed.

**Comment by norsehealer** [comment]
So, it seems the currency spot isn't where the AP option is located.  It's located in the Plugins part, a spot I wouldn't have thought of checking.

I checked the Currency first because it was listed in the Currency bar/section of the bag UI.
