### ISSUE TITLE
Error upon reload.

### ISSUE THREAD

**Issue by danzbichorski** [AdiAddons/AdiBags#165]
Date: 2017-02-22 15:13:10
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Filters.lua line 126:
   Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.
Debug:
   [C]: ?
   ...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:270: NewModule()
   AdiBags\core\Filters.lua:126: RegisterFilter()
   AdiBags_Bound\AdiBags_Bound.lua:52: in main chunk
Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists."

AddOns:
  Swatter, v7.3a.5701 (TasmanianThylacine)
  AdiBags, vv1.9.4
  AdiBagsArmourType, vv1.0
  AdiBagsBoEBoA, vv1.5
  AdiBagsBound, vv1.1
  BlizRuntimeLib_enUS v7.1.5.70100 <none>
  (ck=b0)

**Comment by TK51508** [comment]
Getting this for a while as well.  

220x AdiBags\core\Filters-Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.
[C]: ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:270: in function `NewModule'
AdiBags\core\Filters-Filters.lua:126: in function `RegisterFilter'
AdiBags_Bound\AdiBags_Bound-v1.1.lua:52: in main chunk

Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists."

**Comment by Talyrius** [comment]
This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.
