### ISSUE TITLE
Pawn's upgrade arrow not shown when using Adibags

### ISSUE THREAD

**Issue by Mrhgb** [AdiAddons/AdiBags#167]
Usually Pawn will put a green up arrow on items that are an upgrade for you but after switching to Adibags I no longer get this, could you please make your addon compatible with Pawn?

**Comment by Zarggg** [comment]
@Adirelle has been absent for a while, but a solution has been posted in issue #156 if you're willing to edit the LUA files yourself.

**Comment by Talyrius** [comment]
This is a duplicate of #151.
