### ISSUE TITLE
Hide S(Sort) Button

### ISSUE THREAD

**Issue by shinjiat** [AdiAddons/AdiBags#168]
1) I do not want to disable the item level plugin to fix the freezing issue when I sort the bag
So I will be playing with the item level plugin but I'm afraid I will click the S button accidentally, so my request is to hide the "S" button on the bar

2) Also, when do items in "Recent Items" get sort to its categories ? Since that sorting feature is not usable by me, and I thought opening the bag will auto sort the items somehow but the my items are staying in the recent items section for quite a long time

**Comment by Talyrius** [comment]
Duplicate of #137.
