### ISSUE TITLE
translation bugs with 7.2.0 with adibags 1.9.4 & 1.9.5

### ISSUE THREAD

**Issue by Guilwin** [AdiAddons/AdiBags#176]
Hello,

i saw some translation bugs in the german translation now since 7.2.0, with 1.9.4 and also 1.9.5

Some categtories get the wrong translation.

eg. Armory will be translated into "Edelsteine", Weapons to "Behälter" ans so one.

Maybe someone can take a look on it.

Greetings

A.Share

**Comment by Talyrius** [comment]
Localization is done at [WowAce](https://www.wowace.com/projects/adibags/localization). Feel free to contribute.
