### ISSUE TITLE
Error when opening bags when running Dugi questing essential

### ISSUE THREAD

**Issue by DedTV** [AdiAddons/AdiBags#177]
Not sure which one is causing it, but when Dugi Questing Essential is enabled, this error occurs whenever a bag is opened.

1x Usage: local itemIDs = C_EquipmentSet.GetItemIDs(equipmentSetID)
[C]: in function `GetItemIDs'
...faceBlizzard_Deprecated\Deprecated_7_2_0.lua:152: in function <...faceBlizzard_Deprecated\Deprecated_7_2_0.lua:149>
AdiBags\core\DefaultFilters.lua:108: in function `UpdateSlots'
AdiBags\core\DefaultFilters.lua:145: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `SendMessage'
AdiBags\widgets\ContainerFrame.lua:908: in function `RedispatchAllItems'
AdiBags\widgets\ContainerFrame.lua:1054: in function `FullUpdate'
AdiBags\widgets\ContainerFrame.lua:563: in function <AdiBags\widgets\ContainerFrame.lua:549>
[C]: ?
AdiBags\core\Utility.lua:89: in function <AdiBags\core\Utility.lua:81>
AdiBags\widgets\LayeredRegion.lua:119: in function <AdiBags\widgets\LayeredRegion.lua:108>

Locals:
nil

**Comment by zgavin** [comment]
This is squarely on Dugi's.  They are changing the behavior of built in functions, which is something you should do everything in your power to avoid.  If you are going to do it, then you better make damn sure you're not ruining someone else's day, and they clearly are not.  It's lazy programming.

Here is a temporary workaround.  Change line 3219 of Dugi's "GearAdvisor.lua" to:

    local isCalledByAdibags = (string.find(stack, "AdiBags") ~= nil)
    return  isCalledByBagnonAddon or isCalledCargBags_NivayaAddon or isCalledByAdibags

That said, though, Adibags is now using deprecated functions here and they should be updated to the new C_EquipmentSet API.

**Comment by Talyrius** [comment]
@zgavin said:
> That said, though, Adibags is now using deprecated functions here and they should be updated to the new C_EquipmentSet API. Doing so seems to resolve the issue even with Dugis enabled.

Can you open a pull request with necessary changes?
