### ISSUE TITLE
Border color of Mythic Keystone's 

### ISSUE THREAD

**Issue by shpark1359** [AdiAddons/AdiBags#181]
Now, the color of Mythic Keystone's doesn't appear. 
Because, the quality of mythic keystone from GetItemInfo(KEYSTONE_ID) is 1.
And GetItemInfo(KEYSTONE_LINK) doesn't work.

so how about change the line 368 of widgets/ItemButton.lua
 
from 
local _, _, quality = GetItemInfo(itemId)

to 

local _, _, _, quality = GetContainerItemInfo(bag, slot)

**Comment by legowxelab2z8** [comment]
The change you suggested also fixes the border color of Battlepets.

**Comment by johnallers** [comment]
This is great. I knew something looked off. Didn't realize what it was until I saw this.
