### ISSUE TITLE
Feature Request: 'Show Section When Empty'

### ISSUE THREAD

**Issue by xelepart** [AdiAddons/AdiBags#183]
I like to move various things into the "junk" category with the manual filtering feature, so I can quickly identify "oh, yeah, I'm doing Pandarian stuff nad I keep getting consumables/tradeskill items that I just want to vendor" without having to sift through the consumables/tradeskill sections. I also have a "things I want to auction/mail to my auction character" section.

But after I stop by town, I have no items in there, so it's hard to sort things into there, and I get into a cycle where I'm in town, sell stuff/don't have real junk, but want to clean up my tradeskill bag, but can't 'cause I don't have one/both of those "sort to" sections I wnat.

I was thinking a feature like "if the bag is empty, keep the title and a single empty spot visible in your bag for easy manual sorting" would be awesome, and hopefully pretty straight forward?

PS this addon is basically a requirement for me to enjoy WoW. Total props for writing/supporting it.

**Comment by Talyrius** [comment]
Once a single item has been manually sorted to a category, that category and item will be displayed in the options. Add/remove items from there.

**Comment by xelepart** [comment]
That's an incredibly inconvenient UI for moving items between categories? :(
