### ISSUE TITLE
Lots of items non right-clickable

### ISSUE THREAD

**Issue by Holt59** [AdiAddons/AdiBags#186]
Since last update, some items cannot be right-clicked when Adibags is enabled. At least the following items are not working:

- Some of the AP items
- Nethercluster (from Broken Shore)

**Comment by SpareSimian** [comment]
I used a lot of AP items yesterday with, I think, v1.95 from Curse. Perhaps 8-12 different kinds.

**Comment by Holt59** [comment]
@SpareSimian I might have exaggerated the "most". Currently I have the following that do not work (some others did not work but I disabled Adibags to use them):

- Accolade of Achievement
- Nar'thalas Research Tome
- Spoid Manawine Dregs

Also, not all instances of a given items are bugged - I was able to use some "Accolade of Achievement" without problem... Only some seems to be bugged.

**Comment by Talyrius** [comment]
This is most likely a cache issue. This stuff tends to happen after a patch.

v1.9.6 is the newest version, BTW.

**Comment by Holt59** [comment]
@Talyrius I am using v1.9.6. I have cleared the cache, I'll close or update this issue if the problem stops / persists.
