### ISSUE TITLE
Cooldown timer on item usage?

### ISSUE THREAD

**Issue by sonicbl** [AdiAddons/AdiBags#189]
I just got adibags and absolutely love the layout, but the killer issue for me right now is that it doesn't display a countdown on items, similar to how your skills show a countdown in seconds instead of just a clockwise animation.

It's just very unpleasant when you cant tell how long exactly an item is going off cooldown (prime example being whistle) without hovering over it every now and then.

Is this possible to be added to this? It's the only thing thats causing me to revert back to elvui default bag :(

**Comment by Talyrius** [comment]
Have you tried using [OmniCC](https://mods.curse.com/addons/wow/omni-cc)?
