### ISSUE TITLE
Single Row Per Category

### ISSUE THREAD

**Issue by DonGar** [AdiAddons/AdiBags#203]
I'd like to be able simplify the layout to only have a single category per row, and to vertically sort the categories in a consistent way, perhaps with the highest priority categories at the top of the bag.

It would waste some screen real estate, but I think it would be a little easier to find things in the bags, and category names would very rarely be truncated.

I love your addon, so consider this a feature request, not a bug.

**Comment by Talyrius** [comment]
Sorry, this won't be implemented. See #231
