### ISSUE TITLE
Cannot use World Quest Auto-Complete item 

### ISSUE THREAD

**Issue by scainburger** [AdiAddons/AdiBags#205]
Trying to use the item to auto-complete a world quest (e.g. [Horn of War](http://www.wowhead.com/item=140157/horn-of-war)) fails and gives the following error:

1x [ADDON_ACTION_FORBIDDEN] AddOn 'AdiBags' tried to call the protected function 'UseWorldMapActionButtonSpellOnQuest()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `UseWorldMapActionButtonSpellOnQuest'
FrameXML\WorldMapFrame.lua:2020: in function <FrameXML\WorldMapFrame.lua:2016>
[C]: ?
[C]: ?

Locals:
nil

**Comment by Talyrius** [comment]
This was caused by [taint](https://www.townlong-yak.com/taint.log/about.html) incorrectly blamed on AdiBags.
