### ISSUE TITLE
Bugs when opening chests found on normal/heroic/mythic dungeons.

### ISSUE THREAD

**Issue by piterisonfire** [AdiAddons/AdiBags#208]
Whenever you open one of these boxes, a string of text appears saying that there's an error with AdiBags. When you mouseover any kind of item from the blizzard interface (on inventory or when you hover over some item on the list of itens attained in a dungeon) the error pops again. Some parts of the WoW interface start bugging, such as the artifact trait screen (when you mouseover it, no description of traits appear, but you can still click on them to apply points). Couldn't get a screenshot, but it's quite easy to recreate (happened twice, had to logout to fix the error thingy popping), so I'll update this post later.

**Comment by bughandle** [comment]
seeing the same since 7.2.5. I'll try to get some bugsack details next time.

**Comment by Talyrius** [comment]
Not seeing this happen.
