### ISSUE TITLE
Often when I sell Items, they seem to stay in the bag until I close and reopen it

### ISSUE THREAD

**Issue by X-Knochen** [AdiAddons/AdiBags#209]
Often when I go to the bank or sell something, the items seem to stay in the bag (but they are gone) when I close and reopen the bag the item is gone. After that the bag will not close when I leave the bank. I receive lua errors from callback-handler in adibags. script ran to long ...

**Comment by X-Knochen** [comment]
1x [string "safecall Dispatcher[1]"]:13: script ran too long
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:87>
(tail call): ?

Locals:
handlers = <table> {
 (null) = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147
 (null) = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147
}
index = <table> {
 AcquireItemButton = <function> defined @AdiBags\widgets\ItemButton.lua:155
 modules = <table> {
 }
 UpdateFilters = <function> defined @AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @AdiBags\core\Core.lua:451
 ConfigChanged = <function> defined @AdiBags\core\Core.lua:371
 GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
 Filter = <function> defined @AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 Reconfigure = <function> defined @AdiBags\core\Core.lua:183
 SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterMessage = <function> defined @LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:188
 CreateFont = <function> defined @AdiBags\core\Fonts.lua:122
 filterProto = <table> {
 }
 db = <table> {
 }
 OpenOptions = <function> defined @AdiBags\core\Core.lua:289
 SetEnabledState = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:274
 IterateBags = <function> defined @AdiBags\core\Bags.lua:183
 OnEnable = <function> defined @AdiBags\core\Core.lua:115
 HookBagFrameCreation = <function> defined @AdiBags\core\Bags.lua:304
 NewBag = <function> defined @AdiBags\core\Bags.lua:150
 GetClass = <function> defined @AdiBags\core\OO.lua:128
 RegisterFilter = <function> defined @AdiBags\core\Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 InitializeFilters = <function> defined @AdiBags\core\Filters.lua:64
 IterateFilters = <function> defined @AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @AdiBags\core\Core.lua:362
 CreateBagSlotPanel = <function> defined @AdiBags\widgets\BagSlots.lua:437
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @AdiBags\core\Hooks.lua:137
 ToggleAllBags = <function> defined @AdiBags\core\Hooks.lua:86
 OnProfileChanged = <function> defined @AdiBags\core\Core.lua:191
 GetName = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 name = "AdiBags"
 OpenBackpack = <function> defined @AdiBags\core\Hooks.lua:168
 LayoutBags = <function> defined @AdiBags\core\Layout.lua:101
 Disable = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
 SetGlobalLock = <function> defined @AdiBags\core\Core.lua:419
 Unhook = <function> defined @ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @ElvUI\Libraries\AceConsole-3.0\AceConsole-3.0.lua:54
 OpenAllBags = <function> defined @AdiBags\core\Hooks.lua:109
 L = <table> {
 }
 safecall = <function> defined @AdiBags\core\Utility.lua:81
 Debug = <function> defined @AdiBags\core\Core.lua:61
 CreateAnchorWidget = <function> defined @Interf

**Comment by Talyrius** [comment]
See #213.
