### ISSUE TITLE
World of Warcraft error: Adibags AceAddon "AceEvent-3.0"

### ISSUE THREAD

**Issue by sephiraslight** [AdiAddons/AdiBags#210]
Ive tried everything but the error wont stop. Please help :)
Here is my info from swatter:
Date: 2017-07-14 11:47:47
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Filters.lua line 126:
   Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceEvent-3.0".
Debug:
   [C]: ?
   ...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:220: EmbedLibrary()
   ...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:202: EmbedLibraries()
   ...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:283: NewModule()
   AdiBags\core\Filters.lua:126: RegisterFilter()
   ...rface\AddOns\AdiBags_PT3Filter\AdiBags_PT3Filter.lua:13: in main chunk
Locals:
(*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceEvent-3.0"."

AddOns:
  Swatter, v7.0.5 (<%codename%>)
  AdiBags, vv1.9.6
  AdiBagsBoEBoA, vv1.5
  AdiBagsPT3Filter, vv1.3.1
  BlizRuntimeLib_enUS v7.2.5.70200 <none>
  (ck=91)

**Comment by Talyrius** [comment]
Please download AdiBags from [CurseForge](https://www.curseforge.com/wow/addons/adibags). Releases from GitHub don't contain the dependent libraries.
