### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by luibrain** [AdiAddons/AdiBags#211]
`1x AdiBags\core\Bags.lua:219: script ran too long
AdiBags\core\Bags.lua:219: in function `Sort'
AdiBags\widgets\ContainerFrame.lua:337: in function <AdiBags\widgets\ContainerFrame.lua:336>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:398
 isBank = false
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:266
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:473
 SecureHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:336
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:395
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:440
 name = "AdiBags_Backpack"
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:482
 orderedModules = <table> {
 }
 bagIds = <table> {
 }
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:381
 SecureHookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:410
 frame = AdiBagsContainer1 {
 }
 baseName = "AdiBags"
 Sort = <function> defined @AdiBags\core\Bags.lua:217
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 AdiBags_InteractingWindowChanged = <function> defined @AdiBags\core\Bags.lua:204
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:310
 IsHooked = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:493
 order = 10
 bagName = "Backpack"
 IsModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:248
 hooks = <table> {
 }
 SetDefaultModuleState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:418
 SendMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
 UnhookAll = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:477
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 Unhook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:418
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterAllMessages = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 wasOpen = false
 HookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:366
 defaultModuleState = true
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:468
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 RawHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:313
 PostEnable = <function> defined @AdiBags\core\Bags.lua:200
 moduleName = "Backpack"
 UnregisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:345
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = "script ran too long"
`

**Comment by Talyrius** [comment]
See #213.
