### ISSUE TITLE
error, then doesnt work any more until reload

### ISSUE THREAD

**Issue by thezemo** [AdiAddons/AdiBags#213]
5x AdiBags\core\Bags.lua:89: script ran too long
AdiBags\core\Bags.lua:89: in function `Open'
AdiBags\core\Bags.lua:209: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `SendMessage'
AdiBags\core\Core.lua:447: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:87>
(tail call): ?

Locals:

**Comment by Talyrius** [comment]
We've done our best to avoid triggering these errors. However, if you're running a lot of addons and your CPU can't keep up, it's bound to happen now and again.

**Comment by Indil** [comment]
I got a fix for that bug editing line 84:
`if not frame:IsShown() then`

with

`if not frame:IsShown() and not InCombatLockdown() then`

Blizzard introduced any restrictions to scripting when characters are on combat. You can read below here:
[https://wowwiki.fandom.com/wiki/API_InCombatLockdown](url)
