### ISSUE TITLE
Error 000002146A011310

### ISSUE THREAD

**Issue by Tamati27** [AdiAddons/AdiBags#214]
Sometimes when using items or acquiring new items I get the error 000002146A011310 and it persists until I do a /reload
This error seems to stem from Details, but both addons are up to date.
I am unsure what is causing this issue, and since I love the adibags addon I really want it to be fixed.
https://puu.sh/x6qBf/0f69d5eae5.png Here is a picture of the error message that gets sent.
Thanks!

**Comment by Talyrius** [comment]
This was caused by [taint](https://www.townlong-yak.com/taint.log/about.html) incorrectly blamed on AdiBags.
