### ISSUE TITLE
Bags Disappeared

### ISSUE THREAD

**Issue by Dogenji** [AdiAddons/AdiBags#215]
I installed AdiBags yesterday.  Only four bags were displaying on my backpack and a similar problem occurred in my bank.  I have the full complement of bags on my toon and in the bank.   I eventually turned the Adibags addon off.  The restored vanilla WoW no longer showed all of my bags.  I tried to completely restore WoW by deleting the cache, interface and WTF folder.  No good, the bags are gone.  This is what I describe as a bad problem that didn't exist before I loaded up AdiBags.  I only hope that WoW can restore my missing bags.

**Comment by camreonc** [comment]
me too

**Comment by Talyrius** [comment]
AdiBags cannot delete your bags. Are you sure you aren't just misremembering how many bags you had on that character?

**Comment by Dogenji** [comment]
Thanks for your response.
