### ISSUE TITLE
Bug  widget, ContainerFrame and Callbackhandler

### ISSUE THREAD

**Issue by Mal-content** [AdiAddons/AdiBags#216]
Recently Adibags is giving me quite often errors. Most often when i open bank or vendor windows. Sometimes reload helps sometimes do not. This is error message that I get:

> `Error in AdiBags: [string "safecall Dispatcher[2]"]:13: script ran too long -- details: [Error 0000025B45EAF2A0]
> 1x AdiBags\widgets\Section.lua:250: script ran too long
> AdiBags\widgets\Section.lua:250: in function `AddItemButton'
> AdiBags\widgets\ContainerFrame.lua:773: in function `DispatchItem'
> AdiBags\widgets\ContainerFrame.lua:911: in function `RedispatchAllItems'
> AdiBags\widgets\ContainerFrame.lua:1054: in function <AdiBags\widgets\ContainerFrame.lua:1041>
> ...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:155: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
> [string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
> [C]: ?
> [string "safecall Dispatcher[2]"]:13: in function `?'
> ...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `SendMessage'
> AdiBags\core\Core.lua:445: in function `?'
> ...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
> [string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
> [C]: ?
> [string "safecall Dispatcher[1]"]:13: in function `?'
> ...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85>
> (tail call): ?
> 
> Locals:
> nil`

If you need any extra info please let me know. 
Thanks for making  this amazing bag addon.

**Comment by Talyrius** [comment]
See #213.
