### ISSUE TITLE
Patch 7.3 PlaySound Fix

### ISSUE THREAD

**Issue by Daztek** [AdiAddons/AdiBags#217]
Hi,

Patch 7.3 will break AdiBags tomorrow due to a change to the [PlaySound](https://wow.gamepedia.com/API_PlaySound) api call.

Currently it takes string argument like: 

PlaySound("igMainMenuOption")

Patch 7.3 will require a number id or a key from the SOUNDKIT table like: 

PlaySound(852)

PlaySound(_G.SOUNDKIT.IG_MAINMENU_OPTION)

Here are all the IDs you need to fix it

"igMainMenuOpen" -> IG_MAINMENU_OPEN = 850
"igMainMenuClose" -> IG_MAINMENU_CLOSE = 851
"igMainMenuOption" -> IG_MAINMENU_OPTION = 852
"igBackPackOpen" -> IG_BACKPACK_OPEN = 862
"igBackPackClose" -> IG_BACKPACK_CLOSE = 863 
"UI_BagSorting_01" -> UI_BAG_SORTING_01 = 43937
"sTitleOptionExit" -> GS_TITLE_OPTION_EXIT = 799  
"igCharacterInfoTab" -> IG_CHARACTER_INFO_TAB = 841	
"igMainMenuOptionCheckBoxOn" -> IG_MAINMENU_OPTION_CHECKBOX_ON = 856
"igMainMenuOptionCheckBoxOff" -> IG_MAINMENU_OPTION_CHECKBOX_OFF = 857

I don't know the the table key for this one, only the id number
"igPlayerInviteDecline" -> ??? = 882

Both the core AdiBags files and some in the /libs/ folder have PlaySound calls

Hope this is enough info for you guys to be able to fix it

**Comment by Daztek** [comment]
Here's a band-aid fixed version for 7.3: https://drive.google.com/file/d/0B5nI7qSzeSejR1lPN29rR3UtTm8/view?usp=sharing

**Comment by tpittma2** [comment]
Thanks for the band-aid fix @Daztek. Worked like a charm!

**Comment by Daztek** [comment]
I think the actual config is still broken, at least for me, it opens the config menu but it won't save the stuff you change. Might be a lib issue but I'm not wow addon savvy enough to figure it out.

**Comment by tturff** [comment]
@Daztek you are an angle, thank you so much for the fix

**Comment by millie1978** [comment]
Thank you so much for the fix! Worked like a charm! :)

**Comment by Critney7871** [comment]
Where do i put this bandaid fix?

**Comment by Aingealfire** [comment]
You are awesome @Daztek! Thank you Thank you!

**Comment by Stronggpuss** [comment]
very nice for very lua savvy folks, but for we neandrathals, can't seem to download from link, so can't get zip file into file folder, is there a simpler way to get this file involving rocks and twine?

**Comment by EvilGrinUK** [comment]
The full list of sound kit defines are listed here on wowpedia.

https://wow.gamepedia.com/API_PlaySound

**Comment by Aingealfire** [comment]
For those confused how to get the fix: 
1. Click the google drive link posted above
2. Click the download arrow at the top right of the WINDOW, not the box that shows the files
3. Save the zip file somewhere you can find it
4. Extract the 2 folders in the file and then move them into the WOW / Interface / addons folder
5. Confirm overwriting existing files

That should get you going. :D

**Comment by Gelfin** [comment]
I can't get https://drive.google.com/file/d/0B5nI7qSzeSejR1lPN29rR3UtTm8/view?usp=sharing to load. Is there going to be a fix soon for the bags. I'm lost without this addon
