### ISSUE TITLE
Patch 7.3 Addon does not work

### ISSUE THREAD

**Issue by ThePsyrex** [AdiAddons/AdiBags#218]
The little Adibags are will pop up but not show any of the content of the bag. I keep getting an error and I have had to disable the addon temporarily. Something is not compliant with the new patch for me. Sorry I don't have more information on what is causing it right now. I can't get back on due to work!

**Comment by TWilloughby** [comment]
I'm also having this issue - the bag & bank frames appear but no Items are shown.  Currency is displayed and the bag bar can be toggled, but the item frame is empty except for a small ... icon.

**Comment by tpittma2** [comment]
Fix can be found here: https://github.com/AdiAddons/AdiBags/issues/217

All credit goes to @Daztek
