### ISSUE TITLE
Unable to view/change bagslots

### ISSUE THREAD

**Issue by mnejing** [AdiAddons/AdiBags#222]
This is on the most recent version (1.9.7, Aug 30/17)

Cannot change bags. Obviously this is a result of the same issues that were (mostly) fixed today. 

![wowscrnshot_083017_192940](https://user-images.githubusercontent.com/31494988/29902219-f669cbe4-8db9-11e7-864b-925c5f3bebe4.jpg)
![wowscrnshot_083017_192945](https://user-images.githubusercontent.com/31494988/29902221-f740669a-8db9-11e7-89e0-67aec3c315cd.jpg)

**Comment by Alyred** [comment]
Until a fix is issued, open Interface\Addons\Adibags\Widgets\BagSlots.Lua, go to line 406, and change it to:
PlaySound(39512)

Just below it, change the other PlaySound function to:
PlaySound(39513)

Here's how the two functions look in the code:
`local function Panel_OnShow(self)
	PlaySound(39512)
	addon:SendMessage('AdiBags_FiltersChanged', true)
end

local function Panel_OnHide(self)
	PlaySound(39513)
	addon:SendMessage('AdiBags_FiltersChanged', true)
end`
