### ISSUE TITLE
Error 0000021E5EED50

### ISSUE THREAD

**Issue by camreonc** [AdiAddons/AdiBags#223]
So this addon was good, Until while i was i playing it doesn't show my bag.The space is gone,idk what to do?
![wowscrnshot_082917_213903](https://user-images.githubusercontent.com/31500695/29957825-65a89d74-8ea4-11e7-91cd-3706188f30b9.jpg)

**Comment by Talyrius** [comment]
You need to update the addon. Those errors have been fixed.

**Comment by camreonc** [comment]
do i just redownload the new one?

**Comment by Talyrius** [comment]
Yes?
