### ISSUE TITLE
Legendary item filter missing

### ISSUE THREAD

**Issue by Mycologist** [AdiAddons/AdiBags#224]
I may be blind, but I can no longer find the ability to group all legendary items together. I found this useful, but it's missing from the 7.3 update.

**Comment by SpareSimian** [comment]
Could that be a filter plugin?

**Comment by Mycologist** [comment]
It's entirely possible. I could revert some of the plugins I have and see if it's something in one of them.  I'll do that when I have time later this evening and report back.

**Comment by Mycologist** [comment]
Sure enough it was, a recent update broke that particular filter. My mistake that I thought this was part of the base addon.
