### ISSUE TITLE
Incorrect and/or missing AP amount displayed on tokens

### ISSUE THREAD

**Issue by jasonb4610** [AdiAddons/AdiBags#225]
I've noticed this since the 7.3 patch that some AP tokens are showing incorrect values and consequently the total in the currency bar is showing an incorrect amount of total AP in bags. A good example is the daily heroic AP token which awards 64 million AP as of the first week of patch at max AK, the token displays 20.4 million instead.

Another case is where the token displays no amount on the icon in the bag and doesn't add anything to the total AP in the currency bar. This seems far more prevalent on the Argus tokens and is likely somehow related.

**Comment by Talyrius** [comment]
AdiBags doesn't display Artifact Power on redemption tokens. Perhaps another addon is to blame (a plugin)?

**Comment by jasonb4610** [comment]
I know its been there before, maybe its part of the legion filters plugin.
