### ISSUE TITLE
error on bag open

### ISSUE THREAD

**Issue by undrinkableb** [AdiAddons/AdiBags#226]
When I try to open my bags, I get just the top bit (Backpack, search bar, etc., then the bottom bit with the currencies), and an error:
![adibug](https://user-images.githubusercontent.com/31554162/29990546-acfeb7e4-8f49-11e7-8cf2-6e9144233222.png)

**Comment by Talyrius** [comment]
You need to update the addon. Those errors have been fixed.

**Comment by undrinkableb** [comment]
There's no update available through the client for anything except the hearthstones plugin.

**Comment by Talyrius** [comment]
![image](https://user-images.githubusercontent.com/1068810/29991090-8aecc316-8f36-11e7-99d1-95512271b489.png)

**Comment by undrinkableb** [comment]
Yep, apparently I had to clear the client cache and restart it for that one (and some others) to show, despite having several other updates come through just fine.
