### ISSUE TITLE
AdiBags VS Guild Bank

### ISSUE THREAD

**Issue by Bobeara** [AdiAddons/AdiBags#227]
I understand not wanting to include a guild bank but my issue is it wont open at all. The closest I get to it opening.... When I first Log into WoW and try to open my guild bank, AdiBags opens and so does my original wow interface bag opens. Other than that, nothing. I looked through all of the settings but couldn't figure it out. Please help, I need to snag Flasks!!!
![issue](https://user-images.githubusercontent.com/31675292/30088363-0b3e2de6-9263-11e7-8e76-7760676ce391.PNG)

**Comment by Talyrius** [comment]
The guild bank opens for me just fine. Do you have more than one bag addon enabled?

BTW, you can reduce the width of the frame by tracking fewer currencies.

**Comment by Bobeara** [comment]
No other bag add on while trying this one. I have one but it is disabled. 
Thanks for the tip!
