### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by SteelTheory** [AdiAddons/AdiBags#23]
Particularly with the latest 1.8.3 version, My bags frames are often off the screen.  Particularly problematic when the (N)(D) buttons are inaccessible.  This happened before, but not as badly.  I have been playing with the settings, but each change raises a new problem, and things like this keep happening.  examples:
Bank off left side of screen:
![wowscrnshot_122314_185344 - adibags1_a](https://cloud.githubusercontent.com/assets/10298812/5554921/bb72f366-8c50-11e4-911b-9d263598c644.jpg)
Bank (Reagents) off top of screen:
![wowscrnshot_122314_191224 - adibags2_a](https://cloud.githubusercontent.com/assets/10298812/5554924/f7d9872a-8c50-11e4-993c-e963e2defb7a.jpg)

As a side note, I think I found the rows-sorting method easier to navigate than the new column-based formatting method.  Also, often leaves several column-widths of space empty on right side.  Love the addon, though.  Can't work without it.  Thanks, hope this helps.

**Comment by SteelTheory** [comment]
I don't see that as a fix.  People are invariably going to have many items which fit a category.  Especially with regards to gear types and trade goods.  
Also, I already manually sort many things, but I don't quite know how to get it to automatically separate certain sub-types.  Even the BoE addon filter doesnt work on all BoE items.

**Comment by Cidan** [comment]
I'm closing this report as it's rather old now and mostly out of date. New fixes are coming in soon to help eliminate this problem.

Thanks.
