### ISSUE TITLE
Force section order?

### ISSUE THREAD

**Issue by vonKoenigsberg** [AdiAddons/AdiBags#231]
Is there any way to force a section order? The priority list only forces item assignments to groups but not the order the sections are displayed.

**Comment by Talyrius** [comment]
No and that's by design. Restricting the section order would take away the flexibility in which the bags are displayed. The goal is to reduce the amount of screen real estate being used while also providing categorization. The 'compact layout' option further prioritizes this space saving.

**Comment by vonKoenigsberg** [comment]
Your argument would make sense of there wasn't already a compact layout option. Fail.

**Comment by Talyrius** [comment]
You're misunderstanding the context for the option. It's similar to Gmail's display density options:
![image](https://user-images.githubusercontent.com/1068810/30250966-137e7518-960c-11e7-96f6-d97c566ecc7b.png)

The default behavior would be similar to the 'cozy' option.

Strict section ordering isn't a feature that can be simply added without further adding to the complexity of the layout code.
