### ISSUE TITLE
Icons don't refresh when chest is opened

### ISSUE THREAD

**Issue by AcidWeb** [AdiAddons/AdiBags#232]
When chest like emissary one is opened and item drop from it that item still displayed with chest icon. Reopening backpack fix this issue.

No LUA errors.

**Comment by gitsocko** [comment]
This happens to me when I open a 200% success chance reputation item from an order hall mission.  The icon does not update to the reputation item inside (e.g., Highmountain rep token, Wardens rep token), but instead shows the icon of the token's generic "wrapping" (Greater Tribute of the Broken Isles).

**Comment by VikingSven82** [comment]
Seems to happen for any item that you "open" that spawns a new item that goes into the same category as the one you opened.

**Comment by Talyrius** [comment]
This should no longer occur.
