### ISSUE TITLE
Bag items not useable

### ISSUE THREAD

**Issue by aaroncom2005** [AdiAddons/AdiBags#236]
Hi, Some (all in my case) bag items are not clickable, not to sell, use, consume, anything....that has happened since the latest wow patch....

**Comment by Talyrius** [comment]
If that's the case, there's probably an error that accompanies the behavior... Does a `/reload` fix it?

**Comment by aaroncom2005** [comment]
No, I’m afraid it does not.

Aaron Braun

**Comment by Talyrius** [comment]
Did you check for errors?

Try running this command (note: you'll lose your current AdiBags settings):
`/run AdiBagsDB = nil; ReloadUI()`

**Comment by aaroncom2005** [comment]
Sorry for getting back so late, it started working again on its own....

Aaron Braun
