### ISSUE TITLE
Lua error in ContainerFrame

### ISSUE THREAD

**Issue by Tykwer** [AdiAddons/AdiBags#237]
Hello,

I've been ignoring this error for quite some time as it just required the occasional /reload and didn't affect every play session.  However, lately it has been happening far more frequently (every login), and always at the same time (upon closing my bank or bags).  Thanks so much in advance for your help.

Date: 2017-09-25 15:20:40
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\ContainerFrame.lua line 996:
   AdiBagsSection4:SetPoint(): AdiBagsSection8 is dependent on this
Debug:
   [C]: SetPoint()
   AdiBags\widgets\ContainerFrame.lua:996: LayoutSections()
   AdiBags\widgets\ContainerFrame.lua:1067:
      AdiBags\widgets\ContainerFrame.lua:1041
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:155
   [string "safecall Dispatcher[2]"]:4:
      [string "safecall Dispatcher[2]"]:4
   [C]: ?
   [string "safecall Dispatcher[2]"]:13: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: SendMessage()
   AdiBags\core\Core.lua:445: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
   (tail call): ?
   [C]: ?
   AdiBags\core\Bags.lua:281: PostClose()
   AdiBags\core\Bags.lua:101: Close()
   AdiBags\core\Bags.lua:130:
      AdiBags\core\Bags.lua:130
Locals:
None
AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  NPCScanOverlay, v7.3.0.1
  NPCScanOverlayBroker, v1.2.7
  Ace3, v
  AceGUI30SharedMediaWidgets, v
  AdiBags, vv1.9.8
  Altoholic, vr183
  ArtifactPower, v1.2.5
  AucAdvanced, v7.5.5724 (TasmanianThylacine)
  AucFilterBasic, v7.5.5724 (TasmanianThylacine)
  AucFilterOutlier, v7.5.5724.5459(7.5/embedded)
  AucMatchUndercut, v7.5.5724.5585(7.5/embedded)
  AucStatHistogram, v7.5.5724 (TasmanianThylacine)
  AucStatiLevel, v7.5.5724 (TasmanianThylacine)
  AucStatPurchased, v7.5.5724 (TasmanianThylacine)
  AucStatSales, v7.5.5724.5598(7.5/embedded)
  AucStatSimple, v7.5.5724 (TasmanianThylacine)
  AucStatStdDev, v7.5.5724 (TasmanianThylacine)
  AucStatWOWEcon, v7.5.5724.5613(7.5/embedded)
  AucUtilAHWindowControl, v7.5.5724.5575(7.5/embedded)
  AucUtilAppraiser, v7.5.5724.5719(7.5/embedded)
  AucUtilAskPrice, v7.5.5724.5599(7.5/embedded)
  AucUtilAutoMagic, v7.5.5724.5686(7.5/embedded)
  AucUtilCompactUI, v7.5.5724.5715(7.5/embedded)
  AucUtilEasyBuyout, v7.5.5724.5576(7.5/embedded)
  AucUtilFixAH, v7.5.5724 (TasmanianThylacine)
  AucUtilItemSuggest, v7.5.5724.5651(7.5/embedded)
  AucUtilPriceLevel, v7.5.5724.5633(7.5/embedded)
  AucUtilScanButton, v7.5.5724.5631(7.5/embedded)
  AucUtilScanFinish, v7.5.5724.5720(7.5/embedded)
  AucUtilScanProgress, v7.5.5724.4979(7.5/embedded)
  AucUtilScanStart, v7.5.5724.5347(7.5/embedded)
  AucUtilSearchUI, v7.5.5724.5721(7.5/embedded)
  AucUtilSimpleAuction, v7.5.5724.5705(7.5/embedded)
  AucUtilVendMarkup, v7.5.5724.4828(7.5/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, vv7.3.45
  Bartender4, v4.7.10
  BeanCounter, v7.5.5724 (TasmanianThylacine)
  BetterBattlePetTooltip, v7.3.0.0
  brokerggsocialstate, v6.2.4
  CallbackHandler10, v
  ChatFontsPlus, v0.3
  Chinchilla, vv2.8.5
  ClassMods, vv7.3.0.0
  Clique, vv70200-1.1.0
  Configator, v5.1.DEV.431(/embedded)
  CurseProfiler, v
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAgenda, vr26
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreQuests, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  DBMCore, v7.3.3
  DBMDefaultSkin, v
  DBMLDB, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DraenorTreasures, v7.3.0.24974
  Enchantrix, v7.5.5724 (TasmanianThylacine)
  FishingBuddy, v1.7.13i
  GatherMate2, v1.41
  GetLink, vr033017a
  GoGoMount, v7.1.1
  HideBossFrames, v3.70000
  InFlightLoad, v7.3.001
  Informant, v7.5.5724 (TasmanianThylacine)
  LegionWardrobe, v29
  LibExtraTip, v5.12.DEV.430(/embedded)
  LibPetJournal20, v
  LibQTip10, vr178-release 
  LibSharedMedia30, v3.0-97
  LibStub, v
  LucidNightmareHelper, v
  MasterPlanA, vA
  MinimapButtonFrame, v3.1.10e
  MinimapButtonFrameSkinPack, v3.0.1b
  MoveAnything, v16.3.0
  NeedToKnow, v4.0.26
  NoPetBattleTab, v
  Overachiever, v0.99.9
  OverachieverTabs, v0.99.9
  ParagonReputation, v1.16
  PetBattleTeams, v3.3.9
  SavedInstances, v@project-version@
  SharedMediaAdditionalFonts, v1.0.24
  Skada, v1.7.2
  Stubby, v7.5.5724 (TasmanianThylacine)
  Telemancy, v1.1.8
  TipHelper, v5.12.DEV.405(/embedded)
  TipTac, v16.10.27
  TipTacItemRef, v16.10.27
  TipTacTalents, v16.10.27
  Titan, v5.12.5.70300
  TitanBag, v5.12.5.70300
  TitanClock, v5.12.5.70300
  TitanGold, v5.12.5.70300
  TitanLocation, v5.12.5.70300
  TitanPerformance, v5.12.5.70300
  TitanRepair, v5.12.5.70300
  TitanVolume, v5.12.5.70300
  WIM, v3.7.14
  WorldMapCloseButtonFix, v
  XPBarNone, v70300-1
  ZPerl, v5.4.4
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=fa3)

**Comment by Maxximuss** [comment]
I have been getting a lot of these errors as well, decided to make a github account to report them.

"[12:23] Error in AdiBags: Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:996: AdiBagsSection23:SetPoint(): AdiBagsSection22 is dependent on this -- details: [Error 00000233778794D0] "

There can sometimes quite a few of them, the number behind "AdiBagsSection" can change so its always "AdiBagsSectionXX" where XX is some number.  The result is there are strange shifts and empty spaces in the actual inventory in the bags.

**Comment by Tykwer** [comment]
Hi,

I am sorry that I never updated the GitHub thread on this.  There has not been a fix but there is a simple workaround.  Go into the options and uncheck “compact layout”, and you will stop getting the errors.  At first I was hesitant but tbh not having that option checked didn’t make much of a difference to me, and the errors disappeared.

I am running v1.9.8 and get no Lua errors with that option unchecked.

Good luck!

Matt

**Comment by Tykwer** [comment]
Hi,

I am sorry that I never updated the GitHub thread on this.  There has not been a fix but there is a simple workaround that I learned from the community at some point after my original post.

Go into the options and uncheck “compact layout”, and you will stop getting the errors.  At first I was hesitant but tbh not having that option checked didn’t make much of a difference to me, and the errors disappeared.

I am running v1.9.8 and get no Lua errors with that option unchecked.

Good luck!

Matt

**Comment by Maxximuss** [comment]
Thanks for that tip, will give it a try.
