### ISSUE TITLE
Sending mail confirmation issue

### ISSUE THREAD

**Issue by zalidthebur** [AdiAddons/AdiBags#239]
You added a mail confirmation ("This character might be someone you don't know. Really send xxxx these items?") when sending mail to someone not on your server a little while ago. Recently this has been popping up for characters on my server, and not for other servers.  This is very irritating and obviously not the way it should work.
I tried removing and reinstalling the addon (v1.9.8) without deleting the SavedVariables and it was still the same.
I then renamed the SavedVariables and it was still the same.
So this looks like a setting in the addon.
Hope you can find and fix this.
Thanks.

**Comment by Talyrius** [comment]
This has nothing to do with AdiBags. It's a default Blizzard UI behavior that can't be interfered with by addons. However, a [search](https://www.google.com/search?q=This+character+might+be+someone+you+don%27t+know.+Really+send+these+items%3F+site%3Aus.battle.net) of the official [WoW forums](https://us.battle.net/forums/en/wow/) will reveal that you aren't alone in your frustration with having to deal with it.

I believe it's mostly a problem on connected realms where you have to specify a realm after the character name to differentiate between potential identically named characters (e.g., Talyrius‑Blackrock and Talyrius‑TheForgottenCoast). Some players said adding their alt characters to their friends lists helped to avoid running into the prompt.

As an aside, these are the related [global strings](https://www.townlong-yak.com/framexml/live/GlobalStrings.lua) for anyone who may be curious:
```lua
SEND_ITEMS_TO_STRANGER_WARNING = "This character might be someone you don't know. |n|n Really send %s these items?";
SEND_MONEY_TO_STRANGER_WARNING = "This character might be someone you don't know. |n|n Really send %s the following amount?";
```

**Comment by zalidthebur** [comment]
Sorry about that. I thought you had added it. Thanks for the info. Will now go bug Blizzard ;-)
