### ISSUE TITLE
Duplicate Bank Inventory Frames on Alts 

### ISSUE THREAD

**Issue by Rav3n7x** [AdiAddons/AdiBags#240]
Hello,
I 'm having this issue on several of my alts. When i open the bank, i get double window frames.
So what i mean is when i open my bank on several of my characters it opens up the adibag frames and some other window frames aswell. Anyone got the same issue? 

See attached image.

thanks

![image](https://user-images.githubusercontent.com/33133047/32069640-6dff8ba8-ba92-11e7-9d61-c8d2aad9a31e.png)

**Comment by 26209** [comment]
You have the bags option enabled on ElvUI as well as adibags enabled. Turn off one and you won't see two windows.
