### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by Korrigan1340** [AdiAddons/AdiBags#241]
Error and needed to be disabled to log out, /camp or exit game.
This was a new one...fun one

**Comment by Talyrius** [comment]
This was fixed long ago (#217). In the future, make sure you have the [newest version](https://mods.curse.com/addons/wow/adibags) before opening an issue.

**Comment by Korrigan1340** [comment]
Haha I do have the current version. Rude fck

**Comment by Talyrius** [comment]
No, you don't. I wasn't being rude…

**Comment by SpareSimian** [comment]
This was fixed 2 months ago, released August 31 as v1.9.8, and pushed to Curse. The only rudeness I see here is from the bug reporter.

**Comment by Korrigan1340** [comment]
Yea..of course. Since curse has a current version from Feb. Buttinski

**Comment by niclake** [comment]
I don't really understand why you're attacking the reporter. I'm on 1.9.8, game v7.3.0, and this bug has been happening to me frequently.

**Comment by Talyrius** [comment]
All PlaySound call errors have been fixed in [v1.9.8](https://www.wowace.com/projects/adibags/files/2473344). If you're still receiving them, you don't have v1.9.8.

**Comment by niclake** [comment]
According to Twitch Mods, I have v1.9.8, with game version 7.3.0, author Adirelle. I made certain to verify this. I then went in to Adibags/widgets and found ContainerFrame.lua (all surrounding files have a modified date of 12/10/17 @ 07:50), found the two lines relating to PlaySound, and commented them out.

**Comment by Talyrius** [comment]
There is no need to comment out those lines in v1.9.8 as they will not trigger errors.

In patch 7.3, the [PlaySound](https://wow.gamepedia.com/API_PlaySound) function stopped accepting string arguments. It now requires the use of a soundKitID. Commits 5e6a839 and 10a4840 changed the string arguments to their relevant SOUNDKIT table references which contain a soundKitID.

**Comment by niclake** [comment]
Well, then there's another bug.

Rather than necroing this one, I'll create a new one & post logs there.
