### ISSUE TITLE
Optional search library integration?

### ISSUE THREAD

**Issue by gitsocko** [AdiAddons/AdiBags#244]
I really love AdiBags!  It's *so* easy to find things now that I can hide rarely used groups of items.  The only thing I miss from my previous inventory mod (OneBag3) is more powerful search capability.  OneBag3 uses a 3rd party search library called LibItemSearch (https://github.com/Jaliborc/LibItemSearch-1.2).  I never noticed a performance hit while using it, and would love to have that library's search functionality.  Is this something I could add to AdiBags myself by changing a few lines of code, or would it be a big chore to integrate?

**Comment by psykzz** [comment]
👍  to this request.
Looks like they are just using the built in wow search.

Most of the work would need to be done in https://github.com/AdiAddons/AdiBags/blob/master/widgets/ItemButton.lua#L340-L347

along with the custom search handler being attached to this frame / button
https://github.com/AdiAddons/AdiBags/blob/5e6a839a342fe3a992974476b790bcccf7b1acc1/widgets/ContainerFrame.lua#L191-L196

**Comment by Talyrius** [comment]
See #38.
