### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by serendipity09** [AdiAddons/AdiBags#250]
4x AdiBags\widgets\Section.lua:483: attempt to index local 'b' (a nil value)
AdiBags\widgets\Section.lua:483: in function <AdiBags\widgets\Section.lua:482>
[C]: ?
AdiBags\widgets\Section.lua:365: in function `FullLayout'
AdiBags\widgets\ContainerFrame.lua:953: in function `PrepareSections'
AdiBags\widgets\ContainerFrame.lua:1058: in function <AdiBags\widgets\ContainerFrame.lua:1041>
(tail call): ?
AdiBags\widgets\ContainerFrame.lua:447: in function `RefreshContents'
AdiBags\widgets\ContainerFrame.lua:432: in function `ResumeUpdates'
AdiBags\widgets\ContainerFrame.lua:415: in function <AdiBags\widgets\ContainerFrame.lua:407>
[C]: in function `Show'
AdiBags\core\Bags.lua:89: in function `Open'
AdiBags\core\Bags.lua:262: in function `?'
...
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `SendMessage'
AdiBags\core\Core.lua:447: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:85>
(tail call): ?

Locals:
a = AdiBagsItemButton138 {
 timeSinceUpgradeCheck = 0
 bag = 9
 BattlepayItemTexture = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 icon = AdiBagsItemButton138IconTexture {
 }
 container = AdiBagsContainer2 {
 }
 acquired = true
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1122
 caerdonButton = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton138Cooldown {
 }
 bagFamily = 0
 CanIMogItOverlay = CIMIOverlayFrame_AdiBagsItemButton138 {
 }
 flash = <unnamed> {
 }
 section = AdiBagsSection22 {
 }
 IconQuestTexture = AdiBagsItemButton138IconQuestTexture {
 }
 hasItem = true
 IconTexture = AdiBagsItemButton138IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 Stock = AdiBagsItemButton138Stock {
 }
 slot = 5
 0 = <userdata>
 NormalTexture = AdiBagsItemButton138NormalTexture {
 }
 texture = 962046
 Count = AdiBagsItemButton138Count {
 }
 itemLink = "|cffffffff|Hitem:124051::::::::110:70::::::|h[]|h|r"
 newitemglowAnim = <unnamed> {
 }
 searchOverlay = AdiBagsItemButton138SearchOverlay {
 }
 itemId = 124051
 count = 1
}
b = nil
(*temporary) = 124051
(*temporary) = AdiBagsItemButton138 {
 timeSinceUpgradeCheck = 0
 bag = 9
 BattlepayItemTexture = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 icon = AdiBagsItemButton138IconTexture {
 }
 container = AdiBagsContainer2 {
 }
 acquired = true
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1122
 caerdonButton = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton138Cooldown {
 }
 bagFamily = 0
 CanIMogItOverlay = CIMIOverlayFrame_AdiBagsItemButton138 {
 }
 flash = <unnamed> {
 }
 section = AdiBagsSection22 {
 }
 IconQuestTexture = AdiBagsItemButton138IconQuestTexture {
 }
 hasItem = true
 IconTexture = AdiBagsItemButton138IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 Stock = AdiBagsItemButton138Stock {
 }
 slot = 5
 0 = <userdata>
 NormalTexture = AdiBagsItemButton138NormalTexture {
 }
 texture = 962046
 Count = AdiBagsItemButton138Count {
 }
 itemLink = "|cffffffff|Hitem:124051::::::::110:70::::::|h[]|h|r"
 newitemglowAnim = <unnamed> {
 }
 searchOverlay = AdiBagsItemButton138SearchOverlay {
 }
 itemId = 124051
 count = 1
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'b' (a nil value)"
itemCompareCache = <table> {
 151564:124461 = true
 140896:152782 = true
 136708:127847 = false
 129100:151719 = false
 130173:151720 = false
 147870:104305 = false
 147013:134525 = true
 140155:136708 = true
 36926:124439 = true
 109599:111820 = false
 130173:124105 = false
 144391:142469 = true
 134234:134190 = true
 124444:36917 = false
 124113:124444 = true
 142159:147006 = false
 124444:129100 = false
 147870:28455 = true
 151568:124110 = false
 151568:124113 = true
 33969:56836 = true
 137486:147015 = false
 130180:130175 = true
 137439:147025 = false
 133642:147015 = false
 18706:143661 = true
 140493:128353 = false
 130178:124124 = false
 130178:129100 = true
 140493:118663 = false
 33016:33969 = false
 18562:124444 = true
 139102:144482 = false
 146985:147193 = false
 140896:137369 = true
 18706:124051 = true
 124106:130182 = true
 134408:137046 = false
 151567:124437 = true
 124105:151565 = false
 122124:132982 = false
 134490:134526 = false
 124101:120945 = false
 141017:46874 = false
 108257:98717 = true
 147157:134539 = true
 146985:133644 = false
 103678:63206 = true
 130224:130235 = false
 151722:124105 = false
 134360:147063 = false
 133589:130182 = true
 147072:134500 = false
 72104:130173 = false
 140155:139347 = false
 130224:130223 = false
 94583:94588 = true
 136736:147193 = true
 136715:147025 = false
 151722:124102 = false
 124124:89112 = true
 52182:130174 = false
 147158:144275 = false
 147158:147012 = false
 147066:146985 = true
 139347:133576 = false
 137065:147014 = true
 130236:151590 = false
 146985:134533 = false
 127834:116268 = true
 133579:136708 = true
 147158:136750

**Comment by nechapemnic** [comment]
28x AdiBags\widgets\Section.lua:483: attempt to index local 'b' (a nil value)
AdiBags\widgets\Section.lua:483: in function <AdiBags\widgets\Section.lua:482>
[C]: ?
AdiBags\widgets\Section.lua:365: in function `FullLayout'
AdiBags\widgets\ContainerFrame.lua:953: in function `PrepareSections'
AdiBags\widgets\ContainerFrame.lua:1058: in function <AdiBags\widgets\ContainerFrame.lua:1041>
(tail call): ?
AdiBags\widgets\ContainerFrame.lua:447: in function `RefreshContents'
AdiBags\widgets\ContainerFrame.lua:432: in function `ResumeUpdates'
AdiBags\widgets\ContainerFrame.lua:415: in function <AdiBags\widgets\ContainerFrame.lua:407>
[C]: in function `Show'
AdiBags\core\Bags.lua:89: in function `Open'
AdiBags\core\Bags.lua:119: in function <AdiBags\core\Bags.lua:115>
(tail call): ?
(tail call): ?
FrameXML\MainMenuBarBagButtons.lua:54: in function `BackpackButton_OnClick'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>

Locals:
a = AdiBagsItemButton128 {
 NormalTexture = AdiBagsItemButton128NormalTexture {
 }
 bag = 1
 BattlepayItemTexture = <unnamed> {
 }
 filterName = "Gear manager item sets"
 BagStaticTop = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 icon = AdiBagsItemButton128IconTexture {
 }
 container = AdiBagsContainer1 {
 }
 acquired = true
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1298
 ExtendedOverlay = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton128Cooldown {
 }
 bagFamily = 0
 BagStaticBottom = <unnamed> {
 }
 flash = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 IconQuestTexture = AdiBagsItemButton128IconQuestTexture {
 }
 hasItem = true
 IconTexture = AdiBagsItemButton128IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 Stock = AdiBagsItemButton128Stock {
 }
 slot = 1
 count = 1
 section = AdiBagsSection2 {
 }
 timeSinceUpgradeCheck = 0
 texture = 237241
 0 = <userdata>
 Count = AdiBagsItemButton128Count {
 }
 itemLink = "|cffffffff|Hitem:147017::::::::110:258::5:3:3562:1502:3336:::|h[]|h|r"
 itemId = 147017
 searchOverlay = AdiBagsItemButton128SearchOverlay {
 }
 newitemglowAnim = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
}
b = nil
(*temporary) = 147017
(*temporary) = AdiBagsItemButton128 {
 NormalTexture = AdiBagsItemButton128NormalTexture {
 }
 bag = 1
 BattlepayItemTexture = <unnamed> {
 }
 filterName = "Gear manager item sets"
 BagStaticTop = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 icon = AdiBagsItemButton128IconTexture {
 }
 container = AdiBagsContainer1 {
 }
 acquired = true
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1298
 ExtendedOverlay = <unnamed> {
 }
 UpgradeIcon = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton128Cooldown {
 }
 bagFamily = 0
 BagStaticBottom = <unnamed> {
 }
 flash = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 IconQuestTexture = AdiBagsItemButton128IconQuestTexture {
 }
 hasItem = true
 IconTexture = AdiBagsItemButton128IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 Stock = AdiBagsItemButton128Stock {
 }
 slot = 1
 count = 1
 section = AdiBagsSection2 {
 }
 timeSinceUpgradeCheck = 0
 texture = 237241
 0 = <userdata>
 Count = AdiBagsItemButton128Count {
 }
 itemLink = "|cffffffff|Hitem:147017::::::::110:258::5:3:3562:1502:3336:::|h[]|h|r"
 itemId = 147017
 searchOverlay = AdiBagsItemButton128SearchOverlay {
 }
 newitemglowAnim = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'b' (a nil value)"
itemCompareCache = <table> {
 86143:136653 = false
 17202:142361 = true
 127840:127834 = true
 151943:151946 = true
 50130:143479 = false
 109262:147019 = false
 141446:122618 = false
 132437:132444 = false
 21745:138414 = true
 152352:151940 = true
 151942:151954 = true
 153023:127834 = true
 151942:151949 = false
 141652:141446 = true
 146984:151944 = false
 122124:147836 = true
 152680:151973 = false
 104316:64402 = true
 132861:133971 = false
 140587:153023 = true
 104316:86143 = true
 133571:133940 = false
 151943:146996 = true
 132450:151814 = false
 140493:128353 = false
 116429:86143 = false
 118391:21745 = true
 136653:133940 = true
 127834:133571 = false
 128507:122124 = false
 141446:122124 = false
 144438:152626 = false
 141652:137642 = true
 109076:127834 = true
 132450:132409 = false
 152350:151954 = false
 142117:133571 = false
 151942:151937 = true
 127841:127834 = true
 104316:127834 = true
 152424:151953 = true
 147233:151938 = true
 142361:128507 = true
 132861:132444 = false
 142361:137642 = true
 154177:146996 = false
 144438:144259 = false
 49661:71634 = false
 152352:151951 = false
 136654:124442 = false
 142361:151625 = false
 86143:127841 = true
 133940:136653 = false
 127841:127839 = false
 71634:50130 = true
 140192:128353 = true
 152097:143605 = true
 109076:116429 = false
 49927:153021 = false
 132436:152626 = true
 152424:146
