### ISSUE TITLE
Adibag calls protected functions

### ISSUE THREAD

**Issue by chkgrniv** [AdiAddons/AdiBags#251]
3x [ADDON_ACTION_BLOCKED] AddOn 'AdiBags' tried to call the protected function 'OrderHallMissionFrameMissions:SetHeight()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `SetHeight'
...Blizzard_OrderHallUI\Blizzard_OrderHallMissionUI.lua:626: in function `UpdateCombatAllyMission'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:872: in function <...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:869>
(tail call): ?
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:427: in function `UpdateMissions'
...s\Blizzard_GarrisonUI\Blizzard_GarrisonMissionUI.lua:95: in function `OnEventMainFrame'
...Blizzard_OrderHallUI\Blizzard_OrderHallMissionUI.lua:119: in function <...Blizzard_OrderHallUI\Blizzard_OrderHallMissionUI.lua:115>

Locals:
InCombatSkipped

**Comment by Talyrius** [comment]
This was caused by [taint](https://www.townlong-yak.com/taint.log/about.html) incorrectly blamed on AdiBags.
