### ISSUE TITLE
Item levels too high

### ISSUE THREAD

**Issue by SpareSimian** [AdiAddons/AdiBags#258]
Item levels of legion armor in my bags are showing much higher than the value in their tooltip. Draenor items are unaffected. An example is Leywalker Shoes, which show 689 in the tooltip but 729 in Adibags. I suspect a Blizzard API has changed.

Meanwhile, the values displayed by Kibs Item Level in the character panel match the value on the tooltip.

**Comment by SpareSimian** [comment]
It seems this is only affecting green quest reward armor that could potentially be upgraded upon being awarded. The value displayed in the bag is probably its epic value.

**Comment by Maxximuss** [comment]
This actually happens for many items, not just the ones you mentioned, right now I have nearly 10 items in my bags for which the item level is being displayed as too high in comparison to the actual value on the tooltip.  For me the green items are mostly ok but the blue and purple are being highly overrated.

**Comment by Zarggg** [comment]
Yes, these are all level-adjusted items. Item level now scales by player level below 110. I don't know any solutions to this, but that is the cause.

**Comment by Talyrius** [comment]
See #255.
