### ISSUE TITLE
Unwanted Currency displayed

### ISSUE THREAD

**Issue by bigonrice** [AdiAddons/AdiBags#259]
Its the only thing that bothers me about the mod. Other then that its perfect Thanks for making such a great add-on.
![adibags rules but has a glich](https://user-images.githubusercontent.com/35749242/35308131-d4ebde34-00f1-11e8-9eb1-ffe5bc7e318c.jpg)

**Comment by Talyrius** [comment]
What is the name of the tracked currency? If it isn't togglable in the above list, it's likely being added by a third-party addon.

**Comment by bigonrice** [comment]
Are you sure? I tired clearing all my other add-on's but its still there. Any tips on how to remove it?
![help me](https://user-images.githubusercontent.com/35749242/35367624-015ac230-01cb-11e8-9ed0-0459c38367aa.png)

**Comment by Talyrius** [comment]
Yes. Look for other AdiBags related addons in your addon list. This repository only concerns AdiBags and AdiBags_Config.

**Comment by bigonrice** [comment]
I figured it out myself. I went into the C:\Program Files (x86)\World of Warcraft\WTF and deleted everything there. It reset everything but its finally gone. Thanks for all the feed back hope this helps anyone having the same problem.
