### ISSUE TITLE
Global errors

### ISSUE THREAD

**Issue by uabtodd** [AdiAddons/AdiBags#260]
Past day or two i've been getting a ton of errors everytime i log on, here's the copy/paste.  Any clue?

Date: 2018-03-13 20:49:01
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Filters.lua line 128:
   Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Legion' already exists.
Debug:
   [C]: ?
   ...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:270: NewModule()
   AdiBags\core\Filters.lua:128: RegisterFilter()
   ...ns\AdiBags_Legion_Filters\AdiBags_Legion_Filters.lua:27: in main chunk
Locals:
(*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Legion' already exists."

AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  AdiBags, vv1.9.8
  AdiBagsArmourType, vv1.0
  AdiBagsBoEBoA, vv1.5
  AdiBagsBound, vv1.1
  AdiBagsGarrison, vv1.6
  AdiBagsHearthstones, v7.3-release1
  AdiBagsLegion, vv1.6
  AdiBagsLegionFilters, v1.6.7
  BlizRuntimeLib_enUS v7.3.5.70300 <none>
  (ck=123)

**Comment by Talyrius** [comment]
This error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.
