### ISSUE TITLE
Loading into game.

### ISSUE THREAD

**Issue by cototheburn** [AdiAddons/AdiBags#261]
1x ...ddOns\TradeSkillMaster_CompetitorTracker\Tracker.lua:91: attempt to call method 'NewModule' (a nil value)
...ddOns\TradeSkillMaster_CompetitorTracker\Tracker.lua:91: in function `RegisterModule'
...ddOns\TradeSkillMaster_CompetitorTracker\Tracker.lua:66: in function <...ddOns\TradeSkillMaster_CompetitorTracker\Tracker.lua:55>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:529: in function `InitializeAddon'
...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0-12.lua:644: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals:
nil

**Comment by Talyrius** [comment]
This error is regarding TradeSkillMaster_CompetitorTracker, not AdiBags.
