### ISSUE TITLE
Extra currency shows up with 5 600 000 000

### ISSUE THREAD

**Issue by Mal-content** [AdiAddons/AdiBags#264]
Some mysterious extra currency shows up even when turned off all of them. It shows amount of 5 600 000 000

Looks like that: https://i.imgur.com/04KPEd8.png

It's a bit annoying.

Beside that awesome addon!

**Comment by Talyrius** [comment]
See #259. You have a third-party plugin that's adding that tracked currency.

**Comment by Zarggg** [comment]
You appear to be using some version of ElvUI. Tracking artifact power on the bag frame is a function in that addon.
