### ISSUE TITLE
Mark Unequipple Items

### ISSUE THREAD

**Issue by kealsera** [AdiAddons/AdiBags#265]
FeatureRequest:

I'd really like to be able to highlight/mark unequippable Items with a red glow.
Be it either by type or level requirement

Greetings :)

**Comment by BevansDesign** [comment]
I think this falls into the "Things that Will Likely Not Be Implemented" section.
https://www.wowace.com/projects/adibags

> Anything that requires to scan item tooltips
> Tooltip scanning is quite CPU-consuming and above all requires asynchronous programming, since item tooltips would not always be available at the time AdiBags should use them. This would raise the complexity of bag filtering be an order of magnitude and turn AdiBags into a CPU hog.
> 
> Some examples what requires to scan the item tooltips:
> 
> detecting the kind and state of binding: unbound, soulbound, bind-on-pickup, bind-on-equip…
> detecting already known spells/pets/recipes or faction/race/level/skill/class restrictions ; basically any “red text” in the tooltip.
