### ISSUE TITLE
Font Sizing & Fix (kind of?)

### ISSUE THREAD

**Issue by midnightgirlj** [AdiAddons/AdiBags#267]
For the currency plugin, the fonts don't respect options chosen across characters. Using the same profile, one character gets options of font size 12, 16, 20, 24; while that exact profile on another character yields options of 7, 11, 15, 19, 23 only. This happens with new profiles, copied profiles (copying one with odd choices will not change the even choices), and the add-on generated character name profile.

So while that is really strange, taking a look at the Font.lua file in the core folder, the steps for fonts (line 167) are set to 4. If that is changed to 1, then you can set the font to any number in the 7-23, or 8-24, (or 4-20 for section header) min/max range. I know basically zero about lua code, but it was like a 30 second fix. This fixes the font options for skinning as well as the currency plugin. So now at least all my profiles can enjoy font size 12 or whatever no matter what the min/max show.

**Comment by Alyred** [comment]
This does indeed work great.

**Comment by Imiona** [comment]
Perfect!
