### ISSUE TITLE
Error after 8.0.1 AdiBags update

### ISSUE THREAD

**Issue by fatalicus** [AdiAddons/AdiBags#273]
After installing the 8.0.1 update for AdiBags, on some characters the inventory doesn't show anything.

BugSack show this error:

> 1x AdiBags\widgets\ContainerFrame.lua:932: attempt to compare boolean with string
(tail call): ?
>AdiBags\widgets\LayeredRegion.lua:119: in function <AdiBags\widgets\LayeredRegion.lua:108>
>
>Locals:
>nil

**Comment by pixiejen** [comment]
Same exact issue here, tried reinstalling the addon to no avail.  This is the best bag addon please help!

I do not get any error btw, all the window shows is Currency at the bottom, but nothing else.
![adibas](https://user-images.githubusercontent.com/41373546/42880058-e4bc5dea-8a60-11e8-9696-e5af8dd1c987.JPG)

**Comment by thetakerfan** [comment]
If you're using any plugin addons, check those. For me, it wouldn't work until I disabled "Adibags Legion Filters" which hasn't been updated.
