### ISSUE TITLE
String to Boolean comparison in ContainerFrame.lua line 932

### ISSUE THREAD

**Issue by timfelle** [AdiAddons/AdiBags#274]
I currently get the following error:

`[04:08 PM] Error in AdiBags: Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:932: attempt to compare string with boolean -- details: [Error 0000027C12593C40] `
`[04:08 PM] Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:932: attempt to compare string with boolean `
`[04:08 PM] (tail call): ?
Interface\AddOns\AdiBags\widgets\LayeredRegion.lua:119: in function <Interface\AddOns\AdiBags\widgets\LayeredRegion.lua:108> `
`[04:08 PM] nil `

I hope this helps to identify one of the bugs preventing the addon to run atm

**Comment by xernon** [comment]
im getting the same Error, remove AdiBags Legion Filters and AdiBags Artifact Weapons if you have this modifications
