### ISSUE TITLE
Color Schemes after squish

### ISSUE THREAD

**Issue by bronze** [AdiAddons/AdiBags#275]
Hi

Can we get an update on the item level colors for bag items? There seems to be a lot of red items after the squish.

And if possible can we also have another choice to see item levels related to the average equipped iLvl? Instead of player level or InventoryItemLevels, if an item is -10 it goes red or +10 purple, something like that. (ElVUI Enhanced does it on character sheet and it helps a lot to see where i need to focus upgrading at a glance)

cheers and thank you for the addon!!

**Comment by Alyred** [comment]
Does anyone have a good guide for the roundabout numbers-to-colors for the new iLvls?  It's a much narrower range.

**Comment by Alyred** [comment]
Guesstimated some iLvls and put some updated code in pull #206. You'll need to edit your local code manually though.

**Comment by Talyrius** [comment]
They've been updated.
