### ISSUE TITLE
Joining Community blocked by Adibags

### ISSUE THREAD

**Issue by Lagorsirion** [AdiAddons/AdiBags#276]
Date: 2018-07-20 14:18:13
ID: 52
Error occured in: AddOn: AdiBags
Count: 1
Message: Error: AddOn AdiBags attempted to call a forbidden function (RedeemTicket()) from a tainted execution path.
Debug:
   [C]: RedeemTicket()
   ...\Blizzard_Communities\CommunitiesInvitationFrame.lua:162: AcceptTicket()
   [string "*:OnLoad"]:1:
      [string "*:OnLoad"]:1
Locals:
None
AddOns:
  Swatter, v7.7.6000 (SwimmingSeadragon)
  AckisRecipeList, v7.3.0.1
  AdiBags, vv1.9.9
  AdiBagsLegionFilters, v1.6.9
  AdvancedInterfaceOptions, v1.2.4
  AngryKeystones, v
  AskMrRobot, v61
  Atlas, vv1.43.06
  AtlasArena, vv1.07.01
  AtlasBattlegrounds, vv1.43.00
  AtlasBurningCrusade, vv1.43.00
  AtlasCataclysm, vv1.43.00
  AtlasClassicWoW, vv1.43.00
  AtlasClassOrderHalls, vv1.43.00
  AtlasDungeonLocs, vv1.43.00
  AtlasLegion, vv1.43.03
  AtlasMistsofPandaria, vv1.43.00
  AtlasOutdoorRaids, vv1.43.00
  AtlasScenarios, vv1.43.01
  AtlasTransportation, vv1.43.01
  AtlasWarlordsofDraenor, vv1.43.00
  AtlasWorldEvents, vv3.23
  AtlasWrathoftheLichKing, vv1.43.01
  AtlasLoot, vv8.07.13
  AtlasLootBurningCrusade, vv8.07.13
  AtlasLootCataclysm, vv8.07.13
  AtlasLootClasses, vv3.1
  AtlasLootClassic, vv8.07.13
  AtlasLootLegion, vv8.07.13
  AtlasLootMistsofPandaria, vv8.07.13
  AtlasLootWarlordsofDraenor, vv8.07.13
  AtlasLootWrathoftheLichKing, vv8.07.13
  AucAdvanced, v7.7.6000 (SwimmingSeadragon)
  AucFilterBasic, v7.7.6000 (SwimmingSeadragon)
  AucStatHistogram, v7.7.6000 (SwimmingSeadragon)
  AucStatiLevel, v7.7.6000 (SwimmingSeadragon)
  AucStatPurchased, v7.7.6000 (SwimmingSeadragon)
  AucStatSimple, v7.7.6000 (SwimmingSeadragon)
  AucStatStdDev, v7.7.6000 (SwimmingSeadragon)
  AucUtilFixAH, v7.7.6000 (SwimmingSeadragon)
  AutoCombatLogger, v7.3.2-4-gf2378c5
  BagBrother, v
  Bartender4, v4.8.1
  BeanCounter, v7.7.6000 (SwimmingSeadragon)
  BetterPowerBarAlt, v1.5.2
  BrokerWorldQuests, v8.0.43
  CallbackHandler10, v
  CandyBuckets, v8.0.0.180630
  ColorPickerPlus, v
  CompactRunes, v8.0.1
  CrucibleWeight, v18
  DataStore, vr64
  DataStoreAchievements, vr46
  DataStoreAgenda, vr26
  DataStoreAuctions, vr49
  DataStoreCharacters, vr41
  DataStoreContainers, vr57
  DataStoreCrafts, vr78
  DataStoreCurrencies, vr36
  DataStoreGarrisons, vr22
  DataStoreInventory, vr51
  DataStoreMails, vr50
  DataStorePets, vr43
  DataStoreQuests, vr43
  DataStoreReputations, vr41
  DataStoreSpells, vr31
  DataStoreStats, vr30
  DataStoreTalents, vr60
  DBMCore, v8.0.0-7-g3e50de67d
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r103
  DressUp, v3.0.0
  Enchantrix, v7.7.6000 (SwimmingSeadragon)
  EnchantrixBarker, v7.7.6000 (SwimmingSeadragon)
  ExRT, v3930
  ExRTClassSpells, v
  FactionAddict, v1.48
  FishingBuddy, v1.9.3
  GatherMate2, v1.42-1-ga027862
  HandyNotes, vr301
  HandyNotesAzerothsTopTunes, vv1.2.1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionRaresTreasures, v1.1
  HandyNotesLegionTreasures, v1
  HandyNotesPandariaTreasures, v1.06
  Informant, v7.7.6000 (SwimmingSeadragon)
  ItemLinkLevel, v1.6
  KeyBooster, v1.0.0.6
  KrosusAssist, v
  LegendaryProgressTracker, v0.3.12
  LibWindow11, v1.1.17
  LucidNightmareHelper, v
  Masque, v8.0.0
  MasterPlanA, vA
  MethodAltManager, vv1
  MethodDungeonTools, v2.1.2
  MogIt, v3.8.6
  MogItOneHanded, v3.8.6
  MogItOther, v3.8.6
  MogItPlate, v3.8.6
  MogItRanged, v3.8.6
  MogItTwoHanded, v3.8.6
  MythicPlusProgress, v0.3e for Patch 7.1.0
  NPCScan, v8.0.1.2
  Omen, v3.2.0
  OmniCC, v8.0.0
  OPie, vVanilla 5
  Overachiever, v1.0.0
  ParagonReputation, v1.19
  Pawn, v2.2.20
  PersoLootRoll, v11
  Postal, vv3.6.0
  Quartz, v3.4.0-3-g65bcdc4
  RaidAchieveFilter, v2.0.1
  RaidAchievement, v
  RaidAchievementOldModules, v
  RaiderIO, v8.0.1 (v201807200600)
  RaiderIODBEUA, v
  RaiderIODBEUH, v
  RCLootCouncil, v2.8.0
  ServerHop, v7.3.0.1
  SexyMap, vv8.0.2
  ShadowedUnitFrames, vv4.2.0-1-g66d7e47
  Simulationcraft, v1.10.1
  Skada, v1.7.3
  SlideBar, v7.7.6000 (SwimmingSeadragon)
  SPTimers, v3.12.1
  Stubby, v7.7.6000 (SwimmingSeadragon)
  SunnArt, v3.78
  SunnArtDiablo, v1.14
  TidyPlates, v6.18.11
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipTac, v18.07.19
  TipTacItemRef, v18.07.19
  TipTacTalents, v18.07.19
  Titan, v5.13.1.70300
  TitanBag, v5.13.1.70300
  TitanClock, v5.13.1.70300
  TitanGold, v5.13.1.70300
  TitanLocation, v5.13.1.70300
  TitanLootType, v5.13.1.70300
  TitanPerformance, v5.13.1.70300
  TitanRepair, v5.13.1.70300
  TitanVolume, v5.13.1.70300
  TitanXP, v5.13.1.70300
  TomTom, vv80001-1.0.2-beta
  VuhDo, v3.93
  VuhDoOptions, v3.93
  WeakAuras, v2.6.0-3-g4fc4ee6
  WIM, v3.7.16
  WorldQuestTracker, v
  BlizRuntimeLib_deDE v8.0.1.80000 <none>
  (ck=1129)

**Comment by Talyrius** [comment]
This was caused by [taint](https://www.townlong-yak.com/taint.log/about.html) incorrectly blamed on AdiBags.
