### ISSUE TITLE
Manual Filtering: Items on Config Screen Overflowing Their "Areas"

### ISSUE THREAD

**Issue by Tykwer** [AdiAddons/AdiBags#278]
Hi, I am on 1.9.9 and am having an issue with the Manual Filtering configuration screen.  When you open this screen, the item icons per section are flowing over the borders, which sometimes obstructs the view of the section or sections below.

![adibags](https://user-images.githubusercontent.com/11846294/43052328-88ab751e-8dd9-11e8-8922-0920b52df50a.jpg)

Thanks for your assistance!

**Comment by Tehrible** [comment]
I'm also on v1.9.9.

Filters can overlap horizontally, as well. In the screenshot, all items are in the "Include" list, and none are in "Exclude"

![6ltkcrq](https://user-images.githubusercontent.com/34458706/43739719-e27823da-997d-11e8-948a-02ce76108d4a.png)

**Comment by Tykwer** [comment]
In the meantime, or in case a fix is not forthcoming, I've realized that an easy workaround is to resize the window ever so slightly (just by clicking and dragging the resize area in the lower right-hand corner).  As soon as you resize the window at all, the columns and borders align and "snap" into their proper places.
Annoying, for sure, but at least it just takes a half a second =)

**Comment by zalidthebur** [comment]
Still not fixed.

**Comment by zalidthebur** [comment]
Still broken in v1.9.13 :-(

**Comment by zalidthebur** [comment]
Still broken in v1.9.16 :-(
Hopefully you do fix this really annoying issue when you get the chance.

**Comment by SpareSimian** [comment]
I'm no longer seeing this so it might be fixed with the latest fixes to Ace3 (which I'm using for another addon, and addons use the latest library even if it comes from another addon). Try installing the standalone Ace3 and see if that fixes it for you.

**Comment by Tykwer** [comment]
Unfortunately, even though I am on the most recent version of Adibags (1.9.16), and Ace3 (r1214), I still see the exact same behavior / overflows.

**Comment by zalidthebur** [comment]
I am already using Ace3 r1214, so it looks like Tykwer is correct and that is not the resolution :-(

**Comment by zalidthebur** [comment]
I also just tried replacing the Ace3 I had with a download of the stand-alone and still have the issue.

**Comment by emerald18** [comment]
I'm on v1.9.17, this still appears to be an issue. The overflow also can make sections towards the bottom of the config window unable to be accessed for further item additions, as they run off the clickable window space.
