### ISSUE TITLE
Selling items causes issues with containers when using the Item Category -> Tradeskill Filter

### ISSUE THREAD

**Issue by bfabe8** [AdiAddons/AdiBags#279]
When using the Item Category -> Tradeskill filter, sometimes after selling items the following error happens repeatedly after opening the bag window. Categories seem to get stuck.

 
Error in AdiBags: Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:997: 
AdiBagsSection10:SetPoint(): AdiBagsSection11 is dependent on this -- details: [Error 0000026FB7FBDFF0] 
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:997: AdiBagsSection10:SetPoint(): AdiBagsSection11 is dependent on this 
[C]: in function `SetPoint'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:997: in function `LayoutSections'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:1068: in function <Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:1042>
(tail call): ?
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:448: in function `RefreshContents'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:433: in function `ResumeUpdates'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:416: in function <Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:408>
[C]: in function `Show'
Interface\AddOns\AdiBags\core\Bags.lua:89: in function `Open'
Interface\AddOns\AdiBags\core\Bags.lua:209: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:90: in function `SendMessage'
Interface\AddOns\AdiBags\core\Core.lua:447: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:90: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:85>
(tail call): ? 
(*temporary) = AdiBagsSection10 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 13
 count = 13
 total = 13
 name = "Herb"
 category = "Tradeskill"
 height = 1
 key = "Tradeskill#Herb"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = AdiBagsSection11 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 3
 count = 3
 total = 3
 name = "Cloth"
 category = "Tradeskill"
 height = 1
 key = "Tradeskill#Cloth"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPRIGHT"
(*temporary) = 10.5
(*temporary) = 0

**Comment by Gholrua** [comment]
My game client crashed on Christmas Day and I lost all my addon data.  I've been since setting everything back up and have been getting errors similar to this one since then.  I've tried everything I can think of to avoid it and still this error occurs ALL the time.  It did NOT happen prior to my wipe.  I'm not sure if there's something I may have done before that helped me avoid it but I'm pretty sure I didn't manually edit the LUA files cause I'm pretty sure the addon was listed as "Up to Date" in my Twitch client.
