### ISSUE TITLE
'AdiBags' tried to call the protected function 'MainMenuBar:ClearAllPoints()'.

### ISSUE THREAD

**Issue by als30334** [AdiAddons/AdiBags#285]
1x [ADDON_ACTION_BLOCKED] AddOn 'AdiBags' tried to call the protected function 'MainMenuBar:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `ClearAllPoints'
FrameXML\MainMenuBar.lua:43: in function `SetPositionForStatusBars'
FrameXML\MainMenuBar.lua:8: in function `OnStatusBarsUpdated'
FrameXML\StatusTrackingManager.lua:179: in function `LayoutBars'
FrameXML\StatusTrackingManager.lua:84: in function `UpdateBarsShown'
FrameXML\StatusTrackingManager.lua:206: in function <FrameXML\StatusTrackingManager.lua:202>
[C]: ?
[C]: ?
[C]: in function `SetCVar'
Broker_Everything\shared.lua:192: in function `SetCVar'
Broker_Everything\modules/volume.lua:112: in function `_OnMouseUp_func'
...s\Broker_Everything\libs\LibQTip-1.0\LibQTip-1.0-46.lua:1337: in function <...s\Broker_Everything\libs\LibQTip-1.0\LibQTip-1.0.lua:1336>

Locals:
InCombatSkipped

**Comment by Talyrius** [comment]
This was caused by [taint](https://www.townlong-yak.com/taint.log/about.html) incorrectly blamed on AdiBags.
