### ISSUE TITLE
Item Level incorrect

### ISSUE THREAD

**Issue by hungrypilot** [AdiAddons/AdiBags#288]
It seems BfA items are showing the wrong item level

**Comment by FrogZilla083** [comment]
Here is the error.

130x AdiBags\modules\ItemLevel.lua:340: bad argument #1 to 'unpack' (table expected, got nil)
[C]: ?
AdiBags\modules\ItemLevel.lua:340: in function `?'
AdiBags\modules\ItemLevel.lua:139: in function `?'
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `SendMessage'
AdiBags\widgets\ItemButton.lua:316: in function `Update'
AdiBags\widgets\ItemButton.lua:287: in function `FullUpdate'
AdiBags\widgets\ItemButton.lua:252: in function <AdiBags\widgets\ItemButton.lua:240>
[C]: in function `Show'
AdiBags\widgets\Section.lua:112: in function <AdiBags\widgets\Section.lua:110>
[C]: ?
[C]: in function `Show'
AdiBags\core\Bags.lua:89: in function `Open'
AdiBags\core\Hooks.lua:112: in function <AdiBags\core\Hooks.lua:109>
(tail call): ?
(tail call): ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
InCombatSkipped
