### ISSUE TITLE
Bag's seem to break randomly

### ISSUE THREAD

**Issue by Solgath** [AdiAddons/AdiBags#29]
every so often the bag and categories will break, not sure the cause, but see attached image.
![adibags bug](https://cloud.githubusercontent.com/assets/10452131/5665657/a6a00784-97a5-11e4-9d8a-7286c0937301.png)

**Comment by sheaahhoi1** [comment]
This situation....
I tried to reset the setting but the situation has not improved

**Comment by Solgath** [comment]
yeah, nothing i have done has fixed this, just keeps coming back >.<

**Comment by Batchman85** [comment]
main bug plaguing version 1.8 since very beginning, happens way too often

**Comment by DjRicko** [comment]
+1
![wowscrnshot_122414_055627](https://cloud.githubusercontent.com/assets/3160375/5861499/19c150aa-a26a-11e4-81b9-49d64b24a12f.jpg)

**Comment by forbjok** [comment]
I've been having the same issue for a long time now. It didn't seem to be an issue back when I first started using AdiBags (shortly after WoD came out), but at some point it started happening and keeps happening quite frequently. The sort button fixes it, but unfortunately, often when it happens, the title bar gets pushed off the top of the screen.

**Comment by mynian** [comment]
I've seen this happen too. From my experience, it only happens when my character levels up.

**Comment by amyloid** [comment]
This is the same as GH-53, which I think I found a fix for.

**Comment by DjRicko** [comment]
Clicking the "sort"/"S" button fixes the bags again. One thing tho, after using "sort", the items have wrong icons but closing/opening bags will fix everything, it's slightly annoying with this happening tho, and it's not ONLY related to leveling as it happens to my level 100s aswell.

**Comment by Zarggg** [comment]
@DjRicko: That's a known issue. I forget which tickets cover it, but I believe it was one of the things that @Adirelle hasn't been able to fix. Closing then re-opening your bags will work around that bug.

**Comment by Cidan** [comment]
This bug has been fixed in an upcoming release.
