### ISSUE TITLE
Receiving the follow error with AdiBags.

### ISSUE THREAD

**Issue by Yarlenad** [AdiAddons/AdiBags#290]
Receiving the following with only AdiBags and AdiBags Config enbled.

5x AdiBags\core\Core.lua:269: bad argument #1 to 'strmatch' (string expected, got nil)
[C]:: ?
AdiBags\core\Core.lua:269: in function <AdiBags\core\Core.lua:268>
[C]:: ?
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function 'Fire'
...erface\AdiBags\libs\BugGrabber\BugGrabber.lua:147: in function <...erface\AdiBags\libs\BugGrabber\BugGrabber.lua:145>
...erface\AdiBags\libs\BugGrabber\BugGrabber.lua:380: in function <...erface\AdiBags\libs\BugGrabber\BugGrabber.lua:294>
...erface\AdiBags\libs\BugGrabber\BugGrabber.lua:604: in function '?'
...erface\AdiBags\libs\BugGrabber\BugGrabber.lua:519: in function <...erface\AdiBags\libs\BugGrabber\BugGrabber.lua:519>

**Comment by Talyrius** [comment]
See #289.
