### ISSUE TITLE
strmatch gets a nil value in Core.lua : 269

### ISSUE THREAD

**Issue by Nexxxy** [AdiAddons/AdiBags#292]
Core.lua line 269 : local ref = strmatch(errorObject.stack, pattern)

errorObject.stack can be nil now leading to lua errors.

add anything like to your code

`
if (errorObject.stack == nil) then

			return

		end
`

**Comment by rubensayshi** [comment]
it's causing huge FPS drops when zoning in

**Comment by Nexxxy** [comment]
i just got 3 LUA errors while starting up. No Errors During gameplay.

With the drop of the errorObject.stack == nil messages i got 0 LUA errors and no further FPS drops

**Comment by Talyrius** [comment]
See #289.
