### ISSUE TITLE
BFA - gear upgrade indicators not appearing

### ISSUE THREAD

**Issue by Kefrqn** [AdiAddons/AdiBags#295]
Hello,

The gear upgrade indicators not appearing on gear in bags. 
In issue #151, there was a trick but it does not seem to work in this version anymore ?

Thanks for your help :)

**Comment by zgrzytus** [comment]
Same problem.

**Comment by padmanek** [comment]
Looking forward to a fix.

**Comment by mathieucollet** [comment]
👍 for a fix !

**Comment by ceesco53** [comment]
The gear upgrade icon displays for me in BfA - no fix needed.  It's just buried underneath the item level.  Try this commit to change the item level location to BOTTOMRIGHT - https://github.com/AdiAddons/AdiBags/pull/178/commits/1f49070d895d83da69b6ad8bb8898597049b6e11

**Comment by mathieucollet** [comment]
> The gear upgrade icon displays for me in BfA - no fix needed. It's just buried underneath the item level. Try this commit to change the item level location to BOTTOMLEFT - 1f49070
It works perfectly. I don't believe that I just missed the arrow underneath the item level.
Thanks mate !

**Comment by Kefrqn** [comment]
Thank you ceesco53, working fine ! :)

**Comment by Zarggg** [comment]
Can this be made a configurable option, please?

**Comment by judgment000** [comment]
I have done the above changes for the lua, but still i can't see the itemupgrade arrow on my bag, i have tried also the #151 still no changes. any work around?
