### ISSUE TITLE
Unable to set bags to "ignore" for purposes of deposit.

### ISSUE THREAD

**Issue by Tovrin** [AdiAddons/AdiBags#30]
I've grown sick of having to drag enchanting vellum out of my reagent bag .... or buy another stack when I forget.  I've been looking for the option to set a specific bag to "ignore" for cleanup and deposit, but I can't find the option.

Could you please add one, or let me know where it is?  I'm sorry I had to raise an issue on github, but there is no other way to provide feedback or ask questions as the thread on wowace hasn't been monitored in 2 years and you've turned off comments in Curse.

**Comment by Zarggg** [comment]
Assuming that your problem is vellum being automatically deposited into your reagent bank, you can disable automatic deposit and transfer items to the bank and reagent bank manually.

**Comment by Adirelle** [comment]
I was thinking about this, but as you will not control where the items are moved, I'm not sure it would be that useful.

**Comment by Tovrin** [comment]
@Zarggg.  That's not the problem.  It's one of the reasons I don't turn on automatic deposits.

The problem is Vellum is deposited.  While ideally Blizzard should fix this so that either they allow Vellum to be enchanted from your bank or simply not deposit into you're reagent bank at all, the chances of Blizzard fixing this (or admitting there's a problem are zero to nil).  

The workaround is to make a bag as "ignored" for deposits.  It's part of the native bag interface.  That way anything in that bag is not deposited.  Adi bags nicely lets me organise specific items into specific bags BUT seems to reset the ignore flag on bags (... I think ... at least that's what testing seems to indicate anyway.  I've disabled Adibags, set the indicator on the bag, then reenabled adibags and deposited reagent; Vellum still gets sent there.

Could someone look into this?  In the interim, it would be nice if ignored bags didn't deposit items into the bank.  Ideally, it would be better if you could set the flag from adibags itself.

Thanks.

**Comment by Adirelle** [comment]
If Blizzard's deposit function ignored what was in bags flagged as "ignored", this would be the only way to prevent items to be moved to the reagent bank. There is only one function in Blizzard API to deposit all the reagents: DepositReagentBank(). It has no parameters and cannot be configured directly.

But using an ignored bag would cause issues too. It would require to move ignored items to that bag and move non-ignored out of that bag, which wouldn't be trivial and would probably waste a loot of space.

The other solution would be to rewrite DepositReagentBank() in lua, which would be tedious, complex and error-prone.

**Comment by Cidan** [comment]
I'm going to close this issue. While I understand the pain behind not being able to ignore specific items to autodeposit, marking a bag as ignored while keeping a unified display would be incredibly messy and confusing to the average user.
