### ISSUE TITLE
Sort soulbound equipment separately

### ISSUE THREAD

**Issue by Ryvix** [AdiAddons/AdiBags#300]
Hi there,

Is there any way to sort soulbound equipment separately? If not, could you please add an option to separate soulbound equipment from BoE so that it makes it easier to vendor/disenchant/scrap them etc.

Thanks!

**Comment by Talyrius** [comment]
Yes, but it requires tooltip scanning (an additional process), which is why it isn't done.

However, [AdiBags BoE & BoA](https://www.curseforge.com/wow/addons/adibags-boe-boa) is a filter plugin that will provide you with what you're looking for.
