### ISSUE TITLE
Category Location

### ISSUE THREAD

**Issue by ErdelyLevy** [AdiAddons/AdiBags#301]
The problem is that the categories with items, regardless of their width, prefer to line up next to each other, rather than in a column (as it is showed on the page of the addon).
![image](https://user-images.githubusercontent.com/42609911/44463826-22b35d80-a643-11e8-9598-f4035797bceb.png)
![image](https://user-images.githubusercontent.com/42609911/44463918-73c35180-a643-11e8-8d1a-e02ba07e093c.png)

**Comment by Talyrius** [comment]
You're tracking too many currencies; that's what's causing your problem.
