### ISSUE TITLE
Cant disable auto-sorting?

### ISSUE THREAD

**Issue by raldon00** [AdiAddons/AdiBags#302]
So maybe Im dumb but... is there any option to disable auto-sorting?
I checked the options and I tried to right click in the "s" in the bags but it doesnt work.
Its frustrating because I would love this addon if i could dissable that feature.
(I just want to be able to change the order of the items, but as soon as I close the bag it changes it)

**Comment by Talyrius** [comment]
Sorry, that's the whole point of this addon.

**Comment by billzilla2000** [comment]
A locked sorting option would make this a must-have and I'd be willing to donate to the cause. I realize 'something else has to give in order for that to work' so it could be a 'new items' row/column that stays like that until you manually resort, or just weight priority of category rows as an option... Something, at least. Seems odd to say 'constant resorting is the whole point' of the addon. I thought it was having more control over sorting, not less.

**Comment by Talyrius** [comment]
Section reordering is in the works. See #675.
