### ISSUE TITLE
Deposit Gold

### ISSUE THREAD

**Issue by Destori** [AdiAddons/AdiBags#305]
I just got this addon, and I can't find how to deposit gold from my bag to the bank.  Can someone provide some guidance? 

Thanks!

**Comment by Zarggg** [comment]
If you're trying to transfer gold to you Guild Bank, you must have the Guild Bank interface to do that. There is no way to store gold in the personal bank.

**Comment by Talyrius** [comment]
Yes, the only bank you can deposit gold into is your Guild Bank.
