### ISSUE TITLE
Lua Error on load, relog and reload

### ISSUE THREAD

**Issue by Axaion** [AdiAddons/AdiBags#306]
Getting this every time i load the game, reload or relog - a lot of fatalites

1x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[C]: in function `error'
AdiBags\libs\LibStub\LibStub.lua:38: in function `LibStub'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:7: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceGUI-3.0".

**Comment by Talyrius** [comment]
Download the addon from [CurseForge](https://www.curseforge.com/wow/addons/adibags), not GitHub.

**Comment by Axaion** [comment]
I used the twitch client for it actually, ill give it a go though.

**Comment by Talyrius** [comment]
I just downloaded it manually via the website and verified that AceGUI-3.0 is embedded as a library. If it weren't working, I'd be seeing many more complaints about it.

The Twitch client is definitely buggy though. It sometimes doesn't reflect that an addon has been updated or downloads the wrong files.

**Comment by Axaion** [comment]
Yeah, i just downloaded it through the website too (cursefoge), and the libs are in the folder, yet im still getting the error which is kind of weird
