### ISSUE TITLE
Since 8.0.1 Adibags floods my chat with the following every time i open my bags.

### ISSUE THREAD

**Issue by HentaiKidd** [AdiAddons/AdiBags#308]
Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:117: attempt to index global 'Item' (a function value) -- details: [Error 0000022BE7C01700] 
Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:117: attempt to index global 'Item' (a function value) -- details: [Error 0000022BE7C01700] 
Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:117: attempt to index global 'Item' (a function value) -- details: [Error 0000022BE7C01700] 
Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:117: attempt to index global 'Item' (a function value) -- details: [Error 0000022BE7C01700] 
Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:117: attempt to index global 'Item' (a function value) -- details: [Error 0000022BE7C01700] 
Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:117: attempt to index global 'Item' (a function value) -- details: [Error 0000022BE7C01700] 
Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:117: attempt to index global 'Item' (a function value) -- details: [Error 0000022BE7C01700] 
Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:117: attempt to index global 'Item' (a function value) -- details: [Error 0000022BE7C01700] 
Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:117: attempt to index global 'Item' (a function value) -- details: [Error 0000022BE7C01700] 
Error in AdiBags: Interface\AddOns\AdiBags\modules\ItemLevel.lua:117: attempt to index global 'Item' (a function value) -- details: [Error 0000022BE7C01700]

Annoying, isn't it...

**Comment by Talyrius** [comment]
`Item` is a global variable declared and used in the Blizzard API. If you're receiving this error, another addon you're using has replaced it.
