### ISSUE TITLE
pluging feature request

### ISSUE THREAD

**Issue by jomoroon** [AdiAddons/AdiBags#313]
Hi,

Big fan of adibags, and the multiple plugins. Is there anyway to add to the current tooltip one that shows how much of an item we have in total. E.g. if we had a reagent in our bag, and we alt + hover over it, it will show us how much we have in total including bank + bag.

Thanks!

**Comment by SpareSimian** [comment]
Install Altoholic. It will show you how much of that item you have in all your toons' bags and banks and in their guild vaults.
