### ISSUE TITLE
Adibags error with guild ranks

### ISSUE THREAD

**Issue by shatteredash** [AdiAddons/AdiBags#320]
As a Guild GM, I need to change ranks of members regularly. Recently, when I attempted to make changes (Once attempting to kick a guild member, and multiple times promoting them) it shows me this message. It may do this to any person that attempts to make changes to guild ranks with Adibags installed, or only to GMs. It may interact incorrectly with Guild Roster Manager, which is what I use to keep it organized. 

![image](https://user-images.githubusercontent.com/45927008/50062707-40ff1500-016e-11e9-976d-8cc65fee3d1a.png)

**Comment by Talyrius** [comment]
This was likely the fault of another addon that uses the same libraries.
