### ISSUE TITLE
Re-implement Pull #206

### ISSUE THREAD

**Issue by Alyred** [AdiAddons/AdiBags#323]
Hi All,
For a long time I've been re-implementing #206 in the new code, but something in the more recent updates broke it to where I haven't been able to fix. I'm still working on it, but my experience with LUA is low and my coding skills are better described as 'hobby-level'.
In the meantime, could we get a version of #206 implemented in the main codestream? Being able to move the upgrade icon was pretty handy, so that we can get it out from under the item level itself. Either that, or move the iLevel text to a different corner of our choice?
Thanks.

**Comment by Talyrius** [comment]
See #303.
