### ISSUE TITLE
I'm trying to install adibags but it is not loading in-game nor does it show in the interface menu

### ISSUE THREAD

**Issue by Sithranio** [AdiAddons/AdiBags#326]
When I log into my character I get the following error:

Date: 2019-02-05 10:47:07
ID: 1
Error occured in: Global
Count: 1
Message: ...AdiBags\libs\LibDataBroker-1.1\LibDataBroker-1.1.lua line 3:
   LibDataBroker-1.1 requires CallbackHandler-1.0
Debug:
   [C]: assert()
   ...AdiBags\libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:3: in main chunk
Locals:
(*temporary) = nil
(*temporary) = "LibDataBroker-1.1 requires CallbackHandler-1.0"

AddOns:
  Swatter, v5.20.5464 (RidiculousRockrat)
  ACP, v3.4.9 
  AdiBags, vv1.6.15

**Comment by Talyrius** [comment]
You need to enable the options addon to see it in the interface menu. However, you appear to have been running a nolib (no libraries included) version.
