### ISSUE TITLE
AdiBags for Guild Bank

### ISSUE THREAD

**Issue by Frurox** [AdiAddons/AdiBags#328]
Can we get an option for Guild Bank? I understand in big guilds this might be an issue but for those who are alone in a guild this would help a lot as it will be like an extra Bank.
This could be a separate addon or an option to turn on or off.

**Comment by Frurox** [comment]
Hi Talyrius, can i know why not? I'm curious, please.

**Comment by Talyrius** [comment]
> ## *[Things that likely will not be implemented](https://github.com/AdiAddons/AdiBags/blob/c7a4c11/README.textile#things-that-likely-will-not-be-implemented)*
> 
> ### *[Guild bank](https://github.com/AdiAddons/AdiBags/blob/c7a4c11/README.textile#guild-bank)*
> 
> *AdiBags presents you a nice view of your bags but actually they are in a complete mess. With AdiBags, there is no need and no way to tidy up the items in the actual bags. Guilds usually try to keep their bank tidy. What would happen if some people in a guild used AdiBags for the guild bank ? Well, they would mess up the guild bank content and people NOT using AdiBags would have to deal with that mess. I can hear the screams from there. So that is why I will not implement guild bank.*

**Comment by Frurox** [comment]
Sorry didn't read that before. Thank you for the reply.
