### ISSUE TITLE
Can't unequip tradeskill bag

### ISSUE THREAD

**Issue by Bterrell721** [AdiAddons/AdiBags#33]
I am trying to replace a tradeskill bag (leatherworking) with a standard pack and it refuses to let me.  The leatherworking bag is empty, and I am able to replace any of my other standard packs with the new one, but for some reason cannot unequip or replace the leatherworking bag in any way.  If I am missing something obvious please let me know, otherwise hopefully we can get a fix asap, thanks!

**Comment by Talyrius** [comment]
This has long since been resolved, no?

Once the tradeskill bag is empty, drag it to an empty slot in a normal bag.
