### ISSUE TITLE
Adibags Disappeared

### ISSUE THREAD

**Issue by Dogenji** [AdiAddons/AdiBags#331]
Release v1.9.13-nolib
Adibags doesn't appear at all, only WoW default
Following show bug sack messages related to this ...
4x AdiBags\core\OO.lua:105: attempt to call global 'LibStub' (a nil value)
AdiBags\core\OO.lua:105: in function <AdiBags\core\OO.lua:103>
AdiBags\core\OO.lua:122: in function `NewClass'
AdiBags\widgets\BagSlots.lua:219: in main chunk

Locals:
name = "BagSlotButton"
frameType = "Button"
frameTemplate = "ItemButtonTemplate"
class = nil
prototype = nil
parent = nil
(*temporary) = nil
(*temporary) = "ItemButtonTemplate"
(*temporary) = true
(*temporary) = "attempt to call global 'LibStub' (a nil value)"
NewClass = <function> defined @AdiBags\core\OO.lua:63
CreateFrame = <function> defined =[C]:-1

**Comment by Talyrius** [comment]
> Release v1.9.13-**nolib**

Libraries aren't included in the **_nolib_** version. Unless you understand what libraries are and how they function, use the [default download option](https://www.curseforge.com/wow/addons/adibags/download).
