### ISSUE TITLE
Version v1.9.13 (v1.9.14-nolib) Failure

### ISSUE THREAD

**Issue by toxicdust99** [AdiAddons/AdiBags#336]

**Comment by toxicdust99** [comment]
Following errors caught with Bugsack when trying to open Adibags with the "b" button on keyboard

Error1: 
5x AdiBags\core\OO.lua:54: CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"
(tail call): ?
AdiBags\core\OO.lua:59: in function <AdiBags\core\OO.lua:52>
(tail call): ?
(tail call): ?
AdiBags\core\Bags.lua:129: in function `GetFrame'
AdiBags\core\Bags.lua:83: in function `Open'
AdiBags\core\Hooks.lua:112: in function <AdiBags\core\Hooks.lua:109>
(tail call): ?
(tail call): ?
[C]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Error2:
5x AdiBags\core\Bags.lua:130: attempt to index field 'CloseButton' (a nil value)
AdiBags\core\Bags.lua:130: in function `GetFrame'
AdiBags\core\Bags.lua:83: in function `Open'
AdiBags\core\Hooks.lua:112: in function <AdiBags\core\Hooks.lua:109>
(tail call): ?
(tail call): ?
[C]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 isBank = false
 Enable = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:395
 SetDefaultModulePrototype = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "AdiBags_Backpack"
 IsEnabled = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 bagIds = <table> {
 }
 DisableModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 frame = AdiBagsContainer1 {
 }
 baseName = "AdiBags"
 Sort = <function> defined @AdiBags\core\Bags.lua:217
 RegisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 AdiBags_InteractingWindowChanged = <function> defined @AdiBags\core\Bags.lua:204
 GetName = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 IsHooked = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:493
 order = 10
 bagName = "Backpack"
 IsModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:217
 hooks = <table> {
 }
 SetDefaultModuleState = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 SendMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 UnhookAll = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:477
 SetEnabledState = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 Unhook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:418
 RegisterEvent = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SecureHookScript = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:410
 HookScript = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:366
 defaultModuleState = true
 IterateModules = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 UnregisterAllEvents = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 RawHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:313
 PostEnable = <function> defined @AdiBags\core\Bags.lua:200
 moduleName = "Backpack"
 UnregisterEvent = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Disable = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Backpack"
(*temporary) = false
(*temporary) = "attempt to index field 'CloseButton' (a nil value)"
addon = <table> {
 AcquireItemButton = <function> defined @AdiBags\widgets\ItemButton.lua:155
 modules = <table> {
 }
 Updat

Error3:
30x AdiBags\core\Layout.lua:97: attempt to index field 'Anchor' (a nil value)
AdiBags\core\Layout.lua:97: in function <AdiBags\core\Layout.lua:95>
AdiBags\core\Layout.lua:111: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `SendMessage'
AdiBags\core\Bags.lua:90: in function `Open'
AdiBags\core\Hooks.lua:112: in function <AdiBags\core\Hooks.lua:109>
(tail call): ?
(tail call): ?
[C]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Error 4:
30x AdiBags\widgets\ContainerFrame.lua:555: attempt to index field 'Title' (a nil value)
(tail call): ?
AdiBags\widgets\LayeredRegion.lua:119: in function <AdiBags\widgets\LayeredRegion.lua:108>

**Comment by Talyrius** [comment]
Please [download](https://www.curseforge.com/wow/addons/adibags) the latest version (v1.9.14).

**Comment by toxicdust99** [comment]
It was the latest Alpha on Twitch?

**Comment by Talyrius** [comment]
v1.9.14 is a Release, not an Alpha. According to others (#338), the Twitch app isn't behaving properly.

**Comment by toxicdust99** [comment]
Yea noticed twitch is broken. I manually installed it and it worked fine ... meh
