### ISSUE TITLE
Won't open addon in game

### ISSUE THREAD

**Issue by BilliamYork** [AdiAddons/AdiBags#338]
This is what I get every time I try to open AdiBags in the live game:

```
Date: 2019-03-13 15:16:25
ID: 10
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Layout.lua line 97:
   attempt to index field 'Anchor' (a nil value)
```
These are also showing up:

```
Date: 2019-03-13 15:22:14
ID: 8
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\OO.lua line 54:
   CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"
```
```
Date: 2019-03-13 15:22:14
ID: 9
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Bags.lua line 130:
   attempt to index field 'CloseButton' (a nil value)
```
```
Date: 2019-03-13 15:23:16
ID: 11
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\ContainerFrame.lua line 555:
   attempt to index field 'Title' (a nil value)
```

& after this one comes up(after I his my bag button multi times) nothing happens. As in nothing comes up. No errors nothing.

```
Date: 2019-03-13 15:23:37
ID: 12
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\ContainerFrame.lua line 714:
   attempt to index field 'BagSlotPanel' (a nil value)
```

**Comment by BilliamYork** [comment]
These are also showing up:

Date: 2019-03-13 15:22:14
ID: 8
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\OO.lua line 54:
   CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"
Debug:
   (tail call): ?
   AdiBags\core\OO.lua:59:
      AdiBags\core\OO.lua:52
   (tail call): ?
   (tail call): ?
   AdiBags\core\Bags.lua:129: GetFrame()
   AdiBags\core\Bags.lua:83: Open()
   AdiBags\core\Hooks.lua:112:
      AdiBags\core\Hooks.lua:109
   (tail call): ?
   (tail call): ?
   [C]: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  WowheadLooter, v80100
  ACP, vr259 
  AdiBags, vv1.9.13
  AngryWorldQuests, v
  Archy, v7.3.2.1
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  Bartender4, v4.8.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  CollectMe, v2.10.1
  DailyGlobalCheck, v
  DailyGlobalCheckWorldBosses, v
  DBMCore, v8.1.11
  DBMCountPackHoTS, v1.6
  DBMCountPackOverwatch, v1.4.3
  DBMDefaultSkin, v
  DBMSMGEventsPack, v1.4
  DBMSoundEventsPack, v1.5
  DBMStatusBarTimers, v
  EasyDelete, v8.0
  EasyScrap, v19
  ForTheHorde, v
  GatherMate2, v1.43.5
  GTFO, v4.46.17
  HandyNotes, vv1.5.4
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWitheredChests, v1.2
  Identity2, v4.0.1
  Informant, v8.1.6246 (SwimmingSeadragon)
  MoveAnything, v17.0.3
  NPCScan, v8.0.1.13
  Oilvl, v8.0.2
  Outfitter, v5.22.1
  Pawn, v2.2.38
  PersonalLootHelper, v2.19
  Postal, vv3.6.0
  Prat30, vr1195      
  Routes, vv1.6.1
  SellJunk, v3.0.20
  SexyMap, vv8.0.8
  Simulationcraft, v1.10.11
  Skada, v1.7.5
  Skillet, v4.07
  Stubby, v8.1.6240 (SwimmingSeadragon)
  Titan, v5.17.0.80100
  TitanBag, v5.17.0.80100
  TitanClock, v5.17.0.80100
  TitanCurrenciesMulti, v6.3
  TitanGold, v5.17.0.80100
  TitanLocation, v5.17.0.80100
  TitanLootType, v5.17.0.80100
  TitanMail, v7.35
  TitanPerformance, v5.17.0.80100
  TitanPoints, v8.0.1
  TitanProfessionsMulti, v7.0
  TitanRepair, v5.17.0.80100
  TitanReputations, vv1.17
  TitanSocial, v8.0.1
  TitanSpacer, v2.3.2
  TitanVolume, v5.17.0.80100
  TitanXP, v5.17.0.80100
  VuhDo, v3.100
  VuhDoOptions, v3.100
  WarfrontRareTracker, v0.9.8-1
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=81c)

Date: 2019-03-13 15:22:14
ID: 9
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Bags.lua line 130:
   attempt to index field 'CloseButton' (a nil value)
Debug:
   AdiBags\core\Bags.lua:130: GetFrame()
   AdiBags\core\Bags.lua:83: Open()
   AdiBags\core\Hooks.lua:112:
      AdiBags\core\Hooks.lua:109
   (tail call): ?
   (tail call): ?
   [C]: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 isBank = false
 Enable = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:395
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "AdiBags_Backpack"
 IsEnabled = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 bagIds = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 frame = AdiBagsContainer1 {
 }
 baseName = "AdiBags"
 Sort = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:217
 RegisterMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 AdiBags_InteractingWindowChanged = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:204
 GetName = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 IsHooked = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:493
 order = 10
 bagName = "Backpack"
 IsModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:217
 hooks = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 SendMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 UnhookAll = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:477
 SetEnabledState = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 Unhook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:418
 RegisterEvent = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SecureHookScript = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:410
 HookScript = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:366
 defaultModuleState = true
 IterateModules = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 UnregisterAllEvents = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 RawHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:313
 PostEnable = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:200
 moduleName = "Backpack"
 UnregisterEvent = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Disable = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:314
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Backpack"
(*temporary) = false
(*temporary) = "attempt to index field 'CloseButton' (a nil value)"
addon = <table> {
 AcquireItemButton = <function> defined @Interface\AddOns\AdiBags\widgets\ItemButton.lua:155
 modules = <table> {
 }
 Updat
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  WowheadLooter, v80100
  ACP, vr259 
  AdiBags, vv1.9.13
  AngryWorldQuests, v
  Archy, v7.3.2.1
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  Bartender4, v4.8.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  CollectMe, v2.10.1
  DailyGlobalCheck, v
  DailyGlobalCheckWorldBosses, v
  DBMCore, v8.1.11
  DBMCountPackHoTS, v1.6
  DBMCountPackOverwatch, v1.4.3
  DBMDefaultSkin, v
  DBMSMGEventsPack, v1.4
  DBMSoundEventsPack, v1.5
  DBMStatusBarTimers, v
  EasyDelete, v8.0
  EasyScrap, v19
  ForTheHorde, v
  GatherMate2, v1.43.5
  GTFO, v4.46.17
  HandyNotes, vv1.5.4
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWitheredChests, v1.2
  Identity2, v4.0.1
  Informant, v8.1.6246 (SwimmingSeadragon)
  MoveAnything, v17.0.3
  NPCScan, v8.0.1.13
  Oilvl, v8.0.2
  Outfitter, v5.22.1
  Pawn, v2.2.38
  PersonalLootHelper, v2.19
  Postal, vv3.6.0
  Prat30, vr1195      
  Routes, vv1.6.1
  SellJunk, v3.0.20
  SexyMap, vv8.0.8
  Simulationcraft, v1.10.11
  Skada, v1.7.5
  Skillet, v4.07
  Stubby, v8.1.6240 (SwimmingSeadragon)
  Titan, v5.17.0.80100
  TitanBag, v5.17.0.80100
  TitanClock, v5.17.0.80100
  TitanCurrenciesMulti, v6.3
  TitanGold, v5.17.0.80100
  TitanLocation, v5.17.0.80100
  TitanLootType, v5.17.0.80100
  TitanMail, v7.35
  TitanPerformance, v5.17.0.80100
  TitanPoints, v8.0.1
  TitanProfessionsMulti, v7.0
  TitanRepair, v5.17.0.80100
  TitanReputations, vv1.17
  TitanSocial, v8.0.1
  TitanSpacer, v2.3.2
  TitanVolume, v5.17.0.80100
  TitanXP, v5.17.0.80100
  VuhDo, v3.100
  VuhDoOptions, v3.100
  WarfrontRareTracker, v0.9.8-1
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=81c)

**Comment by BilliamYork** [comment]
Date: 2019-03-13 15:23:16
ID: 11
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\ContainerFrame.lua line 555:
   attempt to index field 'Title' (a nil value)
Debug:
   (tail call): ?
   AdiBags\widgets\LayeredRegion.lua:119:
      AdiBags\widgets\LayeredRegion.lua:108
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  WowheadLooter, v80100
  ACP, vr259 
  AdiBags, vv1.9.13
  AngryWorldQuests, v
  Archy, v7.3.2.1
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  Bartender4, v4.8.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  CollectMe, v2.10.1
  DailyGlobalCheck, v
  DailyGlobalCheckWorldBosses, v
  DBMCore, v8.1.11
  DBMCountPackHoTS, v1.6
  DBMCountPackOverwatch, v1.4.3
  DBMDefaultSkin, v
  DBMSMGEventsPack, v1.4
  DBMSoundEventsPack, v1.5
  DBMStatusBarTimers, v
  EasyDelete, v8.0
  EasyScrap, v19
  ForTheHorde, v
  GatherMate2, v1.43.5
  GTFO, v4.46.17
  HandyNotes, vv1.5.4
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWitheredChests, v1.2
  Identity2, v4.0.1
  Informant, v8.1.6246 (SwimmingSeadragon)
  MoveAnything, v17.0.3
  NPCScan, v8.0.1.13
  Oilvl, v8.0.2
  Outfitter, v5.22.1
  Pawn, v2.2.38
  PersonalLootHelper, v2.19
  Postal, vv3.6.0
  Prat30, vr1195      
  Routes, vv1.6.1
  SellJunk, v3.0.20
  SexyMap, vv8.0.8
  Simulationcraft, v1.10.11
  Skada, v1.7.5
  Skillet, v4.07
  Stubby, v8.1.6240 (SwimmingSeadragon)
  Titan, v5.17.0.80100
  TitanBag, v5.17.0.80100
  TitanClock, v5.17.0.80100
  TitanCurrenciesMulti, v6.3
  TitanGold, v5.17.0.80100
  TitanLocation, v5.17.0.80100
  TitanLootType, v5.17.0.80100
  TitanMail, v7.35
  TitanPerformance, v5.17.0.80100
  TitanPoints, v8.0.1
  TitanProfessionsMulti, v7.0
  TitanRepair, v5.17.0.80100
  TitanReputations, vv1.17
  TitanSocial, v8.0.1
  TitanSpacer, v2.3.2
  TitanVolume, v5.17.0.80100
  TitanXP, v5.17.0.80100
  VuhDo, v3.100
  VuhDoOptions, v3.100
  WarfrontRareTracker, v0.9.8-1
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=81c)

**Comment by BilliamYork** [comment]
& after this one comes up(after I his my bag button multi times) nothing happens. As in nothing comes up. No errors nothing.

Date: 2019-03-13 15:23:37
ID: 12
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\ContainerFrame.lua line 714:
   attempt to index field 'BagSlotPanel' (a nil value)
Debug:
   AdiBags\widgets\ContainerFrame.lua:714: FilterSlot()
   AdiBags\widgets\ContainerFrame.lua:751: DispatchItem()
   AdiBags\widgets\ContainerFrame.lua:811: UpdateButtons()
   AdiBags\widgets\ContainerFrame.lua:448: RefreshContents()
   AdiBags\widgets\ContainerFrame.lua:433: ResumeUpdates()
   AdiBags\widgets\ContainerFrame.lua:416:
      AdiBags\widgets\ContainerFrame.lua:408
   [C]: Show()
   AdiBags\core\Bags.lua:89: Open()
   AdiBags\core\Hooks.lua:112:
      AdiBags\core\Hooks.lua:109
   (tail call): ?
   (tail call): ?
   [C]: ToggleAllBags()
   [string "OPENALLBAGS"]:1:
      [string "OPENALLBAGS"]:1
Locals:
self = AdiBagsContainer1 {
 removed = <table> {
 }
 HeaderLeftRegion = AdiBagsSimpleLayeredRegion1 {
 }
 isBank = false
 changed = <table> {
 }
 added = <table> {
 }
 stacks = <table> {
 }
 BottomLeftRegion = AdiBagsSimpleLayeredRegion3 {
 }
 dirtyLayout = true
 buttons = <table> {
 }
 isReagentBank = false
 widgets = <table> {
 }
 paused = false
 BottomRightRegion = AdiBagsSimpleLayeredRegion4 {
 }
 name = "Backpack"
 bagObject = <table> {
 }
 0 = <userdata>
 HeaderRightRegion = AdiBagsSimpleLayeredRegion2 {
 }
 content = <table> {
 }
 sections = <table> {
 }
}
slotData = <table> {
 bag = 0
 isBank = false
 class = "Miscellaneous"
 equipSlot = ""
 slotId = 1
 itemId = 6948
 link = "[Hearthstone]"
 subclass = "Junk"
 reqLevel = 0
 texture = 134414
 name = "Hearthstone"
 quality = 1
 count = 1
 iLevel = 1
 maxStack = 1
 vendorPrice = 0
 slot = 1
 bagFamily = 0
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'BagSlotPanel' (a nil value)"
FilterByBag = <function> defined @Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:689
addon = <table> {
 AcquireItemButton = <function> defined @Interface\AddOns\AdiBags\widgets\ItemButton.lua:155
 modules = <table> {
 }
 UpdateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:451
 ConfigChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:371
 GetSlotId = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:57
 Filter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 Reconfigure = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:183
 SetupTooltip = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:188
 CreateFont = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:122
 filterProto = <table> {
 }
 db = <table> {
 }
 OpenOptions = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:289
 SetEnabledState = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 IterateBags = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:183
 OnEnable = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:115
 HookBagFrameCreation = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:305
 NewBag = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:150
 GetClass = <function> defined @Interface\AddOns\AdiBags\core\OO.lua:128
 RegisterFilter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 InitializeFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:64
 IterateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:362
 CreateBagSlotPanel = <function> defined @Interface\AddOns\AdiBags\widgets\BagSlots.lua:437
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:137
 ToggleAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:86
 OnProfileChanged = <function> 
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  WowheadLooter, v80100
  ACP, vr259 
  AdiBags, vv1.9.13
  AngryWorldQuests, v
  Archy, v7.3.2.1
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  Bartender4, v4.8.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  CollectMe, v2.10.1
  DailyGlobalCheck, v
  DailyGlobalCheckWorldBosses, v
  DBMCore, v8.1.11
  DBMCountPackHoTS, v1.6
  DBMCountPackOverwatch, v1.4.3
  DBMDefaultSkin, v
  DBMSMGEventsPack, v1.4
  DBMSoundEventsPack, v1.5
  DBMStatusBarTimers, v
  EasyDelete, v8.0
  EasyScrap, v19
  ForTheHorde, v
  GatherMate2, v1.43.5
  GTFO, v4.46.17
  HandyNotes, vv1.5.4
  HandyNotesBattleForAzerothAchievments, vv7
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesWarfrontRares, v0.5.0
  HandyNotesWitheredChests, v1.2
  Identity2, v4.0.1
  Informant, v8.1.6246 (SwimmingSeadragon)
  MoveAnything, v17.0.3
  NPCScan, v8.0.1.13
  Oilvl, v8.0.2
  Outfitter, v5.22.1
  Pawn, v2.2.38
  PersonalLootHelper, v2.19
  Postal, vv3.6.0
  Prat30, vr1195      
  Routes, vv1.6.1
  SellJunk, v3.0.20
  SexyMap, vv8.0.8
  Simulationcraft, v1.10.11
  Skada, v1.7.5
  Skillet, v4.07
  Stubby, v8.1.6240 (SwimmingSeadragon)
  Titan, v5.17.0.80100
  TitanBag, v5.17.0.80100
  TitanClock, v5.17.0.80100
  TitanCurrenciesMulti, v6.3
  TitanGold, v5.17.0.80100
  TitanLocation, v5.17.0.80100
  TitanLootType, v5.17.0.80100
  TitanMail, v7.35
  TitanPerformance, v5.17.0.80100
  TitanPoints, v8.0.1
  TitanProfessionsMulti, v7.0
  TitanRepair, v5.17.0.80100
  TitanReputations, vv1.17
  TitanSocial, v8.0.1
  TitanSpacer, v2.3.2
  TitanVolume, v5.17.0.80100
  TitanXP, v5.17.0.80100
  VuhDo, v3.100
  VuhDoOptions, v3.100
  WarfrontRareTracker, v0.9.8-1
  WoWDBProfiler, v
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=81c)

**Comment by Roofusia235** [comment]
I get these same errors when trying to open a bag.  I've tried reinstalling but it didn't help.

**Comment by BilliamYork** [comment]
Tried that also. & it's not just this Bag Addon. Ark isn't working...

**Comment by Talyrius** [comment]
This (#332) has already been fixed via b0ccd03. Please [download](https://www.curseforge.com/wow/addons/adibags) the latest version (v1.9.14).

**Comment by cromine** [comment]
Received the same errors:
..\AddOns\AdiBags\core\OO.lua line 54:
CreateFrame(): Couldn't find inherited node "ItemButtonTemplate"
..\AddOns\AdiBags\core\Bags.lua line 130:
attempt to index field 'CloseButton' (a nil value)

Running v1.9.14 (according to Twitch) and tried disabling all other add-ons

**Comment by cromine** [comment]
Actually, regarding Twitch. Its displaying some conflicting info:

AdiBags - v1.9.13
Latest Version: 1.9.14-nolib

But it does not provide an update when trying to refresh.

**Comment by Roofusia235** [comment]
I can confirm that manually downloading the latest version and installing it manually fixed it.  Cromine is correct in that Twitch isn't presenting it as an update.

**Comment by Talyrius** [comment]
It shouldn't offer you the version without libraries included (_nolib_) unless you've opted in to receiving those. I've hidden that one, for now. However, if the update still isn't showing up in the Twitch app, there isn't anything I can do about it. You'll have to install it manually.

**Comment by cromine** [comment]
A restart of Twitch did provide the update to v1.9.14, although it does still list v1.9.14-nolib as the latest version. Not sure about the setting to receive those.. I have it set to 'Release' for the Release Type. Working now though, thanks for all you (and crew) do for this terrific add-on!

**Comment by Zarggg** [comment]
Click the Versions tab in the Twitch client to see all available releases. Don't install the nolib version.

**Comment by BilliamYork** [comment]
Installed manually & it works. I tried the Twitch app it even showed that is was the v1.9.14 not the v1.9.14-nolib & it still didn't work. But doing a manual install works.

**Comment by BilliamYork** [comment]
& thank you guys for making this addon I love it.
