### ISSUE TITLE
Opening bank

### ISSUE THREAD

**Issue by Dajova** [AdiAddons/AdiBags#342]
Getting this error everytime i open up my bank since the last version:

edit: im not sure how and or when it triggers now, sometimes its when i open my bank, sometimes its when i just open my bags normally... Maybe it's related to a specific item?

edit2: Now that i look through the errorcode itself, it might be related to [Caedron Wardrobe](https://www.curseforge.com/wow/addons/caerdon-wardrobe)?

`22x FrameXML\ContainerFrame.lua:1426: attempt to index a nil value
FrameXML\ContainerFrame.lua:1426: in function `GetItemContextMatchResult'
FrameXML\ItemButtonTemplate.lua:214: in function `UpdateItemContextMatching'
FrameXML\ItemButtonTemplate.lua:190: in function <FrameXML\ItemButtonTemplate.lua:189>
[C]: in function `Show'
AdiBags\core\Bags.lua:89: in function `Open'
AdiBags\core\Hooks.lua:112: in function <AdiBags\core\Hooks.lua:109>
(tail call): ?
(tail call): ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = AdiBagsItemButton56 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @FrameXML\ItemButtonTemplate.lua:169
 BattlepayItemTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 GetItemContextMatchResult = <function> defined @FrameXML\ContainerFrame.lua:1425
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 icon = AdiBagsItemButton56IconTexture {
 }
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1347
 ExtendedOverlay = <unnamed> {
 }
 caerdonButton = <unnamed> {
 }
 RegisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:175
 itemContextChangedCallbackIsSet = false
 UnregisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:211
 itemContextMatchResult = 3
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton56Cooldown {
 }
 bagFamily = 0
 bindsOnText = <unnamed> {
 }
 count = 1
 BagStaticBottom = <unnamed> {
 }
 filterName = "Track new items"
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:189
 flash = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = false
 IconTexture = AdiBagsItemButton56IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:222
 slot = 11
 bag = 0
 NormalTexture = AdiBagsItemButton56NormalTexture {
 }
 Stock = AdiBagsItemButton56Stock {
 }
 IconQuestTexture = AdiBagsItemButton56IconQuestTexture {
 }
 itemContextChangedCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:170
 0 = <userdata>
 Count = AdiBagsItemButton56Count {
 }
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:198
 flashAnim = <unnamed> {
 }
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:207
 UpgradeIcon = <unnamed> {
 }
 searchOverlay = AdiBagsItemButton56SearchOverlay {
 }
}
(*temporary) = <function> defined @FrameXML\ItemUtil.lua:47
(*temporary) = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:9
(*temporary) = <table> {
 CreateFromBagAndSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:9
 CreateFromEquipmentSlot = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:15
 CreateEmpty = <function> defined @FrameXML\ObjectAPI\ItemLocation.lua:4
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"
`

**Comment by Dajova** [comment]
After further testing, it seems to happen when i try to sort the reagentbank.

**Comment by Talyrius** [comment]
See #339.
