### ISSUE TITLE
Adibags How do I add/replace bags?

### ISSUE THREAD

**Issue by Royin345** [AdiAddons/AdiBags#345]
Hey so I just got Adibags for WoW and I'm loving everything about it.  But I have a problem, I can't find where to replace old bags with new bags.  I'm leveled up now so I need bigger bags but can't find the bag slots to switch them out.   Can anyone help me figure this out? Thank you!

**Comment by SpareSimian** [comment]
Click the icon at the top-left corner of the AdiBags panel and it will switch the view to physical bags, with bag slots across the top. Drop your new bag there. The new bag must have enough capacity to hold all the stuff in the bag it's replacing. The new bag must not be in the bag it's replacing. The same procedure works for your bank bags.

**Comment by Royin345** [comment]
Thank you that did it! And I will do the thing!

**Comment by OverlordQ** [comment]
In 9.0.3 w/ elvui there are no physical bag slots
