### ISSUE TITLE
"Couldn't load Adibags_Config: Disabled"

### ISSUE THREAD

**Issue by vitor210** [AdiAddons/AdiBags#346]
Installed the addon today, can't open the configuration in game because I get that message in chat.

Anyone knows how to fix this???

**Comment by Zarggg** [comment]
Is Adibags_Config enabled in your addons?

**Comment by Talyrius** [comment]
Yes, you need to enable _AdiBags_Config_ in the _AddOn List_ which can be accessed from the login screen or the in-game menu.
