### ISSUE TITLE
Searching not working?

### ISSUE THREAD

**Issue by hardvark** [AdiAddons/AdiBags#347]
V 1.9.15
Adibags was highlighting scrappables but that has stopped working. I found it really useful. (Possibility Elvui was doing it but I could not find that setting in Elvui either).

Alongside that typing into the search field no longer highlights or hides anything. This is more important.
TY

**Comment by Talyrius** [comment]
![image](https://user-images.githubusercontent.com/1068810/54884987-6027d580-4e34-11e9-906f-1d306aae6d20.png)
Search is still working as intended.

AdiBags itself has never highlighted scrapable items. Some other addon must have been responsible for adding that feature.
