### ISSUE TITLE
Search not working v1.9.15

### ISSUE THREAD

**Issue by idrake88** [AdiAddons/AdiBags#348]
Ever since 8.1.5 and 1.9.15 the search function is not working. I can type in anything and no highlights appear in the bag.

**Comment by idrake88** [comment]
![image](https://user-images.githubusercontent.com/9619711/55265570-85568280-523e-11e9-8241-b949ba4d975e.png)

**Comment by Talyrius** [comment]
It [still worked](./347#issuecomment-475994453) for me when I was on last.

**Comment by idrake88** [comment]
It has not worked for me since the 8.1.5 patch, I have reinstalled it using the twitch client. Maybe I will try fully deleting it and it’s settings or something? I noticed another closed thread with the same issue so it’s not only me, but clearly not everyone.

**Comment by idrake88** [comment]
Tried deleting it fully along with the saved variables and reinstalling. Still no luck with the search filter.

**Comment by Meivyn** [comment]
This is an issue with the recent AddOnSkins update, not related to AdiBags itself.

**Comment by Meivyn** [comment]
Take a look on this: https://git.tukui.org/Azilroka/AddOnSkins/issues/344

![image](https://user-images.githubusercontent.com/793322/55287054-53ded380-5372-11e9-919b-1ab235c40a94.png)

This is funny!

**Comment by RottynDawg** [comment]
I can confirm the same behavior.  Oddly enough, search works in my Guild Bank but not my Personal Bank or Inventory.  Hope this helps...

**Comment by Nivyan** [comment]
I fixed it with ElvUI and AddOnSkins installed:
- /ec -> AddOnSkins -> AddOn Skins -> Disable Adibags
- /adibags config -> Skin -> Bag Background -> ElvUI Blank + Backpack Color (black, 0,0,0, with 33 transparency) -> ElvUI GlowBorder (Insets 1)
- Optional: Reagent/Bank transparency to 33% as well.

Now search works, and AdiBags looks very, very close to ElvUI' style.

For it to be perfect, allow us to modify the border color, and we're set :-)

**Comment by Meivyn** [comment]
You can simply revert the changes made to AdiBags.

To do this, replace everything in ``AddOnSkins/Skins/AdiBags.lua`` by:

```lua
local AS = unpack(AddOnSkins)

if not AS:CheckAddOn('AdiBags') then return end

local function SkinFrame(frame)
	local region = frame.HeaderRightRegion
	AS:SkinFrame(frame)
	AS:SkinFrame(_G[frame:GetName()..'Bags'], 'Default', true)
	AS:SkinCloseButton(frame.CloseButton)
	for i = 1, 5 do
		local widget = region.widgets[i] and region.widgets[i].widget
		if widget then
			if widget:IsObjectType('Button') then
				AS:SkinButton(widget, true)
			elseif widget:IsObjectType('EditBox') then
				AS:SkinEditBox(widget)
			end
		end
	end
	AS:SkinTexture(frame.BagSlotButton:GetNormalTexture())
end

function AS:AdiBags(event)
	local AdiBags = LibStub('AceAddon-3.0'):GetAddon('AdiBags')

	if event == 'PLAYER_ENTERING_WORLD' then
		AS:Delay(1, function()
			if not AdiBagsContainer1 then ToggleBackpack() ToggleBackpack() end
			if AdiBagsContainer1 then
				SkinFrame(AdiBagsContainer1)
				AdiBagsContainer1SearchBox:SetPoint('TOPRIGHT', AdiBagsSimpleLayeredRegion2, 'TOPRIGHT', -75, -1)
			end
		end)
	elseif event == 'BANKFRAME_OPENED' then
		AS:Delay(0.1, function()
			if AdiBagsContainer2 then
				SkinFrame(AdiBagsContainer2)
				AS:UnregisterSkinEvent('AdiBags', event)
			end
		end)
	end
end

AS:RegisterSkin('AdiBags', AS.AdiBags, 'BANKFRAME_OPENED')
```
Then you'll also have to add this line in ``Load_Skins.xml`` since version 4.16 (AddOnSkins have dropped support for AdiBags):
```xml
<Script file="AdiBags.lua"/>
```
This is something you'll have to do each time AddOnSkins is updated.

**Comment by Azilroka** [comment]
Which is the original half skin that was created for it because I could not get to the items itself. When I tried to do the items then it became a pain to work with.

My original comment still stands. It is far easier to support it directly in AdiBags and have perfect support instead of something that is half ass and can't even remotely get close to it. I had them skinned perfectly internally in AdiBags.

**Comment by Meivyn** [comment]
Mind sharing your version? Btw, why are you not using ElvUI internal functions and templates to skin the addons, for consistency with the overall style of ElvUI?

There is also a ElvUI version of AdiBags here if someone is interested: https://www.curseforge.com/wow/addons/elvui-adibags

**Comment by Azilroka** [comment]
I helped Klix with that version.

AddOnSkins is not purely ElvUI. It does the exact same API as I'm a developer on the UI. You have to check 'ElvUI Style' for it to be that way and it should be checked by default.
