### ISSUE TITLE
AdiBags_Outfitter doesn't do anything

### ISSUE THREAD

**Issue by TigerRaven** [AdiAddons/AdiBags#35]
I have been using AdiBags for a while and then started using Outfitter to keep my Tank and DPS gear sets separate. I found AdiBags_Outfitter and installed it thinking it would create filters for "Tank" and "DPS" (the names of my gears sets) in AdiBags but nothing seems to have changed. When I am in DPS set my Tank weapon and shield just appear in the "Weapon" section and I'm worried I'll accidently sell them.

I have confirmed that AdiBags_Outfitter is installed and loaded but cannot see anywhere to configure it. What am I missing?

**Comment by Cidan** [comment]
I can confirm that AdiBags_Outfitter is working as of the latest version.
