### ISSUE TITLE
Adibags not showing even though shows in addons

### ISSUE THREAD

**Issue by RobloxMorty** [AdiAddons/AdiBags#350]
I have adibags installed, it shows it on the addon menu but does not show that for my bag inventory. No options on interface. I have tried reinstalling and deleting then installing again, it hasn't worked.

**Comment by Zarggg** [comment]
Are you using any other addons that might might also be reskinning your bags? One common example would be ElvUI.

**Comment by RobloxMorty** [comment]
I turned off my ElvUI and it still hasnt worked. I dont know whats causing it.

**Comment by Talyrius** [comment]
Disable everything except AdiBags and confirm it's working. From there, enable groups of addons until you find the addon that's causing the conflict.
