### ISSUE TITLE
bag window has set width larger than my screen, more than half empty. "Maximum bag height" does nothing

### ISSUE THREAD

**Issue by NEETWizardJanus** [AdiAddons/AdiBags#352]
There is something really messed up with my personal bag inventory window with this addon. It has a set width that is larger than my screen, whereas my bank inventory is more efficient. "Compact layout" has no effect on this. None of the settings have any effect on this, except to make the scale of my UI smaller than 100%, but it still has a lot of wasted space. The only solution to the window inefficiency is to crank up the column width to a value of 10 or more, but this is not how I want to use my bags! I want to use them the way my bank inventory is displayed.
![WoWScrnShot_052419_180713](https://user-images.githubusercontent.com/19241676/58358889-cdfd7700-7e4e-11e9-972b-60dbb98ff221.jpg)

"Maximum bag height" has NO effect on personal inventory, but it DOES seem to effect bank inventory. I understand that it's a maximum, but it's clearly only working as intended on my bank inventory and not my personal inventory. The difference is most clearly seen with a column width of 8. I believe if my personal inventory was working the way my bank inventory was, there would be no problem.

Here's examples showing at a column width of 8, the effect of min/max bag height has on the bank window, but not personal inventory:
![WoWScrnShot_052419_180018](https://user-images.githubusercontent.com/19241676/58358662-e02ae580-7e4d-11e9-8def-4cea1a818c26.jpg)
![WoWScrnShot_052419_180023](https://user-images.githubusercontent.com/19241676/58358669-e4ef9980-7e4d-11e9-9087-07c4f2e83755.jpg)

I've tried to delete the AdiBags.lua in /World of Warcraft/_retail_/WTF/Account/[redaced]/SavedVariables/
I've tried deleting the /World of Warcraft/_retail_/Interface/AddOns/ folders and installing fresh.
I couldn't find any other configuration files that could be old and need a fresh install.

**Comment by Talyrius** [comment]
You're tracking too many currencies; that's what's causing your problem.
