### ISSUE TITLE
Will WoW Classic be supported?

### ISSUE THREAD

**Issue by amey1956** [AdiAddons/AdiBags#353]
are there any plans to update this for classic?

thanks in advance

**Comment by Talyrius** [comment]
If the dependencies (support libraries) that this addon relies on are updated, yes.

**Comment by amey1956** [comment]
just checking - onebag doesn't cut it ;)

**Comment by jbjt** [comment]
I've opened a PR for this functionality: https://github.com/AdiAddons/AdiBags/pull/369
Anyone interested in using it can download it from https://github.com/jbjt/AdiBags/tree/classic-bundle - there are download and installation instructions in the readme.
