### ISSUE TITLE
AceConfigDialog invalid order function for sorting

### ISSUE THREAD

**Issue by SpareSimian** [AdiAddons/AdiBags#354]
I get this when I type /adibags. I get an almost empty frame with just the two checkboxes at the top, "Enabled" and "Right-click to open options". 

This is likely an issue with a plugin but I wanted to capture it here before I started debugging it. table.sort is complaining about an invalid comparison function. All the code is in a separate AceConfigDialog (not the one bundled in AdiBags) but a diff indicates the newer unbundled one just differs by trailing white space that got cleaned up between January and May. 

I'd reported an error with the same message in bug #257 but I think this one is different and happens when the categories are being laid out in the config dialog. 

Date: 2019-06-11 03:06:14
ID: 1
Error occured in: Global
Count: 1
Message: ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua line 347:
   invalid order function for sorting
Debug:
   [C]: ?
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:347:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:315
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:959:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:955
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:978:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:955
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1012:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:989
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1672: FeedGroup()
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1865: Open()
   AdiBags\config\Options.lua:685: OpenOptions()
   AdiBags\core\Core.lua:295: OpenOptions()
   AdiBags\core\Core.lua:109: ?()
   ..\FrameXML\ChatFrame.lua:4721: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4382: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4418: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:
(*temporary) = <table> {
 1 = "Ancient Mana"
 2 = "BoA"
 3 = "Champion Equipment"
 4 = "Item Enhancement"
 5 = "Item Enhancement!"
 6 = "Key"
 7 = "Power"
 8 = "Recipe"
 9 = "Relic"
 10 = "Junk"
 11 = "Miscellaneous"
 12 = "Trade Goods"
 13 = "Equipment"
 14 = "Consumable"
 15 = "description"
 16 = "Quest"
 17 = "newAssoc"
 18 = "New"
 19 = "Tradeskill"
}
(*temporary) = <function> defined @Interface\AddOns\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:285
(*temporary) = "Junk"
(*temporary) = "Junk"
(*temporary) = "Power"

**Comment by SpareSimian** [comment]
I got some more data and posted it upstream in the Ace3 issue list:

https://www.wowace.com/projects/ace3/issues/501

**Comment by SpareSimian** [comment]
I think I figured out the issue and posted the needed edit to the linked issue for Ace3.

**Comment by SpareSimian** [comment]
Upstream fix is in the latest Ace3 so you'll want to cut a new release at some point. I'm using the upstream directly so it overrides the bundled library. Upstream minor version of AceConfigDialog with the fix is 73.

**Comment by Talyrius** [comment]
Thanks. I'll be pushing a new release for Season 3's iLvl changes which happens on July 9th.
