### ISSUE TITLE
esc interface addon config crash

### ISSUE THREAD

**Issue by Genuvien** [AdiAddons/AdiBags#357]
So, i open interface to addons and click on config button for adibags, it crashes WoW with no error message given, just straight to desktop and client closed. I'm not sure if this is repeatable for you, but it happened twice so far for me. Thanks!

**Comment by SpareSimian** [comment]
Try installing the Ace3 library separately and see if that helps. Addons will use the most recent version of a library and the AdiBags config dialog uses a bundled version of Ace3 for its backend. That library has had a lot of updates recently.
