### ISSUE TITLE
Request: Option to stop auto section sorting / Custom section sorting

### ISSUE THREAD

**Issue by PolarDawn** [AdiAddons/AdiBags#363]
Can you add an option to prevent sections from being moved around depending on where they fit OR allow us to force the order that sections appear?

For example: Depending on how many items I have in one section, the section jumps all over the place and having to find a section each time can be frustrating.

![hidden](https://user-images.githubusercontent.com/33757819/60900792-b7777780-a264-11e9-9b36-1f293b5b193d.jpg)

# #

**Comment by kaqualls** [comment]
This already exists.
/adibags > Bags > uncheck "Compact Layout"

**Comment by Talyrius** [comment]
Sorry, this won't be implemented. See #231.

**Comment by PolarDawn** [comment]
That's unfortunate. I understand the thought process of saving space, but having dynamic sections that wildly shift locations isn't a good user experience, especially on a UI with so many icons and sections.
