### ISSUE TITLE
A slight freeze when open bag, it is very quick.

### ISSUE THREAD

**Issue by strickland** [AdiAddons/AdiBags#366]
I've had adibags enabled with certain plugins for it, once I noticed the freeze on screen when opening bag, I decided to disable each one by one, and the freeze reduces and was quicker, but it still freezes, the only way to make it not freeze at all is when I actualy disable "Adibags configuration with all plugins" after that, the bag opening does not freeze the screen at all, but once I enable adibags configuration even by itself, the screen would freeze for half a second whenever I open the bag.

**Comment by Klixxx** [comment]
That is not an issue, please read the description of the addon, and find the "known issues" section:

"Opening the bank or closing my bag cause lag spike: this is an know issue with Blizzard bag sorting. For now, it is called every time you close your bag with auto-sorting enabled. I am working on a solution to sort bags only if their content actually changed."

**Comment by strickland** [comment]
Klixxx, thats good to hear, but here's the thing my dude! if I disable all the adibags companion addons or extras which I've downloaded from curse, and if I also disable adibags configuration, and only keep one thing enabled "adibags" so basically everything is disabled except for adibags and without the configuration, then guess what.

Lag is all disappeared whenever I open bags, or close bags, either way there will be no freeze or lag spikes at all, try it yourself.

**Comment by Talyrius** [comment]
The more plugins and modules loaded, the more processing overhead there'll be.
