### ISSUE TITLE
Bank doesn't open with adibags

### ISSUE THREAD

**Issue by Chloe-maker** [AdiAddons/AdiBags#368]
Hello,

I use Adibags for one year.

Since June 2019, Adibags does not works for the bank. It opens the bank of wow classic. It works great for the bag pack.

I deleted the file of the addon an re install Adibags. So i have now the July 2019 update.

The bug persists. And i don't understand because my personnal settings are still there (colors, tittles, slots for items...)

My boyfriend just installed the July 2019 update Adibags and the bank works very well. So, i deduce that it does not re install the entiere code and the bug is still running as my own addon settings (filters like colors, titles...).

Can you help me please?

**Comment by Klixxx** [comment]
Please backup your WTF folder and delete it, see if that helps

**Comment by Talyrius** [comment]
Try deleting your settings for AdiBags. Going back to the default settings should fix it.

While WoW is closed, go to the folder where it's installed and navigate to this location:

> _World of Warcraft\_retail_\WTF\Account\YOURACCOUNT\SavedVariables_

Find _AdiBags.lua_ and delete it. Relaunch WoW.

**Comment by Klixxx** [comment]
What he said :)
