### ISSUE TITLE
huge error every time...

### ISSUE THREAD

**Issue by powatwoopa** [AdiAddons/AdiBags#370]
huge error every time i open my bags.. something about scrappingmachineframe 
256x AdiBags\widgets\ItemButton.lua:340: attempt to index field 'ScrappingMachineFrame' (a nil value)
AdiBags\widgets\ItemButton.lua:340: in function `Update'
AdiBags\widgets\ItemButton.lua:305: in function `FullUpdate'
AdiBags\widgets\ItemButton.lua:270: in function <AdiBags\widgets\ItemButton.lua:258>
[C]: in function `Show'
AdiBags\widgets\ContainerFrame.lua:978: in function `PrepareSections'
AdiBags\widgets\ContainerFrame.lua:1084: in function `FullUpdate'
AdiBags\widgets\ContainerFrame.lua:579: in function <AdiBags\widgets\ContainerFrame.lua:565>
[C]: ?
AdiBags\core\Utility.lua:89: in function <AdiBags\core\Utility.lua:81>
AdiBags\widgets\LayeredRegion.lua:119: in function <AdiBags\widgets\LayeredRegion.lua:108>

Locals:
self = AdiBagsItemButton74 {
 timeSinceUpgradeCheck = 0
 PostOnLoad = <function> defined @FrameXML\ItemButtonTemplate.lua:169
 BattlepayItemTexture = <unnamed> {
 }
 IconOverlay = <unnamed> {
 }
 BagStaticTop = <unnamed> {
 }
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined =[C]:-1
 icon = AdiBagsItemButton74IconTexture {
 }
 container = AdiBagsContainer1 {
 }
 ScrapIcon = <unnamed> {
 }
 pushed = <unnamed> {
 }
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1376
 ExtendedOverlay = <unnamed> {
 }
 count = 1
 section = AdiBagsSection4 {
 }
 filterName = "Equipment"
 RegisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:175
 texture = 457932
 UpgradeIcon = <unnamed> {
 }
 UnregisterCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:182
 UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:211
 itemLink = "|cff1eff00|Hitem:131627::::::::47:253:512:11:1:3656:41:::|h[Scaled Pants of Patience]|h|r"
 NewItemTexture = <unnamed> {
 }
 Cooldown = AdiBagsItemButton74Cooldown {
 }
 bagFamily = 0
 itemId = 131627
 BagStaticBottom = <unnamed> {
 }
 glossTex = true
 PixelSnapDisabled = true
 ItemContextOverlay = <unnamed> {
 }
 PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:189
 flash = <unnamed> {
 }
 bag = 2
 acquired = true
 hover = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 ExtendedOverlay2 = <unnamed> {
 }
 hasItem = true
 SetBackdropColor = <function> defined =[C]:-1
 IconTexture = AdiBagsItemButton74IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:202
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:222
 slot = 5
 template = "Default"
 NormalTexture = AdiBagsItemButton74NormalTexture {
 }
 Stock = AdiBagsItemButton74Stock {
 }
 IconQuestTexture = AdiBagsItemButton74IconQuestTexture {
 }
 itemContextChangedCallback = <function> defined @FrameXML\ItemButtonTemplate.lua:170
 0 = <userdata>
 Count = AdiBagsItemButton74Count {
 }
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:198
 flashAnim = <unnamed> {
 }
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:207
 pixelBorders = <table> {
 }
 searchOverlay = AdiBagsItemButton74SearchOverlay {
 }
}
icon = AdiBagsItemButton74IconTexture {
 0 = <userdata>
 PixelSnapDisabled = true
}
tag = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 457932
(*temporary) = 1
(*temporary) = "attempt to index field 'ScrappingMachineFrame' (a nil value)"
unpack = <function> defined =[C]:-1
addon = <table> {
 AcquireItemButton = <function> defined @AdiBags\widgets\ItemButton.lua:173
 modules = <table> {
 }
 UpdateFilters = <function> defined @AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @SunnArt\Libs\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @AdiBags\core\Core.lua:470
 ConfigChanged = <function> defined @AdiBags\core\Core.lua:390
 GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
 Filter = <function> defined @AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 Reconfigure = <function> defined @AdiBags\core\Core.lua:187
 SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @ActionBarProfiles\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @ActionBarProfiles\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:188
 CreateFont = <function> defined @AdiBags\core\Fonts.lua

https://gyazo.com/c5ed2294c0405f661b2dae5e740dbd5f

**Comment by Klixxx** [comment]
I see you use the elvui version, this is fixed in the newest update.
