### ISSUE TITLE
why does adibags have bank and reagent separated?

### ISSUE THREAD

**Issue by artlessknave** [AdiAddons/AdiBags#374]
I saw in one place it said that this addon, which combines storage into one compact window for everything, will not support combining everything into one window, by keeping reagent storage separate?  I'm curious what the reason for that is. haven't been able to find why it requires a button to switch the window state.
I find the addon interesting, but am mystified as to why this is segregated this way

**Comment by Talyrius** [comment]
The reason is it would take up too much space and overflow off of the screen unless most of the items were limited to the same sections.
