### ISSUE TITLE
AdiBags Still Doesn't Allow Pawn to show its upgrade arrows in the bag.

### ISSUE THREAD

**Issue by rslate20** [AdiAddons/AdiBags#376]
I know that this is a duplicate post from 2017, but that's two years ago and I haven't seen a workaround or a fix.

**Comment by MrMotte** [comment]
Actually it does allow the Pawn arrow. I using Adibags on my own together with Pawn. But the arrow is usually in the upper left corner of an item, but right there is the item score displayed.
When you scale the bag a bit up, you'll see tht the arrow is displayed **behind** the item score.

The Workaround:
1. Go To Interface > Adibags
2. Go in the Plugins section, click plugins (not the subcategorys)
3. There you can see every plugin and you just need to uncheck the item score plugin.
4. ???
5. Profit

You'll loose the general item score info, but you gain the pawn arrow.

**Comment by edamievil** [comment]
> Actually it does allow the Pawn arrow. I using Adibags on my own together with Pawn. But the arrow is usually in the upper left corner of an item, but right there is the item score displayed.
> When you scale the bag a bit up, you'll see tht the arrow is displayed **behind** the item score.
> 
> The Workaround:
> 
> 1. Go To Interface > Adibags
> 2. Go in the Plugins section, click plugins (not the subcategorys)
> 3. There you can see every plugin and you just need to uncheck the item score plugin.
> 4. ???
> 5. Profit
> 
> You'll loose the general item score info, but you gain the pawn arrow.

didn't work.

**Comment by MrMotte** [comment]
Should work, for me it does.
Or do you mean something different?

![grafik](https://user-images.githubusercontent.com/24703356/65371397-77b90d00-dc63-11e9-8675-8d78f6521652.png)

**Comment by Talyrius** [comment]
See #303.

**Comment by alienbogart** [comment]
I tried using adibags today in Classic WoW WOTLK and it does not show the Pawn arrows even when I disable all sub-plugins.
