### ISSUE TITLE
request: show tooltips of items in manual filtering lists

### ISSUE THREAD

**Issue by gobacktogo** [AdiAddons/AdiBags#377]
hey,
first of all, not sure this is the right place to make a request, if it isnt, i am sorry.
next, thanks for this great addon!

my request is this: i'd love to see tooltips of items when i check my manual filtering list.
currently playing classic and since there seems to be no outfitter addon or something similar, i am using adibags to handle my sets. i play druid, i got 3 sets, 2 of them are in my bank. when i get a potential upgrade, i'd like to see the tooltip of the items that i got in my bank and in one of the manual filtering sections!

thanks!

**Comment by Talyrius** [comment]
That's outside the scope of this addon. You're either going to have to carry the other sets with you or use an additional addon that'll provide the functionality you seek. You'll need something that'll specifically allow you to manage gear sets or view the contents of your bank remotely.
