### ISSUE TITLE
hiding quiver 

### ISSUE THREAD

**Issue by amey1956** [AdiAddons/AdiBags#379]
i have not been able to figure out how to hide the quiver/ammo pouch on hunter or for any free space to not be included. 

help please - thanks ;)

**Comment by SpareSimian** [comment]
This is going to be an issue with all special bags, like soul shard bags for warlocks and, eventually, profession bags. They became obsolete with the huge bags of retail and the addition of the reagent bank. I think AdiBags does treat profession bags as special, so we just need to add quivers and soul bags to the profession bag logic.
