### ISSUE TITLE
Integrate with LibItemSearch

### ISSUE THREAD

**Issue by swichers** [AdiAddons/AdiBags#38]
It would be extremely useful if https://github.com/Jaliborc/LibItemSearch-1.2 was integrated into this addon. Adibags is my favorite bag addon, but this advanced searching is something I've been missing for a long time. For an example of how it works you can try Bagnon or BagSync, or read the documentation on the github repo.

A quick example is: `slot:feet&lvl:>=640` This would find all boots with an ilvl of 640 or higher.

**Comment by SHJordan** [comment]
is this still planed? this is the feature i miss the most from elvui/bagnon
