### ISSUE TITLE
[Classic WoW] AdiBags hiding lua errors

### ISSUE THREAD

**Issue by Thex-PiedDroit** [AdiAddons/AdiBags#383]
Hello there wonderful person!

I installed adibags basically first thing when starting classic, and i recently i realized my lua errors were not showing up anymore, even when forcing one in my own addons.
I tried disabling all my addons to see if that was caused by any of them and it turns out it's adibags, for some reason.

I've seen there's an option to mute errors, which is disabled on my end (tried enabling it, no change in behaviour), and tracked it down in the code but quite frankly it's late and your bug grabber seems a bit too complicated for me to dive into just now :D But i would guess there may be some issue in there.
I quickly tried commenting out the condition "if not addon.db.global.muteBugGrabber" in Core.lua : 264, but it doesn't work either.

Anyway, i hope this helps and can get fixed, thanks for an awesome addon, and have a good one!
If you need any further details don't hesitate to ask :)

**Comment by wtfblub** [comment]
A quick workaround while this is bugged: Remove the line `libs/BugGrabber/load.xml` from AdiBags.toc

**Comment by Talyrius** [comment]
See #266. The fix will eventually be merged into the classic branch.
