### ISSUE TITLE
Masque support (somewhat fixed)

### ISSUE THREAD

**Issue by HeavensRejected** [AdiAddons/AdiBags#386]
![AdiMasque](https://user-images.githubusercontent.com/5093490/65669675-4c0f9b80-e044-11e9-9ada-27e55d79ec60.png)
So I've already done some "work" on Masque support and here's what I've done:

- https://github.com/AdiAddons/AdiBags/commit/239ac142fa13f4b66393004e3a22943c8ae74638
Adds general Masque support, works fine except that the empty bag slot has a default backdrop.

Now to temporarily fix that in ItemButton.lua on line 288:

```lua
function buttonProto:Update()
	if not self:CanUpdate() then return end
	local icon = self.IconTexture
	if self.texture then
		icon:SetTexture(self.texture)
		icon:SetTexCoord(0,1,0,1)
	else
		icon:SetTexture([[Interface\BUTTONS\UI-EmptySlot]])
		icon:SetTexCoord(12/64, 51/64, 12/64, 51/64)
	end
```
Change this:
icon:SetTexture([[Interface\BUTTONS\UI-EmptySlot]])

To something like this (depending on the Masque skin, pretty sure this would be dynamically doable?)
icon:SetTexture([[Interface\AddOns\Masque_Caith\Textures\Backdrop-Item]])

The only thing I haven't gotten working is the pushed effect but I'm sometimes terribad at this.

Would be nice if you could add Masque support, if not just close the issue.

Thanks!

**Comment by Silverseppel** [comment]
Yes, Masque support would be very nice.

**Comment by leobolin** [comment]
Has anyone managed to get Masque to work properly after patch 9.0? I can get it working with the old code modifications except the quality borders are broken.

**Comment by ppluchon** [comment]
Hello, 
Facing the same issue, all my items have a "goldish" quality border
