### ISSUE TITLE
Bag categories overlapping causing item icons to push beyond addon's frame

### ISSUE THREAD

**Issue by jasonlbeal** [AdiAddons/AdiBags#39]
http://imgur.com/QYaYvaW

It was working normally before. It just started doing this recently. I have some custom categories, nothing too complex. Is there any additional info I can provide?

**Comment by swoosh5** [comment]
Ok, some additional information. In Options under section layout, I had the Backpack column width set to 20. This seem to have caused it. I reduced it to 6 and the sections all cradled back into the frame appropriately.
