### ISSUE TITLE
Constants.lua - table index nil error

### ISSUE THREAD

**Issue by Kugly** [AdiAddons/AdiBags#391]
Got the below error today, tried disabling all other addons and reinstalling - but still keep getting this issue - worked fine on my laptop but not on my PC.

_Date: 2019-10-07 17:45:46
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Constants.lua line 44:
   table index is nil
Debug:
   AdiBags\core\Constants.lua:44: in main chunk
Locals:
addonName = "AdiBags"
addon = <table> {
 L = <table> {
 }
}
L = <table> {
 Reset new items = "Reset new items"
 Use SyLevel = "Use SyLevel"
 Bags = "Bags"
 Bag background = "Bag background"
 Use this section to define any item-section association. = "Use this section to define any item-section association."
 Alt-right-click to configure manual filtering. = "Alt-right-click to configure manual filtering."
 AMMO_TAG = "Am"
 auto-sort = "auto-sort"
 Let SyLevel handle the the display. = "Let SyLevel handle the the display."
 Never = "Never"
 Consider gems as a subcategory of trade goods = "Consider gems as a subcategory of trade goods"
 ... including incomplete stacks = "... including incomplete stacks"
 Filter = "Filter"
 Change stacking at merchants', auction house, bank, mailboxes or when trading. = "Change stacking at merchants', auction house, bank, mailboxes or when trading."
 Same as InventoryItemLevels = "Same as InventoryItemLevels"
 Bind type = "Bind type"
 Recent Items = "Recent Items"
 Size = "Size"
 Track new items in each bag, displaying a glowing aura over them and putting them in a special section. "New" status can be reset by clicking on the small "N" button at top left of bags. = "Track new items in each bag, displaying a glowing aura over them and putting them in a special section. "New" status can be reset by clicking on the small "N" button at top left of bags."
 Display the level of equippable item in the top left corner of the button. = "Display the level of equippable item in the top left corner of the button."
 Font = "Font"
 Press Alt while doing so to open a dropdown menu. = "Press Alt while doing so to open a dropdown menu."
 None = "None"
 Lock anchor = "Lock anchor"
 Opacity = "Opacity"
 Show filtering information... = "Show filtering information..."
 Texture = "Texture"
 Select which first-level categories should be split by sub-categories. = "Select which first-level categories should be split by sub-categories."
 Mininum level = "Mininum level"
 Show only one free slot for each kind of bags. = "Show only one free slot for each kind of bags."
 Split by subcategories = "Split by subcategories"
 When checked, right-clicking on an empty space of a bag opens the configuration panel. = "When checked, right-clicking on an empty space of a bag opens the configuration panel."
 Click to reset item status. = "Click to reset item status."
 Container information = "Container information"
 ENCHANTING_BAG_TAG = "En"
 Filtering information = "Filtering information"
 Item category = "Item category"
 Merge free space = "Merge free space"
 Select how the bags are positionned. = "Select how the bags are positionned."
 Remove = "Remove"
 Toggle and configure item filters. = "Toggle and configure item filters."
 Small = "Small"
 Check this to display one individual section per set. If this is disabled, there will be one big "Sets" section. = "Check this to display one individual section per set. If this is disabled, there will be one big "Sets" section."
 Check this to display an indicator on quest items. = "Check this to display an indicator on quest items."
 Allow you manually redefine the section in which an item should be put. Simply drag an item on the section title. = "Allow you manually redefine the section in which an item should be put. Simply drag an item on the section title."
 Merge stackable items = "Merge stackable items"
 Drop your item there to add it to this section. = "Drop your item there to add it to this section."
 disabled = "disabled"
 Right-click to (un)lock the bag anchor. = "Right-click to (un)lock the bag anchor."
 Check this to show space at your bank in the plugin. = "Check this to show space at your bank in the plugin."
 Bank color = "Bank color"
 Virtual stacks display in one place items that actually spread over several bag slots. = "Virtual stacks display in one place items that actually spread over several bag slots."
 Right-click to open options = "Right-click to open options"
 Right-click to try to empty this bag. = "Right-click to try to empty this bag."
 Highlight scale = "H
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdiBags, vv1.9.17
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=68)_

**Comment by Talyrius** [comment]
There are separate versions of AdiBags for each client version (Classic and Retail). You appear to be using the wrong version for your game client.

**Comment by Kugly** [comment]
So embarrassing! 

But easy fix -works great now with the correct version!
