### ISSUE TITLE
Enchanting doesn't update item count on mats (classic)

### ISSUE THREAD

**Issue by SpareSimian** [AdiAddons/AdiBags#393]
(In Classic) I just enchanted a new cloak with minor resistance with 4 Lesser Magic Essence in my bag and the essence stack count didn't decrease by 2 as expected. I saw 4 and right-clicked, expecting to merge them into a Greater Magic Essence, and the game told me it didn't have enough. I went to the bank and moved the stack into the bank and it updated the count to the expected 2. 

Perhaps the event from the Enchant button isn't hooked? I'll try another enchant shortly to check.

**Comment by SpareSimian** [comment]
I created a Greater Magic Wand and the item counts updated. So perhaps it's only normal enchants and not item creation enchanting that are affected.

**Comment by Talyrius** [comment]
I asked someone I know that's been using AdiBags on Classic and has maxed out their Enchanting if they've experienced anything similar. To their knowledge, they haven't.  ¯\_(ツ)_/¯
