### ISSUE TITLE
Can't open bags

### ISSUE THREAD

**Issue by sleepdprived** [AdiAddons/AdiBags#395]
Earlier today I updated wow and the adibags addon.  Now, when I try to open my bags, I get these error messages:

![image](https://user-images.githubusercontent.com/56417049/66614387-7c038680-eb8e-11e9-8900-38382afc7cce.png)

**Comment by Talyrius** [comment]
There are separate versions of AdiBags for each game client (Classic and Retail). You appear to be using the wrong version for your game client.

**Comment by sleepdprived** [comment]
What the heck....that's exactly what the problem was.  I don't know how it happened -- updated a bunch of addons via Twitch today, and they all updated with the Classic versions...

Thanks for the help!
