### ISSUE TITLE
Opening

### ISSUE THREAD

**Issue by NokuraWoW1** [AdiAddons/AdiBags#396]
7x AdiBags\core\Bags.lua:130: attempt to index field 'CloseButton' (a nil value)
AdiBags\core\Bags.lua:130: in function `GetFrame'
AdiBags\core\Bags.lua:83: in function `Open'
AdiBags\core\Bags.lua:209: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `SendMessage'
AdiBags\core\Core.lua:430: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>

**Comment by Talyrius** [comment]
There are separate versions of AdiBags for each game client (Classic and Retail). You appear to be using the wrong version for your game client.

**Comment by trdahl** [comment]
have the same problem, ive been using adibags for longtime, but after last update, the addon changed ... Now theres only for classic, not retail ...

**Comment by Talyrius** [comment]
No, there are two separate versions of AdiBags. You're currently using the wrong version. 

**Download here:**
https://www.curseforge.com/wow/addons/adibags/files

![image](https://user-images.githubusercontent.com/1068810/66683521-84120380-ec2c-11e9-8320-5534bb7bb438.png)

**Comment by trdahl** [comment]
Yeah i know, but if u auto update all your addons with curse, it installs
the classic... so then you have to reinstall it manually.

-Trond

fre. 11. okt. 2019 kl. 22:43 skrev Talyrius <notifications@github.com>:

**Comment by Talyrius** [comment]
The Twitch app shouldn't be downloading addons that are incompatible with your game client. Previously, someone said it stopped trying to do this after they restarted it. Try that.

**Comment by EmyPica** [comment]
I've had this issue too. Using the Twitch app to download and install, and to reinstall still got the version that won't open. Manually downloading the zip and installing that way got it to work. No idea what's up, but it seems to be Twitch not the addon itself.

**Comment by justix1183** [comment]
I have the same problem, adibags dead in the water using twitch to manage addon

**Comment by Sugarcaen** [comment]
This seems to be an issue with the twitch client, deleting and reinstalling should resolve it.
