### ISSUE TITLE
adibags is suppressing all lua errors from everything

### ISSUE THREAD

**Issue by ssateneth** [AdiAddons/AdiBags#398]
Whenever I have adibags addon running (I disabled all addons except adibags to double check, then turned off adibags), it seems that adibags is suppressing all lua errors. this isnt good if i am developing other things too. i test with something like "/run werfkjewrk" which should pop an error.

**Comment by Klixxx** [comment]
AdiBags has buggrabber implemented in its core, please download BugSack to show those error AdiBags grab for you

**Comment by Talyrius** [comment]
See #266.
