### ISSUE TITLE
Adibags LDB and reagent vs regular bank

### ISSUE THREAD

**Issue by jgwallace3** [AdiAddons/AdiBags#40]
The reagent bank counts are lumped into the regular bank counts in the LDB display. It would be nice to separate them or be able to exclude the reagent bank from the count. 

I almost always have space in my reagent bank but frequently run out of space in my regular bank (darn salvage yard and xmog addiction).

Thanks!

**Comment by jgwallace3** [comment]
Completed? Where?

**Comment by Cidan** [comment]
See #645 -- @Talyrius has reopened it, so we'll take a look.

**Comment by jgwallace3** [comment]
Another pulse check? Which release was it added in?

**Comment by jgwallace3** [comment]
OK. NM. Read https://github.com/AdiAddons/AdiBags/issues/997 and see better things are coming. Will this issue be addressed in the new sw?
