### ISSUE TITLE
hunter ammo - auto put extra into "ammo" bag?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [AdiAddons/AdiBags#402]
If I have an 8 slot bag, but buy 20 ammo stacks can I have an extra stack auto go into the ammo bag?

So 1 stack of 8 is gone, and than Adibags will automove an extra stack into that bag.

I was playing around with item filter and categories, but that stuff looks like it's all visual appeal... maybe I'm wrong.

**Comment by Talyrius** [comment]
Not automatically, no. You'll need to remember to move some more over yourself if you're going to carry extra.

**Comment by Smarnz** [comment]
Hello, was having the same problem. I am happy to manually move ammo over to the right bag. Problem is there is no way to tell which ammo is in my main bag and which is in my quiver without disabling the add on. Is there a solution to this?

**Comment by Smarnz** [comment]
I believe there is a bag type icon on the item but it is covered by the item level
