### ISSUE TITLE
Visual Issue - Manual Filtering Sections

### ISSUE THREAD

**Issue by HolteUnderscore** [AdiAddons/AdiBags#404]
The attached picture shows what is happening better than I can describe it in words.  Basically for some reason, certain sections are wrapping at 11 items and others at 6, by that I mean starting a new row of items in the section (as you can see in the first image).  This causes the items to overlap the title of the next section and also, if the last one in the list has more than a certain number of items in it, it pushes the blank space to add new items to it off the bottom of the screen so you can't add any more (see second image).
![Adibags Issue](https://user-images.githubusercontent.com/36149521/68399898-0976ce00-016f-11ea-8e01-a73b64c9b819.jpg)
![Adibags Issue 2](https://user-images.githubusercontent.com/36149521/68400166-7db17180-016f-11ea-8a9b-1c8175fd548e.jpg)

**Comment by Talyrius** [comment]
See #278.
