### ISSUE TITLE
updated addon today 11.22.19 and got this error:

### ISSUE THREAD

**Issue by Gal10** [AdiAddons/AdiBags#407]
Error in AdiBags: Interface\AddOns\AdiBags\core\OO.lua:54: CreateFrame(): Couldn't find inherited node "ItemButtonTemplate" -- details: [Error 0000021C3A145750]
Error in AdiBags: Interface\AddOns\AdiBags\core\Bags.lua:130: attempt to index field 'CloseButton' (a nil value) -- details: [Error 0000021C3A145A20]

Error in AdiBags: Interface\AddOns\AdiBags\core\Layout.lua:97: attempt to index field 'Anchor' (a nil value) -- details: [Error 0000021C95CF47A0]
Error in AdiBags: Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:453: attempt to index field 'Title' (a nil value) -- details: [Error 0000021C95D63DA0]

And I can not open bags unless I disable addon. Please help.

**Comment by shinsology** [comment]
Hey, there was probably just a error on twitch's side, so you can just reinstall the older version and it'll work just fine.

**Comment by Gal10** [comment]
Thank you. Did a little invastigation and found out that Twitch did an update for Adibags + other addons **for classic and mix it with the retail**...so went back to each addon and downloaded the version before.
