### ISSUE TITLE
probably a big ask...

### ISSUE THREAD

**Issue by feraluna** [AdiAddons/AdiBags#411]
I'm using a variety of AdiBags addons to differentiate which items go to which expansion (Classic to BFA) and I'm finding that none of the reputation items are moving to the appropriate sections even though I'm adding the items to the code for the filtering tables.  

I literally am a complete noob when it comes to code, but I can fill data in a table like nobody's business!

If you can help me get started, I would be happy to fill that data table so it can be shared to work with your most AWESOME of bag addons!

TIA and if it's something I would be better working with a different addon author on, please let me know who you think it should be and I'll definitely reach out to them!

**Comment by SpareSimian** [comment]
I suggest forking the repo so we can see your edits.

**Comment by Talyrius** [comment]
These types of filters are better suited towards external plugins.
