### ISSUE TITLE
Classic

### ISSUE THREAD

**Issue by zurdlol** [AdiAddons/AdiBags#412]
Hello,

When trying to enter AV there is an error and i am forced to disable the addon to continue.

**Comment by mf312** [comment]
Also stopped working for me (not sure if it was the patch, or an AdiBags update - I just d/l from Curse/Twitch without paying much attention). Trashing the prefs through Twitch did not help (who knows if that works anyway).

```
Error0000016C95042AD0
Interface\AddOns\AdiBags\core\Constants.lua:44: table index is nil
Interface\AddOns\AdiBags\core\Constants.lua:44: in main chunk
```

Unfortunately from there the window seems to "jump" to Container information="Container information"

**Comment by Dgc2002** [comment]
To help alleviate this a bit: Instead of clicking "Enter Battle" on the main dialog, you can right click the icon on your mini-map and click "Enter Battle" there without needing to disable addons or reload you rui.
