### ISSUE TITLE
 attempt to call method 'HookScript' (a nil value)

### ISSUE THREAD

**Issue by festisio** [AdiAddons/AdiBags#417]
Date: 2019-12-29 18:19:47
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\modules\Junk.lua line 244:
   attempt to call method 'HookScript' (a nil value)
Debug:
   AdiBags\modules\Junk.lua:244: in main chunk
Locals:
addonName = "AdiBags"
addon = <table> {
 AcquireItemButton = <function> defined @Interface\AddOns\AdiBags\widgets\ItemButton.lua:146
 modules = <table> {
 }
 UpdateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:434
 ConfigChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:354
 GetSlotId = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:57
 Filter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 Reconfigure = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:176
 SetupTooltip = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:188
 CreateFont = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:122
 filterProto = <table> {
 }
 OpenOptions = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:282
 SetEnabledState = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 IterateBags = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:183
 OnEnable = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:115
 HookBagFrameCreation = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:287
 NewBag = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:150
 GetClass = <function> defined @Interface\AddOns\AdiBags\core\OO.lua:129
 RegisterFilter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 InitializeFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:64
 IterateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:116
 CreateBagSlotPanel = <function> defined @Interface\AddOns\AdiBags\widgets\BagSlots.lua:437
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:137
 ToggleAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:86
 OnProfileChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:184
 GetName = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "AdiBags"
 OpenBackpack = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:168
 LayoutBags = <function> defined @Interface\AddOns\AdiBags\core\Layout.lua:101
 Disable = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 SetGlobalLock = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:402
 Unhook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OpenAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:109
 L = <table> {
 }
 safecall = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:81
 Debug = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:61
 CreateAnchorWidget = <function> defined @Interface\AddOns\AdiBags\widgets\AnchorWidget.lua:37
 ITEM_SIZE = 37
 DEFAULT_SETTINGS = <table> {
 }
 CreateBagAnchorWidget = <function> defined @Interface\AddOns\AdiBags\widgets\AnchorWidget.lua:218
 FAMILY_ICONS = <table> {
 }
 UnregisterEvent = <function> defined @Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SetDefaultModuleL
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AAPClassic, v0.13
  AdiBags, vv1.9.17-classic
  Scrap, v8.2.2
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=94)

**Comment by Zarggg** [comment]
Already reported. See #416 for a temporary fix.

**Comment by Talyrius** [comment]
See #416 & #422; fixed via ae53167.
