### ISSUE TITLE
Error opening the bank

### ISSUE THREAD

**Issue by MISTERJT3** [AdiAddons/AdiBags#419]
When I open the bank I see my primary bags in Adi and about 50% of the time the bank bags just don't appear. A partial window appears showing an incorrect amount of empty space. Sometimes I have to close the bags completely and interact with the bank character over and over until it works. I am not sure what is going on there but here is the error that it printed to my chat window. 

Error in AdiBags: Interface\AddOns\AdiBags\modules\DataSource.lua:127: table index is nil -- details: [Error 00000158F1715710]
Interface\AddOns\AdiBags\modules\DataSource.lua:127: table index is nil
Interface\AddOns\AdiBags\modules\DataSource.lua:127: in function <Interface\AddOns\AdiBags\modules\DataSource.lua:119>
Interface\AddOns\AdiBags\modules\DataSource.lua:154: in function <Interface\AddOns\AdiBags\modules\DataSource.lua:151>
(tail call): ?
...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function <...dler-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
(tail call): ?

**Comment by Talyrius** [comment]
Have you tried reinstalling the latest AdiBags release for your game client (Classic or Retail)?

Please use the [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber) & [BugSack](https://www.curseforge.com/wow/addons/bugsack) addon combination to collect your errors and share them here.
