### ISSUE TITLE
junk.lua

### ISSUE THREAD

**Issue by Seehawk28** [AdiAddons/AdiBags#421]
Date: 2020-01-13 06:42:41
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\modules\Junk.lua line 246:
   attempt to call method 'HookScript' (a nil value)
Debug:
   AdiBags\modules\Junk.lua:246: in main chunk
Locals:
addonName = "AdiBags"
addon = <table> {
 AcquireItemButton = <function> defined @Interface\AddOns\AdiBags\widgets\ItemButton.lua:155
 modules = <table> {
 }
 UpdateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:451
 ConfigChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:371
 GetSlotId = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:57
 Filter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 Reconfigure = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:183
 SetupTooltip = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:188
 CreateFont = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:122
 filterProto = <table> {
 }
 OpenOptions = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:289
 SetEnabledState = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 IterateBags = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:183
 OnEnable = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:115
 HookBagFrameCreation = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:305
 NewBag = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:150
 GetClass = <function> defined @Interface\AddOns\AdiBags\core\OO.lua:129
 RegisterFilter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 InitializeFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:64
 IterateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:362
 CreateBagSlotPanel = <function> defined @Interface\AddOns\AdiBags\widgets\BagSlots.lua:437
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:137
 ToggleAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:86
 OnProfileChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:191
 GetName = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "AdiBags"
 OpenBackpack = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:168
 LayoutBags = <function> defined @Interface\AddOns\AdiBags\core\Layout.lua:101
 Disable = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 SetGlobalLock = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:419
 Unhook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OpenAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:109
 L = <table> {
 }
 safecall = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:81
 Debug = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:61
 CreateAnchorWidget = <function> defined @Interface\AddOns\AdiBags\widgets\AnchorWidget.lua:37
 ITEM_SIZE = 37
 DEFAULT_SETTINGS = <table> {
 }
 CreateBagAnchorWidget = <function> defined @Interface\AddOns\AdiBags\widgets\AnchorWidget.lua:218
 FAMILY_ICONS = <table> {
 }
 UnregisterEvent = <function> defined @Interface
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdiBags, vv1.9.18
  Scrap, v8.2.2
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=77)

**Comment by WildBillUK** [comment]
Me getting the same error, it started a few days ago after there was a blizz client update to fix the guild chat issues.

**Comment by zalewskigrzegorz** [comment]
have this same
`1x AdiBags\modules\Junk.lua:246: attempt to call method 'HookScript' (a nil value)
[string "@AdiBags\modules\Junk.lua"]:246: in main chunk

Locals:
addonName = "AdiBags"
addon = <table> {
 AcquireItemButton = <function> defined @AdiBags\widgets\ItemButton.lua:198
 modules = <table> {
 }
 UpdateFilters = <function> defined @AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @AdiBags\core\Core.lua:474
 ConfigChanged = <function> defined @AdiBags\core\Core.lua:394
 GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
 Filter = <function> defined @AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 Reconfigure = <function> defined @AdiBags\core\Core.lua:187
 SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:188
 CreateFont = <function> defined @AdiBags\core\Fonts.lua:122
 filterProto = <table> {
 }
 OpenOptions = <function> defined @AdiBags\core\Core.lua:293
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 IterateBags = <function> defined @AdiBags\core\Bags.lua:183
 OnEnable = <function> defined @AdiBags\core\Core.lua:115
 HookBagFrameCreation = <function> defined @AdiBags\core\Bags.lua:305
 NewBag = <function> defined @AdiBags\core\Bags.lua:150
 GetClass = <function> defined @AdiBags\core\OO.lua:129
 RegisterFilter = <function> defined @AdiBags\core\Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 InitializeFilters = <function> defined @AdiBags\core\Filters.lua:64
 IterateFilters = <function> defined @AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @AdiBags\core\Core.lua:385
 CreateBagSlotPanel = <function> defined @AdiBags\widgets\BagSlots.lua:453
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @AdiBags\core\Hooks.lua:137
 ToggleAllBags = <function> defined @AdiBags\core\Hooks.lua:86
 OnProfileChanged = <function> defined @AdiBags\core\Core.lua:195
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "AdiBags"
 OpenBackpack = <function> defined @AdiBags\core\Hooks.lua:168
 LayoutBags = <function> defined @AdiBags\core\Layout.lua:101
 Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
 SetGlobalLock = <function> defined @AdiBags\core\Core.lua:442
 Unhook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:54
 OpenAllBags = <function> defined @AdiBags\core\Hooks.lua:109
 L = <table> {
 }
 safecall = <function> defined @AdiBags\core\Utility.lua:81
 Debug = <function> defined @AdiBags\core\Core.lua:61
 CreateAnchorWidget = <function> defined @AdiBags\widgets\AnchorWidget.lua:37
 ITEM_SIZE = 37
 DEFAULT_SETTINGS = <table> {
 }
 CreateBagAnchorWidget = <function> defined @AdiBags\widgets\AnchorWidget.lua:218
 FAMILY_ICONS = <table> {
 }
 UnregisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SetDefaultModuleLibrar`

**Comment by Talyrius** [comment]
See #416 & #422; fixed via ae53167.
