### ISSUE TITLE
Can't change bag height 

### ISSUE THREAD

**Issue by LeoNewgate** [AdiAddons/AdiBags#423]
Please fix that i can't change the bag height i really like the addon but that is broken

**Comment by Beaker567** [comment]
I have the same problem. It appears that the 'Maximum bag height' setting works for the bank, but not for the backpack. Backpack height stays very low, forcing it to be very wide - wide enough that when the bank is opened to the left of the backpack, most of the bank is unviewable (past the left edge of the screen).

**Comment by Talyrius** [comment]
Track fewer currencies—that's almost certainly what's to blame.

**Comment by Beaker567** [comment]
Brother you nailed it - thank you very much!!
