### ISSUE TITLE
Junk.lua error on start since 8.2.5

### ISSUE THREAD

**Issue by scipherneo** [AdiAddons/AdiBags#424]
I've been getting this error since I installed AdiBags about a week before 8.3, whenever I load in to my character or do /reload

Date: 2020-01-16 19:10:41
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\modules\Junk.lua line 242:
   attempt to call method 'HookScript' (a nil value)
Debug:
   [string "@AdiBags\modules\Junk.lua"]:242: in main chunk
Locals:
addonName = "AdiBags"
addon = <table> {
 AcquireItemButton = <function> defined @Interface\AddOns\AdiBags\widgets\ItemButton.lua:155
 modules = <table> {
 }
 UpdateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:451
 ConfigChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:371
 GetSlotId = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:57
 Filter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 Reconfigure = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:183
 SetupTooltip = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:188
 CreateFont = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:122
 filterProto = <table> {
 }
 OpenOptions = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:289
 SetEnabledState = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 IterateBags = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:183
 OnEnable = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:115
 HookBagFrameCreation = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:305
 NewBag = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:150
 GetClass = <function> defined @Interface\AddOns\AdiBags\core\OO.lua:129
 RegisterFilter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 InitializeFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:64
 IterateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:362
 CreateBagSlotPanel = <function> defined @Interface\AddOns\AdiBags\widgets\BagSlots.lua:437
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:137
 ToggleAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:86
 OnProfileChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:191
 GetName = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "AdiBags"
 OpenBackpack = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:168
 LayoutBags = <function> defined @Interface\AddOns\AdiBags\core\Layout.lua:101
 Disable = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 SetGlobalLock = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:419
 Unhook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OpenAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:109
 L = <table> {
 }
 safecall = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:81
 Debug = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:61
 CreateAnchorWidget = <function> defined @Interface\AddOns\AdiBags\widgets\AnchorWidget.lua:37
 ITEM_SIZE = 37
 DEFAULT_SETTINGS = <table> {
 }
 CreateBagAnchorWidget = <function> defined @Interface\AddOns\AdiBags\widgets\AnchorWidget.lua:218
 FAMILY_ICONS = <table> {
 }
 UnregisterEvent = <function> defined @Interface
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdiBags, vv1.9.18
  Scrap, v8.3.0
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=77)

**Comment by NobodyNParticular** [comment]
I'm getting this as well: 
393x AdiBags\modules\Junk.lua:246: attempt to call method 'HookScript' (a nil value)
AdiBags\modules\Junk.lua:246: in main chunk

Locals:
addonName = "AdiBags"
addon = <table> {
 AcquireItemButton = <function> defined @AdiBags\widgets\ItemButton.lua:155
 modules = <table> {
 }
 UpdateFilters = <function> defined @AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @AdiBags\core\Core.lua:451
 ConfigChanged = <function> defined @AdiBags\core\Core.lua:371
 GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
 Filter = <function> defined @AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 Reconfigure = <function> defined @AdiBags\core\Core.lua:183
 SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:188
 CreateFont = <function> defined @AdiBags\core\Fonts.lua:122
 filterProto = <table> {
 }
 OpenOptions = <function> defined @AdiBags\core\Core.lua:289
 SetEnabledState = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 IterateBags = <function> defined @AdiBags\core\Bags.lua:183
 OnEnable = <function> defined @AdiBags\core\Core.lua:115
 HookBagFrameCreation = <function> defined @AdiBags\core\Bags.lua:305
 NewBag = <function> defined @AdiBags\core\Bags.lua:150
 GetClass = <function> defined @AdiBags\core\OO.lua:129
 RegisterFilter = <function> defined @AdiBags\core\Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 InitializeFilters = <function> defined @AdiBags\core\Filters.lua:64
 IterateFilters = <function> defined @AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @AdiBags\core\Core.lua:362
 CreateBagSlotPanel = <function> defined @AdiBags\widgets\BagSlots.lua:437
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @AdiBags\core\Hooks.lua:137
 ToggleAllBags = <function> defined @AdiBags\core\Hooks.lua:86
 OnProfileChanged = <function> defined @AdiBags\core\Core.lua:191
 GetName = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 name = "AdiBags"
 OpenBackpack = <function> defined @AdiBags\core\Hooks.lua:168
 LayoutBags = <function> defined @AdiBags\core\Layout.lua:101
 Disable = <function> defined @Accountant\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
 SetGlobalLock = <function> defined @AdiBags\core\Core.lua:419
 Unhook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Accountant\Libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OpenAllBags = <function> defined @AdiBags\core\Hooks.lua:109
 L = <table> {
 }
 safecall = <function> defined @AdiBags\core\Utility.lua:81
 Debug = <function> defined @AdiBags\core\Core.lua:61
 CreateAnchorWidget = <function> defined @AdiBags\widgets\AnchorWidget.lua:37
 ITEM_SIZE = 37
 DEFAULT_SETTINGS = <table> {
 }
 CreateBagAnchorWidget = <function> defined @AdiBags\widgets\AnchorWidget.lua:218
 FAMILY_ICONS = <table> {
 }
 UnregisterEvent = <function>

**Comment by Talyrius** [comment]
See #416 & #422; fixed via ae53167.
