### ISSUE TITLE
Suggestion: Search by category/configure order of categories

### ISSUE THREAD

**Issue by Rave96** [AdiAddons/AdiBags#425]
Hey there :)
One thing that's kinda bothering me is, that categories will be ordered kinda randomly, so I'm constantly searching for the category and cant find it if it only has like 2 items in it.
So my suggestion would be, to either let us configure the order in which categories are displayed, or just highlight all items in a category if you search for the category name.
Would be amazing if one of those things could be implemented :D

**Comment by SpareSimian** [comment]
The order is the same as that of the Auction House. I think there's a setting for minimum width so the 2-item sections can be forced to take up 4 slots of space.
