### ISSUE TITLE
/reload

### ISSUE THREAD

**Issue by TchCzarina** [AdiAddons/AdiBags#426]
My bags are only usable (meaning I can get a tooltip, or click on items) for a short bit after I /reload. This addon seems to be updated. Any idea what is interfering?

**Comment by Talyrius** [comment]
Use the [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber) & [BugSack](https://www.curseforge.com/wow/addons/bugsack) addon combination to collect your errors and share them here.
