### ISSUE TITLE
Feature Request: Tooltips for Currencies

### ISSUE THREAD

**Issue by sthdevilish** [AdiAddons/AdiBags#427]
I'm using BagSync and MoneyTrail addons so I can track what I have on other characters (currencies and gold in this case, shown in the tooltip). It works in the Blizzard UI (showing information in tooltips when you hover mouse cursor over gold and selected currencies), but not in AdiBags sadly :-( I know it's a lot to ask for, but any chance this could be done? Unless it's something I should ask those addons authors for, no idea.

**Comment by Talyrius** [comment]
### Imported from [WowAce #195: Tooltips for Currencies](https://www.wowace.com/projects/adibags/issues/195)
> _**[sparesimian](https://www.wowace.com/members/sparesimian)** created this issue Aug 10, 2014_  
> It would be handy to display a tooltip for currencies similar to to the one displayed on the currency tab of the character window. The main thing I use it for is to see how close I am to the valor cap. If you invoke the same tooltip used on the currency tab, then information from other addons that add information to that tooltip (notably Altoholic) would be visible, and I can see how much of a currency I have on my alts without separately opening the character panel.

> _**[sparesimian](https://www.wowace.com/members/sparesimian)** added an attachment Aug 10, 2014_  
> Example of currency tooltip on character window currency tab
![CurrencyTooltipExample.png](https://user-images.githubusercontent.com/1068810/101238214-8be40100-3693-11eb-819f-8d877e3f1981.png)

> _**[Talyrius](https://www.wowace.com/members/Talyrius)** posted a comment Aug 10, 2014_  
> I asked for this as well:
>> **[WowAce #145: Currency Display Improvements](https://www.wowace.com/projects/adibags/issues/145)**  
>> _**[Talyrius](https://www.wowace.com/members/Talyrius)** created this issue Nov 3, 2012_  
>> It would be helpful if the actual in-game tooltips were displayed for each currency on mouseover. While the icon does a great job of differentiating the various types of currency—it doesn't explicitly identify them. This would be especially useful for checking weekly caps and learning about currencies that you are unfamiliar with.
>
>> _**[Adirelle](https://www.wowace.com/members/Adirelle)** posted a comment Nov 10, 2012_  
>> There is only one frame for all currencies, so there can be only one tooltip. So either it should show all currencies either none.
>
>> _**[Talyrius](https://www.wowace.com/members/Talyrius)** posted a comment Nov 11, 2012_  
>> I understand that there is only one frame for all of the currencies. What I meant to suggest is that the currency tooltips would override the normal tooltip only when mousing over the icon for each currency similarly to the way Blizzard does within their TokenUI. They make each icon a button.

> _**[Adirelle](https://www.wowace.com/members/Adirelle)** posted a comment Aug 10, 2014_  
> Well, this would require to rewrite to currency module to use several sub-frames. Actually this is only a fontstring with some icons ; no way to tell which currency the mouse hovers over.

> _**[sparesimian](https://www.wowace.com/members/sparesimian)** posted a comment Aug 11, 2014_  
> I suspected it would be a SMOP (small matter of programming, meant ironically), so it's not something I'd expect you to be able to just whip out quickly. But it's a nice-to-have that I'm pretty sure was available with the standard bag. Something to add in your "copious spare time". ;)

**Comment by N6REJ** [comment]
I'm all for this 👍

**Comment by GaelicGamer** [comment]
Yeah this would be a nice feature

**Comment by Talyrius** [comment]
### Merged from #772:
> ### Describe the feature
> Mousing over a currency should display a tooltip like the ones on the Currency tab in the Character display.
> 
> ### Describe the implementation
> With the Altoholic addon, this allows me to see which of my alts can afford to buy a BoA item like an heirloom. ![wow-currency-tooltip](https://user-images.githubusercontent.com/1709928/200414527-1cb12c12-3050-47f0-b5a9-f937c2c87519.png)

**Comment by SpareSimian** [comment]
I'm currently using TitanPanel which allows me to display currencies in the Titan bars at the top or bottom of the screen, and those have the desired tooltips. So that might be a solution for others willing to install the additional addon.
