### ISSUE TITLE
I have an error, i cant find how it produces, or what it affects

### ISSUE THREAD

**Issue by jakabszili13** [AdiAddons/AdiBags#428]
I have an error and bugsack always alerts me but i dont know anything else about it. Here is the error: 

`34x AdiBags\modules\Junk.lua:246: attempt to call method 'HookScript' (a nil value)
[string "@AdiBags\modules\Junk.lua"]:246: in main chunk

Locals:
addonName = "AdiBags"
addon = <table> {
 AcquireItemButton = <function> defined @AdiBags\widgets\ItemButton.lua:155
 modules = <table> {
 }
 UpdateFilters = <function> defined @AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @AdiBags\core\Core.lua:451
 ConfigChanged = <function> defined @AdiBags\core\Core.lua:371
 GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
 Filter = <function> defined @AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 Reconfigure = <function> defined @AdiBags\core\Core.lua:183
 SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:188
 CreateFont = <function> defined @AdiBags\core\Fonts.lua:122
 filterProto = <table> {
 }
 OpenOptions = <function> defined @AdiBags\core\Core.lua:289
 SetEnabledState = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 IterateBags = <function> defined @AdiBags\core\Bags.lua:183
 OnEnable = <function> defined @AdiBags\core\Core.lua:115
 HookBagFrameCreation = <function> defined @AdiBags\core\Bags.lua:305
 NewBag = <function> defined @AdiBags\core\Bags.lua:150
 GetClass = <function> defined @AdiBags\core\OO.lua:129
 RegisterFilter = <function> defined @AdiBags\core\Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 InitializeFilters = <function> defined @AdiBags\core\Filters.lua:64
 IterateFilters = <function> defined @AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @AdiBags\core\Core.lua:362
 CreateBagSlotPanel = <function> defined @AdiBags\widgets\BagSlots.lua:437
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @AdiBags\core\Hooks.lua:137
 ToggleAllBags = <function> defined @AdiBags\core\Hooks.lua:86
 OnProfileChanged = <function> defined @AdiBags\core\Core.lua:191
 GetName = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "AdiBags"
 OpenBackpack = <function> defined @AdiBags\core\Hooks.lua:168
 LayoutBags = <function> defined @AdiBags\core\Layout.lua:101
 Disable = <function> defined @AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 SetGlobalLock = <function> defined @AdiBags\core\Core.lua:419
 Unhook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OpenAllBags = <function> defined @AdiBags\core\Hooks.lua:109
 L = <table> {
 }
 safecall = <function> defined @AdiBags\core\Utility.lua:81
 Debug = <function> defined @AdiBags\core\Core.lua:61
 CreateAnchorWidget = <function> defined @AdiBags\widgets\AnchorWidget.lua:37
 ITEM_SIZE = 37
 DEFAULT_SETTINGS = <table> {
 }
 CreateBagAnchorWidget = <function> defined @AdiBags\widgets\AnchorWidget.lua:218
 FAMILY_ICONS = <table> {
 }
 UnregisterEvent = <function> defined @Interface`

**Comment by mitterman2** [comment]
getting the same error on login and reload.

**Comment by Thunderhawk2001** [comment]
Same here. Tried reinstall with cleaning of WTF folder. Still happening.

**Comment by Talyrius** [comment]
See #416 & #422; fixed via ae53167.
