### ISSUE TITLE
Virtual stacks don't auto restack taking up bag space

### ISSUE THREAD

**Issue by philipaarseth** [AdiAddons/AdiBags#430]
Feature request: Automatic restacking

Virtual stacks is amazing and a huge help to help the visual clutter down on screen, but since it doesn't automatically (or any manual way that I can see) restack items, it can lead to your items taking up more technical bag space than you want. Because of the virtual stack you cannot see that an item is not stacked either.

https://imgur.com/a/MZGOXj4

As a side note, a temporary, time-out, item specific unstack would help with stack splitting, but then going back to the default option would be really neat.

**Comment by Talyrius** [comment]
Sorry, doing this automatically would cause unexpected frustration.
