### ISSUE TITLE
Corrupted Icon Overlay missing

### ISSUE THREAD

**Issue by Nercus** [AdiAddons/AdiBags#433]
## Describe the bug
There is no icon overlay for corrupted gear.

**Do you have an error log of what happened?**
no error log

### To Reproduce

1. Open Bag
2. Icon Missing

**Screenshots**

![Unbenannt](https://user-images.githubusercontent.com/48932939/73591812-abe6e900-44f3-11ea-909d-c434cdefb9f7.png)

**Did you try having Adibags as the only enabled addon and everything else disabled?**
yes

**Are you on World of Warcraft Classic or Retail?**
Retail

**Comment by shawngmc** [comment]
Looking at a framestack, in the regular bags a corrupted item has another layer, IconOverlay.
![image](https://user-images.githubusercontent.com/7342147/79922994-b03fe580-8402-11ea-8813-12ab3a197440.png)

Any idea if this layer could be added to Adibags?

**Comment by shawngmc** [comment]
This appears to be a new layer added to ContainerFrameItem, IconOverlay.
![image](https://user-images.githubusercontent.com/7342147/79927157-e2564500-840c-11ea-940c-84acc70db15a.png)

This is controlled in FrameXML\ItemButtonTemplate.lua around line 154:

![image](https://user-images.githubusercontent.com/7342147/79927392-9a83ed80-840d-11ea-9668-15459b37313e.png)

Interestingly enough, this also controls the Azerite Empowered icon overlay. I'm not sure what that frame is off the top of my head though.

I'm not a Lua expert, but I'm a software engineer and may see if I can make a patch to submit. :)
