### ISSUE TITLE
Adibags doesnt load Bank Bags only Backpacks bags

### ISSUE THREAD

**Issue by Gal10** [AdiAddons/AdiBags#435]

**Comment by NewVenari** [comment]
I noticed this too, and have had to go into the settings to disable the bank window to swap bags out for larger bags.

**Comment by Gal10** [comment]
Thank you. on yesterday update it was fix!

**Comment by Talyrius** [comment]
@Gal10
Good to hear!

@NewVenari
You have to click the bag icon at the top-left of your bag frame to swap out bags and/or purchase bank bag slots.
