### ISSUE TITLE
Unable to open mails specifically from Auction House

### ISSUE THREAD

**Issue by NewVenari** [AdiAddons/AdiBags#437]
Able to open other mails such as Brew of the Month and Postmaster with no issues. Opening won/expired mail, or mail containing gold from the AH (Basically ANYTHING from the AH) requires me to log out, disable Adibags, and logging back in to collect. Then, if I'm not too lazy, log back out to enable Adibags again to have a sorted backpack.

**Comment by shawngmc** [comment]
While I'm not the dev, quick question: what happens if you disable AdiBags via the AdiBags UI?

So, for example:
1) Type /adibags.
2) Uncheck 'Enable'
3) Open the Mail

**Comment by Talyrius** [comment]
It appears another addon isn't playing nice. Reenable AdiBags and disable other addons in batches until you're able to narrow down the culprit.
