### ISSUE TITLE
adibags won't load anymore as of last update

### ISSUE THREAD

**Issue by scooterh928** [AdiAddons/AdiBags#438]
Date: 2020-02-20 15:29:54
ID: 16
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Core.lua line 119:
   Usage: RegisterEvent("eventname", "methodname"): 'methodname' - method 'BAG_UPDATE' not found on self.
Debug:
   [C]: ?
   ...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:112: RegisterEvent()
   AdiBags\core\Core.lua:119:
      AdiBags\core\Core.lua:115
   [C]: ?
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...s\AddOnSkins\Libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353:
      ..\FrameXML\UIParent.lua:352
   [C]: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:424: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:693:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AddOnSkins, v4.39
  AdiBags, vv1.9.18 build 0.13
  AtlasLootClassic, vv1.4.6
  AtlasLootClassicData, vv1.4.6
  AtlasLootClassicDungeonsAndRaids, vv1.4.6
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  DBMCore, v1.13.36
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1303r001
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  ElvUI, v1.211
  ElvUIQuestXPClassic, v1.0.0
  GTFO, v4.54
  LeatrixMaps, v1.13.49
  LeatrixPlus, v1.13.50
  NeatMinimap, vv1.06.00
  Pawn, v2.3.22
  Questie, v5.7.1
  Stubby, v8.2.6510 (SwimmingSeadragon)
  WeakAuras, v2.16.6
  WeakAurasCompanion, v1.0.0
  WeaponSwingTimer, v4.1.0
  WIM, v3.8.5
  ZygorGuidesViewerClassic, v1.0
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=44d)

**Comment by Emulsify** [comment]
Any ETA on when this will be fixed? Adibags is by far the best bag addon and I'm so sad that it doesn't work any more D:

**Comment by SpareSimian** [comment]
FWIW, I'm using the alpha release on Classic and haven't had any issues.

**Comment by Talyrius** [comment]
Have you tried reinstalling the Classic version of AdiBags?
