### ISSUE TITLE
can't link items in any chat window.

### ISSUE THREAD

**Issue by Toenail1203** [AdiAddons/AdiBags#439]
this started happening before the most recent update.  the last time i reset chat window to default settings and ran the wow repair feature.  that seemed to fix it.

started again yesterday and changing chat settings didn't do anything  /reload and reload/ui (same thing?) didn't do anything.  I was going to go down the list of addons disabling each and testing.  adibags was the first in the list. chat linking started working as soon as i disabled it.  i tried again just enabling adibags w/o config.  linking stopped again.  i am not seeing any wow popup error message or LUA error window.

**Comment by Talyrius** [comment]
Linking items to chat works just fine with AdiBags enabled. Perhaps another addon isn't playing nice? Reenable AdiBags and disable other addons in batches until you're able to narrow down the culprit.
