### ISSUE TITLE
Changing layout between vertical/horizontal

### ISSUE THREAD

**Issue by epicjaryn** [AdiAddons/AdiBags#45]
I want my bag layout to be narrow and tall (as shown in your screenshot on Curse.com) instead of wide and short. I can't seem to find an option to change the amount of columns/rows.

**Comment by F-I-R-E-F-O-X** [comment]
I actually came here to make this post also haha. There should be a maximum bag width slider as well (or something similar).

**Comment by F-I-R-E-F-O-X** [comment]
As a tip epicjaryn, I found that disabling the currency / gold display in the bags helps keep the bag from stretching across the width of the screen.

**Comment by VulcanTourist** [comment]
I second this.  I was aware of tinkering with the gold and currencies options to manage width somewhat, but it would be nice to have dedicated options to dictate whether the frame expands across or up-down.  I choose to keep the frame locked in position, and so at times it obscures things I would rather not be obscured.

**Comment by flooper21** [comment]
I'd appreciate this feature as well. Isn't there already a way to do this since there is a screenshot featuring it on curse?

**Comment by Cidan** [comment]
If you look closely at the screenshot on Curse, you will notice that not every group has its own row. What you are seeing is the bags open with Compact Mode disabled. Disabling compact mode makes it so rows are packed as tightly together as possible, so long as all the items in all groups fit in a single row. If a row has more items that would fit the column width in the options, it gets a row of its own and "wraps" to the next line.

You can enable this feature by unchecking Compact Mode in the options.

**Comment by sfogarty** [comment]
That is the same as reducing the number of columns-of-columns. I would like to have 3 columns, each of 4, instead of 4 columns of 4.
