### ISSUE TITLE
[classic] error 

### ISSUE THREAD

**Issue by SunnyJang38** [AdiAddons/AdiBags#451]
> 16:07 Interface\AddOns\AdiBags\modules\Junk.lua:244: attempt to call method 'HookScript' (a nil value)
16:07 Interface\AddOns\AdiBags\modules\Junk.lua:244: in main chunk
16:07 addonName = "AdiBags"
addon = <table> {
 AcquireItemButton = <function> defined @Interface\AddOns\AdiBags\widgets\ItemButton.lua:146
 modules = <table> {
 }
 UpdateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:434
 ConfigChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:354
 GetSlotId = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:57
 Filter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 Reconfigure = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:176
 SetupTooltip = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:114
 RegisterMessage = <function> defined @Interface\AddOns\!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:188
 CreateFont = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:122
 filterProto = <table> {
 }
 OpenOptions = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:282
 SetEnabledState = <function> defined @Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceHook-3.0\AceHook-3.0.lua:274
 IterateBags = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:183
 OnEnable = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:115
 HookBagFrameCreation = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:287
 NewBag = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:150
 GetClass = <function> defined @Interface\AddOns\AdiBags\core\OO.lua:129
 RegisterFilter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 InitializeFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:64
 IterateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:116
 CreateBagSlotPanel = <function> defined @Interface\AddOns\AdiBags\widgets\BagSlots.lua:437
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:137
 ToggleAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:86
 OnProfileChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:184
 GetName = <function> defined @Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 name = "AdiBags"
 OpenBackpack = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:168
 LayoutBags = <function> defined @Interface\AddOns\AdiBags\core\Layout.lua:101
 Disable = <function> defined @Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
 SetGlobalLock = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:402
 Unhook = <function> defined @Interface\AddOns\Accountant_Classic\Libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @Interface\AddOns\Questie\Libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OpenAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:109
 L = <table> {
 }
 safecall = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:81
 Debug = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:61
 CreateAnchorWidget = <function> defined @Interface\AddOns\AdiBags\widgets\AnchorWidget.lua:37
 ITEM_SIZE = 37
 DEFAULT_SETTINGS = <table> {
 }
 CreateBagAnchorWidget = <function> defined @Interface\AddOns\AdiBags\widgets\AnchorWidget.lua:218
 FAMILY_ICONS = <table> {
 }
 UnregisterEvent = <function> defined @Interface\AddOns\!KalielsTracker\Libs\Cal

**Comment by Talyrius** [comment]
See #416 & #422; fixed via ae53167.
