### ISSUE TITLE
Unable to filter out mythic keystone

### ISSUE THREAD

**Issue by dpyy** [AdiAddons/AdiBags#452]
I want to put mythic keystone into its own section called Key. Right now it falls into Reagent. 

I was able to setup manual filtering for any other item, but for some reason the mythic keystone is not matched in the manual filtering. It stays as Reagent.

**Comment by Mythos** [comment]
Hey there,

there is already a plugin for that in case you don't know: https://www.curseforge.com/wow/addons/adibags_keystone
It's a very simple addon which you edit if needed. (mainly renaming the category)
