### ISSUE TITLE
BAGS WILL NOT OPEN

### ISSUE THREAD

**Issue by Deanov1234** [AdiAddons/AdiBags#453]
My bags will not open i have read about this issue alot and people have said there is a fix for this, those people are wrong. Fix your dog shit addon please or dont make them at all.

**Comment by Talyrius** [comment]
There's two separate releases for Retail and Classic. Whether through fault of your own or the Twitch app, you're attempting to use the wrong version for your game client.

**Comment by Deanov1234** [comment]
that is incorrect i have already re installed this shit many times from
curse in which there are 2 files for download one for classic and one for
retail i 100% for sure install the retail version.

**Comment by Deanov1234** [comment]
THIS SHIT NO COLSED FUCK BOY FIX YOUR SHIT IM NOT GOING AWAY
