### ISSUE TITLE
DO NOT INSTALL THIS TRASH SHIT

### ISSUE THREAD

**Issue by Deanov1234** [AdiAddons/AdiBags#455]
TRASH AS FUCK ADDON NO WORTH THEN HAIR OFF THE NECKBEARD CUCK THAT WROTE IT. 100% DELETE THIS SHIT IF YOU HAVE IT, PRETTY SURE THEY ARE USEING YOUR COMPUTER AS A RUSSIAN BOT TO SPREAD PROPAGANDA IF YOU DO!!!! FUCK THESE CUCKS BOY DONT BE A SHEEP!!!!!!!!!!!!!!!!!!!

**Comment by Cidan** [comment]
Hey there!

I used to help maintain this addon, though my job largely prevents me from contributing (though this lock down might change things soon...).

Anyway, I'm really sorry that you're having a hard time with this. Would you like to spend some time working on this 1:1 and figure this out? If so, feel free to e-mail me directly at my work address, lobato@google.com. I'd really like to help you here and figure out why this is so rough.

Let me know, and thanks! :)
