### ISSUE TITLE
BUG / Feature Request: Pawn Icons not displaying on items in bag  

### ISSUE THREAD

**Issue by clmcgrath** [AdiAddons/AdiBags#464]
Pawn normally  displays a green arrow on items in your bag that are upgrades 
when using adibags this functionality does not work 

not sure if this should be opened here or on the pawn issue tracker

**Comment by RamyRafik** [comment]
Not sure if this applies to you as well but ...
I thought I have the same issue, then realized the arrow does appear, but behind the ilvl
![image](https://user-images.githubusercontent.com/20221435/87487185-d6d07f80-c5f1-11ea-9f75-0428dd50a161.png)

I couldn't find a way to customize ilvl anchor point for AdiBags

**Comment by clmcgrath** [comment]
oh you know what i am seeing that now , so if we could move the arrow that would be ideal

**Comment by bolerro** [comment]
Pawn would need to update to move the arrow. But if we could get the option to have the iLvl moveable in Adibags, that would be preferred. I would like to have the iLvl number on the right.

**Comment by Alyred** [comment]
iLevel is movable manually in the code:
Line 106 AdiBags\modules\ItemLevel.lua:
Change "TOPLEFT" to "TOPRIGHT","BOTTOMLEFT", or "BOTTOMRIGHT" at your preference.
There used to be a pull request that put a much better format and controls in the configuration menu. It never did get merged in.

**Comment by Talyrius** [comment]
See #303.
