### ISSUE TITLE
Trinket not showing up in bag

### ISSUE THREAD

**Issue by retboi** [AdiAddons/AdiBags#465]
Vita-Charged Titanshard does not show up in bags at all.
![adibag](https://user-images.githubusercontent.com/68204997/87257641-76a2d780-c451-11ea-859c-ab15d5e7731f.jpg)

**Comment by Talyrius** [comment]
Because it's equipped, no? Or, perhaps it's saved to an equipment set or custom section with its visibility (V button, top right) toggled off?
