### ISSUE TITLE
Auto Sort does not toggle on right click

### ISSUE THREAD

**Issue by Lynxvarn** [AdiAddons/AdiBags#468]
Auto Sort does not toggle when right clicking the S.

Currently, both left and right click auto sorts your inventory.

There is also no option to disable auto sort in the Item options. The drop down menu only contains more options for item sorting.

Is there another way to disable auto sort?

**Comment by Talyrius** [comment]
**AdiBag's Feature List:**
> - _Smart item sorting inside each section._
> - _Bag sorting: click on the [S] button._

You're referring to two separate types of sorting here, they aren't one and the same. The bag sorting ([S] button) is only ever user initiated, it's not automatic, and the smart item sorting is the main feature of AdiBags, it can't be disabled.

**Comment by Lynxvarn** [comment]
Thank you for the clarification!

Interesting, I assumed that being able to turn off auto sort within specific sections would be a desired function of the addon.

Just so I fully understand this and don't keep bugging you dudes.
Is there a way to lock the position/order of items inside of a section? I'm loving the addon so far, but would like to make some of the sections retain the order that I put the items in.

**Comment by Talyrius** [comment]
No, sorry. This is the only sorting option:

> _**Sorting order**_
> _Select how items should be sorted within each section._
>    _1. By category, subcategory, quality and item level (default)_
>    _2. By name_
>    _3. By quality and item level_

**Comment by Lynxvarn** [comment]
Guess I'll learn to live with it xD

Thanks again for the insight.
