### ISSUE TITLE
Can't find keyring

### ISSUE THREAD

**Issue by NuclearBlast** [AdiAddons/AdiBags#469]
Can't find keying in bag interface or option.

**Comment by navara** [comment]
Confirming the issue in current classic WoW version.

When I use following macro, keyring pops-up:
`/script ToggleBag(KEYRING_CONTAINER)`

**Comment by SpareSimian** [comment]
The keyring is to the left of the bag icons in the standard interface. I don't recall AdiBags interacting with it in any way. Note that a lot of keys that would go in the keyring in Vanilla don't go into Classic's bag. I consider this a Blizzard bug. 

![WoW-keyring-location](https://user-images.githubusercontent.com/1709928/92837798-dd316c80-f392-11ea-8937-96f5fd8ee10d.png)

**Comment by mastersuleman** [comment]
Has this been fixed yet?

**Comment by EvelynSays** [comment]
This seems to be marked as fixed, but I cannot see my keyring in wotlk classic.

**Comment by Talyrius** [comment]
See #691.
