### ISSUE TITLE
GUI going off screen

### ISSUE THREAD

**Issue by RainbowMagicMarker** [AdiAddons/AdiBags#47]
When switching between my Bank and my Reagent Bank I cannot keep both windows on the screen, when I have it set so that I can see the Reagent bank, my regular Bank extends off the left side of the screen, and when I have it set so that I can see my regular Bank, my Reagent Bank extends off the top of the screen. 

Messing with the Maximum Bag Height setting does not seem to fix either of these issues.

For some reason I can't upload screenshots or I would provide screenshots of my settings.

**Comment by Cidan** [comment]
This is fixed in an upcoming release.
