### ISSUE TITLE
Twitch keeps installing a borked version

### ISSUE THREAD

**Issue by fireboy92k** [AdiAddons/AdiBags#473]
Every time I open Twitch to upgrade plugins, it 'refreshes' AdiBags and breaks it.  Manually copying over and refreshing the UI from the zip file corrects it.  But it's annoying.  Don't know if the file that's uploaded is broken or if it's pointing to the wrong version or what.  I can't seem to locate where Twitch downloads the plugin's before it installs them to compare a before and after.  Any thoughts?

**Comment by Talyrius** [comment]
Unfortunately, we have no control over the Twitch app and reports of its buggy behavior have always fallen on deaf ears. Overwolf purchased Curse from Twitch, so it's being end-of-life'd in favor of their own app. Perhaps you can try [WowUp](https://wowup.io/) in the meantime?
