### ISSUE TITLE
Request: Option not to sort items

### ISSUE THREAD

**Issue by Oettinger77** [AdiAddons/AdiBags#474]
Hello,

your addon looks very nice and the one click movement is a killer.
But can you please please add an option for **not** sorting items automatically? I still want to control my bag slots by myself.
Hope i'm not alone with that :)

And an option to deactivate recent items completely would be nice too, but this is a minor issue (for me personal).

Regards

**Comment by SpareSimian** [comment]
What would it do, instead? The sorting is done when the bag is opened or when items are added and removed. I guess you'd need to disable that and add a button for manual sorting. But adding items is going to expand the bag, so you'd still need to do it then to get a usable layout.

**Comment by SpareSimian** [comment]
What's the use case? _Why_ do you want to disable automatic sorting?

**Comment by Oettinger77** [comment]
> What would it do, instead? 

Welll just: nothing :)
So that i can reorder my items (in a category) just like in a normal bag.


Regards

**Comment by SpareSimian** [comment]
What would your sorting rule be? Maybe it's useful to others.

**Comment by Oettinger77** [comment]
Sorting rule would be "none", like Arkinventory has it.
New items would drop at the end of the category. And because there is no sorting rule i can rearrange them.

In Classic the bag space isn't huge. I deactivated most of the categories (left ony quest) and created my own.
E.g. on my main "Basic" with hearthstone, mount, bandages and so on. Stuff i always carry with me. Then "raid"(with arcane powder...), "AQ" (nr gear and stuff) and just a few others. Stuff i switch from bank to bag before raiding or farming.

Lets say i always want hearthstone to be in the first slot of the category basic, without sorting i can do this :)

Don't if this makes sense to others, but it was the first thing that came to my mind when using Adibags (which is only a few days now).


Regards

**Comment by cgsub** [comment]
That would also present the interest of preventing Adibag from changing what is under my curser every single time that I combine some items into a bigger one... e.g: Crystallized fire into Eternal Fire or whatever... Causing me to unexpectedly right click some random item when trying to combine the second one...

**Comment by Talyrius** [comment]
Section reordering is in the works. See [#675](https://github.com/AdiAddons/AdiBags/issues/675).
