### ISSUE TITLE
[Question] How are categories sorted?

### ISSUE THREAD

**Issue by Oettinger77** [AdiAddons/AdiBags#478]
Hello,

just a little question. How are the categories in the bag/bank sorted? Not the items under it, the categories itself. 
And is there a way ro rearrange them?

Regards

**Comment by Talyrius** [comment]
The sections are arranged by size and the `compactLayout` option does so more aggressively. No, you can't rearrange them.

See the code within the "[Full Layout](https://github.com/AdiAddons/AdiBags/blob/83c298df3ce8eacc500331cbf14cb6c5e63aab42/widgets/ContainerFrame.lua#L877)" section of `AdiBags/widgets/ContainerFrame.lua` for further details.
