### ISSUE TITLE
[Retail] Overlapping Manual Filters with too many Items per Group

### ISSUE THREAD

**Issue by Leylaa2** [AdiAddons/AdiBags#479]
Hey Guys,
having problems, because i have too many items in my filters.
Is there any way to fix this? or is this a Addon Problem?

Filters Groups are Overlapping and i cant change em anymore.
It is a Big Mess, and i dont know if i am the only one with this Problem... (checked a lot of issues, didnt find this one)

Like your Addon!
Best Regards

![WoWScrnShot_091520_165828](https://user-images.githubusercontent.com/42302732/93227820-1728b700-f775-11ea-8b20-45fcb21aa49d.jpg)
![WoWScrnShot_091520_165825](https://user-images.githubusercontent.com/42302732/93227829-1abc3e00-f775-11ea-8409-0d7c43e11041.jpg)

**Comment by SpareSimian** [comment]
This might be related to the glitch with icons showing as green squares. Try stretching the config window to force a redraw. It doesn't completely fix the other problem but it makes the empty slot at the end visible for adding new items.

**Comment by WareditorGit** [comment]
It would be nice to have this fixed so handling large groups would become more pleasant.

**Comment by Talyrius** [comment]
See #278.
