### ISSUE TITLE
Settings don't save all the time

### ISSUE THREAD

**Issue by jana8878** [AdiAddons/AdiBags#480]
I will have created my settings for the addon. I have my bags open so I can see how its changing. Save it. Play a bit. Go to a vendor and none of the settings are implemented. Go back to addon. Addon shows correctly what I chose but it doesn't show. I have tried resetting over and over and still keep getting the same issue.

**Comment by SpareSimian** [comment]
Post a screenshot of your settings and a screenshot of the bags that aren't obeying them. What setting isn't sticking?
