### ISSUE TITLE
receiving technical chat messages

### ISSUE THREAD

**Issue by jazzard** [AdiAddons/AdiBags#481]
Hello! I'm having a weird problem. Every time I open anything, that can have loot (bank, bags, boxes, etc), I receive message, that duplicates 2-3 times:
`isPet: false, isMount: false, isToy: false, isRecipe: false`

**Comment by Talyrius** [comment]
A different addon is responsible for outputting these debug messages. To narrow down which one, disable other addons you've updated since it began happening, individually or in batches, until looting no longer triggers it.

**Comment by jazzard** [comment]
Found it, It's "Caerdon Wardrobe". Sorry for mistake ;)
