### ISSUE TITLE
Request: Option to stack currencies.

### ISSUE THREAD

**Issue by Zxkarie** [AdiAddons/AdiBags#482]
This might seem like a silly request but if you have multiple currencies it causes the bag UI to shape long across the bottom of the screen, This causes a lot of empty space.. and for what? maybe an option to have a user chosen amount of currencies per line. The gold, silver, copper currency can sit on top of it all. It might look a little congested if you have all the currencies shown, but it would use less space, as the UI would scale upwards a couple dozen pixels, and it would be a little more easy on the eye.

**Comment by LiamGBR** [comment]
Was going to suggest this aswell, would be nice to have a vertical currency option to keep the frame from becoming to wide as it means I have to keep changing the column width of my bank or it goes off screen.

**Comment by Cidan** [comment]
I've completely overhauled and rewrote the currency rendering engine in a branch:

* There is now a configuration option to limit the number of columns in currencies
* Currencies now show tooltips when hovering over each individual tooltip

This required a total rewrite to get working, but it's much better and more flexible as a result.

![image](https://user-images.githubusercontent.com/1133628/186528886-f0837bac-3e46-4141-a254-ded8975fcb67.png)

**Comment by Cidan** [comment]
Note: This will be merged and released in the next release, likely for WotLK launch.

**Comment by Cidan** [comment]
This has been fixed, pushed to master, and released as v1.9.30.
