### ISSUE TITLE
Item tooltip flashing on load

### ISSUE THREAD

**Issue by Runisco** [AdiAddons/AdiBags#485]
Whenever I do a reload, or a load is triggered, when mousing over an item in the bags, the item tooltips begin to flash.

Both wow and addon is updated.
Adibags is the only addon enabled.

video of the issue: https://www.youtube.com/watch?v=1P0rt9XCRDI

**Comment by Talyrius** [comment]
I can't reproduce this. The item compare tooltip should only appear if you're holding down the `Shift` key.
