### ISSUE TITLE
Adibags does not work at all in 9.0.1 (36230) (buggrabber+bugsack output linked)

### ISSUE THREAD

**Issue by Kream** [AdiAddons/AdiBags#487]
Hello. Logged into WoW with only Adibags, Buggrabber and Bugsack enabled. Got the following errors: 

Adibags Errors

**Error 1**
```
1x AdiBags\widgets\AnchorWidget.lua:65: attempt to call method 'SetBackdrop' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags\core\OO.lua"]:60: in function <AdiBags\core\OO.lua:52>
[string "=(tail call)"]: ?
[string "@AdiBags\core\Layout.lua"]:34: in function `CreateBagAnchor'
[string "@AdiBags\core\Core.lua"]:98: in function <AdiBags\core\Core.lua:81>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
```

**Error 2**
```
1x AdiBags\core\Layout.lua:37: attempt to call method 'SetBackdrop' (a nil value)
[string "@AdiBags\core\Layout.lua"]:37: in function `CreateBagAnchor'
[string "@AdiBags\core\Core.lua"]:98: in function <AdiBags\core\Core.lua:81>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
```

**Error 3**
```
1x AdiBags\core\Layout.lua:126: attempt to index field 'anchor' (a nil value)
[string "@AdiBags\core\Layout.lua"]:126: in function `UpdatePositionMode'
[string "@AdiBags\core\Core.lua"]:172: in function <AdiBags\core\Core.lua:115>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
```

**Error 4**
```
1x AdiBags\widgets\BagSlots.lua:417: attempt to call method 'SetBackdrop' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags\core\OO.lua"]:60: in function <AdiBags\core\OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@AdiBags\core\Bags.lua"]:129: in function `GetFrame'
[string "@AdiBags\core\Bags.lua"]:83: in function `Open'
[string "@AdiBags\core\Bags.lua"]:119: in function <AdiBags\core\Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@FrameXML\MainMenuBarBagButtons.lua"]:40: in function `BackpackButton_OnClick'
[string "@FrameXML\MainMenuBarBagButtons.lua"]:161: in function <FrameXML\MainMenuBarBagButtons.lua:156>
[string "=[C]"]: ?

```
**Error 5**
```
1x AdiBags\core\Bags.lua:130: attempt to index field 'CloseButton' (a nil value)
[string "@AdiBags\core\Bags.lua"]:130: in function `GetFrame'
[string "@AdiBags\core\Bags.lua"]:83: in function `Open'
[string "@AdiBags\core\Bags.lua"]:119: in function <AdiBags\core\Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@FrameXML\MainMenuBarBagButtons.lua"]:40: in function `BackpackButton_OnClick'
[string "@FrameXML\MainMenuBarBagButtons.lua"]:161: in function <FrameXML\MainMenuBarBagButtons.lua:156>
[string "=[C]"]: ?

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 isBank = false
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:336
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:395
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 name = "AdiBags_Backpack"
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 bagIds = <table> {
 }
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 frame = AdiBagsContainer1 {
 }
 baseName = "AdiBags"
 Sort = <function> defined @AdiBags\core\Bags.lua:217
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 AdiBags_InteractingWindowChanged = <function> defined @AdiBags\core\Bags.lua:204
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 IsHooked = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:493
 order = 10
 bagName = "Backpack"
 IsModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:217
 hooks = <table> {
 }
 SetDefaultModuleState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 SendMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 UnhookAll = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:477
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 Unhook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:418
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SecureHookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:410
 HookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:366
 defaultModuleState = true
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:437
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 RawHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:313
 PostEnable = <function> defined @AdiBags\core\Bags.lua:200
 moduleName = "Backpack"
 UnregisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Backpack"
(*temporary) = false
(*temporary) = "attempt to index field 'CloseButton' (a nil value)"
addon = <table> {
 AcquireItemButton = <function> defined @AdiBags\widgets\ItemButton.lua:155
 modules = <table> {
 }
 UpdateFilters = <function> defined @AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @AdiBags\core\Core.lua:4
```

**Comment by Barthezzcz** [comment]
...they had like only half a year to prepare it for the prepatch, so no rush guyz...

**Comment by Runisco** [comment]
> 
> 
> ...they had like only half a year to prepare it for the prepatch, so no rush guyz...

If they had access to beta. Chill out.

**Comment by jomo666** [comment]
Barthezzcz - github is an collaborative software development platform and not an flaming platform. YOU CAN HELP with the development too, especially when do you think that it is going slowly.

**Comment by NelsonMinar** [comment]
It looks like @Talyrius has done most of the recent development. Thanks for your work! Do you have any time to fix up AdiBags for 9.0? Or do you need some help?

**Comment by tehbob** [comment]
I went though the beta branch changes and made the changes to my local copy.  Once its updated for real, for sure (or those changes are merged) , use that one.  https://bit.ly/3lLK4zL

**Comment by Voraga** [comment]
Grabbed that file from @tehbob but now I'm getting this error:

`Message: ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:3: attempt to index global 'LibStub' (a nil value)
Time: Wed Oct 14 10:41:32 2020
Count: 1
Stack: ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:3: attempt to index global 'LibStub' (a nil value)
[string "@Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:3: in main chunk

Locals: MAJOR = "CallbackHandler-1.0"
MINOR = 7
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'LibStub' (a nil value)"
`

Any help is greatly appreciated.

**Comment by Nercus** [comment]
> Grabbed that file from @tehbob but now I'm getting this error:
> 
> `
> Message: ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:3: attempt to index global 'LibStub' (a nil value)
> Time: Wed Oct 14 10:41:32 2020
> Count: 1
> Stack: ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:3: attempt to index global 'LibStub' (a nil value)
> [string "@interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:3: in main chunk
> '
> It appears the file Libstub.lua was missing. I copyed the one from details shadowlands into the folder: \World of Warcraft_retail_\Interface\AddOns\AdiBags\libs\LibStub and it works great! thanks a million!

That means LibStub is missing and it actually does miss in the folder. If you go to Adibags -> libs just replace the LibStub with that version https://www.wowace.com/projects/libstub.

**Comment by Roetetoet** [comment]
still gives huge errors even with those adjusted files. Bugsack does not like it. 

10x AdiBags\modules\ItemLevel.lua:343: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: ?
[string "@AdiBags\modules\ItemLevel.lua"]:343: in function `?'
[string "@AdiBags\modules\ItemLevel.lua"]:141: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\widgets\ItemButton.lua"]:316: in function `Update'
[string "@AdiBags\widgets\ItemButton.lua"]:287: in function `FullUpdate'
[string "@AdiBags\widgets\ItemButton.lua"]:252: in function <AdiBags\widgets\ItemButton.lua:240>
[string "=[C]"]: in function `Show'
[string "@AdiBags\widgets\ContainerFrame.lua"]:953: in function `PrepareSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1059: in function `FullUpdate'
[string "@AdiBags\widgets\ContainerFrame.lua"]:564: in function <AdiBags\widgets\ContainerFrame.lua:550>
[string "=[C]"]: ?
[string "@AdiBags\core\Utility.lua"]:89: in function <AdiBags\core\Utility.lua:81>
[string "@AdiBags\widgets\LayeredRegion.lua"]:119: in function <AdiBags\widgets\LayeredRegion.lua:108>

**Comment by paultreny** [comment]
Thanks to @tehbob for all the hard work

I added in LibStub and also fixed that item level coloring issue with a new range for pre-patch (level 50 cap)

When SL comes out and the cap goes back up to 60 the coloring will break but should be good til then.

https://share.getcloudapp.com/bLuwgwBz

**Comment by paultreny** [comment]
Looks like there's a pull request with similar changes, we may be duplicating efforts here, but hey, it works!
https://github.com/AdiAddons/AdiBags/pull/477

**Comment by Roetetoet** [comment]
> 
> 
> Thanks to @tehbob for all the hard work
> 
> I added in LibStub and also fixed that item level coloring issue with a new range for pre-patch (level 50 cap)
> 
> When SL comes out and the cap goes back up to 60 the coloring will break but should be good til then.
> 
> https://share.getcloudapp.com/bLuwgwBz

thank you!

**Comment by BourgeoisM** [comment]
Nice work @tehbob  Almost like you copy paste my work and removed the comments .....
same names etc  ...

**Comment by tehbob** [comment]
> 
> 
> Nice work @tehbob Almost like you copy paste my work and removed the comments .....
> same names etc ...

Yes, that's what I said I did.  Until your changes get merged, this was a quick a dirty fix to get it working again.  Nothing more.  I take no credit for any of the work.  I'm sorry if that wasn't apparent.

**Comment by BourgeoisM** [comment]
Sorry, i misinterpretted you're comment since some came to my pull request and said you fixed the things .......

why did you remove the comments though?
Should i remove them from my branch aswell????
I think it can help people that are willing to enhance the things

**Comment by tehbob** [comment]
Why didn't I copy the comments?  It was just a quick and dirty to get the addon into some sort of working state until your PR got approved and the official addon was updated.

Should you remove them in your PR?  No, on the official release those comments could help someone debug something later.  

Once again, what I did was just to get Adibags working while your PR is waiting to be merged...or until the original developer gets everything updated.

**Comment by gitsocko** [comment]
Thanks to everyone who fixed this addon enough to be usable.  Such an important one to me as well -- your efforts are much appreciated!

**Comment by BourgeoisM** [comment]
> Thanks to @tehbob for all the hard work
> 
> I added in LibStub and also fixed that item level coloring issue with a new range for pre-patch (level 50 cap)
> 
> When SL comes out and the cap goes back up to 60 the coloring will break but should be good til then.
> 
> https://share.getcloudapp.com/bLuwgwBz

actually i didn't include a complete zip/extract for you, but thanks to tehbob you can have a complete folder libs included.
As for the item level i as working on it but on the beta i didn't recreate an alt from level 0 nor an high item level 60 character so i couldn't adjust the range for the colorings.
I could not log on tonight after work since there was a huge queue in EU.
I have alt wihin all levels so i'll see tomorrow evening if i can tweak the item level range.
I don't remember having errors on itemlevel.lua on beta though.
The only changes i have stashed on itemlevel.lua are that i did change ranges [60-120] to [0-60] and the item level range "{ xxx,xxx}" according to item i saw.

**Comment by t-mart** [comment]
I'm not sure if this is counter-productive, but I had been working on bring this up to date on my fork: https://github.com/t-mart/AdiBags

I apologize if this is duplicated work. But nonetheless, I think we need to get this code on github instead of cloud downloads.

I tested it with the current prepatch state of the game and it works.

Diff: https://github.com/t-mart/AdiBags/commit/4be3fd2fdf7b10d47bf59397941d477f4e0f585c

Release zip: https://github.com/t-mart/AdiBags/releases/tag/AdiBags-v1.9.20-1-g4be3fd2

Notable fixes:
- Bumped TOC version to 90001
- Used the newly-required frame template parent `"BackdropTemplate"` in various places when `CreateFrame` is called to support backdrop changes. This uses the method described at https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes
- Used the new currency API functions, documented at https://www.townlong-yak.com/framexml/beta/Blizzard_APIDocumentation#C_CurrencyInfo.GetCurrencyListInfo. 
  - Before, AdiBags had a currency iterator function that I felt did more harm than good with its complexity. I removed it and just iterated over the currencies manually with a for-loop.
- I removed the item `MAX_PLAYER_LEVEL` coloring logic in favor of the simpler item-difference logic further down in the original code. The former logic seemed to rely on knowing the max item level for an expac, and I don't think we can know that at this point. 
- Fixed up some changed constant variable names for item quality. See https://wow.gamepedia.com/Enum.ItemQuality

**Comment by kp9928** [comment]
OMG I love you guys who fixed Adibags! Everyone of you!!! God forbid I have to use bagn...... :P

**Comment by Accalon** [comment]
Thank you sooooo much, it's hard for me to function at this point without this addon.  Hopefully at some point I can learn enough to help.

**Comment by Walkerbo** [comment]
> The first error can be fixed by modifying line 63 in AnchorWidget.lua to the following
> `local corner = CreateFrame("Frame", nil, self, "BackdropTemplate")`
> 
> Also, the following link might help:
> https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes

This change caught more than a few addon authors on the hop, myself included.

**Comment by Kream** [comment]
> I'm not sure if this is counter-productive, but I had been working on bringing this up to date on my fork: https://github.com/t-mart/AdiBags
> 
> I apologize if this is duplicated work. But nonetheless, I think we need to get this code on github instead of cloud downloads.
> 
> I tested it with the current prepatch state of the game and it works.
> 
> Diff: [t-mart@4be3fd2](https://github.com/t-mart/AdiBags/commit/4be3fd2fdf7b10d47bf59397941d477f4e0f585c)
> 
> **Release zip: https://github.com/t-mart/AdiBags/releases/tag/AdiBags-v1.9.20-1-g4be3fd2 (in other words, if you're not interested in code, the ZIP containing the addon for your Interface/Addons folder)**
> 
> Notable fixes:
> 
> * Bumped TOC version to 90001
> * Used the newly-required frame template parent `"BackdropTemplate"` in various places when `CreateFrame` is called to support backdrop changes. This uses the method described at https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes
> * Used the new currency API functions, documented at https://www.townlong-yak.com/framexml/beta/Blizzard_APIDocumentation#C_CurrencyInfo.GetCurrencyListInfo.
>   
>   * Before, AdiBags had a currency iterator function that I felt did more harm than good with its complexity. I removed it and just iterated over the currencies manually with a for-loop.
> * I removed the item `MAX_PLAYER_LEVEL` coloring logic in favor of the simpler item-difference logic further down in the original code. The former logic seemed to rely on knowing the max item level for an expac, and I don't think we can know that at this point.
> * Fixed up some changed constant variable names for item quality. See https://wow.gamepedia.com/Enum.ItemQuality
> 
> BTW, I had to do some research on how to cut releases of this project into actual addon folders you can drop into your Interface folder. I pretty much just followed the instructions from https://github.com/BigWigsMods/packager#using-releasesh-to-build-locally and ran the script with `.release/./release.sh -d -m .pkgmeta -t .` (on a Linux machine with the required dependencies).

Can confirm works

**Comment by joao44289** [comment]
> EDIT: I'm going to keep this comment updated with the latest version of my fork (as long as I can stand it 😅).
> 
> I'm not sure if this is counter-productive, but I had been working on bringing this up to date on my fork: https://github.com/t-mart/AdiBags
> 
> I apologize if this is duplicated work. But nonetheless, I think we need to get this code on github instead of cloud downloads.
> 
> I tested it with the current prepatch state of the game and it works.
> 
> Diff between this project and my fork: [master...t-mart:master](https://github.com/AdiAddons/AdiBags/compare/master...t-mart:master)
> 
> **Latest release zip: https://github.com/t-mart/AdiBags/releases/tag/v1.9.20-1-gcf77aa0 (in other words, if you're not interested in code, the ZIP containing the addon for your Interface/Addons folder)**
> 
> Notable fixes:
> 
> * Bumped TOC version to 90001
> * Used the newly-required frame template parent `"BackdropTemplate"` in various places when `CreateFrame` is called to support backdrop changes. This uses the method described at https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes
> * Used the new currency API functions, documented at https://www.townlong-yak.com/framexml/beta/Blizzard_APIDocumentation#C_CurrencyInfo.GetCurrencyListInfo.
>   
>   * Before, AdiBags had a currency iterator function that I felt did more harm than good with its complexity. I removed it and just iterated over the currencies manually with a for-loop.
> * I removed the item `MAX_PLAYER_LEVEL` coloring logic in favor of the simpler item-difference logic further down in the original code. The former logic seemed to rely on knowing the max item level for an expac, and I don't think we can know that at this point.
> * Fixed up some changed constant variable names for item quality. See https://wow.gamepedia.com/Enum.ItemQuality
> 
> BTW, I had to do some research on how to cut releases of this project into actual addon folders you can drop into your Interface folder. I pretty much just followed the instructions from https://github.com/BigWigsMods/packager#using-releasesh-to-build-locally and ran the script with `.release/./release.sh -d -m .pkgmeta -t .` (on a Linux machine with the required dependencies).

You're doing god's work. If the addon itself isn't updated any time soon you should upload it on curseforge under a new name.

**Comment by layday** [comment]
@t-mart Thanks for this. Would it be possible to cut a regular release on GH? Not a pre-release, so I can keep it updated with my add-on manager.

**Comment by Oglaf** [comment]
@t-mart I just want to say tyvm!

**Comment by NelsonMinar** [comment]
@t-mart just to clarify; your fork is _only_ 9.0 fixes so far right?  Not other changes?

No replies yet from any of the folks in this project who've been doing maintenance. Last commits were in June though, which isn't that long ago. I guess we'll find out in a few days whether anyone's around to make an official release. Starting with a pull of the work folks have done here would be a pretty good head start.

**Comment by Greeng0** [comment]
The addon isn't working for me in classic either. Not sure if the fixes you guys are talking about apply to both or if you'll need more time for a classic fix, just FYI.

**Comment by Malkom** [comment]
Thx for the update guys !!

BTW, I have an error : 

`30x AdiBags\modules\Junk.lua:105: attempt to compare number with nil
[string "=(tail call)"]: ?
[string "@AdiBags\core\Filters-Filtres.lua"]:146: in function `Filter'
[string "@AdiBags\widgets\ContainerFrame.lua"]:717: in function `FilterSlot'
[string "@AdiBags\widgets\ContainerFrame.lua"]:751: in function `DispatchItem'
[string "@AdiBags\widgets\ContainerFrame.lua"]:912: in function `RedispatchAllItems'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1055: in function `FullUpdate'
[string "@AdiBags\widgets\ContainerFrame.lua"]:564: in function <AdiBags\widgets\ContainerFrame.lua:550>
[string "=[C]"]: ?
[string "@AdiBags\core\Utility.lua"]:89: in function <AdiBags\core\Utility.lua:81>
[string "@AdiBags\widgets\LayeredRegion.lua"]:119: in function <AdiBags\widgets\LayeredRegion.lua:108>`

**Comment by Leichenengel** [comment]
> 
> 
> > I'm not sure if this is counter-productive, but I had been working on bringing this up to date on my fork: https://github.com/t-mart/AdiBags
> > I apologize if this is duplicated work. But nonetheless, I think we need to get this code on github instead of cloud downloads.
> > I tested it with the current prepatch state of the game and it works.
> > Diff: [t-mart@4be3fd2](https://github.com/t-mart/AdiBags/commit/4be3fd2fdf7b10d47bf59397941d477f4e0f585c)
> > **Release zip: https://github.com/t-mart/AdiBags/releases/tag/AdiBags-v1.9.20-1-g4be3fd2 (in other words, if you're not interested in code, the ZIP containing the addon for your Interface/Addons folder)**
> > Notable fixes:
> > 
> > * Bumped TOC version to 90001
> > * Used the newly-required frame template parent `"BackdropTemplate"` in various places when `CreateFrame` is called to support backdrop changes. This uses the method described at https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes
> > * Used the new currency API functions, documented at https://www.townlong-yak.com/framexml/beta/Blizzard_APIDocumentation#C_CurrencyInfo.GetCurrencyListInfo.
> >   
> >   * Before, AdiBags had a currency iterator function that I felt did more harm than good with its complexity. I removed it and just iterated over the currencies manually with a for-loop.
> > * I removed the item `MAX_PLAYER_LEVEL` coloring logic in favor of the simpler item-difference logic further down in the original code. The former logic seemed to rely on knowing the max item level for an expac, and I don't think we can know that at this point.
> > * Fixed up some changed constant variable names for item quality. See https://wow.gamepedia.com/Enum.ItemQuality
> > 
> > BTW, I had to do some research on how to cut releases of this project into actual addon folders you can drop into your Interface folder. I pretty much just followed the instructions from https://github.com/BigWigsMods/packager#using-releasesh-to-build-locally and ran the script with `.release/./release.sh -d -m .pkgmeta -t .` (on a Linux machine with the required dependencies).
> 
> Can confirm works

Just wanted to let you know, that this fix does NOT work for me. Unfortunately. I don't have that buggrabber and bugsack thingy installed so I can't tell you why it isn't working. It just isn't. Thank you though for putting effort into this. It's good to see there are people who care and who try.

**Comment by t-mart** [comment]
> @t-mart just to clarify; your fork is _only_ 9.0 fixes so far right? Not other changes?

Correct.

**Comment by vonduck** [comment]
nice to see you guys are getting along but when will there be a stable version uploaded to twitch?

**Comment by Leichenengel** [comment]
> 
> 
> Thanks to @BourgeoisM and @tehbob for all the hard work
> 
> I added in LibStub and also fixed that item level coloring issue with a new range for pre-patch (level 50 cap)
> 
> When SL comes out and the cap goes back up to 60 the coloring will break but should be good til then.
> 
> https://share.getcloudapp.com/bLuwgwBz

Thank you for your efforts but I sadly have to tell you, that this temp fix did not work for me - as did none of the others. I appreciate the attempt though. This Addon receives much more of these community effort than any other addon I use. Then again, I am just an end user. I have no idea of coding or scripting so maybe I did it wrong. I'm used to downloading a zip-file and putting it into the Addon folder of the game. In case there are other steps that need to be done beforehand they sort of got lost along the lines about what code was changed or what errors were fixed. I just now picked up a line talking about linux. So I now wonder, if this was a fix intended for linux users only? If so then I know why it doesn't work for me for I don't use linux ;D

**Comment by BourgeoisM** [comment]
> > Thanks to @BourgeoisM and @tehbob for all the hard work
> > I added in LibStub and also fixed that item level coloring issue with a new range for pre-patch (level 50 cap)
> > When SL comes out and the cap goes back up to 60 the coloring will break but should be good til then.
> > https://share.getcloudapp.com/bLuwgwBz
> 
> Thank you for your efforts but I sadly have to tell you, that this temp fix did not work for me - as did none of the others. I appreciate the attempt though. This Addon receives much more of these community effort than any other addon I use. Then again, I am just an end user. I have no idea of coding or scripting so maybe I did it wrong. I'm used to downloading a zip-file and putting it into the Addon folder of the game. In case there are other steps that need to be done beforehand they sort of got lost along the lines about what code was changed or what errors were fixed. I just now picked up a line talking about linux. So I now wonder, if this was a fix intended for linux users only? If so then I know why it doesn't work for me for I don't use linux ;D


have you tested without any other addons? which game do you play ? classic/retail ? i have not tested classic, and i think other didn't test either.
it's nothing related to linux, as the addons works with wow not with the operating system.
Without error bug report it's quite difficult to understand your error though.....

**Comment by Leichenengel** [comment]
> 
> 
> > > Thanks to @BourgeoisM and @tehbob for all the hard work
> > > I added in LibStub and also fixed that item level coloring issue with a new range for pre-patch (level 50 cap)
> > > When SL comes out and the cap goes back up to 60 the coloring will break but should be good til then.
> > > https://share.getcloudapp.com/bLuwgwBz
> > 
> > 
> > Thank you for your efforts but I sadly have to tell you, that this temp fix did not work for me - as did none of the others. I appreciate the attempt though. This Addon receives much more of these community effort than any other addon I use. Then again, I am just an end user. I have no idea of coding or scripting so maybe I did it wrong. I'm used to downloading a zip-file and putting it into the Addon folder of the game. In case there are other steps that need to be done beforehand they sort of got lost along the lines about what code was changed or what errors were fixed. I just now picked up a line talking about linux. So I now wonder, if this was a fix intended for linux users only? If so then I know why it doesn't work for me for I don't use linux ;D
> 
> have you tested without any other addons? which game do you play ? classic/retail ? i have not tested classic, and i think other didn't test either.
> it's nothing related to linux, as the addons works with wow not with the operating system.
> Without error bug report it's quite difficult to understand your error though.....

Apparently I have been an idiot the whole time. I installed the whole thingy wrong. Actually I have installed every addon I use wrong and what WOW showed me in my list were actually all old versions from pre 8.3. I sort of mixed up the Addons-Folder in retail with the AddOns-Folder in retail/Interface. *headdesks several times* plus I forgot to unzip them or better I unzipped them to the respective folder and forgot that blizz doesn't recognize addons when they are in subfolders with no files to access otherwise ^^; So you could say this was a classical PEBCAK :'D

I have now successfully installed the 3rd AdiBags-Tempfix by t-mart and it works like a charm - at least by now...

**So for everyone who just can't seem to get this thing (and others) running and also manually installs addons instead of using twitch:**

1. Unzip the ZIP-Files of your Addons telling your unzip-app "Unzip here" 

2. Make sure that in the unzipped folders are accessible files and that the folder does NOT contain another single subfolder

3. Move those unzipped Addon-folders to: `_World of Warcraft/_retail_/Interface/AddOns_`

4. Enjoy your Addons

**Comment by DarbiiRue** [comment]
To those of you who are unable to get the temporary fix to work on your game client, make sure you go into your WTF > SavedVariables folder, and delete the AdiBags entries. That fixed the issue for me where the fix wasn't working. Now I'm back to being able to use AdiBags until a stable update is put in.

**Comment by rabscutle** [comment]
> nice to see you guys are getting along but when will there be a stable version uploaded to twitch?

Does this add-on have an official owner anymore or is it going to be purely driven by users? Either way works, just wanting to know.

**Comment by Malkom** [comment]
Any chance to push the new version on Curse ?

**Comment by Malkom** [comment]
Any chance to push the new version on Curse ?

**Comment by ghudavj** [comment]
Thanks guys for fixing Adibags.

There are 2 things I am missing though:

- Elvui skin

- scrappable icon

**Comment by grimmtooth** [comment]
Kudos to everyone that put in the time to get this addon working again.
