### ISSUE TITLE
BUG: Missing Skin Options

### ISSUE THREAD

**Issue by DarbiiRue** [AdiAddons/AdiBags#490]
It looks like the settings for the skins has disappeared. The font can be changed, but there are no options to skin the addon to make it match the UI to your liking any longer.

**Comment by Talyrius** [comment]
Can you be more specific about what you're referring to? There has never been an option to skin AdiBags. Perhaps you were using another addon to skin it?

**Comment by DarbiiRue** [comment]
![image](https://user-images.githubusercontent.com/31390451/96285643-38b3d300-0fad-11eb-8237-5b84d2aa6eb6.png)

You've always been able to change the color of the back, the border, etc. and that is no longer available.

**Comment by Talyrius** [comment]
![image](https://user-images.githubusercontent.com/1068810/96286926-fb901680-0f95-11eb-8242-d2d745a39d18.png)
Those options are still available. Your libraries are probably out of date. AdiBags v1.9.21 is pending review at Curse and it should resolve your issue once it's approved.

**Comment by legowxelab2z8** [comment]
When opening the skins tab in the options I was getting an error 
Widgets\AceGUI-3.0-41-SharedMediaWidgets\prototypes.lua:119: attempt to call method 'SetBackdrop' (a nil value).   
and the bag background section was collapsed like in the image from @DarbiiRue

After downloading the curse version I no longer get the error and the bag background works.
