### ISSUE TITLE
AceAddon Libs Error

### ISSUE THREAD

**Issue by DarbiiRue** [AdiAddons/AdiBags#495]
`5x ...rfaceRarity\Libs\LibBars-1.0\LibBars-1.0-90024.lua:362: attempt to call method 'SetBackdrop' (a nil value)
[string "@Rarity\Libs\LibBars-1.0\LibBars-1.0-90024.lua"]:362: in function `NewBarGroup'
[string "@Rarity\Core\GUI.lua"]:129: in function `InitialiseBar'
[string "@Rarity\Core.lua"]:194: in function `DoEnable'
[string "@Rarity\Core.lua"]:165: in function <Rarity\Core.lua:164>
[string "=[C]"]: ?
[string "@AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:615>`

**Comment by Talyrius** [comment]
[Rarity](https://www.curseforge.com/wow/addons/rarity) is responsible for this error.
