### ISSUE TITLE
Move items between the bank and the reagent bank

### ISSUE THREAD

**Issue by jcastrov** [AdiAddons/AdiBags#500]
I was looking at how to display the bank and the reagent bank at the same, but in issue #374, someone explained it would take much space to show both at the same time. 

So, I have another question. Is there a shortcut to move objects between both banks? For instance, if you right-click on an object or a group title, you will move the items between your bags and your bank. However, I'm not sure if there is already a shortcut to move objects between both banks.

BTW, this addon is amazing ❤️

**Comment by Talyrius** [comment]
No, there's not. You'll have to move them from the bank to your bags and then into the reagent bank or click the button that deposits all reagents into the reagent bank.
