### ISSUE TITLE
Add support for PawnIsContainerItemAnUpgrade (IsContainerItemAnUpgrade depricated in Pawn 2.4.2)

### ISSUE THREAD

**Issue by Beet4** [AdiAddons/AdiBags#503]
From Pawn Changelog Version 2.4.2

> **Pawn's bag arrows integration will no longer work by default with custom bag addons.**
> The game no longer allows customizing that functionality while in combat, so before this change, Pawn's bag arrow integration caused errors while performing certain actions in combat, such as swapping weapons from the character sheet. Disabling support for custom bag addons is unfortunately the only way I can work around this.
> To work around this, custom bag addons that call IsContainerItemAnUpgrade directly can use PawnIsContainerItemAnUpgrade when available instead, falling back to IsContainerItemAnUpgrade if it's nil. Then Pawn will control the bag arrows like it did before.

**Comment by Zeffuro** [comment]
I second this, please implement this :)

**Comment by bolerro** [comment]
Yes, please implement this along with the iLvl text and being able to choose its corner location.

**Comment by andywy119** [comment]
modify function buttonProto:UpdateUpgradeIcon() at 360 line in ItemButton.lua file
change self.UpgradeIcon:SetShown( IsContainerItemAnUpgrade(self.bag, self.slot) or false)  to

if IsAddOnLoaded('Pawn') then itemIsUpgrade = _G.PawnIsContainerItemAnUpgrade(self.bag, self.slot) end
if itemIsUpgrade == nil then itemIsUpgrade = _G.IsContainerItemAnUpgrade(self.bag, self.slot) end
self.UpgradeIcon:SetShown( itemIsUpgrade or false)
