### ISSUE TITLE
Request: Icon Borders

### ISSUE THREAD

**Issue by Zwegert** [AdiAddons/AdiBags#506]
Hey , 
great work so far.

is it possible to change the borders of icons in the bags? Something like this:

Old:
![old](https://user-images.githubusercontent.com/55796429/97817005-eefc0580-1c99-11eb-84fd-2c1b85d7f0b8.JPG)

New:
![new](https://user-images.githubusercontent.com/55796429/97817010-f6231380-1c99-11eb-8c95-c047a5f9a56d.JPG)

**Comment by Talyrius** [comment]
With #467, perhaps? It needs testing and feedback.
