### ISSUE TITLE
[ Feature ] Static location for the catagories.

### ISSUE THREAD

**Issue by strickland** [AdiAddons/AdiBags#509]
This is the only thing that annoys me with adibags, is that everytime I open the bag, the location of the places for things is changed, example.... one time the Junk is up to far to the right, then the other time its most lower right spot, then after awhile, Newly received items might be at top left, or the next time it's bottom right.

Equipment can be in the middle to the left, then the next time its at top right spot, I mean, you know where I am getting...The human muscle can always get used to certain spots for things where your eyes will automatically goes into a certain stuff if you are used to it, so therefore I think it can be useful if the location of each catagory can be static, maybe an option to keep things at static location? I don't know how it can be done, but would be useful, just an idea to think about.

For example I would die to have junk + newly received items to be in the same spot everytime.

**Comment by Dogy007** [comment]
I would love a feature like this. I have a category "always in bag" that holds several items like hearthstones, fishing pole etc. Would be great if the category would always be displayed at the defined location
