### ISSUE TITLE
Ace 3 Error Message just started today

### ISSUE THREAD

**Issue by Caynn** [AdiAddons/AdiBags#512]
17x FrameXML\UIParent.lua:496: script ran too long
[string "@FrameXML\UIParent.lua"]:496: in function `UIParentLoadAddOn'
[string "@Rarity\Core\Collections-Collections.lua"]:63: in function `ScanToys'
[string "@Rarity\Core\Collections-Collections.lua"]:307: in function `ScanExistingItems'
[string "@Rarity\Core.lua"]:198: in function `DoEnable'
[string "@Rarity\Core.lua"]:167: in function <Rarity\Core.lua:166>
[string "=[C]"]: ?
[string "@AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...ceAdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Talyrius** [comment]
This error was triggered by [Rarity](https://www.curseforge.com/wow/addons/rarity).
