### ISSUE TITLE
[Suggestion] WoWUp trouble loading your addon straight from github from WoWup client.

### ISSUE THREAD

**Issue by ZeNz384** [AdiAddons/AdiBags#513]
It would be nice if you could update Adibags in wowup addon manager using github repositories.
see: https://wowup.io/guide/section/get-addons/install-from-url

![afbeelding](https://user-images.githubusercontent.com/24679549/99718552-53e19900-2aab-11eb-8bfd-3698b28a24b4.png)

**Comment by SpareSimian** [comment]
That will be handy during the downtime when Twitch hands over Curseforge to Overwolf:

https://www.pcgamer.com/wows-largest-add-on-repository-is-disabling-updates-during-shadowlands-launch/

**Comment by ZeNz384** [comment]
Nice to see #633 is now labelt pending, looking forwards on the changes done! 
And also joining up on saying: appreciate your work. :)
