### ISSUE TITLE
9.0 change to Pawn requires AdiBags change to API call

### ISSUE THREAD

**Issue by Luxyr** [AdiAddons/AdiBags#514]
https://www.curseforge.com/wow/addons/pawn:
"Hello bag addon authors!

Unfortunately in 9.0, replacing IsContainerItemAnUpgrade can cause taint errors, leading to (for example) being unable to swap weapons using the character sheet during combat lockdown. That's how Pawn used to let your addon know whether it should show upgrade arrows. But as of Pawn 2.4.2, Pawn supplies PawnIsContainerItemAnUpgrade instead of replacing the built-in version. To get Pawn suggestions working again with your bag addon, just use PawnIsContainerItemAnUpgrade whenever it's non-nil, and IsContainerItemAnUpgrade otherwise."

Currently with the latest version of AdiBags, upgrade icons do not show up, whether or not the item level plugin is enabled or not(which was the core of previous reports of pawn incompatibility).

![image](https://user-images.githubusercontent.com/5474643/99870195-130a8280-2b86-11eb-89df-a44ed7775e3c.png)

**Comment by Luxyr** [comment]
https://github.com/AdiAddons/AdiBags/pull/504

Looks like there is already a pull request to handle it.

**Comment by bolerro** [comment]
Why hasn't this been updated yet? Someone already provided the complete change that worked and the last updated did not include this. Pawn is a highly used addon and I know myself and others would really appreciate the update be added to Adibags.

**Comment by JackedNerd** [comment]
Agreed, I got #503 to work, with addition of 
`text:SetPoint("BOTTOMRIGHT", button, 0, 1)` line 106 of ItemLevel.lua to move the ilvl to the bottom right.

Would be nice to have this added into the plugin (or even an option to let you choose the corner).

**Comment by YWI** [comment]
Pawn still doesnt work, tried everything :3 :(

**Comment by Talyrius** [comment]
See #503.
