### ISSUE TITLE
Invisible bags? Can hear them opening but can't see them

### ISSUE THREAD

**Issue by ireland381** [AdiAddons/AdiBags#516]
Sorry if this has been answered but I can't find anyone with this issue.

Pretty much as the title says... I have current version of ElvUI, Adibags, but when I open my bags, there's no display at all. As I said, I can hear them opening; I tried resetting anchors on ElvUI in case the window disappeared or got moved somewhere, but nothing.

Bags open fine if AdiBags is disabled.

I'd reeeeeallly like to use this addon, please help!

**Comment by Zarggg** [comment]
Have you disabled the Bags feature in ElvUI?

**Comment by ireland381** [comment]
Yep. No change.

**Comment by Jeffister** [comment]
I have exactly the same problem since this morning without change anything. The only way to see bags is to disable Adibag for blizzard bags or re enable bag management in elvui to have, at least a one bag interface.

**Comment by volllastfan** [comment]
For some reason, even though AdiBags is up today, when logging in, in the list of addons, AdiBags is stated as out of date.  In game - same issue.  Cannot open bags (hear the bag opening, but not visible) unless AdiBags is disabled and standard Bags / ElvUI Bags are used.

**Comment by Kazuhma** [comment]
Resolved for me after updating _ElvUI AdiBags_ today, works without issues now.

**Comment by shinlang** [comment]
Updating _ElvUI AdiBags_ did nothing for me, still doesn't work. In fact, both _AdiBags_ and _ElvUI Adibags_ behave exactly the same, I hear the sound but nothing happens.

**Comment by shinlang** [comment]
Update: Fixed it for me by opening the AdiBags options via _/adibags_ and enabling the addon for backpack and bank, both were apparently disabled after the last update.

**Comment by ireland381** [comment]
FIXED!!

So... although I'd updated everything, I finally looked at Wowup and strangely the actual AdiBags addon itself was missing (the dependent ones were still there)... very strange, since it was showing up as installed in-game. Or at least according to Wowup it wasn't there; didn't check the actual folder. 

Anyway, reinstalling Adibags solved it.

Apologies, I thought I'd pretty much tried all the no-brainer stuff, but I guess not. So check your actual addons in the game folder or whatever program you use to manage your addons... no idea how the core addon went missing, but somehow it was gone.
