### ISSUE TITLE
auto tradeskill reagent deposit of some items I need

### ISSUE THREAD

**Issue by andrewboie** [AdiAddons/AdiBags#517]
I'm noticing in Shadowlands that the "Deposit reagents" option is depositing items which I would rather keep in my inventory.

- Weapon oils
- Cut gems

This seems new behavior in Shadowlands. The root cause I expect is Blizzard making these items available to be deposited in the reagent bank, which I don't believe was the case for cut gems before. Weapon oils are new.

Some way of filtering out certain items for auto-deposit would be really useful, particularly for weapon oils, as they are part of my usual adventuring kit. For now I work around it by disabling "Deposit reagents".

**Comment by Talyrius** [comment]
AdiBags is just making use of Blizzard's in-game functionality. Adding exceptions would require the whole system to be completely re-implemented within AdiBags and that's not something that's likely to happen.

I know it's unlikely to result in the desired change, but this feedback should still be directed towards Blizzard. Sorry.
