### ISSUE TITLE
AddOn 'AdiBags' tried to call the protected function 'CompactRaidFrame2:ClearAllPoints()'

### ISSUE THREAD

**Issue by Deathfiend1504** [AdiAddons/AdiBags#518]
Happens after every boss fight and the group loot appears in the middle of the screen.

Error dump:
6x [ADDON_ACTION_BLOCKED] AddOn 'AdiBags' tried to call the protected function 'CompactRaidFrame2:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@FrameXML\FlowContainer.lua"]:157: in function `FlowContainer_DoLayout'
[string "@FrameXML\FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by Talyrius** [comment]
This is a misattribution of taint originating from another addon. AdiBags doesn't interact with raid frames.
