### ISSUE TITLE
Pawn doesnt work

### ISSUE THREAD

**Issue by YWI** [AdiAddons/AdiBags#519]
I'm using PAWN to display tooltip upgrades. While using Adibags pawn doesn't seem to display the upgrade tooltips. I checked the old issues, tried to reach a resolution. Nothing seems to be valuable. I hope this issue can be fixed soon.

**Comment by Zarggg** [comment]
Pawn's upgrade arrow is anchored on the same corner of the icon as AdiBag's item level display. If you use these two addons together, you will need to modify the positioning of one of those.

If you mean the Pawn "score" is missing from the tooltip itself, that may be an configuration issue with Pawn, or another addon is modifying the tooltip in a way that conflicts with Pawn. I use AdiBags and Pawn together and have no issues with the tooltip.

**Comment by Cabby1970** [comment]
Modifying the positioning of the Adibags item level display to bottom left and bottom right did not allow the Pawn upgrade arrow to become visible.  Nor is it visible if you turn off the item level display in Adibags.

**Comment by Alyred** [comment]
PR #504 addresses this and is tested (ongoing), but it (and #499 and #496, for that matter) haven't been merged into the main yet, though I'm not sure why.  They seem to work well.
The changes in PR#504 are fairly small if you want to integrate them into your current version yourself.

**Comment by YWI** [comment]
Understood, I'd love to do the changes. I'm very confused about how to do them. Can anyone here please advise me with a noob-friendly guide.  Thanks for the swift replies, much apperaiocted.

**Comment by YWI** [comment]
Alright, never mind, it's resolved! It appears now, on the other hand. The issue is that the pawn arrow appears under the item level, and I don't want to have to disable the Item level for pawn. Is there a way to reposition the item level text on an equipment's icon?

**Comment by Adorei** [comment]
> Alright, never mind, it's resolved! It appears now, on the other hand. The issue is that the pawn arrow appears under the item level, and I don't want to have to disable the Item level for pawn. Is there a way to reposition the item level text on an equipment's icon?

Resolved how? Please include your solution to help others :) Thank you in advance!

**Comment by YWI** [comment]
> PR #504 addresses this and is tested (ongoing), but it (and #499 and #496, for that matter) haven't been merged into the main yet, though I'm not sure why. They seem to work well.
> The changes in PR#504 are fairly small if you want to integrate them into your current version yourself.

that was the solution post 504. Now power level is placed above the pawn arrow in which the Ilevel is cluttering the visuals. Need to find a way to relocate the location of the text on the item icon.

**Comment by Adorei** [comment]
You yourself asked for a noob-friendly guide, thought you would tell exactly what you did. I have no idea how to add new lines to addons without breaking stuff, so on a hunch I did the following and it seems to work. If something is wrong, feel free to correct me please!

So a noob-friendly version here :)


**1.** Open with Notepad or similar: C:\World of Warcraft\_retail_\Interface\AddOns\AdiBags\widgets\ItemButton.lua

**2.** CTRL+F the following: _C_Item_DoesItemExist(itemLocation) and C_Item_CanScrapItem(itemLocation) or false)
 	end_

**3.** Press Enter after "_end_" and paste this: 

function buttonProto:UpdateUpgradeIcon()
	self.UpgradeIcon:SetShown(IsContainerItemAnUpgrade(self.bag, self.slot) or false)
	if IsAddOnLoaded('Pawn') then itemIsUpgrade = _G.PawnIsContainerItemAnUpgrade(self.bag, self.slot) end
	if itemIsUpgrade == nil then itemIsUpgrade = _G.IsContainerItemAnUpgrade(self.bag, self.slot) end
	self.UpgradeIcon:SetShown( itemIsUpgrade or false)
end

**Comment by YWI** [comment]
Yup press emter them save the file then restart. Let me know if that resolved it for you ;)

**Comment by Adorei** [comment]
I mentioned that I got it to work with the above steps, just wrote the little guide for people who may find this thread and don't know what to do. The enter/save/restart I thought was self explanatory :)

**Comment by YWI** [comment]
Yup, its resolved thank god, now for item restoration, we shall wait. Still haven't figured out how to fix the item level text display location on the equipment's icon. hopefully, Adibags can implement it as a feature.

**Comment by chuckzhang** [comment]
To move item level text display location:
1. open this file Interface\AddOns\AdiBags\modules\ItemLevel.lua
2. find: CreateText(button)
3. change: SetPoint("TOPLEFT"... to something else, like BOTTOMLEFT to avoid overlap with Pawn upgrade icon.
