### ISSUE TITLE
items disappearing from adibags

### ISSUE THREAD

**Issue by Laggz** [AdiAddons/AdiBags#521]
I bought 2 different missives and a legendary base item all three disappeared from adibags. I disabled adibags and only the base item was in my bags.  I have no other issues with any item disappearing but it seems to be select tradeskill items because on another character I did not have herbs go missing.

**Comment by Alyred** [comment]
Adibags doesn't destroy any items that I am aware of, and have moved thousands of items in and out. However, I did read that Missives were (are?) going into the reagent bank, so if you have auto-deposit reagents it's possible that they might have gone there.
If it's a display issue, you should be able to find the items by disabling the addon to see. It would be helpful for the maintainers to know if you can find the items when the addon is disabled, but they're not displaying when the addon is loaded.

**Comment by Laggz** [comment]
I did not check my reagent bank at all, I will do that once I get in game. Im new to adibags but love how it sorts things out.  Thank you for the response.

**Comment by Alyred** [comment]
#496 and #499 deal with those issues, but are a bit more complex to add in as they have a lot of different parts. Adding the changes to your own addon install takes a bit of time, but basically, you look at the pull requests, examine the files, and copy the changes and deletions that are highlighted in each file to your own.
If you are only integrating one pull request at a time, you can view the "Raw" file and copy the whole thing in to your file at once.
