### ISSUE TITLE
Currency tooltip don't work. Each icon showing the same tooltip for "Gold".

### ISSUE THREAD

**Issue by ruslanzelinskyy** [AdiAddons/AdiBags#524]
Currency tooltip don't work. I guess there is only one tooltip for gold that shows up, but there should different tootips for each currency. Please fix.
PS: i've saw the similar issue opened, but thought that it is not described fully

**Comment by ruslanzelinskyy** [comment]
Last version (1.9.22) Shadowlands official
https://prnt.sc/vw79a6

**Comment by Talyrius** [comment]
It's never worked any differently on AdiBags, so there's nothing to fix. What you're asking for is a feature request and it's already been asked for previously (#427).
