### ISSUE TITLE
Pawn icon don't work (master)

### ISSUE THREAD

**Issue by ruslanzelinskyy** [AdiAddons/AdiBags#525]
I did the "hax" for Pawn in widgets/ItemButton.lua to make it work:
![Screenshot_4](https://user-images.githubusercontent.com/35612895/101236159-84464b80-36d7-11eb-9468-0d79a8de7943.png)

But icon now is under the item level, so that is the problem now i can't fix.
Also when that "hax" will be added to master?

**Comment by ruslanzelinskyy** [comment]
Fixed it by doing this in AdiBags/widgets/ItemButton.lua:
![Screenshot_2](https://user-images.githubusercontent.com/35612895/101236025-3b41c780-36d6-11eb-8904-da3f0e7c2f06.png)

Now it looks like this:
![Screenshot_3](https://user-images.githubusercontent.com/35612895/101236027-3f6de500-36d6-11eb-8e33-aac9d14b53b0.png)

Hope could be usefull for somebody!

**Comment by Yasinahh** [comment]
How i can set the Upgrade Arrow Topright? Now it is Top Left
![grafik](https://user-images.githubusercontent.com/28381047/101283921-bf32a700-37dd-11eb-9d37-8b219c0988f7.png)

**Comment by ruslanzelinskyy** [comment]
Don't know, probably you should make some changes in Pawn addon. 
I've fixed this issue by moving item level number to topright. To see how check upper comments.

**Comment by janxtv** [comment]
Do line's 104-110 need to be added or replaced?

The file you supplied has the itemlevel over the pawn arrow.

**Comment by ruslanzelinskyy** [comment]
> 
> 
> Do line's 104-110 need to be added or replaced?
> 
> The file you supplied has the itemlevel over the pawn arrow.

Sorry, i've accidentally mixed up the files.
Updated my comment, please check: https://github.com/AdiAddons/AdiBags/issues/525#issuecomment-739135777

**Comment by Talyrius** [comment]
See #503.
