### ISSUE TITLE
Item Lvl Colors

### ISSUE THREAD

**Issue by Yasinahh** [AdiAddons/AdiBags#527]
Hi, 
it is possible to Display the Item lvl Color in the Bag same as the Quality? 
uncommon = green
Rare = Blue
Epic = Purple
Legendary = Orange

Now all these qualitys has the same color
![Screenshot 2020-12-06 150108](https://user-images.githubusercontent.com/28381047/101282212-0b78e980-37d4-11eb-8e00-766b1af738e6.png)

**Comment by Hoid-droid** [comment]
I found something that might help you.

I checked through the ItemLevel.lua that came with the elvui remake of adibags and ran it through a text compare module and found that some pieces of the lua from the original addon had some things missing.

You could try it out if you want, I don't know if this is what you're looking for but this will give you an extra option for color schemes. (don't forget to save your original lua before trying this)
https://pastebin.com/DraRMTfm
![adibags](https://user-images.githubusercontent.com/47645690/117517355-16f75900-af9c-11eb-8bbe-8c3baac88ece.PNG)
