### ISSUE TITLE
Pawn addon upgrade arrow

### ISSUE THREAD

**Issue by DonJuan835** [AdiAddons/AdiBags#528]
The Pawn upgrade arrow isn't working with this addon anymore. This is from the Pawn author.

"Hello bag addon authors!
Unfortunately in 9.0, replacing IsContainerItemAnUpgrade can cause taint errors, leading to (for example) being unable to swap weapons using the character sheet during combat lockdown. That's how Pawn used to let your addon know whether it should show upgrade arrows. But as of Pawn 2.4.2, Pawn supplies PawnIsContainerItemAnUpgrade instead of replacing the built-in version. To get Pawn suggestions working again with your bag addon, just use PawnIsContainerItemAnUpgrade whenever it's non-nil, and IsContainerItemAnUpgrade otherwise."

**Comment by ruslanzelinskyy** [comment]
@DonJuan835 could you please check my comment or add suggestion how to fix it?
#525 (comment)

**Comment by Talyrius** [comment]
See #503.
