### ISSUE TITLE
Strange numbers in names

### ISSUE THREAD

**Issue by N6REJ** [AdiAddons/AdiBags#529]
Some of the labels have strange numbers in front of them.
![image](https://user-images.githubusercontent.com/1850089/101623561-4189b980-39de-11eb-84a5-2d2dbd01d49d.png)

**Comment by Talyrius** [comment]
Those labels are from a different addon that's added custom filters.

**Comment by N6REJ** [comment]
thanks, was caused by the "by expansion" addon

**Comment by N6REJ** [comment]
@Talyrius do we need the fishing addon?

**Comment by Talyrius** [comment]
I don't know which addon you're referring to, so you definitely don't need it.
