### ISSUE TITLE
Group ALL consumables

### ISSUE THREAD

**Issue by N6REJ** [AdiAddons/AdiBags#531]
Can we please get all consumables together?  Or at the very least be able to drag them in and have them stay permanently?
![image](https://user-images.githubusercontent.com/1850089/101625069-86165480-39e0-11eb-8c8c-9983a15a5846.png)

**Comment by Talyrius** [comment]
You're using another addon that's filtering those items by expansion.

**Comment by N6REJ** [comment]
thanks, removed.  There are soooo many adibag addon's its confusing.
