### ISSUE TITLE
Multiple bag ui's

### ISSUE THREAD

**Issue by N6REJ** [AdiAddons/AdiBags#532]
How do I stop the multiple bag ui's?
![image](https://user-images.githubusercontent.com/1850089/101639610-1f4f6600-39f5-11eb-84ce-6456601f469a.png)
I'm using evlui & tsm & adi

**Comment by Zarggg** [comment]
ElvUI also modifies the Blizzard bag interface. If you don't want to use that, you need to disable it in ElvUI.

This is not an issue caused by AdiBags.

**Comment by N6REJ** [comment]
I assumed not.  I just don't know which addon to investigate.  Should I assume if I tell elvui to use blizzard bag that will solve the issue?

**Comment by Talyrius** [comment]
Yes.
