### ISSUE TITLE
(suggestion) Vanilla Bag toggle button

### ISSUE THREAD

**Issue by Arlochorim** [AdiAddons/AdiBags#534]
I'd love to see a button to toggle between the sorted bags and a single large bag overlay (or enable/disable) button.

As useful as I find having sorted segments, sometimes it's difficult to find exactly what I want and it can be easier in vanilla bag layout.

**Comment by SpareSimian** [comment]
How is this different from clicking the button at the top left that lets you install new bags? That switches the display to a classic bag view.

**Comment by Arlochorim** [comment]
I have decided i'm an idiot and closed the issue =P

**Comment by Talyrius** [comment]
The search box is also helpful for finding items.
