### ISSUE TITLE
Sell Junk button disapear

### ISSUE THREAD

**Issue by geofraynils** [AdiAddons/AdiBags#536]
Hi, 

I noticed a "sell junk" button at top right of bags, in normal interface (wow shadowlands). When I activate the add-on, this button disapear. It would be very nice to see it back.

**Comment by Talyrius** [comment]
I suggest using [Scrap](https://www.curseforge.com/wow/addons/scrap) alongside AdiBags to sell/manage junk.

**Comment by SpareSimian** [comment]
Why clutter up the screen? With a vendor window open, just right-click the word "Junk" above the junk section of the bag and all your junk will be sold.
