### ISSUE TITLE
Stopping putting specific items in the Reagent Bank?

### ISSUE THREAD

**Issue by Foreverzero86** [AdiAddons/AdiBags#537]
Specifically gems but also specific items like BFA's Midnight Salmon. I have the "auto-deposit" turned off and every time I click on "Deposit All Reagents" in the bank they are deposited along with other stuff since they are, indeed, "reagents", but I want to keep them in my bags instead.

**Comment by Zarggg** [comment]
I believe that button just follows Blizzard's built-in function, which directly deposits anything that can go into the Reagent Bank.

You're probably better off using something like TSM's BankUI module if you specifically want to use the regular bank.
