### ISSUE TITLE
Sort bag Button

### ISSUE THREAD

**Issue by Birrout** [AdiAddons/AdiBags#538]
Hi, 
I recently installed Adibags and i was looking for a Sort bag button but i appears that mine does not show.
Is there is none in the new update or does need to do something to make it show?

**Comment by Talyrius** [comment]
A sorting function hasn't been implemented for the Classic version. The Retail version uses Blizzard's sort function which isn't available on the Classic client.

**Comment by Birrout** [comment]
Ok thanks

**Comment by silverhawke249** [comment]
kind of related question: if items aren't stacked optimally, does this addon restack them so they take the least amount of bag space? e.g. instead of having (3, 3, 3) stacks of an item that can stack to 5, have (5, 4) stacks instead

**Comment by Talyrius** [comment]
Items generally stack optimally unless you've manually intervened by splitting them.

**Comment by Zamralik** [comment]
Would it be possible to add the button back just so it guarantee all partial stacks are properly merged ?
