### ISSUE TITLE
Pawn arrow will not show while using adbags

### ISSUE THREAD

**Issue by gigecogary** [AdiAddons/AdiBags#539]
Pawn arrow will not show while using adbags

**Comment by derekengel** [comment]
I can second this.  If you're using Pawn, and you have an upgrade in your bags, there is no green arrow on the item.  If you disable Adibags, it shows.

**Comment by mackhankins** [comment]
I'd love to be able to see the arrow instead of having to mouse-over.

**Comment by JamesMDenton** [comment]
Same here. It used to, but I'm not sure how long ago... Even with Itemlevel disabled it still doesn't show.

**Comment by ruslanzelinskyy** [comment]
@JamesMDenton @mackhankins @derekengel @gigecogary 
You will need to replace two files
Check this issue for my fix https://github.com/AdiAddons/AdiBags/issues/525#issuecomment-739135777

**Comment by gigecogary** [comment]
Is there a way to just fix this for the release? If I do the file replacement its gone on the next update no?

**Comment by ruslanzelinskyy** [comment]
@gigecogary I suppose there is no way for now to make it for release. Author of addon @Adirelle should add this changes to master self. By the way @Adirelle , I could create pull request for this changes if you accept this changes (mentioned in #525 )

**Comment by Talyrius** [comment]
See #503.
