### ISSUE TITLE
Incompatible with 6.1.2

### ISSUE THREAD

**Issue by stoffer81** [AdiAddons/AdiBags#54]
Hello!
I love the AdiBags addon and can't imagine playing without it to keep me organized.
It will not load in the latest patch (6.1.2) without checking the "Load out of date addons" checkbox.
It seems to work fine once checked
Can you update it?

**Comment by Zarggg** [comment]
If you have a specific reason to *not* leave "Load out of date addons" checked, you can simply change line 24 in AdiBags.toc to read `## Interface: 60100`.
