### ISSUE TITLE
Is it possible to have Adibags not abbreviate sections?

### ISSUE THREAD

**Issue by peikaboo** [AdiAddons/AdiBags#540]
I tried looking for an option for this by googling, but couldn't find anything on it. It would just be nice to see the whole name of sections in my bags instead of En... (for enchanting) Co... (for consumables) I don't really care if it makes my bag bigger. It could be because I downloaded premade sections from other people. Thanks for taking the time to help. If it is an option I will try and fix it.

**Comment by Moregaze** [comment]
Did you find a solution?  I too want the full header name to show instead of just a letter or two and some ....s

**Comment by peikaboo** [comment]
No never found a solution unfortunately  :(
