### ISSUE TITLE
[Oil of Ethereal Force] (Maw consumable) needs to be excluded from junk

### ISSUE THREAD

**Issue by Bronski** [AdiAddons/AdiBags#542]
[Oil of Ethereal Force] (Maw consumable) needs to be excluded from junk. It costs Stygia to buy.

https://www.wowhead.com/item=181245/oil-of-ethereal-force

**Comment by Bronski** [comment]
[Sticky-Fingered Skeletal Hand] (sold by the same vendor) also has this problem.

**Comment by Talyrius** [comment]
That's the way Blizzard classified it. ¯\_(ツ)_/¯
