### ISSUE TITLE
LUA errors are hidden with AdiBags

### ISSUE THREAD

**Issue by LenweSaralonde** [AdiAddons/AdiBags#543]
When AdiBags is running, LUA errors no longer show up.

```lua
/run nil()
```
Checking / unchecking the "No error reports" has no effect.

This could be a side effect with the embedded BugGrabber library that is not embedded correctly

**Comment by Iyadriel** [comment]
Started having the same issue recently and discovered that AdiBags was causing this.

**Comment by LenweSaralonde** [comment]
As workaround, you can install a bug reporting addon such as Swatter to have the errors back.

[https://gitlab.com/norganna-wow/libs/swatter]
