### ISSUE TITLE
Better vertical stacking of small sections?

### ISSUE THREAD

**Issue by emersonrp** [AdiAddons/AdiBags#546]
Is there, or could there be, some way to specify how high to pile small sections?  I currently have about a zillion filters, therefore many sections with like four things in them.  This leads to short, wide bag windows:

![image](https://user-images.githubusercontent.com/307232/103488791-bbdf0b00-4ddd-11eb-8ec1-c81a1bd7f674.png)

I'd love the ability to "square up" that window somehow -- previous to yesterday (when I cleaned my inventory to mitigate this) I had about six more sections in there, and the super-short window took up like 75% of the bottom of my screen horizontally.

Thanks!

**Comment by Zarggg** [comment]
The first thing you need to do is limit the number of currencies you're tracking on your backpack. That's what's forcing the horizontal stretching.

**Comment by emersonrp** [comment]
Aha!  See, I'd noticed it started doing that right around the start of SL, and I assumed it was new behavior but I guess it's tracking all the new ones as well as the large handful I already had in there and I just hadn't reviewed that bit.  And yes, fixing that makes it work just fine.  Thanks, and sorry for the user error.  :)
