### ISSUE TITLE
Icons getting mixed up/repeating.

### ISSUE THREAD

**Issue by Doomsponge** [AdiAddons/AdiBags#55]
Hello!

I'm not sure how to explain this or the best way to take a picture of it, but I'll try. 

Every so often when I open up my bags I notice that the icons for the items in my inventory have gotten all mixed up and placed in the wrong categories. Suddenly they've started to repeat (even when I do not have two of an item or more than 1 stack of an item) or the icon will change to something else and inaccurately represent what the item actually is. 

Case in point, here is a screenshot of it happening. The things I have hovered over (see the red arrows) show the correct tooltips for what they are, but their icons have weirdly changed to be inaccurate of what their item really is. If I click on the item it will be correctly/based on what the tooltip says (be it the gloves or blingtron) and not what the changed icon shows it to be.
![adibags](https://cloud.githubusercontent.com/assets/11697089/6881955/720f20bc-d531-11e4-971c-338b99b72494.png)

Closing and opening my bags a few times will fix this issue, but I though I'd put it out there anyways in case anyone else is experiencing this. If this is not adibags doing this, I apologize for putting it here.

Thanks!

**Comment by Cidan** [comment]
This is fixed in an upcoming release.
