### ISSUE TITLE
SetPoint error once every hour

### ISSUE THREAD

**Issue by derickso** [AdiAddons/AdiBags#551]
16x AdiBags\widgets\ContainerFrame.lua:998: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: AdiBagsSection14:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@AdiBags\widgets\ContainerFrame.lua"]:998: in function `LayoutSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1069: in function <AdiBags\widgets\ContainerFrame.lua:1043>
[string "=(tail call)"]: ?
[string "@AdiBags\widgets\ContainerFrame.lua"]:449: in function `RefreshContents'
[string "@AdiBags\widgets\ContainerFrame.lua"]:434: in function `ResumeUpdates'
[string "@AdiBags\widgets\ContainerFrame.lua"]:417: in function <AdiBags\widgets\ContainerFrame.lua:409>
[string "=[C]"]: in function `Show'
[string "@AdiBags\core\Bags.lua"]:89: in function `Open'
[string "@AdiBags\core\Hooks.lua"]:112: in function <AdiBags\core\Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
(*temporary) = AdiBagsSection14 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 6
 count = 6
 total = 6
 name = "Finger"
 category = "Equipment"
 height = 1
 key = "Equipment#Finger"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = AdiBagsSection9 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 2
 count = 2
 total = 2
 name = "Quest"
 category = "Quest"
 height = 1
 key = "Quest#Quest"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPRIGHT"
(*temporary) = 10.500000
(*temporary) = 0

**Comment by wuhan890809** [comment]
open Interface\AddOns\Adibags\widgets\ContainerFrame.lua and change the content of Line 997
from:
if section and previous then
to
if section and previous and section ~= previous then

that will stop the layout from anchoring to itself recursively

**Comment by CodeAnxiety** [comment]
This bug can still happen. I've made a PR that should also handle the edge when a circular dependency involves more than two sections.
