### ISSUE TITLE
AdiBags doesn't work on Classic

### ISSUE THREAD

**Issue by joao-fidalgo** [AdiAddons/AdiBags#552]
AdiBags version: 1.9.20-classic-nolib
WoW version: 1.13.6.36935

**Comment by Zarggg** [comment]
You posted that you are using the "-nolib" version of the addon, which (as the name implies) does not include any third-party libraries utilized by the the addon. This is most likely the problem; try redownloading the standard version located here: https://github.com/AdiAddons/AdiBags/releases/tag/v1.9.20-classic

**Comment by Talyrius** [comment]
Don't use the "-nolib" version unless you know what it's used for. I just verified 1.9.20-classic still works just fine on Classic. You just have to force it to load out of date addons.
![image](https://user-images.githubusercontent.com/1068810/111051139-c3d2b100-8405-11eb-9d84-a05b0de2814a.png)
