### ISSUE TITLE
Can't attach Infra-green Reflex Sight

### ISSUE THREAD

**Issue by clumba** [AdiAddons/AdiBags#556]
Can't attach Infra-green Reflex Sight while AdiBags enabled. Turn it off -> works fine.

**Comment by Talyrius** [comment]
A `/reload` should have sufficed. Are you using any third-party AdiBag addons and if so, which ones?

**Comment by clumba** [comment]
Yes: `https://i.imgur.com/8MXv7A5.png`

**Comment by Talyrius** [comment]
I was able to attach the scope even with those other addons installed. I can only surmise that this was caused by some type of combat related taint and in that case, a `/reload` would resolve it.
