### ISSUE TITLE
Way to make the currency only show gold, not silver/copper?

### ISSUE THREAD

**Issue by ImmutableBug** [AdiAddons/AdiBags#557]
Sorry if wrong spot for this. Can't find an issue for it, and really don't care how much silver/copper I have, so I'd like to hide it for the extra space. Is there a way to do that? Thanks!

**Comment by SpareSimian** [comment]
Interesting idea. You could probably also still show the silver and copper as a 4-digit fraction, but saving the space from the extra coin icons.

**Comment by Kuipo** [comment]
Or you could show the silver/copper on hover.
