### ISSUE TITLE
Adibag attempts to use ItemRack:RegisterExternalEventListener before Itemrack has initialized

### ISSUE THREAD

**Issue by MatthewBerkvens** [AdiAddons/AdiBags#558]
Latest versions of both addons on 11/03 (will edit version numbers later)
https://i.imgur.com/wRXUtXr.png
https://i.imgur.com/9EwtkDN.png

I don't know who is responsible for fixing this, created an issue on both repos
https://github.com/Rottenbeer/ItemRack/issues/148

**Comment by Rottenbeer** [comment]
@MatthewBerkvens test this please: https://github.com/Rottenbeer/ItemRack/tree/fix-adibags-race

**Comment by EnvoyMajeh** [comment]
I posted in the [AdiBags-ItemRackSets](https://github.com/apottere/AdiBags-ItemRackSets/issues/2) issues already, but I'll put this here in case it helps anyone:
Seems that ItemRack:RegisterExternalEventListener gets loaded later so ItemRack needs to finish loading before it can be used.
Not sure if this is the ideal fix, but I was able to get mine working again by changing a little bit in the Adibags-ItemRackSets.lua file -
On line 35/36 I changed:
```
ItemRack:RegisterExternalEventListener("ITEMRACK_SET_SAVED", itemRackUpdated)
ItemRack:RegisterExternalEventListener("ITEMRACK_SET_DELETED", itemRackUpdated)
```

to this:
```
local IREvents = CreateFrame("Frame", nil)
IREvents:RegisterEvent("ADDON_LOADED")
IREvents:SetScript("OnEvent", function(self, event, addon)
    if (addon == "ItemRack") then
        ItemRack:RegisterExternalEventListener("ITEMRACK_SET_SAVED", itemRackUpdated)
        ItemRack:RegisterExternalEventListener("ITEMRACK_SET_DELETED", itemRackUpdated)
    end
end)
```

**Comment by SpareSimian** [comment]
Is it possible that the order of loading might change in the future? If so, you might add code to handle the case where IR is already loaded.

**Comment by Talyrius** [comment]
[AdiBags-ItemRackSets](https://github.com/apottere/AdiBags-ItemRackSets) is a third-party addon, so this issue definitely belongs there.  However, [ItemRack](https://github.com/Rottenbeer/ItemRack)'s addon author already implemented a [workaround](https://github.com/Rottenbeer/ItemRack/commit/e027dc9f63a9c6be4a2c0f35241964ef4f03a40d).
