### ISSUE TITLE
Stopped working completely since last patch

### ISSUE THREAD

**Issue by StryNght** [AdiAddons/AdiBags#559]
I hadnt realy logged on since the last patch. I checked my vault on tuesday and my bags were fine. Then when I logged on again on Sunday evening Adibags wasnt working at all. At this point Ive removed all old files and done a complete reinstall of Adibags. Then I loaded up with just Adibags and bug grabber.  These are what errors I got on load up. I just want my bags back!  :'( Please help

**Error 1** 

> 2x ...AdiBags\libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:2: LibDataBroker-1.1 requires LibStub
> [string "=[C]"]: in function `assert'
> [string "@AdiBags\libs\LibDataBroker-1.1\LibDataBroker-1.1.lua"]:2: in main chunk
> 
> Locals:
> (*temporary) = nil
> (*temporary) = "LibDataBroker-1.1 requires LibStub"

 **Error 2**

>  2x AdiBags\core\EventHandlers.lua:35: attempt to call global 'LibStub' (a nil value)
>  [string "@AdiBags\core\EventHandlers.lua"]:35: in main chunk
> Locals:
> addonName = "AdiBags"
> addon = <table> {
>  L = <table> {
>  }
> }
> _G = <table> {
>  UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML\ActionButton.lua:78
>  ERR_OUT_OF_CHI = "Not enough chi"
>  DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
>  MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
>  }
>  MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
>  }
>  GetTrainerServiceTypeFilter = <function> defined =[C]:-1
>  UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
>  SetTrainerServiceTypeFilter = <function> defined =[C]:-1
>  LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 743
>  SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
>  LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 401
>  ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
>  RecruitAFriendFrame = RecruitAFriendFrame {
>  }
>  CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
>  }
>  TutorialFrameLeft19 = TutorialFrameLeft19 {
>  }
>  MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
>  }
>  ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
>  PVP_RANK_6_1 = "Corporal"
>  MultiBarLeftButton7 = MultiBarLeftButton7 {
>  }
>  AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
>  }
>  VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture = VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture {
>  }
>  MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
>  }
>  OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
>  BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
>  CHAT_HEADER_SUFFIX = ": "
>  MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
>  }
>  COVENANT_MISSIONS_HEALTH = "Health"
>  MAIL_LETTER_TOOLTIP = "Click to make a permanent
> copy of this letter."
>  UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML\UnitFrame.lua:789
>  PaperDollTitlesPaneButton10BgTop = PaperDollTitlesPaneButton10BgTop {
>  }
>  CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
>  CHAT_CONFIG_OTHER_COMBAT = <table> {
>  }
>  FCFDockOverflowButton_OnClick = <function> defined @FrameXML\FloatingChatFrame.lua:2379
>  TutorialFrameRight19 = TutorialFrameRight19 {
>  }
>  ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
>  }
>  BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
>  AutoCompleteEditBox_OnKeyDown = <function> defined @FrameXML\AutoComplete.lua:366
>  CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
>  }
>  LFGTeleport = <function> defined =[C]:-1
>  LE_GAME_ERR_ONLY_ONE_QUIVER = 33
>  INT_SPELL_DURATION_HOURS = "%d |4hour:hrs;"
>  ToggleEncounterJournal = <function> defined @FrameXML\UIParent.lua:1047
>  LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
>  Graphics_QualityText = Graphics_QualityText {
>  }
>  OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
>  }
>  ROGUE_COMBAT_CORE_ABILITY_4 = "Melee attack that spends Combo Points."
>  JoinSkirmish = <function> defined =[C]:-1
>  FriendsFriendsScrollFrameButton14 = FriendsFriendsScrollFrameButton14 {
>  }
>  Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_GraphicsAPIDropDownButtonHighlightTexture {
>  }
>  MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
>  }
>  BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
>  }
>  LFGListSearchPanelScrollFrameButton10BottomRight = LFGListSearchPanelScrollFrameButton10BottomRight {
>  }
>  DMG_LCD = "DMG"
>  VideoOptionsPanel_Cancel = <function> defined @SharedXML\VideoOptionsPanels.lua:334
>  Is64BitClient = <function> defined =[C]:-1
>  SecureCmdItemParse = <function> defined @FrameXML\ChatFrame.lua:1145
>  SLASH_STOPATTACK1 = "/stopattack"
>  MultiCastActionButton4HotKey = 

**Error 3**

> 2x AdiBags\core\Fonts.lua:34: attempt to call global 'LibStub' (a nil value)
> [string "@AdiBags\core\Fonts.lua"]:34: in main chunk
> 
> Locals:
> addonName = "AdiBags"
> addon = <table> {
>  HEADER_SIZE = 18
>  BACKDROP = <table> {
>  }
>  FAMILY_TAGS = <table> {
>  }
>  GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:188
>  GetFamilyTag = <function> defined @AdiBags\core\Utility.lua:276
>  IsValidItemLink = <function> defined @AdiBags\core\Utility.lua:151
>  L = <table> {
>  }
>  TOP_PADDING = 32
>  CompareSectionKeys = <function> defined @AdiBags\core\Utility.lua:246
>  safecall = <function> defined @AdiBags\core\Utility.lua:81
>  IsJunk = <function> defined @AdiBags\core\Utility.lua:222
>  SplitSectionKey = <function> defined @AdiBags\core\Utility.lua:238
>  BuildSectionKey = <function> defined @AdiBags\core\Utility.lua:231
>  IsSameLinkButLevel = <function> defined @AdiBags\core\Utility.lua:196
>  GetItemFamily = <function> defined @AdiBags\core\Utility.lua:268
>  GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
>  SECTION_SPACING = 16.333333
>  ITEM_SIZE = 37
>  ITEM_SPACING = 4
>  SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
>  FAMILY_ICONS = <table> {
>  }
>  BAG_IDS = <table> {
>  }
>  DEFAULT_SETTINGS = <table> {
>  }
>  BAG_INSET = 8
>  GetBagSlotFromId = <function> defined @AdiBags\core\Utility.lua:63
> }
> L = <table> {
>  Reset new items = "Reset new items"
>  Use SyLevel = "Use SyLevel"
>  Bags = "Bags"
>  Bag background = "Bag background"
>  Use this section to define any item-section association. = "Use this section to define any item-section association."
>  Alt-right-click to configure manual filtering. = "Alt-right-click to configure manual filtering."
>  AMMO_TAG = "Am"
>  auto-sort = "auto-sort"
>  Let SyLevel handle the the display. = "Let SyLevel handle the the display."
>  Never = "Never"
>  Consider gems as a subcategory of trade goods = "Consider gems as a subcategory of trade goods"
>  ... including incomplete stacks = "... including incomplete stacks"
>  Filter = "Filter"
>  Change stacking at merchants', auction house, bank, mailboxes or when trading. = "Change stacking at merchants', auction house, bank, mailboxes or when trading."
>  Same as InventoryItemLevels = "Same as InventoryItemLevels"
>  Bind type = "Bind type"
>  Recent Items = "Recent Items"
>  Size = "Size"
>  Track new items in each bag, displaying a glowing aura over them and putting them in a special section. "New" status can be reset by clicking on the small "N" button at top left of bags. = "Track new items in each bag, displaying a glowing aura over them and putting them in a special section. "New" status can be reset by clicking on the small "N" button at top left of bags."
>  Display the level of equippable item in the top left corner of the button. = "Display the level of equippable item in the top left corner of the button."
>  Font = "Font"
>  Press Alt while doing so to open a dropdown menu. = "Press Alt while doing so to open a dropdown menu."
>  None = "None"
>  Lock anchor = "Lock anchor"
>  Opacity = "Opacity"
>  Show filtering information... = "Show filtering information..."
>  Texture = "Texture"
>  Select which first-level categories should be split by sub-categories. = "Select which first-level categories should be split by sub-categories."
>  Mininum level = "Mininum level"
>  Show only one free slot for each kind of bags. = "Show only one free slot for each kind of bags."
>  Split by subcategories = "Split by subcategories"
>  When checked, right-clicking on an empty space of a bag opens the configuration panel. = "When checked, right-clicking on an empty space of a bag opens the configuration panel."
>  Click to reset item status. = "Click to reset item status."
>  Container information = "Container information"
>  ENCHANTING_BAG_TAG = "En"
>  Filtering information = "Filtering information"
>  Item category = "Item category"
>  Merge free space = "Merge free space"
>  Select how the bags are positionned. = "Select how the bags are positionned."
>  Remove = "Remove"
>  Toggle and configure item filters. = "Toggle and configure item fi

**Error 4**

> 2x AdiBags\core\Core.lua:47: attempt to call global 'LibStub' (a nil value)
> [string "@AdiBags\core\Core.lua"]:47: in main chunk
> Locals:
> addonName = "AdiBags"
> addon = <table> {
>  HEADER_SIZE = 18
>  BACKDROP = <table> {
>  }
>  FAMILY_TAGS = <table> {
>  }
>  GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:188
>  GetFamilyTag = <function> defined @AdiBags\core\Utility.lua:276
>  IsValidItemLink = <function> defined @AdiBags\core\Utility.lua:151
>  L = <table> {
>  }
>  TOP_PADDING = 32
>  CompareSectionKeys = <function> defined @AdiBags\core\Utility.lua:246
>  safecall = <function> defined @AdiBags\core\Utility.lua:81
>  IsJunk = <function> defined @AdiBags\core\Utility.lua:222
>  SplitSectionKey = <function> defined @AdiBags\core\Utility.lua:238
>  BuildSectionKey = <function> defined @AdiBags\core\Utility.lua:231
>  IsSameLinkButLevel = <function> defined @AdiBags\core\Utility.lua:196
>  GetItemFamily = <function> defined @AdiBags\core\Utility.lua:268
>  GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
>  SECTION_SPACING = 16.333333
>  ITEM_SIZE = 37
>  ITEM_SPACING = 4
>  SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
>  FAMILY_ICONS = <table> {
>  }
>  BAG_IDS = <table> {
>  }
>  DEFAULT_SETTINGS = <table> {
>  }
>  BAG_INSET = 8
>  GetBagSlotFromId = <function> defined @AdiBags\core\Utility.lua:63
> }
> L = <table> {
>  Reset new items = "Reset new items"
>  Use SyLevel = "Use SyLevel"
>  Bags = "Bags"
>  Bag background = "Bag background"
>  Use this section to define any item-section association. = "Use this section to define any item-section association."
>  Alt-right-click to configure manual filtering. = "Alt-right-click to configure manual filtering."
>  AMMO_TAG = "Am"
>  auto-sort = "auto-sort"
>  Let SyLevel handle the the display. = "Let SyLevel handle the the display."
>  Never = "Never"
>  Consider gems as a subcategory of trade goods = "Consider gems as a subcategory of trade goods"
>  ... including incomplete stacks = "... including incomplete stacks"
>  Filter = "Filter"
>  Change stacking at merchants', auction house, bank, mailboxes or when trading. = "Change stacking at merchants', auction house, bank, mailboxes or when trading."
>  Same as InventoryItemLevels = "Same as InventoryItemLevels"
>  Bind type = "Bind type"
>  Recent Items = "Recent Items"
>  Size = "Size"
>  Track new items in each bag, displaying a glowing aura over them and putting them in a special section. "New" status can be reset by clicking on the small "N" button at top left of bags. = "Track new items in each bag, displaying a glowing aura over them and putting them in a special section. "New" status can be reset by clicking on the small "N" button at top left of bags."
>  Display the level of equippable item in the top left corner of the button. = "Display the level of equippable item in the top left corner of the button."
>  Font = "Font"
>  Press Alt while doing so to open a dropdown menu. = "Press Alt while doing so to open a dropdown menu."
>  None = "None"
>  Lock anchor = "Lock anchor"
>  Opacity = "Opacity"
>  Show filtering information... = "Show filtering information..."
>  Texture = "Texture"
>  Select which first-level categories should be split by sub-categories. = "Select which first-level categories should be split by sub-categories."
>  Mininum level = "Mininum level"
>  Show only one free slot for each kind of bags. = "Show only one free slot for each kind of bags."
>  Split by subcategories = "Split by subcategories"
>  When checked, right-clicking on an empty space of a bag opens the configuration panel. = "When checked, right-clicking on an empty space of a bag opens the configuration panel."
>  Click to reset item status. = "Click to reset item status."
>  Container information = "Container information"
>  ENCHANTING_BAG_TAG = "En"
>  Filtering information = "Filtering information"
>  Item category = "Item category"
>  Merge free space = "Merge free space"
>  Select how the bags are positionned. = "Select how the bags are positionned."
>  Remove = "Remove"
>  Toggle and configure item filters. = "Toggle and configure item fi

**Error 5**

> 2x AdiBags\core\Bags.lua:151: attempt to call method 'Debug' (a nil value)
> [string "@AdiBags\core\Bags.lua"]:151: in function `NewBag'
> [string "@AdiBags\core\Bags.lua"]:198: in main chunk
> 
> Locals:
> self = <table> {
>  BACKDROP = <table> {
>  }
>  CloseBackpack = <function> defined @AdiBags\core\Hooks.lua:180
>  BAG_INSET = 8
>  SplitSectionKey = <function> defined @AdiBags\core\Utility.lua:238
>  TOP_PADDING = 32
>  hookedBags = <table> {
>  }
>  OpenBag = <function> defined @AdiBags\core\Hooks.lua:137
>  ToggleAllBags = <function> defined @AdiBags\core\Hooks.lua:86
>  GetItemFamily = <function> defined @AdiBags\core\Utility.lua:268
>  GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
>  SECTION_SPACING = 16.333333
>  ToggleBackpack = <function> defined @AdiBags\core\Hooks.lua:195
>  ToggleBag = <function> defined @AdiBags\core\Hooks.lua:156
>  GetContainerFrame = <function> defined @AdiBags\core\Hooks.lua:71
>  CloseAllBags = <function> defined @AdiBags\core\Hooks.lua:119
>  HEADER_SIZE = 18
>  SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
>  CloseSpecialWindows = <function> defined @AdiBags\core\Hooks.lua:208
>  OpenAllBags = <function> defined @AdiBags\core\Hooks.lua:109
>  BuildSectionKey = <function> defined @AdiBags\core\Utility.lua:231
>  GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:188
>  IterateDefinedBags = <function> defined @AdiBags\core\Bags.lua:188
>  L = <table> {
>  }
>  bagProto = <table> {
>  }
>  NewBag = <function> defined @AdiBags\core\Bags.lua:150
>  safecall = <function> defined @AdiBags\core\Utility.lua:81
>  IsJunk = <function> defined @AdiBags\core\Utility.lua:222
>  IterateBags = <function> defined @AdiBags\core\Bags.lua:183
>  OpenBackpack = <function> defined @AdiBags\core\Hooks.lua:168
>  CloseBag = <function> defined @AdiBags\core\Hooks.lua:149
>  BAG_IDS = <table> {
>  }
>  IsSameLinkButLevel = <function> defined @AdiBags\core\Utility.lua:196
>  FAMILY_TAGS = <table> {
>  }
>  ITEM_SIZE = 37
>  DEFAULT_SETTINGS = <table> {
>  }
>  GetFamilyTag = <function> defined @AdiBags\core\Utility.lua:276
>  FAMILY_ICONS = <table> {
>  }
>  IsValidItemLink = <function> defined @AdiBags\core\Utility.lua:151
>  CompareSectionKeys = <function> defined @AdiBags\core\Utility.lua:246
>  ITEM_SPACING = 4
>  GetBagSlotFromId = <function> defined @AdiBags\core\Utility.lua:63
> }
> name = "Backpack"
> order = 10
> isBank = false
> (*temporary) = nil
> (*temporary) = <table> {
>  BACKDROP = <table> {
>  }
>  CloseBackpack = <function> defined @AdiBags\core\Hooks.lua:180
>  BAG_INSET = 8
>  SplitSectionKey = <function> defined @AdiBags\core\Utility.lua:238
>  TOP_PADDING = 32
>  hookedBags = <table> {
>  }
>  OpenBag = <function> defined @AdiBags\core\Hooks.lua:137
>  ToggleAllBags = <function> defined @AdiBags\core\Hooks.lua:86
>  GetItemFamily = <function> defined @AdiBags\core\Utility.lua:268
>  GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
>  SECTION_SPACING = 16.333333
>  ToggleBackpack = <function> defined @AdiBags\core\Hooks.lua:195
>  ToggleBag = <function> defined @AdiBags\core\Hooks.lua:156
>  GetContainerFrame = <function> defined @AdiBags\core\Hooks.lua:71
>  CloseAllBags = <function> defined @AdiBags\core\Hooks.lua:119
>  HEADER_SIZE = 18
>  SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
>  CloseSpecialWindows = <function> defined @AdiBags\core\Hooks.lua:208
>  OpenAllBags = <function> defined @AdiBags\core\Hooks.lua:109
>  BuildSectionKey = <function> defined @AdiBags\core\Utility.lua:231
>  GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:188
>  IterateDefinedBags = <function> defined @AdiBags\core\Bags.lua:188
>  L = <table> {
>  }
>  bagPro

**Error 6**

> 2x AdiBags\widgets\ContainerFrame.lua:75: attempt to call global 'LibStub' (a nil value)
> [string "@AdiBags\widgets\ContainerFrame.lua"]:75: in main chunk
> 
> Locals:
> addonName = "AdiBags"
> addon = <table> {
>  RegisterFilter = <function> defined @AdiBags\core\Filters.lua:120
>  BACKDROP = <table> {
>  }
>  CloseBackpack = <function> defined @AdiBags\core\Hooks.lua:180
>  BAG_INSET = 8
>  UpdateFilters = <function> defined @AdiBags\core\Filters.lua:83
>  IterateFilters = <function> defined @AdiBags\core\Filters.lua:116
>  SplitSectionKey = <function> defined @AdiBags\core\Utility.lua:238
>  TOP_PADDING = 32
>  GetPool = <function> defined @AdiBags\core\OO.lua:220
>  ITEM_SPACING = 4
>  hookedBags = <table> {
>  }
>  OpenBag = <function> defined @AdiBags\core\Hooks.lua:137
>  ToggleAnchor = <function> defined @AdiBags\core\Layout.lua:117
>  ToggleAllBags = <function> defined @AdiBags\core\Hooks.lua:86
>  GetItemFamily = <function> defined @AdiBags\core\Utility.lua:268
>  GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
>  SECTION_SPACING = 16.333333
>  ToggleBackpack = <function> defined @AdiBags\core\Hooks.lua:195
>  CompareSectionKeys = <function> defined @AdiBags\core\Utility.lua:246
>  NewClass = <function> defined @AdiBags\core\OO.lua:118
>  ToggleBag = <function> defined @AdiBags\core\Hooks.lua:156
>  GetContainerFrame = <function> defined @AdiBags\core\Hooks.lua:71
>  LayoutBags = <function> defined @AdiBags\core\Layout.lua:102
>  ResetBagPositions = <function> defined @AdiBags\core\Layout.lua:146
>  UpdatePositionMode = <function> defined @AdiBags\core\Layout.lua:125
>  CloseAllBags = <function> defined @AdiBags\core\Hooks.lua:119
>  CreateBagAnchor = <function> defined @AdiBags\core\Layout.lua:33
>  HEADER_SIZE = 18
>  SetupTooltip = <function> defined @AdiBags\core\Utility.lua:114
>  Filter = <function> defined @AdiBags\core\Filters.lua:144
>  OnModuleCreated = <function> defined @AdiBags\core\Filters.lua:135
>  CloseSpecialWindows = <function> defined @AdiBags\core\Hooks.lua:208
>  OpenAllBags = <function> defined @AdiBags\core\Hooks.lua:109
>  BuildSectionKey = <function> defined @AdiBags\core\Utility.lua:231
>  GetDistinctItemID = <function> defined @AdiBags\core\Utility.lua:188
>  InitializeFilters = <function> defined @AdiBags\core\Filters.lua:64
>  filterProto = <table> {
>  }
>  IterateDefinedBags = <function> defined @AdiBags\core\Bags.lua:188
>  L = <table> {
>  }
>  bagProto = <table> {
>  }
>  NewBag = <function> defined @AdiBags\core\Bags.lua:150
>  safecall = <function> defined @AdiBags\core\Utility.lua:81
>  IsJunk = <function> defined @AdiBags\core\Utility.lua:222
>  IterateBags = <function> defined @AdiBags\core\Bags.lua:183
>  OpenBackpack = <function> defined @AdiBags\core\Hooks.lua:168
>  CloseBag = <function> defined @AdiBags\core\Hooks.lua:149
>  BAG_IDS = <table> {
>  }
>  IsSameLinkButLevel = <function> defined @AdiBags\core\Utility.lua:196
>  FAMILY_TAGS = <table> {
>  }
>  ITEM_SIZE = 37
>  DEFAULT_SETTINGS = <table> {
>  }
>  GetFamilyTag = <function> defined @AdiBags\core\Utility.lua:276
>  FAMILY_ICONS = <table> {
>  }
>  IsValidItemLink = <function> defined @AdiBags\core\Utility.lua:151
>  GetClass = <function> defined @AdiBags\core\OO.lua:129
>  CreatePool = <function> defined @AdiBags\core\OO.lua:205
>  GetBagSlotFromId = <function> defined @AdiBags\core\Utility.lua:63
> }
> L = <table> {
>  Reset new items = "Reset new items"
>  Use SyLevel = "Use SyLevel"
>  Bags = "Bags"
>  Bag background = "Bag background"
>  Use this section to define any item-section association. = "Use this section to define any item-section association."
>  Alt-right-click to configure manual filtering. =

**Error 7**

> 2x AdiBags\core\OO.lua:86: attempt to call global 'LibStub' (a nil value)
> [string "@AdiBags\core\OO.lua"]:86: in function <AdiBags\core\OO.lua:64>
> [string "@AdiBags\core\OO.lua"]:110: in function <AdiBags\core\OO.lua:104>
> [string "@AdiBags\core\OO.lua"]:123: in function `NewClass'
> [string "@AdiBags\widgets\BagSlots.lua"]:219: in main chunk
> 
> Locals:
> name = "BagSlotButton"
> parent = <unnamed> {
>  GetItemLocation = <function> defined @FrameXML\ItemButtonTemplate.lua:418
>  SetItem = <function> defined @FrameXML\ItemButtonTemplate.lua:355
>  IconOverlay = <unnamed> {
>  }
>  OnItemContextChanged = <function> defined @FrameXML\ItemButtonTemplate.lua:256
>  showMatchHighlight = true
>  icon = TopIconTexture {
>  }
>  LevelLinkLockTexture = <unnamed> {
>  }
>  PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:269
>  SetItemButtonCount = <function> defined @FrameXML\ItemButtonTemplate.lua:422
>  SetItemInternal = <function> defined @FrameXML\ItemButtonTemplate.lua:360
>  ItemContextOverlay = <unnamed> {
>  }
>  PostOnEvent = <function> defined @FrameXML\ItemButtonTemplate.lua:273
>  GetItemID = <function> defined @FrameXML\ItemButtonTemplate.lua:399
>  SetItemSource = <function> defined @FrameXML\ItemButtonTemplate.lua:339
>  itemContextMatchResult = 3
>  0 = <userdata>
>  IconOverlay2 = <unnamed> {
>  }
>  IconBorder = <unnamed> {
>  }
>  SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:287
>  UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:307
>  PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:260
>  SetItemLocation = <function> defined @FrameXML\ItemButtonTemplate.lua:343
>  GetItemLink = <function> defined @FrameXML\ItemButtonTemplate.lua:414
>  GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:292
>  GetItemInfo = <function> defined @FrameXML\ItemButtonTemplate.lua:386
>  SetAlpha = <function> defined @FrameXML\ItemButtonTemplate.lua:430
>  GetItemButtonCount = <function> defined @FrameXML\ItemButtonTemplate.lua:426
>  Count = TopCount {
>  }
>  UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:296
>  Stock = TopStock {
>  }
>  searchOverlay = TopSearchOverlay {
>  }
>  GetItem = <function> defined @FrameXML\ItemButtonTemplate.lua:410
>  Reset = <function> defined @FrameXML\ItemButtonTemplate.lua:330
> }
> prototype = <table> {
> }
> mixins = <table> {
> }
> class = <table> {
>  metatable = <table> {
>  }
>  name = "BagSlotButton"
>  Create = <function> defined @AdiBags\core\OO.lua:52
>  prototype = <table> {
>  }
>  mixins = <table> {
>  }
>  serial = 0
>  parent = <unnamed> {
>  }
> }
> (for index) = 1
> (for limit) = 1
> (for step) = 1
> i = 1
> name = "ABEvent-1.0"
> (*temporary) = nil
> (*temporary) = "ABEvent-1.0"
> (*temporary) = "attempt to call global 'LibStub' (a nil value)"
> Meta_ToString = <function> defined @AdiBags\core\OO.lua:48
> Class_Create = <function> defined @AdiBags\core\OO.lua:52
> setmetatable = <function> defined =[C]:-1
> select = <function> defined =[C]:-1
> safecall = <function> defined @AdiBags\core\Utility.lua:81
> addon = <table> {
>  RegisterFilter = <function> defined @AdiBags\core\Filters.lua:120
>  BACKDROP = <table> {
>  }
>  CloseBackpack = <function> defined @AdiBags\core\Hooks.lua:180
>  BAG_INSET = 8
>  UpdateFilters = <function> defined @AdiBags\core\Filters.lua:83
>  IterateFilters = <function> defined @AdiBags\core\Filters.lua:116
>  SplitSectionKey = <function> defined @AdiBags\core\Utility.lua:238
>  TOP_PADDING = 32
>  GetPool = <function> defined @AdiBags\core\OO.lua:220
>  ITEM_SPACING = 4
>  hookedBags = <table> {
>  }
>  OpenBag = <function> defined @AdiBags\core\Hooks.lua:137
>  ToggleAnchor = <function> defined @AdiBags\core\Layout.lua:117
>  ToggleAllBags = <function> defined @AdiBags\core\Hooks.lua:86
>  GetItemFamily = <function> defined @AdiBags\core\Utility.lua:268
>  GetSlotId = <function> defined @AdiBags\core\Utility.lua:57
>  SECTION_SPACING = 16.333333
>  ToggleBackpack = <function> defined @AdiBags\core\Hooks.lua:195
>  CompareSectionKeys = <function> defined @AdiBags

**Error 8**

> 6x AdiBags\core\OO.lua:106: attempt to call global 'LibStub' (a nil value)
> [string "@AdiBags\core\OO.lua"]:106: in function <AdiBags\core\OO.lua:104>
> [string "@AdiBags\core\OO.lua"]:123: in function `NewClass'
> [string "@AdiBags\widgets\ItemButton.lua"]:61: in main chunk
> 
> Locals:
> name = "ItemButton"
> frameType = "ItemButton"
> frameTemplate = "ContainerFrameItemButtonTemplate"
> class = nil
> prototype = nil
> parent = nil
> (*temporary) = nil
> (*temporary) = "ContainerFrameItemButtonTemplate"
> (*temporary) = true
> (*temporary) = "attempt to call global 'LibStub' (a nil value)"
> NewClass = <function> defined @AdiBags\core\OO.lua:64
> CreateFrame = <function> defined =[C]:-1

**Error 9**

> 20x (null)

**Comment by Alyred** [comment]
As a question, did you by chance install the nolib version? I'm not a Lua expert but it looks like you're missing some libraries completely...

**Comment by Talyrius** [comment]
Yes, libraries aren't included in the **_nolib_** version. Unless you understand what libraries are and how they function, use the [default download option](https://www.curseforge.com/wow/addons/adibags/download) from [CurseForge](https://www.curseforge.com/wow/addons/adibags/).

**Comment by StryNght** [comment]
I only use curse forge to update my addons and I didn't change anything from the default

**Comment by StryNght** [comment]
It looks like it did download the nolib version. Im not exactly sure how or why though.

**Comment by StryNght** [comment]
![image](https://user-images.githubusercontent.com/80717798/111238796-10a8ba00-85b5-11eb-9386-95edaf5ede95.png)
So I downloaded the correct version and its wanting to update to the nolib

**Comment by Talyrius** [comment]
> Thanks for assuming I changed something and downloaded something that I didn't.

Sorry, but I made no such assumption as I never placed blame.

Make sure that the "Install Libraries Separately" option is unchecked within the CurseForge app (right-click AdiBags):
![image](https://user-images.githubusercontent.com/1068810/111248246-c6c8cf80-85c6-11eb-99d3-9c2174a7676c.png)

Also, verify that the "Library Preference" option is toggled off in the CurseForge app's game specific settings for World of Warcraft:
![image](https://user-images.githubusercontent.com/1068810/111249110-676bbf00-85c8-11eb-8313-be9d0f386e4c.png)

If both options are configured correctly and it's still installing the nolib version, submit a support ticket [here](https://support.curseforge.com/en/support/tickets/new).

**Comment by Shrugster** [comment]
Thank you this fixed my issue.

**Comment by seanawesome** [comment]
This hasn't fixed the problem I've been having with AdiBags. I see it on my addon list in-game, but it doesn't change anything. This addon used to work for me, but I've had to use Bagnon since I reinstalled.
