### ISSUE TITLE
Is this addon still being supported?

### ISSUE THREAD

**Issue by Tykwer** [AdiAddons/AdiBags#56]
Many thanks for all the work that has gone into this addon over the years.  I grew to love it very much, and considered it part of my "must-have" set of addons for WoW.

I'm sad to say that this addon is not stable anymore; there are numerous problems with icon sorting, repeating icons, LUA errors both with and without graphical errors, and multiple /reloads required during a normal play session.

I'm happy to begin collecting and reporting information if the addon is still being supported.  I see the last update was three months ago, and both the Curse and WoWAce comment / ticket systems have been removed.  With this being the last and only choice for support, I expected to see a lot of chatter going on here.  But sadly, I found none when I came here.

If it's dead, that's fine, I just want to know so I can look into other options.  People change, the game changes and perhaps the creators or supporters here just aren't interested anymore - I completely understand that.

The constant /reloads (at least once per toon, per session) are one thing, but the duplicate/incorrect icons are leading me to sell and DE things that I don't want to sell or DE.  I can only utilize Blizzard's item restore feature every 30 days, and I can't be second-guessing what icons I am looking at.

Thanks for your time.

Matt

**Comment by Tykwer** [comment]
I'll add LUA errors here as I come across them.  This error causes the icons to flow off the edge of the frame and overlap, requiring a /reload:

Date: 2015-04-10 01:33:13
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\ContainerFrame.lua line 985:
   AdiBagsSection34:SetPoint(): AdiBagsSection6 is dependent on this
Debug:
   [C]: SetPoint()
   AdiBags\widgets\ContainerFrame.lua:985: LayoutSections()
   AdiBags\widgets\ContainerFrame.lua:1054:
      AdiBags\widgets\ContainerFrame.lua:1030
   (tail call): ?
   AdiBags\widgets\ContainerFrame.lua:394: ?()
   ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147:
      ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147
   [string "safecall Dispatcher[2]"]:4:
      [string "safecall Dispatcher[2]"]:4
   [C]: ?
   [string "safecall Dispatcher[2]"]:13: ?()
   ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: SendMessage()
   AdiBags\core\Core.lua:349: ?()
   ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147:
      ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:92:
      ...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:87
   (tail call): ?
Locals:
None
AddOns:
...

**Comment by Adirelle** [comment]
Hello, I'm asking myself the same question.

I stopped (temporarily) playing WoW three months ago, which greatly reduced my need to maintain my addons. I stepped down in favour of a competent maintainer for AdiButtonAuras, but I found no one for AdiBags.

Even before that, this addon had become so overly complex over its lifetime that updating/fixing it had become a chore instead of a pleasure. Moreover, it has a fairly large user base (something I didn't expect), so every little change to please one half of the users makes the other half complains about it, sometimes angrily. And keeping the old behaviours as options adds to the complexity. If I had to work again on AdiBags, I'd probably throw out the existing code and starts again with a 2.0 version.

For now, I think we can tell AdiBags is dead.

**Comment by Tykwer** [comment]
I really appreciate your response =)

I hope I didn't come across as demanding or being unappreciative; that was not my intention.  My situation was that I knew there were problems with the addon, but everywhere I looked, no one was discussing them.  I suppose I was hoping for the possibility that no one had bothered to report the errors, and I would put something in motion.

Truth be told I will probably still stick with Adibags for a while yet, just doing regular /reloads.  I know I cannot bear to use the default UI for bags.  Bagnon and similar addons are great but don't provide the deep organizational tools that Adibags does.

I don't know what would be involved in opening up the addon for someone else out there to pick it up and continue support (such as what happened with Xperl Unit Frames, which was abandoned, then picked up, modified and now supported as Zperl Unit Frames), nor do I even know if you would be willing to allow this with your intellectual property.  I'm not part of the coding scene, so for all I know, this is possible right now -- I'm not sure what all is involved.

Anyway, thank you again for your time, not only in responding to my inquiry here, but also for all the work over the years.  I'll keep an eye on this addon for a long time still.

Matt
