### ISSUE TITLE
Pawn arrow support please

### ISSUE THREAD

**Issue by strickland** [AdiAddons/AdiBags#560]
I am using the latest version and still the arrow for items which are upgrades are not showing in the item itself, it only shows within the tooltip, I am not sure if someone else created an issue for this, but it has been a very long issue.

**Comment by laseryxa** [comment]
There are a pull request avalibale to fix this. #504 
Why it is not accepted/merged yet is a mystery though...

**Comment by Talyrius** [comment]
See #503.
