### ISSUE TITLE
Issues of the CPU usage

### ISSUE THREAD

**Issue by GnomeTW** [AdiAddons/AdiBags#562]
I use the AddonsCpuUsage in raid to see all the addons cpu usage.
Sometimes the ADIBAGS would use high cpu for some boss, and I didnt open bags in combat.

https://imgur.com/xhIqwJE.jpg

https://imgur.com/LVKSKF2.jpg

In Castle Nathria Raid,
I got **127ms** cpusage for The Council of Blood, and **21ms** for Sire Denathrius.

I don't know what caused it, and I got nothing error report in Bugsack.
Can i do something to improve it? Or this is its normal usage.

**Comment by Talyrius** [comment]
I don't know what would cause that. Make sure you're using the latest alpha release of [Ace3](https://www.wowace.com/projects/ace3/files) with your testing as that's what AdiBags embeds (a smaller subset of individual Ace3 libraries, to be more accurate). If an addon embeds a newer version of any library, they'll get loaded from there and blamed for their CPU usage.
