### ISSUE TITLE
Adibags no longer detected

### ISSUE THREAD

**Issue by rhmiguel** [AdiAddons/AdiBags#563]
Since last reset (Tuesday March 23th), my Adibags has not been working. My bags have returned to default Blizzard bags and when I type "/adibags" nothing happens. A friend of mine also uses Adibags and his works fine, so I'm assuming its something tied to my computer or an interaction with other addons? 

I've tried a coupe things:
- disable all addons except Adibags
- reset WoW UI (https://us.battle.net/support/en/article/7549)

Anyone else experiencing the same thing or have any idea what the issue maybe?

**Comment by SpareSimian** [comment]
Does it show up in the Addons selection screen? That should tell you if the addon is missing a dependency or why it's disabled.

**Comment by Talyrius** [comment]
Are you using the CurseForge app to download and manage your addons? If so, see if [this situation](https://github.com/AdiAddons/AdiBags/issues/559#issuecomment-799847350) applies to you.

**Comment by rhmiguel** [comment]
Yes! It seems that I had the nolib version installed. I've
uninstalled Adibags and made sure to follow the settings listed on that
page. However it looks like only available version to download is the nolib
version? Do you know how I could download it with libraries?

**Comment by rhmiguel** [comment]
disregard last email. I overlooked your comment with the original file on
curseforge. It works, thank you for your help!

**Comment by huzerpro** [comment]
TYVM! This was really helpfull.
