### ISSUE TITLE
Addon shows normal bags in 9.0.5

### ISSUE THREAD

**Issue by StefanFourie** [AdiAddons/AdiBags#564]
It seems that v9.0.5 is not working at all at this point, not sure why. Thought I'd post here in case it is something specific, like maybe a dependency not being listed or something?

REALLY want these bags again, they are literally game-changing for us!

**Comment by Talyrius** [comment]
Are you using the CurseForge app to download and manage your addons? If so, see if [this situation](https://github.com/AdiAddons/AdiBags/issues/559#issuecomment-799847350) applies to you.

**Comment by StefanFourie** [comment]
Enabled LUA errors to see, and it does seem like it is a lib thing >,< Damn

**Comment by StefanFourie** [comment]
Should I download the `AdiBags - Shadowlands` version? Or some other one? Or just grab the libs one by one?

**Comment by StefanFourie** [comment]
I see, you just untick the thing to "install libraries separately", so it installs everything with it... That should be on by default :( Thanks though

**Comment by Talyrius** [comment]
You can also manually select which version to download from within the CurseForge app:
![image](https://user-images.githubusercontent.com/1068810/112763258-8ef35c00-8fb8-11eb-8978-cb29cbd3c4e9.png)
