### ISSUE TITLE
Adibags not sorting items properly on login

### ISSUE THREAD

**Issue by ned406** [AdiAddons/AdiBags#565]
I'm not sure what causes this but when I log into characters and open up my bags for the first time the items are unsorted and the item quality glow doesn't turn on. I have to close the bags then re open them to sort the items

![image](https://user-images.githubusercontent.com/41378787/112986291-38715380-9159-11eb-8a9b-ba53e78ccb73.png)

**Comment by abardill** [comment]
I also have this issue
