### ISSUE TITLE
Lua - Error

### ISSUE THREAD

**Issue by Zwegert** [AdiAddons/AdiBags#567]
1x AdiBags\modules\CurrencyFrame.lua:130: attempt to index global 'CurrencyListInfo' (a nil value)
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Bags.lua"]:132: in function `GetFrame'
[string "@AdiBags\core\Bags.lua"]:83: in function `Open'
[string "@AdiBags\core\Bags.lua"]:210: in function `?'
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Core.lua"]:472: in function `?'
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>

**Comment by Talyrius** [comment]
This error isn't possible using the [latest version](https://www.curseforge.com/wow/addons/adibags/files), so make sure that's what you're using.
