### ISSUE TITLE
Rename herbs

### ISSUE THREAD

**Issue by Dr4fto** [AdiAddons/AdiBags#569]
Hello can you please rename the herbs tab to Herbs (yes with a caps lock) my ocd is killing me here :D thanks!

**Comment by Talyrius** [comment]
If you're using the [item category filter](https://github.com/AdiAddons/AdiBags/blob/abafc316b0052526af131a5649cfd0bae36e1c85/core/DefaultFilters.lua#L289) and it's configured to [split tradeskill items into subcategories](https://github.com/AdiAddons/AdiBags/blob/abafc316b0052526af131a5649cfd0bae36e1c85/core/DefaultFilters.lua#L306), herbs are placed in a section titled "Herb," not "herbs." If you're seeing something different, you're using a custom filter (third-party addon or manually defined override).

**See here:**
![image](https://user-images.githubusercontent.com/1068810/113960876-fcce2d80-97d9-11eb-9fc0-02886ecdf4b2.png)
