### ISSUE TITLE
Error Message LUA / Bug for adibags

### ISSUE THREAD

**Issue by redguar** [AdiAddons/AdiBags#575]
Am I missing a library or something ?
![Screenshot_1](https://user-images.githubusercontent.com/65287246/116625858-57a9ff00-a918-11eb-864f-6ebd26b3acc4.jpg)

**Comment by Talyrius** [comment]
Indeed. You're missing libraries which aren't included in the **_nolib_** version. Unless you understand what libraries are and how they function, use the [default download option](https://www.curseforge.com/wow/addons/adibags/download) from [CurseForge](https://www.curseforge.com/wow/addons/adibags/).

If you're using the [CurseForge app](https://curseforge.overwolf.com/) to download and manage your addons, make sure that the "Install Libraries Separately" option is unchecked (right-click AdiBags):
![image](https://user-images.githubusercontent.com/1068810/111248246-c6c8cf80-85c6-11eb-99d3-9c2174a7676c.png)

Also, verify that the "Library Preference" option is toggled off in the game specific settings for World of Warcraft:
![image](https://user-images.githubusercontent.com/1068810/111249110-676bbf00-85c8-11eb-8313-be9d0f386e4c.png)

If both options are configured correctly and it's still installing the nolib version, submit a support ticket [here](https://support.curseforge.com/en/support/tickets/new).
