### ISSUE TITLE
Keep getting this error message through BugSack

### ISSUE THREAD

**Issue by richyvee** [AdiAddons/AdiBags#576]
Hey, its RichyVee. this is the error code of the bugsack. if you need me to provide anything else feel free to reach out on discord. RichyVee#0369

4x AdiBags\libs\AceDB-3.0\AceDB-3.0-27.lua:372: bad argument #1 to 'pairs' (table expected, got string)
[string "=[C]"]: ?
[string "@AdiBags\libs\AceDB-3.0\AceDB-3.0-27.lua"]:372: in function <AdiBags\libs\AceDB-3.0\AceDB-3.0.lua:359>

Locals:
(*temporary) = "0"
(*temporary) = "table expected, got string"
 = <function> defined =[C]:-1

**Comment by Talyrius** [comment]
🤨

Running the following command should fix it. However, your AdiBags settings will be reset back to default.
`/run AdiBagsDB = nil; ReloadUI()`
