### ISSUE TITLE
Partial Guild Bank [Feature Request]

### ISSUE THREAD

**Issue by luisperezart** [AdiAddons/AdiBags#577]
I'm not asking for full Guild Bank integration.
Is it possible to just have the frames, but not have it effect the position of the items?
I'm having the issue where Adibag overlaps the Guild Bank.
It would be nice if the Guild Bank frame will move along with the Bag frame the way the Bag frame moves with the regular Bank frame.
For now I'm using Move Anything to be able to move the Guild Bank out of the way when needed.

**Comment by Talyrius** [comment]
No, sorry.
