### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by Throwthehammer** [AdiAddons/AdiBags#578]
This happened just out of no where.

Addon list shows adibags, curseforge shows adibags installed, however with all addons disabled except adibags, blizard bag UIs still launch instead of adibags. /Adibags also shows invalid command. 

Please help! Life is so diferent without adibags!

**Comment by Wanny** [comment]
I just checked the configuration in the CurseForge client and they're JUST like the screenshots. 

![image](https://user-images.githubusercontent.com/569307/120819395-891e7780-c521-11eb-8d9c-7fb36b714a95.png)

Why are the errors happening now, while the previous version was working fine?

**Comment by Talyrius** [comment]
**@Wanny:**
I was mistaken; your issue is unrelated. Please see my latest [comment](https://github.com/AdiAddons/AdiBags/issues/582#issuecomment-855161618) on #582.
