### ISSUE TITLE
Anchor resets when using SurroundFix

### ISSUE THREAD

**Issue by Argentum771** [AdiAddons/AdiBags#579]
When using the SurroundFix addon to bring UI frames closer to the center (I'm using it for my Ultrawide), AdiBag's anchor keeps resetting to the far right side of the screen.  If I enable the anchor point to move it, when I finish moving it to my desired location it snaps back to the right side of the screen.

I have recorded video of the bug occurring and can recreate the issue with only AdiBags and SurroundFix on.

**Comment by Talyrius** [comment]
This is an unsupported use case.
