### ISSUE TITLE
Sort (S+N) Keybinding

### ISSUE THREAD

**Issue by TripleEYE** [AdiAddons/AdiBags#58]
I was looking for a way to make a macro or at least a keybind to Sort Bags (Blizzard's Sort a.k.a. Adibags S button) And to Reset Recent Items (Adibags N button).

I tried using "/fstack" to find the names of the buttons so I can make the "/click AdiBagsContainer1SortButton" (or N button), but had no success. Whatever button names I found were long, number+letter coded, made no language-logic to a simple user like me, and most importantly, didn't work on a "/click" macro command.

Is there, or can you please add. a way to macro "/click AdiBagsSort" & "/click AdiBagsNew"?
Or at least add Keybing functions on the Addon Keybinds Panel for Sort, for New, and for both of them at once?

Thank you, 
TripleEYE

**Comment by rodalpho** [comment]
I would like to request this too. I very frequently get hit with the bug where ALL my items go to recent items, and the top of the window is off the top of my screen, so I have no way to hit the "reset new items" button. Would love to keybind it.

**Comment by smb** [comment]
Try /script SortBags()
