### ISSUE TITLE
TBC Classic support please

### ISSUE THREAD

**Issue by GregoryGH** [AdiAddons/AdiBags#580]

**Comment by fastorro** [comment]
pls !!!

**Comment by ConnorJBeck** [comment]
Indeed, I tested on the PTR before prepatch started and bags did not even open. Support here would be amazing.

**Comment by Litholin** [comment]
bump

**Comment by hyperart** [comment]
Yes, please!

**Comment by polarvogel** [comment]
This pull request works fine, isntall it manually: https://github.com/Talryn/AdiBags/tree/tbc

**Comment by pbjtime** [comment]
tbc branch doesnt seem to work..

**Comment by SapMagic** [comment]
+1, downloaded that branch. I see the addon in WoW, it doesn't seem to do anything when I load into the game.

**Comment by vekvoid** [comment]
I copied the libs from AdiBags-v1.9.20 into the branch libs and now it works for me.

**Comment by SapMagic** [comment]
Great suggestion. Ok, recapping, this is what works:

- Download the branch from https://github.com/Talryn/AdiBags/tree/tbc as a zip file
- Unzip it
- Rename the folder to `AdiBags` and put it in your addons folder
- Copy the entirety of the `libs` folder from an existing installation, overwriting the (empty) one from the new version

After that, it seems to load and work properly for me.

**Comment by Mitch3llO01** [comment]
> I copied the libs from AdiBags-v1.9.20 into the branch libs and now it works for me.



> Great suggestion. Ok, recapping, this is what works:
> 
> * Download the branch from https://github.com/Talryn/AdiBags/tree/tbc as a zip file
> * Unzip it
> * Rename the folder to `AdiBags` and put it in your addons folder
> * Copy the entirety of the `libs` folder from an existing installation, overwriting the (empty) one from the new version
> 
> After that, it seems to load and work properly for me.

This worked for me. Thank you very much. Hopefully this can be fixed in Curseforge sooner or later so my Cursebreaker can pick it up. Good enough for now!

**Comment by d4kir92** [comment]
hope it gets updated soon :D

**Comment by timss** [comment]
The ElvUI AdiBags fork(?) has a release working for TBC now. It also works if you don't use ElvUI.

https://www.curseforge.com/wow/addons/elvui-adibags

**Comment by Buttonz52** [comment]
Tried the above link for TBC adibags and still no success.
https://www.curseforge.com/wow/addons/elvui-adibags
in the Interface > Addons >AdiBags menu.. licking Configure does nothing

**Comment by henkethebenke** [comment]
+1

**Comment by celixftw** [comment]
> The ElvUI AdiBags fork(?) has a release working for TBC now. It also works if you don't use ElvUI.
> 
> https://www.curseforge.com/wow/addons/elvui-adibags

How you van use it without ElvUI?
After joining the world, he asks to use ElvUi or KlixUI.
Could not find a way zo use it without

thanks

**Comment by timss** [comment]
@celixftw Seems like you downloaded the retail version, not the one for TBC. Here's the latest working version, it works out of the box even without ElvUI.

https://www.curseforge.com/wow/addons/elvui-adibags/files/3315512

**Comment by Zyin055** [comment]
> Great suggestion. Ok, recapping, this is what works:
> 
> * Download the branch from https://github.com/Talryn/AdiBags/tree/tbc as a zip file
> * Unzip it
> * Rename the folder to `AdiBags` and put it in your addons folder
> * Copy the entirety of the `libs` folder from an existing installation, overwriting the (empty) one from the new version
> 
> After that, it seems to load and work properly for me.

I LOVE YOU

**Comment by KonstantinosKoubetsos** [comment]
Pull request works but we still need to have the proper channels for auto updating in addon managers.
Can change Interface: 11304 to Interface: 20501 but theres not corresponding bcc version here in curseforge and it shows as ignored in WoWUp
