### ISSUE TITLE
Lua errors on log-in after update

### ISSUE THREAD

**Issue by Wanny** [AdiAddons/AdiBags#582]

**Comment by Talyrius** [comment]
See #578.

**Comment by Wanny** [comment]
I'll reopen this because AdiBags was working perfectly until last night without any errors.

I updated AdiBags to the latest version with the Curseforge client and now I'm getting the following Lua erros after logging into the game:

```Message: Interface\AddOns\AdiBags\core\Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.
Time: Fri Jun  4 10:09:11 2021
Count: 1
Stack: Interface\AddOns\AdiBags\core\Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:239: in function `NewModule'
[string "@Interface\AddOns\AdiBags\core\Filters.lua"]:126: in function `RegisterFilter'
[string "@Interface\AddOns\AdiBags_Bound\AdiBags_Bound.lua"]:52: in main chunk

Locals: (*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists."
```

```
Message: ...rface\AddOns\AdiBags_Legion_Filters\Localization.lua:11: attempt to call global 'GetCurrencyInfo' (a nil value)
Time: Fri Jun  4 10:09:11 2021
Count: 1
Stack: ...rface\AddOns\AdiBags_Legion_Filters\Localization.lua:11: attempt to call global 'GetCurrencyInfo' (a nil value)
[string "@Interface\AddOns\AdiBags_Legion_Filters\Localization.lua"]:11: in main chunk

Locals: AddonName = "AdiBags_Legion_Filters"
AddonTable = <table> {
 L = <table> {
 }
}
L = <table> {
 Put items from Legion in their own sections. = true
 Legion = "Legion"
 Artifact Power = "Poder de artefacto"
}
locale = "esMX"
(*temporary) = nil
(*temporary) = 1155
(*temporary) = "attempt to call global 'GetCurrencyInfo' (a nil value)"
```

```
Message: ...ns\AdiBags_Legion_Filters\AdiBags_Legion_Filters.lua:15: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jun  4 10:09:11 2021
Count: 1
Stack: ...ns\AdiBags_Legion_Filters\AdiBags_Legion_Filters.lua:15: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface\AddOns\AdiBags_Legion_Filters\AdiBags_Legion_Filters.lua"]:15: in main chunk

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
```

```
Message: ...Ons\AdiBags_Legion_Filters\Artifact_Power_Plugin.lua:15: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri Jun  4 10:09:11 2021
Count: 1
Stack: ...Ons\AdiBags_Legion_Filters\Artifact_Power_Plugin.lua:15: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface\AddOns\AdiBags_Legion_Filters\Artifact_Power_Plugin.lua"]:15: in main chunk

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1
```

```
Message: ...s\AdiBags_Legion_Filters\Artifact_Power_Currency.lua:15: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - string expected got 'nil'.
Time: Fri Jun  4 10:09:11 2021
Count: 1
Stack: ...s\AdiBags_Legion_Filters\Artifact_Power_Currency.lua:15: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - string expected got 'nil'.
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:236: in function `NewModule'
[string "@Interface\AddOns\AdiBags_Legion_Filters\Artifact_Power_Currency.lua"]:15: in main chunk

Locals: (*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - string expected got 'nil'."
```

```
Message: (null)
Time: Fri Jun  4 10:09:26 2021
Count: 15
```

It's clearly related to the [AdiBags - Legion Filters](https://www.curseforge.com/wow/addons/adibags-legion-filters) addon... but what could be different now? that Legion filters addon hasn't been changed.

**Comment by Talyrius** [comment]
https://github.com/AdiAddons/AdiBags/issues/578#issuecomment-854781574:
> I just checked the configuration in the CurseForge client and they're JUST like the screenshots.
> 
> ![image](https://user-images.githubusercontent.com/569307/120819395-891e7780-c521-11eb-8d9c-7fb36b714a95.png)
> 
> Why are the errors happening now, while the previous version was working fine?
> 
> EDIT: ALSO, it's not that the addon isn't working. It's just the Lua errors appearing at log-on as I mention in the ticket I opened (that Talyrius closed **twice**)

Your ticket was never reopened. Therefore, it hadn't been closed **_twice_**.

You're right, your issue is unrelated to the one I previously referenced. However, your initial comment provided no information to the contrary.

> It's clearly related to the [AdiBags - Legion Filters](https://www.curseforge.com/wow/addons/adibags-legion-filters) addon... but what could be different now? that Legion filters addon hasn't been changed.

Yes, and if you read the comments there, you'll find that that addon has been broken for quite some time. What changed is that I disembedded BugGrabber (abafc316b0052526af131a5649cfd0bae36e1c85) from the latest version which was suppressing these errors unless you had [BugSack](https://www.curseforge.com/wow/addons/bugsack) installed to display them (#266).

> `Stack: Interface\AddOns\AdiBags\core\Filters.lua:126: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Bound' already exists.`
This specific error is due to conflicting module names being used by other AdiBags addons. I suggest you remove one of them.

**Comment by Wanny** [comment]
Huh, I could've sworn I saw the "open" text when I posted the 2nd comment. And, well, it was indeed my bad that I pressed Enter after writing the issue title, not expecting the issue to be posted without any description...

> What changed is that I disembedded BugGrabber (abafc31) from the latest version which was suppressing these errors unless you had BugSack installed to display them (#266).

And... oh, that explains why I'm now getting the errors. I'll see how can I fix that Legion Filters addon myself (because I doubt the author will do at this point)
