### ISSUE TITLE
Feature Request: Move low-level food/beverages to junk category

### ISSUE THREAD

**Issue by stiffsen** [AdiAddons/AdiBags#584]
I frequently have to go through my consumeables to sell or destroy low-level food and beverages. It would be briliant if adibags were capable of automatically moving those items to the junk category, so they can be quickly sold or destroyed.

**Comment by SpareSimian** [comment]
Just drag them to the Junk area (drop the item on the word "junk") and AdiBags will remember your preference. I do that with stuff I never want to keep. The manual filtering feature is wonderful for this. For example, I have a category Consumable/Containers for all the locked boxes and reward chests I get. I have tons of manual customization that makes life so much easier with lots of alts.

**Comment by stiffsen** [comment]
Oh thanks a bunch. I wasn't aware that you can actually move objects to another category right in your inventory. That makes things a lot easier!
