### ISSUE TITLE
TBC - couple of lua errors

### ISSUE THREAD

**Issue by InfernalDark** [AdiAddons/AdiBags#585]
Message: Interface\FrameXML\UIPanelTemplates.lua:28: attempt to call method 'GetText' (a nil value)
Time: Tue Jun  8 00:04:29 2021
Count: 2
Stack: Interface\FrameXML\UIPanelTemplates.lua:28: attempt to call method 'GetText' (a nil value)
[string "@Interface\FrameXML\UIPanelTemplates.lua"]:28: in function <Interface\FrameXML\UIPanelTemplates.lua:23>

Locals: self = AdiBagsContainer1SearchBox {
 0 = <userdata>
 Left = <unnamed> {
 }
 searchIcon = AdiBagsContainer1SearchBoxSearchIcon {
 }
 Instructions = <unnamed> {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 clearButton = AdiBagsContainer1SearchBoxClearButton {
 }
}
userChanged = false
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "BagItemSearchBox"
 2 = "GuildItemSearchBox"
 3 = "VoidItemSearchBox"
 4 = "BankItemSearchBox"
 5 = "AdiBagsContainer1SearchBox"
}
(for control) = 1
_ = 1
barName = "BagItemSearchBox"
bar = <unnamed> {
 Show = <function> defined @Interface\AddOns\bdUI\core\core.lua:156
 overlay = <unnamed> {
 }
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 Show = <function> defined @Interface\AddOns\bdUI\core\core.lua:156
 overlay = <unnamed> {
 }
 0 = <userdata>
}
(*temporary) = "attempt to call method 'GetText' (a nil value)"

Message: Interface\FrameXML\UIPanelTemplates.lua:28: attempt to call method 'GetText' (a nil value)
Time: Tue Jun  8 00:14:07 2021
Count: 3
Stack: Interface\FrameXML\UIPanelTemplates.lua:28: attempt to call method 'GetText' (a nil value)
[string "@Interface\FrameXML\UIPanelTemplates.lua"]:28: in function `BagSearch_OnTextChanged'
[string "@Interface\FrameXML\UIPanelTemplates.lua"]:19: in function <Interface\FrameXML\UIPanelTemplates.lua:9>
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@Interface\AddOns\AdiBags\core\Bags.lua"]:98: in function `Close'
[string "@Interface\AddOns\AdiBags\core\Bags.lua"]:117: in function <Interface\AddOns\AdiBags\core\Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals: self = AdiBagsContainer1SearchBox {
 0 = <userdata>
 Left = <unnamed> {
 }
 searchIcon = AdiBagsContainer1SearchBoxSearchIcon {
 }
 Instructions = <unnamed> {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 clearButton = AdiBagsContainer1SearchBoxClearButton {
 }
}
userChanged = nil
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "BagItemSearchBox"
 2 = "GuildItemSearchBox"
 3 = "VoidItemSearchBox"
 4 = "BankItemSearchBox"
 5 = "AdiBagsContainer1SearchBox"
}
(for control) = 1
_ = 1
barName = "BagItemSearchBox"
bar = <unnamed> {
 Show = <function> defined @Interface\AddOns\bdUI\core\core.lua:156
 overlay = <unnamed> {
 }
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 Show = <function> defined @Interface\AddOns\bdUI\core\core.lua:156
 overlay = <unnamed> {
 }
 0 = <userdata>
}
(*temporary) = "attempt to call method 'GetText' (a nil value)"

**Comment by Talyrius** [comment]
AdiBags isn't at fault for these errors. Try disabling addons in groups until the error goes away and then reenable them one by one them until it returns to identify the addon responsible.
