### ISSUE TITLE
TBC Version does not have Keyring

### ISSUE THREAD

**Issue by raynaldNathanael** [AdiAddons/AdiBags#586]
TBC Version of Adibags does not have keyring, have to turn off addon in order to check keyring. Please add this feature so i can enjoy then game again as Adibags is the only addon anyone really ever needs.

**Comment by Reudig** [comment]
yep, has been that way in classic before - very annoying :(

**Comment by arthurEspooner** [comment]
yep, super annoying. this addon also has conflicts with lots of others and barely works in TBC classic. checkout BagAnon, works way better but lacks the main selling point of this one which is the sorting :(

**Comment by Reudig** [comment]
actually the sorting works very well. and apart from Adibags I hardly use any other addons, apart from ElvUI. So far it has worked great, but as mentioned: not being able to see the keyring sux ...

**Comment by silverhawke249** [comment]
currently my workaround is to just type `/run ToggleBag(-2)` whenever i need to see the keyring... but that's dumb :P 

i don't know how to write additional modules for AdiBags, but i feel like you can sneak in a button here to toggle the keyring, or something like that...
![image](https://user-images.githubusercontent.com/50395934/122247719-23a39100-cefa-11eb-836e-a7384b45ca0c.png)
