### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by GregoryGH** [AdiAddons/AdiBags#592]
Sometimes get errors like that

2x AdiBags\widgets\ContainerFrame.lua:898: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: AdiBagsSection5:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@AdiBags\widgets\ContainerFrame.lua"]:898: in function `LayoutSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:969: in function <AdiBags\widgets\ContainerFrame.lua:943>
[string "=(tail call)"]: ?
[string "@AdiBags\widgets\ContainerFrame.lua"]:370: in function `RefreshContents'
[string "@AdiBags\widgets\ContainerFrame.lua"]:355: in function `ResumeUpdates'
[string "@AdiBags\widgets\ContainerFrame.lua"]:338: in function <AdiBags\widgets\ContainerFrame.lua:332>
[string "=[C]"]: in function `Show'
[string "@AdiBags\core\Bags.lua"]:89: in function `Open'
[string "@AdiBags\core\Bags.lua"]:119: in function <AdiBags\core\Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

**Comment by trinidadr** [comment]
Turn off the ilevel plugin
/adibags
> plugins > item level

**Comment by GregoryGH** [comment]
Already not enabled and it is kinda strange way to "fix" errors.
