### ISSUE TITLE
PTR classic 2.5.2

### ISSUE THREAD

**Issue by CKNOEP** [AdiAddons/AdiBags#599]
hello 
a lot of lua error withe the definition with the PTR
local MISCELLANEOUS = GetItemClassInfo(LE_ITEM_CLASS_MISCELLANEOUS)
I use french client 
if i substitue le litteral withe the number , the problem disappears.
ex : local MISCELLANEOUS = GetItemClassInfo(15)

**Comment by Talyrius** [comment]
Is this still happening for you on live? I'm not receiving any errors.
