### ISSUE TITLE
Words need to be localized

### ISSUE THREAD

**Issue by class2u** [AdiAddons/AdiBags#60]
The following words in enUS = zhTW pairs need to be imported into wowace localization for AdiBags 1.8.4 :

L["AdiBags"] = "Adi智能背包"
L['Automatically...'] = "自動..."
L["Open"] = "打開背包"
L["Deposit reagents"] = "存放材料"
L["Automtically deposit all reagents into the reagent bank when you talk to the banker."] = "與銀行員對話時，自動將所有材料存放至材料銀行。"
L["Configure"] = "設定"
L['Position & size'] = "位置 & 大小"
L['Section layout'] = "版面區塊配置"
L['Compact layout'] = "精簡版面"
L['Reagent bank color'] = "材料銀行顏色"

**Comment by Cidan** [comment]
Please update these here:

http://www.wowace.com/addons/adibags/localization/
