### ISSUE TITLE
need to support Guild bank 2.5.2

### ISSUE THREAD

**Issue by SunnyJang38** [AdiAddons/AdiBags#600]
need to support Guild bank 2.5.2 tbcc

**Comment by Talyrius** [comment]
Guild banks have never been supported in AdiBags:
> ### _Guild Bank_
> _AdiBags presents you a nice view of your bags but actually they are in a complete mess. With AdiBags, there is no need and no way to tidy up the items in the actual bags. Guilds usually try to keep their bank tidy. What would happen if some people in a guild used AdiBags for the guild bank ? Well, they would mess up the guild bank content and people NOT using AdiBags would have to deal with that mess. I can hear the screams from there. So that is why I will not implement guild bank._
