### ISSUE TITLE
AddOn 'AdiBags' tried to call the protected function 'GuildControlSetRank()'.

### ISSUE THREAD

**Issue by Jakobud** [AdiAddons/AdiBags#601]
Lately when interacting with the guild tab, I am getting this error

```
2x [ADDON_ACTION_FORBIDDEN] AddOn 'AdiBags' tried to call the protected function 'GuildControlSetRank()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GuildControlSetRank'
[string "@Interface_TBC\FrameXML\FriendsFrame.lua"]:2756: in function `GuildControlPopupFrameDropDownButton_ClickedRank'
[string "@Interface_TBC\FrameXML\FriendsFrame.lua"]:2508: in function `GuildControlPopupFrame_Initialize'
[string "@Interface_TBC\FrameXML\FriendsFrame.lua"]:966: in function `FriendsFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
[string "=[C]"]: in function `SortGuildRoster'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>
```

**Comment by Talyrius** [comment]
This was caused by [taint](https://www.townlong-yak.com/taint.log/about.html) incorrectly blamed on AdiBags. AdiBags makes use of several libraries shared by other addons and as addons are generally loaded alphabetically, AdiBags often loads first and taint caused by other addons using these libraries gets misattributed.

**Comment by Jakobud** [comment]
Dang I was suspecting that. That seems like one of the very poorly design aspects of Wowace's shared libraries. How do I determine which addon is causing this?

**Comment by Talyrius** [comment]
Find a way to reproduce it and then disable addons in batches until it no longer occurs. Once that's happened, reenable the addons you disabled in the last batch one by one until the problem returns.
