### ISSUE TITLE
Anyway to filter items bought from vendor? Crafting Reagents

### ISSUE THREAD

**Issue by acps87** [AdiAddons/AdiBags#609]
Is there anyway to filter any item that could be bought from a vendor, specifically crafting reagents that are super cheap and only cost a few g but are needed to craft with most professions?

**Comment by SpareSimian** [comment]
Learn how to use the manual filter? I have a ton of manual filters for things like this.

**Comment by Talyrius** [comment]
Yes, see [AdiBags_PT3Filter](https://www.curseforge.com/wow/addons/adibags-pt3filter).
