### ISSUE TITLE
Blank space to the right since patch 6.2

### ISSUE THREAD

**Issue by nanrector** [AdiAddons/AdiBags#61]
My bags have a huge blank space to the right since the patch. No matter how many rows or columns it stays there. Any ideas?  Here's a screenshot. 

Thanks!
Nancy
![screenshot100 jul 21 10 05](https://cloud.githubusercontent.com/assets/13437068/8804217/b3268554-2f90-11e5-99a8-f6f2012163e6.png)

**Comment by Syllean** [comment]
It's because of all the currencies that you're tracking on the bottom of your bag. Disable some of the currencies and your bag won't be so wide.

**Comment by nanrector** [comment]
ahhh... thanks so much!
