### ISSUE TITLE
New 'Adibags has been blocked from an action only available to the Blizzard UI' issue.

### ISSUE THREAD

**Issue by DiscordianKitty** [AdiAddons/AdiBags#613]
This issue occurs when attempting to link an outfit with the new transmog ui.

![WoWScrnShot_110521_034823](https://user-images.githubusercontent.com/93753406/140455914-42325328-8cec-4e34-8f1b-e6fc803140a0.jpg)
![WoWScrnShot_110521_034828](https://user-images.githubusercontent.com/93753406/140455954-08b750cb-cc25-4347-80e6-e406f58a54ff.jpg)

**Comment by Talyrius** [comment]
Disable all of your addons except for AdiBags and AdiBags Configuration. If the error goes away, the issue is caused by taint from another addon that makes use of the same shared libraries.
