### ISSUE TITLE
Classic Era - Cant open bags

### ISSUE THREAD

**Issue by celixftw** [AdiAddons/AdiBags#614]
Hi,

the addon is not working in Classic Era anymore.
I cant open my bags, even when deactivating all other addons.

**Comment by celixftw** [comment]
the tbc version is working for me

**Comment by ButteredGroove** [comment]
But it's not working in Classic Season of Mastery, aka Classic Era.

**Comment by MrVining** [comment]
I have this issue as well. Is there a work around for it that anyone has found?
