### ISSUE TITLE
Item Upgrade Fails.

### ISSUE THREAD

**Issue by Mrunderwonder** [AdiAddons/AdiBags#615]
Get the following error when upgrading items and the item upgrade fails. Buggrabber says adibags and asks to disable. Not sure its actually true though. If I reenable and reload I can upgrade just fine with adibags on. Thought I would post here anyway just in case. 
```
[ADDON_ACTION_FORBIDDEN] AddOn 'AdiBags' tried to call the protected function 'UpgradeItem()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `UpgradeItem'
[string "@Blizzard_ItemUpgradeUI\Blizzard_ItemUpgradeUI.lua"]:104: in function `OnConfirm'
[string "@FrameXML\StaticPopup.lua"]:325: in function `OnAccept'
[string "@FrameXML\StaticPopup.lua"]:5137: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

**Comment by Talyrius** [comment]
Yeah, AdiBags likely isn't at fault here. It uses several libraries that are shared among many other addons and because they're loaded alphabetically, it often gets falsely blamed for the taint introduced by these other addons.
