### ISSUE TITLE
Classic Era (Season of Mastery) - Fails to open bags

### ISSUE THREAD

**Issue by Haymz** [AdiAddons/AdiBags#616]
Adibags errors on login and then does not display any bags in the Classic Era (Season of Mastery) client. Error below:

2x AdiBags\core\Layout.lua:61: attempt to index field 'anchor' (a nil value)
[string "@AdiBags\core\Layout.lua"]:61: in function <AdiBags\core\Layout.lua:60>
[string "@AdiBags\core\Layout.lua"]:109: in function `LayoutBags'
[string "@AdiBags\core\Layout.lua"]:128: in function `UpdatePositionMode'
[string "@AdiBags\core\Core.lua"]:165: in function <AdiBags\core\Core.lua:115>
[string "=[C]"]: ?
[string "@ElvUI\Core\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...UI\Core\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@ElvUI\Core\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@ElvUI\Core\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...UI\Core\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Haymz** [comment]
As per a user comment on another issue, the BCC version (1.9.26-bcc) works in game for me.

**Comment by Qwexx123** [comment]
Chances of getting any reaction to this issue? 
Damn did i get used to adibags, cant play anymore without....

**Comment by iambryan0** [comment]
still having this issue.
