### ISSUE TITLE
Category tooltip is fixed while item tooltip is dynamic

### ISSUE THREAD

**Issue by linaori** [AdiAddons/AdiBags#619]
This recording illustrates the issue best; Would be awesome if both tooltips would have the same setting 😄 

https://user-images.githubusercontent.com/1754678/144111330-96318234-3765-4f14-b932-a78df9c7e187.mp4

**Comment by Talyrius** [comment]
AdiBags doesn't control the anchoring of item tooltips. However, this can be achieved with tooltip specific addons.
