### ISSUE TITLE
Enhancement: Support TSM Groups

### ISSUE THREAD

**Issue by Irayna** [AdiAddons/AdiBags#62]
I think it would be awesome if the add on, or a separate plugin, could support TSM groups similar to how the outfitter one works. Right now I'm creating manual groups that just mimic the TSM groups for some characters, so I'm basically doing twice the work... Setting up the TSM group and then setting up the manual filtering. I would love it if I could check a box and it would use that for group creation instead.

**Comment by copystring** [comment]
How can I upvote this? This would be very nice to have

**Comment by mrdeadlocked** [comment]
This would be great!

**Comment by seirl** [comment]
I wrote the plugin you wanted! 

https://github.com/seirl/AdiBags_TSM

https://wow.curseforge.com/projects/adibags_tsm
