### ISSUE TITLE
wont open in Classic ERA

### ISSUE THREAD

**Issue by WoWEye** [AdiAddons/AdiBags#621]
i log in and get these errors.

Date: 2021-12-04 12:16:37
ID: -13
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\widgets\AnchorWidget.lua line 65:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@AdiBags\core\OO.lua"]:60:
      AdiBags\core\OO.lua:52
   [string "=(tail call)"]: ?
   [string "@AdiBags\core\Layout.lua"]:34: CreateBagAnchor()
   [string "@AdiBags\core\Core.lua"]:98:
      AdiBags\core\Core.lua:81
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:498: InitializeAddon()
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:623:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:615
Locals:
None
AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  Ace3, vr1253
  AdiBags, vv1.9.20-classic
  BlizRuntimeLib_enUS v1.14.1.11401 <none>
  (ck=80)

and this one, gives many with different  layout errors: lines 61, 37, 171,
Date: 2021-12-04 12:16:37
ID: -12
Error occured in: Global
Count: 1
Message: ..\AddOns\AdiBags\core\Layout.lua line 37:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "@AdiBags\core\Layout.lua"]:37: CreateBagAnchor()
   [string "@AdiBags\core\Core.lua"]:98:
      AdiBags\core\Core.lua:81
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:498: InitializeAddon()
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:623:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:615
Locals:
None
AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  Ace3, vr1253
  AdiBags, vv1.9.20-classic
  BlizRuntimeLib_enUS v1.14.1.11401 <none>
  (ck=80)

**Comment by timss** [comment]
Try v1.9.26-bcc. Works for me in SoM.

https://www.curseforge.com/wow/addons/adibags/files/3460625

**Comment by Qwexx123** [comment]
It actually works! Great, tyvm @timss

**Comment by d4kir92** [comment]
please fix it for wow classic SoM

**Comment by timss** [comment]
@d4kir92 Please see my previous comment. That one does work for SoM.
