### ISSUE TITLE
ElvUI / KlixUI ?

### ISSUE THREAD

**Issue by Dracorosa** [AdiAddons/AdiBags#622]
Why is it demanding elvui or klixui addon be loaded?
![WoWScrnShot_122121_124003](https://user-images.githubusercontent.com/96493143/146975062-dcf475dc-ada4-4595-a3cc-e592d0b7f9ea.jpg)

**Comment by Talyrius** [comment]
The official distribution of [AdiBags](https://www.curseforge.com/wow/addons/adibags) does not do this. If you've made sure that's what you're using, it may be a separate addon that is attempting to skin AdiBags. Review what addons you've installed.
