### ISSUE TITLE
Intermittent Error on Visiting Vendor

### ISSUE THREAD

**Issue by Lissard** [AdiAddons/AdiBags#623]
Retail addon version 1.9.26

Error text: https://pastebin.com/53cgkNx6

This is an intermittent error when visiting a vendor.  It doesn't happen every time, but usually at least 3 or 4 times per session.  Once the error occurs it then reoccurs every time on opening bags (Whether at a vendor or not) until a /reload.

Also when it happens it visually messes up the bag frame as well (https://i.imgur.com/UKisXxS.png).  The screenshot isn't great unfortunately as I don't have a lot in my bags at the moment.  When your bags are fuller the different sections & bag slots go out of the bag frame and cascade downwards off the screen.

**Comment by Theonidus17** [comment]
I've had a similar problem with Adibags for the last few weeks. It would bug out almost every time when visiting a vendor. After doing some trial and error it looked like the 'MoveAnything' addon was the culprit, I first disabled MoveAnything and AdiBags finally worked, but then I learned you could just disable the Adibags mover in MoveAnything, so you could still keep both addons. Hope this works for you!
