### ISSUE TITLE
Feature Request: Add releases for 3rd party addon manager support

### ISSUE THREAD

**Issue by mgejo** [AdiAddons/AdiBags#625]
With the coming [CurseForge API changes](https://mailchi.mp/overwolf/whats-new-with-overwolf-curseforge-november3), 3rd party addon managers won't be able to pull from CF. [Cursebreaker](https://github.com/AcidWeb/CurseBreaker/issues/325) and [Ajour](https://github.com/ajour/ajour/issues/746) have officially thrown the towel because of this.

Some addon managers like [WowUp](https://wowup.io/) and [instawow](https://github.com/layday/instawow) can handle pulling from github, but only from releases, not source. Moreover, instawow [requires a mapping](https://github.com/layday/instawow#github) in a `release.json` file.

Can this be added to the project?

**Comment by Cidan** [comment]
This is coming in #633, will try to get this out the door soon(tm). Closing this issue.
