### ISSUE TITLE
Size BUG

### ISSUE THREAD

**Issue by Coremassive** [AdiAddons/AdiBags#627]
Iam changing the column width to get a smaller inventory and it simply doesnt work. Bcos the window size of inventory is straight from left to right corner of the screen. Means that I have massive blank black space covering game interface.
Windows 10. Monitor 3440x1440. Playing in window mode.

**Comment by Talyrius** [comment]
Please share a screenshot.

**Comment by Gypsykittens** [comment]
I have the same issue.  I really like this addon but right now it takes up the majority of a screen.
![image](https://user-images.githubusercontent.com/100890578/156687914-d4797b18-e8cc-4a67-9da0-6d1d2920ad43.png)

**Comment by Talyrius** [comment]
Yes, if you're tracking a lot of currencies, it's forced to expand horizontally.

**Comment by Coremassive** [comment]
Thank u, will try to fix it
