### ISSUE TITLE
bugsack error

### ISSUE THREAD

**Issue by matton300** [AdiAddons/AdiBags#628]
i'm getting this error

30x AdiBags_ZerethMortis\AdiBags_ZerethMortis-1.1.0.lua:235: attempt to index field 'items' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags\core\Filters-Filters.lua"]:146: in function `Filter'
[string "@AdiBags\widgets\ContainerFrame.lua"]:718: in function `FilterSlot'
[string "@AdiBags\widgets\ContainerFrame.lua"]:752: in function `DispatchItem'
[string "@AdiBags\widgets\ContainerFrame.lua"]:913: in function `RedispatchAllItems'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1056: in function `FullUpdate'
[string "@AdiBags\widgets\ContainerFrame.lua"]:565: in function <AdiBags\widgets\ContainerFrame.lua:551>
[string "=[C]"]: ?
[string "@AdiBags\core\Utility.lua"]:89: in function <AdiBags\core\Utility.lua:81>
[string "@AdiBags\widgets\LayeredRegion.lua"]:119: in function <AdiBags\widgets\LayeredRegion.lua:108>

**Comment by Talyrius** [comment]
Sorry, but **AdiBags_ZerethMortis** is a third-party addon and that's what's responsible for your errors.
