### ISSUE TITLE
Item Categories sometimes don't load, all items "Misc"

### ISSUE THREAD

**Issue by Stefen74** [AdiAddons/AdiBags#629]
Hi all,

When I open my bank, I'm often met by this ...
![Bank](https://user-images.githubusercontent.com/78644640/160108464-06ba01d5-2855-4a77-85f5-61277ce08308.jpg)

The bank window is out the top of the screen, it can't be moved or reset using the 'N' button. If I press ESC to close it, and then re-open it, this can sometimes solve it, but it can also make it vanish altogether, when it does this I just presume it's now outside the screen somewhere. From here the only way to get it back is to reset the window positions and sizes from the settings.

My only thought is that by bank might be a bit big slot number wise? Other then that I have no idea.

Anyone?

Thank you in advance.

**Comment by Stefen74** [comment]
After a /reload the top is now back on screen. To me it seems the issue is that the addon is displaying everything downwards and not across ... 

![Bank2](https://user-images.githubusercontent.com/78644640/160111610-3f6bf312-7f8d-4cc1-b2b2-b6e75a0da581.jpg)

**Comment by Stefen74** [comment]
From above if you close and reopen the bank window, it now displays across ...

![Bank3](https://user-images.githubusercontent.com/78644640/160111703-5cb8bf72-06d9-4e24-bacd-07636ecc9d9e.jpg)

**Comment by Stefen74** [comment]
... no longer being maintained I'm guessing?

**Comment by Cidan** [comment]
Interesting. We'll see if we can reproduce it.

**Comment by Stefen74** [comment]
Just testing it again on the beta. When I open my bank I get this ...

![image](https://user-images.githubusercontent.com/78644640/186991963-6540e4f0-61a4-47c4-82f8-f82cf1e5349f.png)

**Comment by Stefen74** [comment]
But if I close the bank and re-open it, it now looks correct ...

![image](https://user-images.githubusercontent.com/78644640/186992057-49c1aa61-1c3b-4e21-ba70-39a08193b341.png)

**Comment by Cidan** [comment]
What version of AdiBags and WoW are you on? (Looks like Wrath PTR, but can you confirm?)

**Comment by Stefen74** [comment]
Just an idea, but could it be the sheer number of items in the bank? The addon cannot cache them all quick enough to display them correctly, and so it looks like the first picture? And by time you've closed and re-opened it, it the addon has had the time to sort everything and so it can display it correctly?

You'll notice that the first picture only has a few items under a "Armor" heading, the rest (other than a few "Junk" items) are in "Miscellaneous", that's what makes me think the addon cannot handle that many items in such a short time. I'd test it by emptying my bank a bit, but of course, my bags are also nearly full :(

**Comment by Stefen74** [comment]
Sec, I'll look ...

**Comment by Stefen74** [comment]
Adibags is version 1.9.26-bcc. So yea, it is the TBC version, I've not seen a wrath version? Or have I not been looking hard enough? :\
It is the Wrath PTR, which is showing version 3.4.0

**Comment by Cidan** [comment]
So, Curse isn't up to date, but there have been a ton of updates, and there's no more "branches." I'm working on getting Curse up to date for non-retail, but if you take the release from GitHub, v1.9.34 ([click here to go to it](https://github.com/AdiAddons/AdiBags/releases)) and install this, you'll have the newest version.

Can you confirm this newest version works?

**Comment by Stefen74** [comment]
Let me have a quick try ...

**Comment by Stefen74** [comment]
Perfect! The new version fixes it. Thanks a ton for this, facing the realisation of the default bags UI was giving me nightmares :( ... thank you again :)

**Comment by Cidan** [comment]
Awesome! We'll work on getting Curse updated so those addon clients auto-update. You can also use wowup, etc, to manage updates until we get this done.

Thanks!

**Comment by Stefen74** [comment]
... crap ... I wandered off, walked back, opened the bank, and it's done it again ... 

![image](https://user-images.githubusercontent.com/78644640/186994489-63b77bfd-dd89-4748-aa66-c06aee066b90.png)


This is only PTR, I can delete a load of my stuff and simply copy my char over again, let me see if I can test it by reducing the number of items in my bank.

**Comment by Cidan** [comment]
Shoot, okay. Unfortunately, the PTR is down for me right now and I can't test. I don't have a high level character to test with on the classic game versions, but I will level something up really fast and get multiple items to test as soon as I can. This will be a priority, as it is breaking for Wrath.

**Comment by Stefen74** [comment]
I'll keep playing with it and get back to you, I was convinced it was the number of armor items in the bank, but although I could get it to fail, I have loaded my bank up with over 70 items of armor, and of course, now it won't fall over :( ... It might be a certain item, but more testing, maybe not tonight, but I will keep on it and see if I can get it to fall over on demand :)

**Comment by Stefen74** [comment]
Ok, it's not an addon conflict as it still does with Adibags enables only ...

**Comment by Cidan** [comment]
How are you getting into Wrath PTR? All realms are down for me right now.

**Comment by Stefen74** [comment]
I play on EU? Maybe that’s why? The PTR is definitely up.

**Comment by Talyrius** [comment]
Appears related to #252. My characters' banks and bags have always been quite filled up when observing such behavior.

**Comment by Cidan** [comment]
This is happening because item data is pulled asynchronously from the game. This will require us to implement [RequestLoadItemData](https://wowpedia.fandom.com/wiki/API_C_Item.RequestLoadItemData), register for the event, and track what has been loaded. It shouldn't be too hard, but it does add complexity as we need fan out and join pattern to determine when all requests are done.

We'll get this in place after the other Layout bits are done.

**Comment by Stefen74** [comment]
Thank you Cidan, appreciated :)
