### ISSUE TITLE
Regent Deposit (non-auto) not working properly

### ISSUE THREAD

**Issue by TripleEYE** [AdiAddons/AdiBags#63]
When I click on the "D" button to deposit regents - it deposits some of them, and others stay in my bags.
It's not always the same ones (sometimes one herb will deposit when I click the "D" button and other times the same herb won't deposit, for example).
And sometimes, though more rarely, it WILL deposit all regents when I click said button.
Please help.
Is there any info you need? Can you explain how to give it to you please?
Is this a known issue with a known solution maybe?
Thanks

**Comment by Cidan** [comment]
The depositing of reagents is not handled by AdiBags, but by Blizzard. You likely have a bag marked as "ignored" in the default bag interface. Everything in an ignored bag is not deposited when calling the Blizzard auto deposit function.
