### ISSUE TITLE
Masque support

### ISSUE THREAD

**Issue by Acrivec** [AdiAddons/AdiBags#631]
Hey, can we have an option to change skins on items? Rounded edges do not fit my UI. Would love to get then to be just square.

**Comment by Cidan** [comment]
This feels like a reasonable change/option to add. We'll take a look at it.

**Comment by Imiona** [comment]
> Hey, can we have an option to change skins on items? Rounded edges do not fit my UI. Would love to get then to be just square.

there is an elv ui adibags addon that makes the item skins look like that (why isnt there an option in the default adibags Addon to skin it like elv btw)

https://www.curseforge.com/wow/addons/elvui-adibags

**Comment by Talyrius** [comment]
> why isnt there an option in the default adibags Addon to skin it like elv btw

Why would there be? ElvUI is one of countless UI replacements. It's not realistic to expect every addon to cater to matching each ones' aesthetics.

**Comment by Cidan** [comment]
I actually want to tackle this one at some point. I think over the years, our stance has to evolve with the community. Specifically, there are so many great compilations (heck, even I personally use [HydraUI](https://www.curseforge.com/wow/addons/hydraui)) that it would be a shame to not support some more common place functionality, such as skinning.

I realize it's a non-trivial task, but if we don't evolve, the world will move on without us eventually. I'd hate to see a world without AdiBags!

**Comment by Imiona** [comment]
> Why would there be? ElvUI is one of countless UI replacements.

Because its by FAR the most popular? Heck, its the only Addon i know who has its own Button in the Game Menu.

**Comment by Talyrius** [comment]
> Hey, can we have an option to change skins on items? Rounded edges do not fit my UI. Would love to get then to be just square.

Masque support (see #467) would provide this functionality.

**Comment by glassleo** [comment]
Any progress on this?

**Comment by griddark** [comment]
> Any progress on this?

Pretty sure (not 100%) that you won't see anything like this getting added until after 10.0.2 as I've read this update will break many things.

**Comment by Cidan** [comment]
Hi everyone.

Masque support has been implemented in a branch, and is slated for the next release. With Masque support also comes a more comprehensive theme system, which will allow external addons to reskin AdiBags without resorting to ugly hacks.

When you see this issue close, Masque will have gone live :)

Thanks!
