### ISSUE TITLE
Recent Items instantly resetting after closing bags and not highlighting new items

### ISSUE THREAD

**Issue by BoomsiFTW** [AdiAddons/AdiBags#632]
Version 1.9.26
My Recent Items are not working well. New items missing the flash animation and also getting sorted directly after closing the bag, or even already sorted when looting with closed bags.
the "N" in the top right corner is always greyed out.

Recent Items Filter is set to 100% and every other filter is below 100%.
Tried already to disable all other filters. Making new profiles. Deactivating other Loot relevant addons.

Any hint?

**Comment by Cidan** [comment]
I'll visit this after #646 is done and we're on a unified codebase.

**Comment by Cidan** [comment]
I'm able to reproduce this on the latest release. Can you confirm if this is still happening for you?

**Comment by Cidan** [comment]
After a bit more testing, I'm able to reproduce this. We'll take a look at it, thanks!

**Comment by Cidan** [comment]
This is fixed with the latest changes to the main branch, and will be pushed in the next release.
