### ISSUE TITLE
wowup support

### ISSUE THREAD

**Issue by HawkCorrigan** [AdiAddons/AdiBags#633]
How high is the chance that you would package the addon releases here on github in a way that is supported by wowup?

Otherwise, what is your stance to people forking your repo and doing so?

**Comment by HawkCorrigan** [comment]
The setup process for packaging should be relatively easy to my understanding with https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow.

**Comment by SpareSimian** [comment]
I'm using Ajour for updating addons and would love to see this. (The Overwolf updater took a long time to start and then to update my long list of addons. Ajour does both in less than a second. I don't mind the ads, just the huge delay in those two steps.)

**Comment by woodyj13** [comment]
AdiBags is one of the best addons in WoW. PLEASE make it available in WowUp!

**Comment by jec324** [comment]
> How high is the chance that you would package the addon releases here on github in a way that is supported by wowup?
> 
> Otherwise, what is your stance to people forking your repo and doing so?

AdiBags uses the GNU GPL3 license and under section 5 it lists that having/using/sharing modified code is OK provided you properly and adequately list it as such.  That would probably be fine.  However, give them a bit of time and they might just do so as well.  Course that was just a cursory scan and I could have missed something more detailed saying no, I assume tho they'll have it up on other distributions when able.

**Comment by Cidan** [comment]
Hey folks,

I just added a simple workflow for packaging. It's a WIP and not live yet. @Talyrius any thoughts around versioning here?

**Comment by Talyrius** [comment]
AdiBags doesn't require nor receive frequent updates, so lets not pretend the need for this is more urgent than it actually is. It'll happen it happens, alright?

**Comment by woodyj13** [comment]
> AdiBags doesn't receive nor require frequent updates, so lets not pretend the need for this is more urgent than it actually is. It'll happen when it happens, alright?

Ok! That's good to know. AdiBags is one of my favorite addons. Good news that it doesn't break easily.

**Comment by mewt666** [comment]
> AdiBags doesn't receive nor require frequent updates, so lets not pretend the need for this is more urgent than it actually is. It'll happen when it happens, alright?

I think it's more that people are trying to resolve the broken links in wowup and thus hounding developers endlessly. We appreciate your work and look forward to being able to use this addon in wowup whenever you're done :)

**Comment by Cidan** [comment]
Can someone externally confirm the new release on Github works with wowup? The release process is now ready for retail only -- no TBC/WotLK/Classic support yet.

**Comment by Daegalus** [comment]
> Can someone externally confirm the new release on Github works with wowup? The release process is now ready for retail only -- no TBC/WotLK/Classic support yet.

I can confirm it works with WoWUp

It uses the AdiAddons org icon as it's icon. So if you ever want it to have a custom icon, I guess you can just set the icon of the org.

![PXL_20220821_052648034.jpg](https://user-images.githubusercontent.com/670212/185776907-583a2736-b596-42b2-b596-9760c4bf6a9e.jpg)

**Comment by Cidan** [comment]
Excellent! I too confirmed locally that it works. I'm closing this and moving all further work on this to #646 -- the next goal is to get a unified tag/release for all running versions of WoW.

Thanks everyone!

**Comment by SpareSimian** [comment]
This also works with [Ajour](https://github.com/ajour/ajour/). I'd had the addon installed from Curse until they cut off 3rd party updaters so it was showing as "Unknown" source. I just used the "Install from URL" button and entered the GitHub link and it updated to the new release! Thanks for doing this!
