### ISSUE TITLE
Items wrapped into gifts are not updated

### ISSUE THREAD

**Issue by LenweSaralonde** [AdiAddons/AdiBags#634]
Items can be wrapped into gifts using wrapping paper such as [\[Red Ribboned Wrapping Paper\]](https://www.wowhead.com/item=5042/red-ribboned-wrapping-paper). Such items then become a gift item such as [\[Red Ribboned Gift\]](https://www.wowhead.com/item=5043/red-ribboned-gift).

The problem is the wrapped item is not updated into a gift: the icon remains the same and the item is not moved to its category (assuming that there is a category for gifts). Only the tooltip seems to be updated.
The same issue occurs in reverse, when a gift is opened, the item keeps showing as a wrapped gift and still shows up in the wrong category.

![95def67154521d3ea34eb0c86a709414](https://user-images.githubusercontent.com/34239920/169700768-b9d8b032-ec8e-4dc3-bc79-59e7669ad81d.gif)

**Comment by Cidan** [comment]
I am unable to reproduce this on Retail. If this is still happening for you, can you open a new bug using the bug template?

Thanks!

**Comment by LenweSaralonde** [comment]
The bug seems to be specific to battle pets. I raised issue #647 with more details.
