### ISSUE TITLE
Feature(?): Make adibags sort manually (e.g. when you open/close) instead of automatically every time an item is added/removed

### ISSUE THREAD

**Issue by Fandaxd** [AdiAddons/AdiBags#638]
It can be frustrating when you're selling items to a vendor or moving items to bank fast and the bags are resorting as you're removing them. Quite often during these processes I click on an item I didn't mean to because adibags sorts items around and by doing that switches the item I want to click with another item I don't.

https://user-images.githubusercontent.com/57537122/177550806-3ec2e803-bfea-4ba1-9dc5-446d0bb2d132.mp4

In the clip above I was right clicking motes of mana quickly to convert them to primal mana, but then adibags jebaited me by sorting automatically and switched places of mote of mana and dark rune. Resulting in me dying, losing gold and laughing. Don't get me wrong I love laughing but most of the time it just gets frustrating when you're trying to do something quickly, but the inventory keeps changing, so you have to either do it slowly or fix mistakes, which slows the process anyway.

I suggest adibags to instead sort manually - clicking a button and whenever you open/close bags. This could be a toggleable "feature" ofc.

Other than that this addon is great, thanks for making it.

**Comment by Cidan** [comment]
I've been bitten by this as well -- marking this as a feature request. Thanks!

**Comment by Meilinn** [comment]
I've been cursed with this too. Many times I used items when I didn't want to, or sold items I didn't want to sell.
