### ISSUE TITLE
Lua error today

### ISSUE THREAD

**Issue by Milky063** [AdiAddons/AdiBags#639]
So i've been getting this lua error on my toons,

8x AdiBags\widgets\Section.lua:483: attempt to index local 'b' (a nil value)
[string "@AdiBags\widgets\Section.lua"]:483: in function <AdiBags\widgets\Section.lua:482>
[string "=[C]"]: ?
[string "@AdiBags\widgets\Section.lua"]:365: in function `FullLayout'
[string "@AdiBags\widgets\ContainerFrame.lua"]:955: in function `PrepareSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1060: in function <AdiBags\widgets\ContainerFrame.lua:1043>
[string "=(tail call)"]: ?
[string "@AdiBags\widgets\ContainerFrame.lua"]:449: in function `RefreshContents'
[string "@AdiBags\widgets\ContainerFrame.lua"]:434: in function `ResumeUpdates'
[string "@AdiBags\widgets\ContainerFrame.lua"]:417: in function <AdiBags\widgets\ContainerFrame.lua:409>
[string "=[C]"]: in function `Show'
[string "@AdiBags\core\Bags.lua"]:89: in function `Open'
[string "@AdiBags\core\Hooks.lua"]:172: in function <AdiBags\core\Hooks.lua:168>
[string "=(tail call)"]: ?
[string "@FrameXML\ContainerFrame.lua"]:1536: in function <FrameXML\ContainerFrame.lua:1505>
[string "@ElvUI\Core\Modules\DataTexts\Bags.lua"]:50: in function `onClick'
[string "@ElvUI\Core\Modules\DataTexts\DataTexts.lua"]:399: in function <...ceElvUI\Core\Modules\DataTexts\DataTexts.lua:397>

Locals:
a = AdiBagsItemButton83 {
 GetItemLocation = <function> defined @FrameXML\ItemButtonTemplate.lua:418
 bag = 3
 SetItem = <function> defined @FrameXML\ItemButtonTemplate.lua:355
 itemContextMatchResult = 3
 IconOverlay = <unnamed> {
 }
 count = 80
 section = AdiBagsSection2 {
 }
 OnItemContextChanged = <function> defined @FrameXML\ItemButtonTemplate.lua:256
 showMatchHighlight = true
 newitemglowAnim = <unnamed> {
 }
 bagFamily = 0
 icon = AdiBagsItemButton83IconTexture {
 }
 container = AdiBagsContainer1 {
 }
 texture = 3528446
 acquired = true
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1345
 LevelLinkLockTexture = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 itemLink = "|cff0070dd|Hitem:172231::::::::60:64:::::::::|h[Sacred Shard]|h|r"
 itemId = 172231
 slot = 8
 UpgradeIcon = <unnamed> {
 }
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:269
 NormalTexture = AdiBagsItemButton83NormalTexture {
 }
 SetItemButtonCount = <function> defined @FrameXML\ItemButtonTemplate.lua:422
 Cooldown = AdiBagsItemButton83Cooldown {
 }
 SetItemInternal = <function> defined @FrameXML\ItemButtonTemplate.lua:360
 BattlepayItemTexture = <unnamed> {
 }
 0 = <userdata>
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:292
 timeSinceUpgradeCheck = 0
 flashAnim = <unnamed> {
 }
 ItemContextOverlay = <unnamed> {
 }
 PostOnEvent = <function> defined @FrameXML\ItemButtonTemplate.lua:273
 flash = <unnamed> {
 }
 GetItemID = <function> defined @FrameXML\ItemButtonTemplate.lua:399
 SetItemSource = <function> defined @FrameXML\ItemButtonTemplate.lua:339
 IconBorder = <unnamed> {
 }
 ExtendedSlot = <unnamed> {
 }
 IconQuestTexture = AdiBagsItemButton83IconQuestTexture {
 }
 hasItem = true
 IconOverlay2 = <unnamed> {
 }
 IconTexture = AdiBagsItemButton83IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 SetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:287
 UpdateItemContextOverlay = <function> defined @FrameXML\ItemButtonTemplate.lua:307
 GetDebugReportInfo = <function> defined @FrameXML\ContainerFrame.lua:1076
 SetItemLocation = <function> defined @FrameXML\ItemButtonTemplate.lua:343
 GetItemLink = <function> defined @FrameXML\ItemButtonTemplate.lua:414
 PostOnShow = <function> defined @FrameXML\ItemButtonTemplate.lua:260
 GetItemInfo = <function> defined @FrameXML\ItemButtonTemplate.lua:386
 UpdateItemContextMatching = <function> defined @FrameXML\ItemButtonTemplate.lua:296
 SetAlpha = <function> defined @FrameXML\ItemButtonTemplate.lua:430
 Count = AdiBagsItemButton83Count {
 }
 GetItemButtonCount = <function> defined @FrameXML\ItemButtonTemplate.lua:426
 Stock = AdiBagsItemButton83Stock {
 }
 searchOverlay = AdiBagsItemButton83SearchOverlay {
 }
 GetItem = <function> defined @FrameXML\ItemButtonTemplate.lua:410
 Reset = <function> defined @FrameXML\ItemButtonTemplate.lua:330
}
b = nil
(*temporary) = "|cff0070dd|Hitem:172231::::::::60:64:::::::::|h[Sacred Shard]|h|r"
(*temporary) = AdiBagsItemButton83 {
 GetItemLocation = <function> defined @FrameXML\ItemButtonTemplate.lua:418
 bag = 3
 SetItem = <function> defined @FrameXML\ItemButtonTemplate.lua:355
 itemContextMatchResult = 3
 IconOverlay = <unnamed> {
 }
 count = 80
 section = AdiBagsSection2 {
 }
 OnItemContextChanged = <function> defined @FrameXML\ItemButtonTemplate.lua:256
 showMatchHighlight = true
 newitemglowAnim = <unnamed> {
 }
 bagFamily = 0
 icon = AdiBagsItemButton83IconTexture {
 }
 container = AdiBagsContainer1 {
 }
 texture = 3528446
 acquired = true
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1345
 LevelLinkLockTexture = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 itemLink = "|cff0070dd|Hitem:172231::::::::60:64:::::::::|h[Sacred Shard]|h|r"
 itemId = 172231
 slot = 8
 UpgradeIcon = <unnamed> {
 }
 PostOnHide =

**Comment by Milky063** [comment]
So are people done updating or fixing this addon?

**Comment by Milky063** [comment]
Its still broken fyi...

**Comment by Milky063** [comment]
HELLOOOOOOO ANYONE HERE?????????

**Comment by SpareSimian** [comment]
Works fine for me. Have you eliminated other addons to narrow it down?

**Comment by Cidan** [comment]
I am unable to reproduce this error. If possible, can you post the steps to reproduce this error? Also, for each error, please open a new issue.

Feel free to reopen when you can reproduce this. Thanks!
