### ISSUE TITLE
Adibags Not working after 08/10/22 reset

### ISSUE THREAD

**Issue by Rey67** [AdiAddons/AdiBags#641]
After the reset today, my adibags addons is not working anymore.
The addon is loaded, but /adibags is not working, and I don't know why.
Here's attached screenshot
![Screenshot_147](https://user-images.githubusercontent.com/10940785/183892331-50730f94-c23d-4b64-a24c-45c59db4ad6e.png)
![Screenshot_148](https://user-images.githubusercontent.com/10940785/183892334-f52b2bc4-7a67-4908-8788-72ab2b875f43.png)
![Screenshot_149](https://user-images.githubusercontent.com/10940785/183892335-22a1064f-b177-4ad9-91a2-72790a21fd7d.png)
![Screenshot_150](https://user-images.githubusercontent.com/10940785/183892336-58522000-5a07-4e37-9ab1-9a6cf55cf10a.png)
.

**Comment by Rey67** [comment]
More info : I deleted all Adibags folders + removed it with curseforge app. But it still doesn't work.

**Comment by Rey67** [comment]
Closed thise cause the addons worked for no reason one time I logged on, but the next time I logged in, the addon didn't work anymore.

**Comment by SpareSimian** [comment]
Not enough info to work the problem. Have you eliminated all other addons? Sounds like a race condition with another addon.

**Comment by Rey67** [comment]
Disabled every other addons and restarted the game, still didn't change a thing

**Comment by Cidan** [comment]
I am unable to reproduce this issue. Please reopen if you have a reproducible case. Thanks!
