### ISSUE TITLE
Allow Skin Bag Background to be Opaque 

### ISSUE THREAD

**Issue by LeahPike** [AdiAddons/AdiBags#643]
It doesn't seem possible to make the bag background opaque even when I move the slider to the top I can still see through the background? I would be great to have it opaque as I find it looks messy seeing the other windows behind it.

![image](https://user-images.githubusercontent.com/6124100/184676681-8e7b9039-db61-49fa-8727-e0686c717c7a.png)

**Comment by Cidan** [comment]
I'm able to reproduce this, marking this as a bug as this does seem like an unexpected UX.

**Comment by Cidan** [comment]
Investigating this a bit more, it seems like it does work, but there's a bug where the texture picker doesn't update the bag frame without a UI reload.

Can you try:

1) Select Solid as your background color
2) Close the configuration window
3) Type `/reload` into your chat window and hit enter
4) Set the opacity to 100

It should be completely black/solid. Does that work for you?

**Comment by Cidan** [comment]
I'm pushing a fix so the skin changes happen after you click them without having to wait for a reload. I've tested this on all versions of WoW, and it works, including your test case.
