### ISSUE TITLE
Properly create TBC/WotLK releases based on BigWigsMods release mechanisms

### ISSUE THREAD

**Issue by Cidan** [AdiAddons/AdiBags#646]
The current implementation of Github Actions only creates retail releases of AdiBags. Creation of TBC/WotLK/Classic releases can be done from Actions automatically, however this will require a bit of work to sort out. This issue will track updates to the release mechanism to support this.

**Comment by Cidan** [comment]
I've got a branch going (unified-build) that adds support for Classic/TBC automatic building from a unified TOC, without having to create sub tags.

@Talyrius I tried dropping AdiBags into classic and TBC, and while the addon loads, it silently fails to work. What changes need to be made to make TBC/Classic work? I'll go ahead and do the work to unify everything.

**Comment by Cidan** [comment]
I think I might have my answer. [Comparing master and classic](https://github.com/AdiAddons/AdiBags/compare/master...classic) shows the differences needed to make AdiBags work in Classic.

I'm going to work on unifying the branches via the [WOW_PROJECT_ID global](https://wowpedia.fandom.com/wiki/WOW_PROJECT_ID) and write branching logic so we don't have to maintain two branches. There's some more reference documentation [here](https://wowpedia.fandom.com/wiki/Porting_addons_to_Classic). There's quite a bit of files to comb through (6 commits ahead, 25 commits behind, over 50 files), but slowly the goal is to converge before Dragonflight.

Here we go!

**Comment by Talyrius** [comment]
Thanks for taking this on. I've been meaning to do it, but I've been too busy to do so.

**Comment by Cidan** [comment]
No worries -- it was actually much easier than I thought it would be. The CL is up now if you want to take a look!
