### ISSUE TITLE
Battle pet items wrapped into gifts are not updated then moved to the right category

### ISSUE THREAD

**Issue by LenweSaralonde** [AdiAddons/AdiBags#647]
**Describe the bug**

Wrapping a battle pet item into a gift doesn't update the icon and is not moved to the correct category.

**To Reproduce**
1. Purchase a bunch of [\[Red Ribboned Wrapping Paper\]](https://www.wowhead.com/item=5042/red-ribboned-wrapping-paper) from [Brog Hamfist](https://www.wowhead.com/npc=151/brog-hamfist) in Goldshire Inn.
2. Put any battle pet to cage.
3. Click "Recent items" label to move the battle pet item under "Battle pets".
4. Wrap the battle pet item into a [\[Red Ribboned Wrapping Paper\]](https://www.wowhead.com/item=5042/red-ribboned-wrapping-paper).

**Expected behavior**
* The item icon is changed to the [\[Red Ribboned Gift\]](https://www.wowhead.com/item=5043/red-ribboned-gift).
* The gift item is moved to the "Consumable" section.
* The tooltip says "Red Ribboned Gift".

**Actual behavior**
* The battle pet icon is unchanged.
* The gift item is still under the "Battle pets" section.
* The tooltip says "Red Ribboned Gift".

**Screenshots**
![95def67154521d3ea34eb0c86a709414](https://user-images.githubusercontent.com/34239920/169700768-b9d8b032-ec8e-4dc3-bc79-59e7669ad81d.gif)

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
* AdiBags 1.9.26 
* WoW Retail 9.2.7.45114

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
* AdiBags and AdiBags Configuration are the 2 only add-ons loaded.

**Additional context**
* Game language set to English.
* Fresh AdiBags installation (delete the AdiBags.lua file from SavedVariables).

Closing then opening the bag again fixes the icon. However, the item is still showing under the "Battle pets" section instead of "Consumables". The only way to have it under the right category is to do a `/reload`.

For other item types (ie a piece of equipment), the icon seems to be properly updated but the resulting wrapped gift is not moved to its new category until the bag is closed and open again.

**Comment by Cidan** [comment]
Thanks for the report! We'll take a look at this soon.

**Comment by LenweSaralonde** [comment]
I just tested the fix. The texture is properly updated as expected but the item still remains in its current category until the bags are closed and opened again. Is it something that would be complicated to fix, eventually in another ticket ?

**Comment by Cidan** [comment]
Hm, would the item appearing in "recent items" be acceptable? I feel like that should be the use case here, but I'm curious as to your feedback.

**Comment by LenweSaralonde** [comment]
If the item was previously in "recent items", I think it would make sense to leave it in "Recent Items", but if the item was already put in a category using the filter/rules, I would run the filters again on the item to move it to a new category if applicable.

**Comment by Cidan** [comment]
So I just tested it, and figuring out if it was previously in recent items would be excessive work for a somewhat weird UX. Making it materialize in recent items "feels" better as a UX, because you'll likely want to trade it right then and there.

I'm going to go ahead with the recent items for all new wraps, if you don't mind.

**Comment by LenweSaralonde** [comment]
> I'm going to go ahead with the recent items for all new wraps

It might actually even be better because the wraped gift would be easier to find in "Recent Items" than in another category.

**Comment by Cidan** [comment]
Agreed -- this also applies to the reverse. An unwrap will show up in recent items.

**Comment by Cidan** [comment]
Fixed in master, will go out in next release, or clone master to use now!
