### ISSUE TITLE
How do I get my bag to show much more vertically similar to Bagnon vs horizontal?

### ISSUE THREAD

**Issue by Jaladhjin** [AdiAddons/AdiBags#649]
I'm a bit embarrassed to be asking I figured this would be easily achievable in the settings but I've looked through every section & changed some values it doesn't seem to want to go vertical instead of horizontal.

Anyone know how to achieve this view style?

On Retail EN-US client.

Thanks! :-)

**Comment by Cidan** [comment]
Can you please use the feature template for this issue? Also, can you provide a screenshot of what you want, i.e. something from Bagnon?

Closing, and awaiting your new issue :)
