### ISSUE TITLE
Always Vertical Bag Orientation

### ISSUE THREAD

**Issue by Jaladhjin** [AdiAddons/AdiBags#655]
**Please give us a brief overview (1-2 sentences) of what you would like to see added**
I'd really love it if AdiBags would be able to... always display vertically never growing horizontally.

I had originally submitted this: https://github.com/AdiAddons/AdiBags/issues/649

**Describe how you would like to see this feature implemented**
When I go to the config options, I would like xyz in a menu so I can do abc.

I would say maybe a Grow Vertically / Force Vertical orientation type option.

**Additional context**

Here's the difference between how Adibags is going horizontal vs Bagnon going vertical: <blockquote class="imgur-embed-pub" lang="en" data-id="a/gFYsYAX" data-context="false" ><a href="//imgur.com/a/gFYsYAX"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

In case that embed doesn't work: https://imgur.com/a/gFYsYAX

**Comment by Cidan** [comment]
Thanks for the report! Are you saying you would like an "ungrouped" view, or would you like each group to only be stacked one on top of the other, and never side to side?
