### ISSUE TITLE
Request: option to hide item count from tooltip 

### ISSUE THREAD

**Issue by Vettic** [AdiAddons/AdiBags#660]
Please add an option to hide the item count from tooltips, specifically this
![WoWScrnShot_082522_112919](https://user-images.githubusercontent.com/11394109/186647616-e4fb133f-d25a-46ba-8d6a-7c3fe48f0df7.jpg)

I plan to use a different addon to show my item counts, to see the count in my alts inventories at the same time, which makes this item count redundant.

**Comment by Cidan** [comment]
That tooltip you highlighted is not from AdiBags. AdiBags tooltip notifications can already be disabled under the Plugins menu.

**Comment by Vettic** [comment]
my bad, thought i had identified the addon
