### ISSUE TITLE
after leaving arena, emblems update once, then they don't anymore

### ISSUE THREAD

**Issue by sod** [AdiAddons/AdiBags#663]
AdiBags-v1.9.32 / german retail patch 9.2.7

![image](https://user-images.githubusercontent.com/905328/186790849-45d7d8c6-006b-431c-ad40-c41382be2623.png)

Tried to reproduce it in this vod https://www.twitch.tv/videos/1572612573?t=0h15m10s. The startpoint is after it already froze. In that clip you see how i buy something from a garrison vendor. The blizzard ui updates, but adibags doesn't:

![image](https://user-images.githubusercontent.com/905328/186790648-081a9d75-a135-481a-8ef3-457c759d487f.png)

I joined an arena skirmish (also happens after arena ranked though) beforehand, then the emblems updated once (the honor I got was reflected) but didn't do any updates afterwards. Also adding/removing emblems in the settings didn't update the UI anymore.

I don't see any errors in my console though.

Maybe related, maybe not: When updating still works, it removes the 1000th divider, like it goes from `1.700` to `1650` (for garrison resources, didn't test the others)

**Comment by sod** [comment]
Installed bugsack as recommended and actually there is an error right when the arena match ends:

```log
1x AdiBags\modules\CurrencyFrame.lua:201: attempt to index local 'cell' (a nil value)
[string "@AdiBags\modules\CurrencyFrame.lua"]:201: in function `?'
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?
```

seems like `cell` is `nil` in https://github.com/AdiAddons/AdiBags/blob/d894b8d5eb5f05889b05081c3278d7422fc84fe5/modules/CurrencyFrame.lua#L200-L201

**Comment by Cidan** [comment]
Thank you for the report! We completely redid the currency frames in the latest patch, and we definitely missed something. Are you able to trigger this in any other situation other than the Arena?
