### ISSUE TITLE
Automatic Category for Container/Box Items

### ISSUE THREAD

**Issue by ZINK-ZINK** [AdiAddons/AdiBags#669]
ATM I am manually adding every Paragon Cache, Callings Box, Patterns Within Patterns Box, etc etc to my Manual "BOXES" Category in the Quest Item Section; so that openable containers are always on top. I did the exact same thing with all Lockpickable LockBoxes too, but they have their own separate Category.

It would be great for all Boxes to have an optional automatic sorting override "Tag" that shoves them way to the very top, so I don't have to click through 5 or so menu levels just to add every stinking box I find to my boxes category. 

That seems like a reasonably easy API check: isContainer=true; then setPriority100 ...or something like that, IDK, I can't do math or code lol.

(Thinking about Tags also has me wondering if that might be a good replacement for the current Options Windows. Like maybe some kind of ctrl+right click the item in bags to open a small dialog box where I could literally type "box" and adibags would create the "box" category if it didn't already exist and place the item there. Mostly the same as the current way, but with WAY less clicking through menus. But I'm rambling again).

**Comment by Cidan** [comment]
> It would be great for all Boxes to have an optional automatic sorting override "Tag" that shoves them way to the very top, so I don't have to click through 5 or so menu levels just to add every stinking box I find to my boxes category.

You should only need to do this once per item. Are you dragging the boxes to the literal word "BOXES" and clicking on the word? All future instances of items that match that name should automatically go to the "BOXES" category. If the category isn't present (because you have no boxes), just alt-click any header to get a popup, and pick the category, like so:

![category](https://user-images.githubusercontent.com/1133628/187012141-dd11fad5-710e-4abe-8f6d-7b92724aace0.gif)

**Comment by Cidan** [comment]
One idea that I like is something like alt-click an item, and the dropdown appears so you can just pick a new category, without having to move the item. We'll take a look at that.

**Comment by ZINK-ZINK** [comment]
Yes I discovered the clicking on text feature by accident a few months ago (might want to document that better, I didn't know about it for years I think). I love it and it works well, BUT the issue I often encounter is I have zero boxes in my bags, then I find a new one out in the world or from a new patch weekly like Patterns Within Patters. Since it is the only box I currently have there isn't any text to click yet. 

Pretty much just let me access that "text clicky thing" but by mod:clicking on an item too, I guess? ATM there is no clean solution for: New Uncategorized Item I have already made a group for but currently am not carrying any other items from said group. If I'm still not making any sense I'll try to explain better.

**Comment by Cidan** [comment]
Check the gif above -- it does exactly what you're asking for. If you ALT+Click any header, you will get the menu (not just the "boxes" header). However, I do think ALT-clicking an item directly is a better UX. We'll implement that.

Thanks!

**Comment by ZINK-ZINK** [comment]
Oh btw, I stream myself on youtube/twitch for the free personal VOD storage. If any of this would be easier to explain via video I could easily "screen share" and show you exactly what I mean.

**Comment by ZINK-ZINK** [comment]
> Check the gif above -- it does exactly what you're asking for. If you ALT+Click any header, you will get the menu (not just the "boxes" header). However, I do think ALT-clicking an item directly is a better UX. We'll implement that.
> 
> Thanks!

Ah I see now, yea it does. It threw me off cause you clicked on "Tabards" so I assumed it worked the same way as what I've been doing: Left Click Dragging an Item on top of the text then left clicking again. But I see that "Tabards" would have been one of the choices even if you hadn't clicked on "Tabards".

Basically that gif makes a coincidence look like a requirement.
