### ISSUE TITLE
Dynamically Scaling % Size to Force Bags to occupy an exact area

### ISSUE THREAD

**Issue by ZINK-ZINK** [AdiAddons/AdiBags#671]
Max Bag Height has never seemed to work very well, adibags often seems to just kind of shrug and "ignore" whatever I set it to. I've even had to reset the WTF Folder one time I broke it so badly and made my Bag so unreachable lol. 

It would be cool to set a HARD screen area limit for each bag window and have adibags re-Scale itself to take up near-exactly the screen area I set, no matter how full or empty my bags are. So like if my bags are half full like normal it scales to 100% size, if my bags are almost empty they scale to ~150%, and if I go to the bank and fill my bags to the brim then they scale to ~70% so the windows always cleanly take up the "same sized corner of my screen". Maybe the UX could be a draggable overlay? I'm thinking kind of like how Dominoes Action Bars does their settings overlay, since that is a great example of Elegant UX Design.

BAG-MAGEDDON every time I visit the bank with full bags is pretty funny, but it's a bit much for a AH Goblin power-user. I have many storage-alt-characters with literally maxed out full banks+bags, but my vision is really bad too. So I can't just scale everything to 50% or else I'd be squinting to see my Main's Items.

**Comment by glassleo** [comment]
I wouldn't mind a scroll bar if the bag gets too large, but that might be difficult to implement.
