### ISSUE TITLE
Global Font Choice.

### ISSUE THREAD

**Issue by ZINK-ZINK** [AdiAddons/AdiBags#672]
This one should be really easy to implement and I was shocked it wasn't already an option: Add the Option to set all Fonts in adibags Globally. I use font:Expressway everywhere in my UI that I can, for the improved legibility. Adibags currently lets me change only about half the Fonts that it uses and it's aesthetically ugly to have 2 different Fonts on 1 addon.

**Comment by Cidan** [comment]
This will come with #631, when we get to adding Masque support. Closing this, and feel free to track the other bug.
