### ISSUE TITLE
Improve Overall Documentation

### ISSUE THREAD

**Issue by ZINK-ZINK** [AdiAddons/AdiBags#673]
This evening of bug reporting/writing feature requests has made it very clear to me that adibag's Documentation is sorely lacking. In other words you have a ton of super cool features that even hardcore power-users like myself don't know about. 

Look at the addon Kaliel's Quest Tracker (linked below) for an example of, IMO, extremely well-done New Feature Documentation. When they add a feature a very legible and clean window pops up telling the user all the nifty cool things they can do now and ALSO lists ALL the other older cool features below it. Details Damage Meters does this acceptably as well, though their way isn't nearly as "clear to the user". 

https://www.curseforge.com/wow/addons/kaliels-tracker

**Comment by Cidan** [comment]
I absolutely agree here, and this is something that we're tracking. We just enabled the Wiki on this repo a few days ago, and all offline documentation will go there, with images and gifs as an exampled. We started the overhaul of the documentation with the main README file on the Code page in an attempt to make it easier to digest and highlighting main features.

> very legible and clean window pops up telling the user all the nifty cool things they can do now

Amusingly enough, I spent part of today drafting a plan for this exact thing. The goal is to have an in-game button you can click to see "What's New" when a new version is detected. I don't want nagging popups during updates, but likely some sort of in-game notification that you can click to get a full screen of updates is the plan. I'll keep this issue open to track this.

**Comment by ZINK-ZINK** [comment]
> Amusingly enough, I spent part of today drafting a plan for this exact thing. The goal is to have an in-game button you can click to see "What's New" when a new version is detected. I don't want nagging popups during updates, but likely some sort of in-game notification that you can click to get a full screen of updates is the plan. I'll keep this issue open to track this.

LOL, Perfect. 

FWIW my immediate reaction was "oooo it could be a subtly shiny button on the bag window itself!(the shine would disappear after clicking and just become an unobtrusive clickable). Like right next to [V][N][X] or on the other side next to the "Bags" text. The user couldn't **_possibly_** miss it there!(Wishful thinking lol)"

And now that I brought those red buttons in the top corner: Can those be re-skinned and made bigger/nicer looking or are they hard-locked "protected" Blizzard buttons? Do I need to write ANOTHER Request? lol
