### ISSUE TITLE
Rebuild the Manual Category filter experience

### ISSUE THREAD

**Issue by ZINK-ZINK** [AdiAddons/AdiBags#674]
This is probably a big request that would require a major re-write. The more I think about it, the more I realize that the only reason I think the options menu in adibags is logical is because I've used your addon for years now and just gotten used to it. 

Honestly digging through the menus has become a mess of spaghetti at this point. The category titles seem haphazard and barely make sense. Creating a new Manual Category is such an obtuse UX that even though I have made dozens of categories I STILL often fail and have to re-try because I forgot to press enter or drag the item to the empty area before(or was it after?) clicking. You inexplicably have a single expanding menu even though there is plenty of space to just make it permanently expanded. 

I understand you didn't mean to make it a mess on purpose and it's just how things ended up after you added features on top of spaghetti then rewrote the spaghetti then added more features; if anything it reminds me of WoW's Code lol. 

But at this point the UX is honestly... pretty god-awful. I've been comfortable with PC's since DOS and Windows 3.1. A multi-year Power User like me DEFINITELY shouldn't be getting lost in your Options Menu. IMO focus on "reducing clicks". Think about how you could reorganize the Options in such a way that the User never has to click more than about 3 times to change any setting they want to. 

Like if I want to change the Priority of a Category that should go like: ESC>Interface>Addons>AdiBags(now you have 3 clicks to 'spend' on UX)>Item Category>Priorities>[User is now changing the variable]. 

There shouldn't be any Options Setting buried any deeper than that, IMO.

edit: I wasn't super clear about this: 3 click to reach ANYTHING should be the maximum. 1 to 2 Clicks is preferable when reasonable. Think of a lost, confused user: they will go "hmm ok, let's see... Items /click/.... wait... wtf are all these new options? /click/ hmmm no that's not what I need... /click/ no not here either.... /click/... you know what? forget it. I have no idea what I'm doing and this is a maze of options. I'll just delete adibags and go back to Bagnon" ((ewwww bagnon lol))

**Comment by Cidan** [comment]
I think you're probably right here to some extent, but it's unfair to call it spaghetti code. The code itself is pretty well laid out, and UX changes like this wouldn't be too terribly difficult to implement. Please reserve judgement on things you haven't evaluated yourself -- we have feelings too :)

That being said, I do think some of the workflows can definitely be improved, including the manual filtering. AdiBags is a very old addon, and some of the design principles were okay for the early 2010's, but it does need to be brought up to 2022 standards. This is not an area that is unfamiliar to me (I manage large scale software and products at Google), and is something I want to focus on at some point after the "main" bag experience is modernized.

Thanks for the feedback, and I'll keep this issue open to track manual category cleanup specifically.

**Comment by ZINK-ZINK** [comment]
I tried to edit before you read this, but check the edit at the very bottom too.

**Comment by ZINK-ZINK** [comment]
> I think you're probably right here to some extent, but it's unfair to call it spaghetti code. The code itself is pretty well laid out, and UX changes like this wouldn't be too terribly difficult to implement. Please reserve judgement on things you haven't evaluated yourself -- we have feelings too :)

Apologies! I was just using spaghetti hyperbolically as a fellow geek. I meant zero offense and very much appreciate your(yalls?) work. I'm a jerry-rigg-er duct-tape kind of 'just make it work again' hardware geek, so to me it's just how I think we all think of our own tech work. That make sense at all? I've been writing too much tonight lol

**Comment by ZINK-ZINK** [comment]
Basically I am almost completely code-naïve and my design philosophy is "put hundreds of hours into rigging up Conditional Automation for myself so I can be SUPER LAZY afterwards lol. I have spent dozens of hours tweaking adibags and TSM setting so that I never have to look at my bags or touch them at all. I just open vendors etc and everything just happens.

BTW I've been looking for someone to help me write tiny amounts of LUA for some Weakaura needs. Just really simple 100%-0% gradients of Color and Opacity for Health Bar type of code snippets. Could you recommend any specific contact to me? I would even pay a small reasonable fee, maybe like $10 for like 12 or so lines of code?

**Comment by Cidan** [comment]
Totally get it. Take a look at the new pinned issue at the top of the issues page. This is something I've been planning for a while now -- I haven't done real addon development in 6 or so years now, and I'm just now finding myself at a place where I can actually play video games again and focus on hobbies like this. We'll modernize this :)
