### ISSUE TITLE
Skinnable or Custom Bag Control Buttons [V][N][X]

### ISSUE THREAD

**Issue by ZINK-ZINK** [AdiAddons/AdiBags#676]
Those red buttons in the top right corner: Can those be re-skinned and made bigger/nicer/easier to click or are they hard-locked "protected" Blizzard buttons? I'd love to make them like 400% larger and use higher res textures for the icons. 
![AdiBags Buttons](https://user-images.githubusercontent.com/96964163/187017230-7b290f57-badf-4ebd-a542-637d096290e3.png)

**Comment by Cidan** [comment]
All fit and finish will be editable once Masque support (#631) is implemented. Closing as duplicate.
