### ISSUE TITLE
Not so much of an issue. It's more of a question.

### ISSUE THREAD

**Issue by als30334** [AdiAddons/AdiBags#68]
Please tell me there's a way to get it to stop sorting everything in my bags when  i go into the guild bank and then it sorts everything all and messes up my bags.
![wowscrnshot_113015_002057](https://cloud.githubusercontent.com/assets/1158919/11464953/2b49c07a-96fa-11e5-9f7a-bc59a28b338f.jpg)

**Comment by Cidan** [comment]
This is a bug and should be fixed.
