### ISSUE TITLE
Action[SetPoint] failed because[Cannot anchor to a region dependent on it]

### ISSUE THREAD

**Issue by Jakobud** [AdiAddons/AdiBags#680]
**Describe the bug**
I hit the "New Items" (N) Button and this happened:

![image](https://user-images.githubusercontent.com/87356/187846993-eb6fecbc-378d-4ffc-ace9-a958a5548c4e.png)

Here is the error:

```
5x AdiBags\widgets\ContainerFrame.lua:1071: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: AdiBagsSection15:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1071: in function `LayoutSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1142: in function <AdiBags\widgets\ContainerFrame.lua:1116>
[string "=(tail call)"]: ?
[string "@AdiBags\widgets\ContainerFrame.lua"]:463: in function `RefreshContents'
[string "@AdiBags\widgets\ContainerFrame.lua"]:448: in function `ResumeUpdates'
[string "@AdiBags\widgets\ContainerFrame.lua"]:431: in function <AdiBags\widgets\ContainerFrame.lua:423>
[string "=[C]"]: in function `Show'
[string "@AdiBags\core\Bags.lua"]:89: in function `Open'
[string "@AdiBags\core\Hooks.lua"]:112: in function <AdiBags\core\Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
(*temporary) = AdiBagsSection15 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 3
 count = 3
 total = 3
 name = "Consumable"
 category = "Consumable"
 height = 1
 key = "Consumable#Consumable"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = AdiBagsSection12 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 2
 count = 2
 total = 2
 name = "Cloth"
 category = "Trade Goods"
 height = 1
 key = "Trade Goods#Cloth"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPRIGHT"
(*temporary) = 10.500000
(*temporary) = 0
```

**To Reproduce**
1. Click the "N" button

**Expected behavior**
No error and the layout does not go nuts

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
- WOTLK Prepatch

**AdiBags Version**
1.9.35

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Additional context**
I cannot recreate it. It happens not very often. Maybe once a month or something. I do not know what is causing it to be able to accurately and consistently recreate the problem.

**Comment by Cidan** [comment]
It looks like this is an old bug from years ago. I'll go ahead and try to get this fixed.

**Comment by Jakobud** [comment]
I know you are also interested in refactoring the layout engine so maybe spending time on that would be a better idea since it very might eliminate this bug at the same time.

**Comment by Cidan** [comment]
Thanks!

I have a workaround in place already for a future release. The old layout engine is going to stick around for a while as a "legacy" option, so it's best to fix this.
