### ISSUE TITLE
WOTLK Sept 2 update new CURSOR_UPDATE bug

### ISSUE THREAD

**Issue by Jakobud** [AdiAddons/AdiBags#682]
**Describe the bug**
There was a new WOTLK Classic update Sept 2 and it introduced the following bug on startup:

```
3x AdiBags\core\EventHandlers.lua:44: Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@AdiBags\core\EventHandlers.lua"]:44: in function `OnUsed'
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:76: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "CURSOR_UPDATE"
```

**To Reproduce**
1. Log into the world with Adibags enabled

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Wotlk Classic

**AdiBags Version**
- v1.9.35

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Comment by Cidan** [comment]
Push fixed in 1.9.37 -- should show up on curse within the hour, or directly from this repo in a few seconds under Releases.

**Comment by Jakobud** [comment]
Yeah it looks like they added the `WOW_PROJECT_WRATH_CLASSIC` project ID. Was that just added today but missed with the prepatch?

**Comment by Cidan** [comment]
Yeah, it seems like that's the case. Oh well.
