### ISSUE TITLE
WOTLK Equipment Set integration

### ISSUE THREAD

**Issue by NoobTaco** [AdiAddons/AdiBags#685]
**Please give us a brief overview (1-2 sentences) of what you would like to see added**
Please implement Equipment sets in the WRATH version.

**Describe how you would like to see this feature implemented**
Just the same as it is on the Retail version

**Additional context**
Blizzard added Equipment Set as a feature for this release. It is disabled by default (for some reason) To enable it go to options and then features.

Thanks

**Comment by towicode** [comment]
Sorry not sure if this is helpful but i think the relevant code would be:

[C_EquipmentSet.GetItemIDs](https://wowpedia.fandom.com/wiki/API_C_EquipmentSet.GetItemIDs)(equipmentSetID) : itemIDs - Returns the item IDs of an equipment set.

[C_EquipmentSet.GetEquipmentSetIDs](https://wowpedia.fandom.com/wiki/API_C_EquipmentSet.GetEquipmentSetIDs)() : equipmentSetIDs - Returns an array containing all currently saved equipment set IDs.

If this isn't picked up closer to release I will look into it. Not sure if this should be a module or baked into the base. @Cidan What is your thoughts?

**Comment by NoobTaco** [comment]
Thanks @towicode I will try to take a look myself, but I am not to familiar with Adi's code base.

**Comment by Cidan** [comment]
It's possible that the only thing we need to change is one line on [DefaultFilters.lua](https://github.com/AdiAddons/AdiBags/blob/master/core/DefaultFilters.lua#L70). Adding `or addon.isWrath` might just work, depending on if the API changed at all for Wrath. We'll take a look at this soon.

**Comment by Cidan** [comment]
Update: Just tested, and it does not work (though it fails silently), which means there is a difference somewhere in the API. I'll parse through it and figure it out shortly. Sit tight.

**Comment by Cidan** [comment]
Alright, fix found and put into a PR. It will be rolled out with the next release (later tonight or tomorrow).

Thanks folks!

**Comment by NoobTaco** [comment]
Awesome!!! Thanks @Cidan !!

**Comment by towicode** [comment]
Hey @Cidan Sorry to bother but was this released? I'm using latest version from wow-ace and I'm not seeing this in any of the options.

**Comment by Cidan** [comment]
Hey there -- the latest version was just pushed a few minutes ago as of this comment. It might take a while to show up on Curse, but you can use wowup, etc, or the release from the release page on Github to get it right away.
