### ISSUE TITLE
sry again, found the problem

### ISSUE THREAD

**Issue by d4kir92** [AdiAddons/AdiBags#689]
![image](https://user-images.githubusercontent.com/23246564/188263602-57638477-57d6-42b2-839c-4e837833d378.png)

something went wrong on supported version of wow
i play on classic :D

**Comment by d4kir92** [comment]
on 36 version

it has classic
![image](https://user-images.githubusercontent.com/23246564/188263623-b6d8c248-fcd5-4db1-8ed3-e3c02faeef90.png)

**Comment by Cidan** [comment]
Please stop opening issues as if this were a chat room. Version on curse updated.
