### ISSUE TITLE
No keyring after pre-patch WoTLK

### ISSUE THREAD

**Issue by Iowerth** [AdiAddons/AdiBags#691]
**Describe the bug**
- There is no keyring after pre-patch WoTLK.

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - WoTLK 3.4.0

**AdiBags Version**
- v1.9.37

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - No

**Additional context**
There was a keyring before WoTLK.

**Comment by Cidan** [comment]
I think the keyring code was taken out quite some time ago, and was proposed to be readded in #590. We'll take a look at this at some point in the near future.

**Comment by navara** [comment]
It was never there in TBC.

**Comment by Iowerth** [comment]
> It was never there in TBC.
> 
> See 2020 report #469

It was in AdiBags and I used it.

**Comment by david-driscoll** [comment]
It was there, I had categories to show hide/key rings.  Looking at the history though I don't know how or when it got changed which is really strange, lol.

**Comment by Talyrius** [comment]
> Looking at the history though I don't know how or when it got changed which is really strange, lol.

It didn't survive the unification of the codebase (#648).

**Comment by EvelynSays** [comment]
Any word on this? It's pretty frustrating given the number of keys in the game now!

**Comment by navara** [comment]
> Any word on this? It's pretty frustrating given the number of keys in the game now!

This macro still works - as a workaround
`/script ToggleBag(KEYRING_CONTAINER)`

**Comment by Cidan** [comment]
It's on the list to get to -- sorry folks. We have actual jobs and families, we'll get to it as soon as we can, promise!

**Comment by Iowerth** [comment]
Watching that new updates are releasing, but still no fix for this :(

**Comment by xinomahc** [comment]
any plan(s) of "fixing" this soonish?
