### ISSUE TITLE
Bank is not skinned in latest version for WOTLK

### ISSUE THREAD

**Issue by capSAR273** [AdiAddons/AdiBags#694]
~~**Describe the bug**
In the latest version of AdiBags 1.9.37 the bank is not properly condensed and skinned by the addon. It shows in its vanilla state. I also tried 1.9.36 and the issue remained.~~

~~**To Reproduce**~~
~~1. Open Bank~~

~~**World of Warcraft Release and Version (Retail 9.2.7, etc)**~~
 ~~- Classic Wrath 3.4.0.45435~~

~~**AdiBags Version**~~
~~- 1.9.37~~

~~**Have you tried disabling all your other addons to ensure only this addon causes the issue?**~~
~~- Yes~~

**Comment by capSAR273** [comment]
Okay so apparently the Bank setting for AdiBags was unchecked at some point, so the bank does skin properly now but the setting should've remained enabled by default. So maybe that is the actual bug :D

**Comment by Cidan** [comment]
Just double checked and wiped out my settings -- bank is enabled by default.
