### ISSUE TITLE
Dragonflight Patch Breaks AdiBags

### ISSUE THREAD

**Issue by Cidan** [AdiAddons/AdiBags#699]
Currently, the main releases on Curse and on the `master` branch do not support Dragonflight. Dragonflight support has been added in the `layout-redesign` branch, and will release in time for the pre-patch in ~a month (early Oct).

**Comment by N6REJ** [comment]
Will my plugins require modifications ?

**Comment by N6REJ** [comment]
Also do you know if there is a list of the mats for DF?
