### ISSUE TITLE
Is Adibags dead?

### ISSUE THREAD

**Issue by kureus** [AdiAddons/AdiBags#70]
No active branches under dev. Last commit on master seems to be from Jan 6 2015, with plenty of open (tho potentially erroneous) issues. With history saying there is only one committer, yourself, I guess adibags is either dead or in hibernation while other projects take precedence. Elegant addon that is delightful at first glance. Would love to know the status of this project and any future plans.

**Comment by Zarggg** [comment]
Yes, this project is more or less abandoned by Adirelle. It's a shame, since this was one of the better inventory management addons, IMHO. If anyone has the LUA skill to keep it updated, there should be no restrictions on forking it.

**Comment by Adirelle** [comment]
Actually all my addons are on hold, since I canceled my WoW subscription some months ago. The project is licensed under GPL, so anyone with enough motivation can fork it and tweak it.

**Comment by zgavin** [comment]
Are you planning to come back for legion, adirelle?
