### ISSUE TITLE
Wrath Classic pre-patch Bank bug

### ISSUE THREAD

**Issue by Kelryth** [AdiAddons/AdiBags#700]
NOTE: Bugs can sometimes be caused by conflicts with other addons. Please disable all other addons and try to reproduce your issue. You must answer below that you have tried disabling all your addons before this bug is accepted. If you have not tried disabling all your addons, your bug will be closed.

**Describe the bug**
Bank bags won't open.

**To Reproduce**
click on bank npc

**Expected behavior**
bank bag ui should open

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
3.4.0

**AdiBags Version**
1.9.37

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Additional context**
4x AdiBags\core\Bags.lua:276: attempt to call global 'DepositReagentBank' (a nil value)
[string "@AdiBags\core\Bags.lua"]:276: in function `PreOpen'
[string "@AdiBags\core\Bags.lua"]:87: in function `Open'
[string "@AdiBags\core\Bags.lua"]:263: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Core.lua"]:438: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?

**Comment by Cidan** [comment]
This has been fixed on `master` but not pushed out to Curse yet. Expect a release to be cut tonight.
