### ISSUE TITLE
Icon Quest Item disappear

### ISSUE THREAD

**Issue by MacChooffe** [AdiAddons/AdiBags#703]
**Describe the bug**
The Icon Quest Item (yellow exclamation point) disappears in bags.

**To Reproduce**
1. Go to Bags
2. Have and Select an item quest
3. See error

**Expected behavior**
A Yellow excalmation point must appears ont the quest item to says this item can start a quest

**Screenshots**
Joined a screeshot with AdiBags 
![image](https://user-images.githubusercontent.com/113307938/189543833-aaf4bde7-e7cf-4022-ae3b-247397a5a5f2.png)

And another without AdiBags
![image](https://user-images.githubusercontent.com/113307938/189543903-0aaaf698-4b0a-4849-9102-fe133e12bfea.png)

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Classic WOTLK 3.4.0

**AdiBags Version**
- v2.5.4

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Additional context**

**Comment by Cidan** [comment]
This was fixed in #697 and will be in the next release.
