### ISSUE TITLE
Keep getting this after restarting UI

### ISSUE THREAD

**Issue by cndrbdu** [AdiAddons/AdiBags#704]
After disabling all of the add-ons except for adibags,  I keep getting this after logging and UI restarts:  
Message: Interface\AddOns\AdiBags\core\Filters.lua:128: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Anima' already exists.
Time: Mon Sep 19 11:10:42 2022
Count: 1
Stack: Interface\AddOns\AdiBags\core\Filters.lua:128: Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Anima' already exists.
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua"]:239: in function `NewModule'
[string "@Interface\AddOns\AdiBags\core\Filters.lua"]:128: in function `RegisterFilter'
[string "@Interface\AddOns\AdiBags_Anima&Conduits\AdiBags_Anima&Conduits.lua"]:5: in main chunk

Locals: (*temporary) = "Usage: NewModule(name, [prototype, [lib, lib, lib, ...]): 'name' - Module 'Anima' already exists."

This is from the retail version. I hope this helps to find a solution to correct the problem.

**Comment by Cidan** [comment]
It looks like you didn't disable all addons, and you have [another addon installed](https://www.curseforge.com/wow/addons/adibags-anima-conduits). This is the addon that is causing your issue -- please contact that author.
