### ISSUE TITLE
Adibags v1.0-nolib 3.3.5 (not classic) won't work

### ISSUE THREAD

**Issue by Narvet** [AdiAddons/AdiBags#706]
(Sent that to the mail in the file description on curseforge but the adress wasn't found)

Hello, 
Ran into your Adibags addon and I want to give it a try (the v1.0-nolib --> https://www.curseforge.com/wow/addons/adibags/files/814362), but it seems that I can't make it work on a 3.3.5 server (not classic)
/adibags doesn't work, the bags UI is unchanged and the addon doesn't appear in my addon control panel (https://www.curseforge.com/wow/addons/acp/files/all?filter-game-version=2020709689%3A98)
Tried to disable all others addons but won't work

The filename is "AdiBags-wod-v1.0-nolib.zip", so is it the WOD version, would explain a thing or two actually ?

Have a nice day :-)

NOTE: Bugs can sometimes be caused by conflicts with other addons. Please disable all other addons and try to reproduce your issue. You must answer below that you have tried disabling all your addons before this bug is accepted. If you have not tried disabling all your addons, your bug will be closed.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Retail 9.2.7, etc, etc

**AdiBags Version**
- vx.x.x...

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes/No

**Additional context**

**Comment by Cidan** [comment]
Hi there,

You are downloading a very, very old version of the addon that doesn't apply to you. You want to download v1.9.38, and make sure you do not use the "nolib" version unless you know what you are doing/are a developer your self.

**Comment by Narvet** [comment]
Hello Cidan,
Tried v1.1 (described as compatible with 4.0.1), and it seems to work like a charm ! Link : https://www.curseforge.com/wow/addons/adibags/files/462249

Guess you did not pay attention to the "3.3.5 (not classic)" in the title :(
v1.9.38 would work on wrath classic (3.4.0) yes, but does not on wrath retail (3.3.5)
Anyway thanks for your time, hope this helps someone !

**Comment by Talyrius** [comment]
Older versions of the game running on unsanctioned servers are completely unsupported here and any issues opened regarding the topic will be closed.

**Comment by Cidan** [comment]
Hah, I didn't even catch that. Thanks @Talyrius -- agreed.
