### ISSUE TITLE
Hard crash to desktop when trying to open bags with a particular character

### ISSUE THREAD

**Issue by tubedogg** [AdiAddons/AdiBags#708]
**Describe the bug**
Whenever I try to open my bag or bank with one particular character, WoW hard crashes all the way to the desktop. 

**To Reproduce**
1. Open bag.

**Expected behavior**
- Not crash.

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
- WotLK 3.4.0.45704

**AdiBags Version**
- v1.9.38

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
- Yes

**Additional context**
This started a couple of hours ago. Please understand I get that bug reports that say "it don't work fix it" are useless, but I don't know what else to say--BugGrabber and BugSack do not allow me to do anything because the game crashes instantly upon me trying to open my bags. My Mac generates a crash report for WoW itself but it doesn't mention AdiBags. It seems like WoW isn't even able to generate an error log--after the most recent crash I looked in the folder [they say](https://us.battle.net/support/en/article/82454) contains it, and there's no Errors folder, nor is the Blizzard Error Reporter launching when it crashes. (If you want the crash report that macOS itself generates, let me know.)

I have tried: disabling all other addons, deleting all profiles within AdiBags' config (config window loads fine), deleting the WTF/Account/ACCOUNTNAME/SavedVariables/AdiBags.lua and .lua.bak files, reinstalling the addon several times after downloading a fresh copy from CurseForge, and emptying my bags completely (I was going to try adding one item back at a time, since it started earlier this evening and I was assuming it had something to do with some item I picked up tonight). AdiBags works on other characters on my account just fine.

One thing that occurred to me is I obtained a new currency for the first time tonight--Badge of Justice--but AdiBags was working fine while I was collecting it in the raid, and for a while afterwards, and only later started crashing. Because of that, I'm not sure it's actually related.

Let me know what else would help with debugging this issue and I will be happy to provide it if I can.

**Comment by Cidan** [comment]
This is really interesting. I recently also found a hard crash in the WoW client, but it was in Dragonflight and unrelated to bags outright.

Do you have an M1/M2 Mac?

**Comment by tubedogg** [comment]
Yeah, I do--Mac Studio with M1 Max.

Is there a Blizzard-created file in WTF that could be corrupted for that character that might be causing this?

**Comment by Cidan** [comment]
I'm not sure -- I strongly suspect the crash is happening somewhere due to the unique architecture of the M1 chipset, but I can't prove that.

Unfortunately, I don't have a character to test with in WotLK. What happens if you disable the currency plugin in the addon option screen? This should cause the code for currencies to not execute when you open your bag, and eliminate (or confirm) currency as an issue.

**Comment by tubedogg** [comment]
I just tried disabling all plugins (except LDB, which was checked but grayed out and I couldn't change it) and it crashed upon trying to open the bag again.

I also have an Intel Mac Mini (late 2018) with the Interface and WTF folders synced between them. I just tried on there and AdiBags loads just fine for this character that it continues to crash with on the M1 Max. So I think you're onto something.

**Comment by Cidan** [comment]
Yeah, I've seen this behavior a lot at work as well, so it's not too terribly surprising. Sadly, I don't think I can do anything about it on this end. You can try submitting an issue [here](https://github.com/Stanzilla/WoWUIBugs/issues/), with as much detail as you can. Blizzard does scan those bugs, but, no promises.

Sorry!

**Comment by tubedogg** [comment]
Thanks for trying, anyway!
