### ISSUE TITLE
Why do I even need Anchor? Can you make it movable all the time?

### ISSUE THREAD

**Issue by SegoItCh** [AdiAddons/AdiBags#709]
1x AdiBags\widgets\AnchorWidget.lua:81: attempt to perform arithmetic on local 'x' (a nil value)
[string "@AdiBags\widgets\AnchorWidget.lua"]:81: in function `GetPosition'
[string "@AdiBags\widgets\AnchorWidget.lua"]:110: in function `SaveSettings'
[string "@AdiBags\widgets\AnchorWidget.lua"]:148: in function <AdiBags\widgets\AnchorWidget.lua:134>

Locals:
self = AdiBagsAnchor1 {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:390
 corner = <unnamed> {
 }
 target = AdiBagsAnchor1 {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:409
 name = "anchor"
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:266
 label = "AdiBags Anchor"
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:278
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:188
 0 = <userdata>
 text = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 Center = <unnamed> {
 }
 OnMovingStopped = <function> defined @AdiBags\core\Layout.lua:44
 backdropInfo = <table> {
 }
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 BottomEdge = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:422
 BottomRightCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:399
 LeftEdge = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
}
target = AdiBagsAnchor1 {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:390
 corner = <unnamed> {
 }
 target = AdiBagsAnchor1 {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:409
 name = "anchor"
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:266
 label = "AdiBags Anchor"
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:278
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:188
 0 = <userdata>
 text = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 Center = <unnamed> {
 }
 OnMovingStopped = <function> defined @AdiBags\core\Layout.lua:44
 backdropInfo = <table> {
 }
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 BottomEdge = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:422
 BottomRightCorner = <unnamed> {
 }
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:399
 LeftEdge = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
}
scale = 1
w = 1517.037109
h = 853.333374
x = nil
y = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'x' (a nil value)"
UIParent = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}

**Comment by Cidan** [comment]
Please re-file the bug and do not ignore the template provided.

Thanks.
