### ISSUE TITLE
I don't want new items in their own category!

### ISSUE THREAD

**Issue by TchCzarina** [AdiAddons/AdiBags#71]
As of 1.84 I CANNOT TURN OFF this feature. No matter what I do (I turn it off, I make it's priority 0), I still see new items called out and I think this is distracting and annoying. Why can't I turn this off?

**Comment by Cidan** [comment]
This is fixed, however note that when purchasing items, they will be sorted into recent items while purchasing. After you close the window/leave the shop, the items will sort into their proper categories. This is by design.
