### ISSUE TITLE
Manually temporarily disable merged stacks

### ISSUE THREAD

**Issue by Jakobud** [AdiAddons/AdiBags#711]
I'd really love it if AdiBags would be able to have an option to temporarily show unmerged stacks when typically all item stacks are merged. For example, whenever you open the mailbox or trade window, etc, if you have "Merge stackable items" enabled, then those merged stacks temporarily become unmerged until you close the window. This is obviously very helpful for splitting up items to trade or mail to someone, etc. The feature request is adding the ability for the user to manually unmerge stackable items in this same way but be able to do it anytime they want without having to open the mail or trade window.

**Describe how you would like to see this feature implemented**
Add a button at the top of the bag window that only appears when you have "Merge stackable items" enabled. When you click this button it temporarily unmerges items in your bags.

**Additional context**
This purpose of this feature is to be able to manually split stacks without having to open the trade window or mail window, etc. A good use case for this a player asks "Does anyone have a stack of water I could have?". Adibags shows a stack of 83 water. I pick up the item and drag it over to the player. I have no idea if I'm dragging a full stack or a stack of 3 or what to the player until the trade window opens up and it appears in there. And THEN I have to drag it back and adjust the stack or combine the stack with another, etc. It would be lovely if you could simply do stuff like this in the window anytime you want.

Additionally the button would only be temporary. When you close the Adibags and reopen it, it would revert back to merged stackable items.

**Comment by Cidan** [comment]
I think a better experience would be to have a virtual stack splitter, instead of more clutter in the UI. So for example, you could shift-right click a stacked set of items and split them as much as you want within the max stackable amount for that item. This would mimic Blizzard behavior and provide one flow for stack management.

I've had my eye on this for a while and have also hit this frustration. We'll look at implementing this. Thanks for the request!

**Comment by Jakobud** [comment]
Yeah anything like that would be nice. Sometimes though, the purpose might not be to split the stack. For example like above, if I have several stacks of water but also a couple partial stacks of water, I want to drag a full stack of 20 water to my friend. But I can't tell what I'm dragging until I do it. Is it a stack of 20? Or a partial stack? etc. I'm not sure how to overcome this.

**Comment by AlexMecker** [comment]
It would be very convenient if, when splitting item stacks, you would just need to click on an empty area and not on an empty bag slot
