### ISSUE TITLE
Lots of Categories causes game freezing.

### ISSUE THREAD

**Issue by Fizgig1973** [AdiAddons/AdiBags#712]
Hello, 

Not sure if this can be resolved or not. But I use a lot of categories. I am attempting to have a separate category for quests, based on their zones, for example "Quest - Classic (Westfall)", "Quest - Legion (Azshara)", etc..

Lately when creating the new category, the game will freeze, sometimes for 30secs, sometimes indefinitely.  Sometimes I can restart and the category will be there, sometimes not. If it is there, dragging a new item in the bag to the category works fine, no lag, freeze, or disconnect.

**Comment by Cidan** [comment]
Please refile this bug using the bug template, and fill out the requested information in the template. Thanks!
