### ISSUE TITLE
New Bag issue...

### ISSUE THREAD

**Issue by Milky063** [AdiAddons/AdiBags#714]
Got this bug today,

4x AdiBags\widgets\Section.lua:365: invalid order function for sorting
[string "=[C]"]: ?
[string "@AdiBags\widgets\Section.lua"]:365: in function `FullLayout'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1008: in function `PrepareSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1120: in function <AdiBags\widgets\ContainerFrame.lua:1103>
[string "=(tail call)"]: ?
[string "@AdiBags\widgets\ContainerFrame.lua"]:463: in function `RefreshContents'
[string "@AdiBags\widgets\ContainerFrame.lua"]:448: in function `ResumeUpdates'
[string "@AdiBags\widgets\ContainerFrame.lua"]:431: in function <AdiBags\widgets\ContainerFrame.lua:423>
[string "=[C]"]: in function `Show'
[string "@AdiBags\core\Bags.lua"]:89: in function `Open'
[string "@AdiBags\core\Hooks.lua"]:172: in function <AdiBags\core\Hooks.lua:168>
[string "=(tail call)"]: ?
[string "@FrameXML\ContainerFrame.lua"]:1536: in function <FrameXML\ContainerFrame.lua:1505>
[string "@ElvUI\Core\Modules\DataTexts\Bags.lua"]:51: in function `onClick'
[string "@ElvUI\Core\Modules\DataTexts\DataTexts.lua"]:402: in function <...ceElvUI\Core\Modules\DataTexts\DataTexts.lua:400>

Locals:
(*temporary) = <table> {
 1 = AdiBagsItemButton30 {
 }
 2 = AdiBagsItemButton52 {
 }
 3 = AdiBagsItemButton41 {
 }
 4 = AdiBagsItemButton118 {
 }
 5 = AdiBagsItemButton8 {
 }
 6 = AdiBagsItemButton145 {
 }
 7 = AdiBagsItemButton55 {
 }
 8 = AdiBagsItemButton58 {
 }
 9 = AdiBagsItemButton133 {
 }
 10 = AdiBagsItemButton125 {
 }
 11 = AdiBagsItemButton31 {
 }
 12 = AdiBagsItemButton7 {
 }
 13 = AdiBagsItemButton28 {
 }
 14 = AdiBagsItemButton89 {
 }
 15 = AdiBagsItemButton92 {
 }
 16 = AdiBagsItemButton72 {
 }
 17 = AdiBagsItemButton131 {
 }
 18 = AdiBagsItemButton104 {
 }
 19 = AdiBagsItemButton27 {
 }
 20 = AdiBagsItemButton127 {
 }
 21 = AdiBagsItemButton19 {
 }
 22 = AdiBagsItemButton115 {
 }
 23 = AdiBagsItemButton150 {
 }
 24 = AdiBagsItemButton157 {
 }
 25 = AdiBagsItemButton34 {
 }
 26 = AdiBagsItemButton99 {
 }
 27 = AdiBagsItemButton140 {
 }
 28 = AdiBagsItemButton57 {
 }
 29 = AdiBagsItemButton159 {
 }
 30 = AdiBagsItemButton85 {
 }
 31 = AdiBagsItemButton103 {
 }
 32 = AdiBagsItemButton64 {
 }
 33 = AdiBagsItemButton129 {
 }
 34 = AdiBagsItemButton151 {
 }
 35 = AdiBagsItemButton13 {
 }
 36 = AdiBagsItemButton59 {
 }
 37 = AdiBagsItemButton45 {
 }
 38 = AdiBagsItemButton38 {
 }
 39 = AdiBagsItemButton53 {
 }
 40 = AdiBagsItemButton56 {
 }
 41 = AdiBagsItemButton98 {
 }
 42 = AdiBagsItemButton50 {
 }
 43 = AdiBagsItemButton102 {
 }
 44 = AdiBagsItemButton78 {
 }
 45 = AdiBagsItemButton12 {
 }
 46 = AdiBagsItemButton86 {
 }
 47 = AdiBagsItemButton4 {
 }
 48 = AdiBagsItemButton147 {
 }
 49 = AdiBagsItemButton117 {
 }
 50 = AdiBagsItemButton156 {
 }
 51 = AdiBagsItemButton9 {
 }
 52 = AdiBagsItemButton42 {
 }
 53 = AdiBagsItemButton47 {
 }
 54 = AdiBagsItemButton54 {
 }
 55 = AdiBagsItemButton108 {
 }
 56 = AdiBagsItemButton100 {
 }
 57 = AdiBagsItemButton121 {
 }
 58 = AdiBagsItemButton83 {
 }
 59 = AdiBagsItemButton143 {
 }
 60 = AdiBagsItemButton146 {
 }
 61 = AdiBagsItemButton17 {
 }
 62 = AdiBagsItemButton87 {
 }
 63 = AdiBagsItemButton155 {
 }
 64 = AdiBagsItemButton106 {
 }
 65 = AdiBagsItemButton60 {
 }
 66 = AdiBagsItemButton49 {
 }
 67 = AdiBagsItemButton81 {
 }
 68 = AdiBagsItemButton154 {
 }
 69 = AdiBagsItemButton79 {
 }
 70 = AdiBagsItemButton149 {
 }
 71 = AdiBagsItemButton24 {
 }
 72 = AdiBagsItemButton96 {
 }
 73 = AdiBagsItemButton35 {
 }
 74 = AdiBagsItemButton84 {
 }
 75 = AdiBagsItemButton160 {
 }
 76 = AdiBagsItemButton23 {
 }
 77 = AdiBagsItemButton74 {
 }
 78 = AdiBagsItemButton93 {
 }
 79 = AdiBagsItemButton111 {
 }
 80 = AdiBagsItemButton18 {
 }
 81 = AdiBagsItemButton73 {
 }
 82 = AdiBagsItemButton109 {
 }
 83 = AdiBagsItemButton63 {
 }
}
(*temporary) = <function> defined @AdiBags\widgets\Section.lua:482
(*temporary) = AdiBagsItemButton55 {
 GetItemLocation = <function> defined @FrameXML\ItemButtonTemplate.lua:418
 bag = 4
 SetItem = <function> defined @FrameXML\ItemButtonTemplate.lua:355
 itemContextMatchResult = 3
 IconOverlay = <unnamed> {
 }
 count = 1
 section = AdiBagsSection2 {
 }
 OnItemContextChanged = <function> defined @FrameXML\ItemButtonTemplate.lua:256
 showMatchHighlight = true
 newitemglowAnim = <unnamed> {
 }
 bagFamily = 0
 icon = AdiBagsItemButton55IconTexture {
 }
 container = AdiBagsContainer1 {
 }
 texture = 133738
 acquired = true
 UpdateTooltip = <function> defined @FrameXML\ContainerFrame.lua:1345
 LevelLinkLockTexture = <unnamed> {
 }
 NewItemTexture = <unnamed> {
 }
 itemLink = "|cffff8000|Hitem:187785::::::::60:64::11::1:28:2057:::::|h[Tome of the Eternal]|h|r"
 itemId = 187785
 slot = 12
 UpgradeIcon = <unnamed> {
 }
 PostOnHide = <function> defined @FrameXML\ItemButtonTemplate.lua:269
 NormalTexture = AdiBagsItemButton55NormalTexture {
 }
 SetItemButtonCount = <function> defined @FrameXML\ItemButtonTemplate.lua:422
 Cooldown = AdiBagsItemButton55Cooldown {
 }
 SetItemInternal = <function> defined @FrameXML\ItemButtonTemplate.lua:360
 BattlepayItemTexture = <unnamed> {
 }
 0 = <userdata>
 GetMatchesSearch = <function> defined @FrameXML\ItemButtonTemplate.lua:292

**Comment by Milky063** [comment]
Also got this when i open my bags,

4x AdiBags\widgets\Section.lua:483: attempt to index local 'b' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags\widgets\LayeredRegion.lua"]:119: in function <AdiBags\widgets\LayeredRegion.lua:108>

**Comment by Talyrius** [comment]
Please open a new issue for this bug without ignoring the provided template.

Thank you.
