### ISSUE TITLE
Equipment manager filter is not including all items belonging to the set

### ISSUE THREAD

**Issue by mantysalo** [AdiAddons/AdiBags#717]
**Describe the bug**
All of the items belonging to an equipment set (Blizzard implementation) are not displayed under the same filter. Some items are under jewelry or armor even though they belong to an equipment set.

**To Reproduce**
Not sure how to reproduce reliably since it does not happen consistently for all items belonging to equipment sets. For example if I move a cloak from my restoration equipment to the bank, it displays correctly under the `Set: Resto` filter.

**Expected behavior**
All items belonging to an equipment set should display under the same filter.

**Screenshots**
Feral cloak not included in the feral equipment set but cloak belonging to resto set is correctly in the `Set: Resto` filter.
<img width="480" alt="image" src="https://user-images.githubusercontent.com/33690850/195956214-7f669a7c-00c6-40df-ab8c-af6db3df2dc7.png">

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Wotlk Classic

**AdiBags Version**
- v1.9.38

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Comment by benhamlin** [comment]
Saw this today as well in 10.0.2 with latest version
