### ISSUE TITLE
9x AdiBags\modules\ItemLevel.lua:448: bad argument #1 to 'unpack' (table expected, got nil)

### ISSUE THREAD

**Issue by d4kir92** [AdiAddons/AdiBags#718]
**Describe the bug**
9x AdiBags\modules\ItemLevel.lua:448: bad argument #1 to 'unpack' (table expected, got nil)

**To Reproduce**
1. Open Bag, close bag (fast)

**Expected behavior**
no error

**Screenshots**
-

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
Wrath

**AdiBags Version**
latest (1.9.38)

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes/No

**Additional context**

**Comment by Cidan** [comment]
Thanks, this is fixed in the next major release.
