### ISSUE TITLE
two set point errors - multiple times per day

### ISSUE THREAD

**Issue by amey1956** [AdiAddons/AdiBags#719]
i get these two errors multiple times daily with no idea of the trigger. i have wiped my saved variables and started from scratch to see if that might be part of the problem with no resolution. 

`6x AdiBags\widgets\ContainerFrame.lua:1053: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: AdiBagsSection6:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1053: in function `LayoutSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1129: in function <AdiBags\widgets\ContainerFrame.lua:1103>
[string "=(tail call)"]: ?
[string "@AdiBags\widgets\ContainerFrame.lua"]:410: in function `?'
[string "@Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Core.lua"]:340: in function `?'
[string "@Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?`

and 
`4x AdiBags\widgets\Section.lua:184: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[string "=(tail call)"]: ?
[string "@AdiBags\core\Utility.lua"]:121: in function `UpdateTooltip'
[string "@FrameXML\GameTooltip.lua"]:431: in function <FrameXML\GameTooltip.lua:410>
[string "=[C]"]: ?
[string "@AdiBags\libs\AceHook-3.0\AceHook-3.0-9.lua"]:95: in function <...faceAdiBags\libs\AceHook-3.0\AceHook-3.0.lua:87>
[string "=[C]"]: ?`

**Comment by Cidan** [comment]
Please use the bug template and answer the questions in the template in a new bug. Thanks!
