### ISSUE TITLE
Wrong picture

### ISSUE THREAD

**Issue by fireymerlin** [AdiAddons/AdiBags#72]
After using "Sort Items" and "reset new items", the icon or picture that shows for items in the bags are wrong.  This is dangerous.  I almost deleted something I wanted.  Closing and re-opening the bags fixes this.

**Comment by Zarggg** [comment]
This is a known issue: see #4, #9, and #37. It seems unlikely this will be fixed unless someone is willing to take over development.

**Comment by Cidan** [comment]
This is fixed.
