### ISSUE TITLE
Mass LUA errors

### ISSUE THREAD

**Issue by GregoryGH** [AdiAddons/AdiBags#720]
WOTLK classic

8x AdiBags\widgets\ContainerFrame.lua:1053: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: AdiBagsSection4:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1053: in function `LayoutSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1129: in function <AdiBags\widgets\ContainerFrame.lua:1103>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:124: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:124>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:24: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:20>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:59: in function `SendMessage'
[string "@AdiBags\core\Core.lua"]:436: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:114: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:24: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:20>

**Comment by Cidan** [comment]
Please use the bug template and fill out the questions in the template. Thanks!

**Comment by GregoryGH** [comment]
i provided all info i have. if you don't want to do anything - can't help with "better" reports

**Comment by Cidan** [comment]
Please understand, the questions in the bug template are meant to better service you, the user, and to help us better sort out what sort of bugs we're looking at.

We, the maintainers, have full time jobs, families, and obligations outside of our work in the community. We do this work because we're passionate about the game, and we don't ask for any compensation for our time. Please reconsider your approach when communicating with people that provide a service to you, for free, out of the kindness of their heart.

Thanks!

**Comment by GregoryGH** [comment]
but i can't provide any additional info anyway. i also have full time job, family etc.

**Comment by GregoryGH** [comment]
![image](https://user-images.githubusercontent.com/9971731/197355744-451f2bdf-2b85-4a0c-8fe1-cf544605e3fb.png)

it looks like that when i open bags

**Comment by Cidan** [comment]
When you go to create an issue, there is a button that says "Get started" next to "Report a bug". When you do this, the issue field will be filled out with a bunch of questions -- please reopen a bug and fill those questions out/answer all the questions. This will give us a good idea of where to start.

**Comment by GregoryGH** [comment]
I see you guys very busy getting proper report format for 9 months already. Nvm then, I dont have eternity like you do.
https://github.com/AdiAddons/AdiBags/issues/551
