### ISSUE TITLE
TOC update version to 10.0.0

### ISSUE THREAD

**Issue by jisamcom** [AdiAddons/AdiBags#723]
TOC still has 9.2.7

## Interface: 90207

please update it to 10.0.0 = )

**Comment by Cidan** [comment]
yes it's on my list to get to, sorry! the power company decided that today
of all days, they would be doing 10 hour maintenance on my building, so no
power for a bit. I'll push the update tonight, but the latest release will
work on DF

**Comment by Cidan** [comment]
Fixed in #727 -- new release going out shortly.
