### ISSUE TITLE
Can we have options for Shadowlands?

### ISSUE THREAD

**Issue by jsauerland** [AdiAddons/AdiBags#724]
There's an adi bags add-on for Shadowlands that was abandoned. Current version of adi doesn't include separate containers for stuff like anima so it gets lost in your bags. Please consider this?

**Comment by Cidan** [comment]
You can manually create bag categories in AdiBags as you wish -- is there something specifically the plugin offers that manually categorizing things doesn't solve?

**Comment by SpareSimian** [comment]
I see this plugin for filtering anima: https://www.curseforge.com/wow/addons/adibags-anima-filter

**Comment by SiJiL82** [comment]
This Shadowlands filter still works fine for me https://www.curseforge.com/wow/addons/adibags-shadowlands
![image](https://user-images.githubusercontent.com/65114782/198214198-b6014b9f-377d-4083-aed3-808bdd58294c.png)

**Comment by jsauerland** [comment]
Closing this issue out since it is no longer relevant.
