### ISSUE TITLE
Bank Bags cannot be opened when AdiBags Bank Handling is Disabled

### ISSUE THREAD

**Issue by shawngmc** [AdiAddons/AdiBags#729]
**Describe the bug**
When AdiBags is set to NOT handle Bank management - ie, the default UI is used instead - the bank UI opens, but using B or clicking on a bag fails to open the bank bags.

**To Reproduce**
1. Ensure "Bags > Enabled Bags > Bank" is unchecked.
2. Open your bank
3. Click on a bank bag or hit B.

**Expected behavior**
One or more bank bags should appear, ideally using the default UI.

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Retail 10.0.0

**AdiBags Version**
- v1.9.40 beta
- This also occurs in v1.9.39 stable

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
Yes.

**Additional context**
Error message captured via BugSack:

1x Interface/FrameXML/ContainerFrame.lua:42: attempt to compare number with nil
[string "@Interface/FrameXML/ContainerFrame.lua"]:42: in function <Interface/FrameXML/ContainerFrame.lua:41>
[string "@Interface/FrameXML/ContainerFrame.lua"]:759: in function `CanUseForBagID'
[string "@Interface/FrameXML/ContainerFrame.lua"]:330: in function <Interface/FrameXML/ContainerFrame.lua:326>
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:80: in function `GetContainerFrame'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:115: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
id = nil
(*temporary) = 5
(*temporary) = "attempt to compare number with nil"

**Comment by Cidan** [comment]
I was able to reproduce this -- fix will come in the next version.

**Comment by Cidan** [comment]
Alright, found the bug and confirmed it is fixed for me locally. Once I sweep through the other bugs, I'll push the fix into .41.
