### ISSUE TITLE
AdiBags does not work on 10.0.2 (DF Beta/Mid Nov release)

### ISSUE THREAD

**Issue by arcadiatostark** [AdiAddons/AdiBags#732]
**Describe the bug**
Quality highlight and dim junk features are not working anymore with Dragonflight. These features stopped working right after I started playing with the opacity value.

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Retail 10.0.2

**AdiBags Version**
- v1.9.40

**Comment by Cidan** [comment]
I don't have access to 10.0.2, but there are major, major API changes for this version that will break all sorts of things for all bag addons. As soon as I have access to 10.0.2, I will resolve this.

**Comment by Cidan** [comment]
Using this bug as the main tracking bug for 10.0.2 issues. For those wondering, Blizzard is making major changes to the 10.0.2 bag API, as detailed [here](https://wowpedia.fandom.com/wiki/Patch_10.0.2/API_changes). Unfortunately, I do not have access to the DF beta, so this addon will likely break on release until I can fix it.

**Comment by Mal-content** [comment]
Hey, just wanted to let you know the issue persis on current live server too - aka Dragonflight pre-patch.

**Comment by Cidan** [comment]
There's a similar bug that I have fixed for the next release. See #758

**Comment by antonywpaul** [comment]
APpreciate the work you do on this awesome addon.

Also Blizzard should give you alpha access for the kind service you do for their user base!

**Comment by prathmell** [comment]
without a doubt this is the best bag addin/mod ever.  I'm lost without it.  Thank you for all the work you do maintaning this in a very complex and fast changing environment!
