### ISSUE TITLE
Bag opening/closing issue with guild bank

### ISSUE THREAD

**Issue by zalidthebur** [AdiAddons/AdiBags#733]
NOTE: Bugs can sometimes be caused by conflicts with other addons. Please disable all other addons and try to reproduce your issue. You must answer below that you have tried disabling all your addons before this bug is accepted. If you have not tried disabling all your addons, your bug will be closed.

**Describe the bug**
Bags do not auto-open at guild bank. Works elsewhere.
Bags do not auto-close on leaving guild bank (opened manually at guild bank). Works elsewhere.

**To Reproduce**
1. Go to Guild bank.
2. Open bags manually. Leave Guild bank

**Expected behavior**
Bags should auto-open/close when using guild bank.

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Retail 10.0.046313

**AdiBags Version**
- v1.90.40

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Comment by Cidan** [comment]
Confirmed this bug is valid, though I'm not sure off the top of my head what is causing it. We'll investigate it and get a fix out.

**Comment by zalidthebur** [comment]
Thanks :-)

**Comment by Cidan** [comment]
This also happens with the stock Blizzard UI, leading me to believe the bag open event isn't being fired when using the guild bank. Right now, unfortunately, there's not much we can do about this.

Sorry!

**Comment by zalidthebur** [comment]
Ah. Was wondering why it was not working with issue closed. Actually glad you realised it was not Adbags and started pulling your hair out :-)
Thanks. WIll put in a bug report :-)
