### ISSUE TITLE
Can not use Esc to close panels  in combat

### ISSUE THREAD

**Issue by class2u** [AdiAddons/AdiBags#737]
**Describe the bug**
Panels do not close in combat by pressing Esc key.

**To Reproduce**
1. Go into combat.
2. Open spell book (or other panels) in combat.
3. Press Esc key.
4. The spell book dose not close in combat. And there is a warning message in chat window.
5. Press P key (the default keybind), the spell book can be closed in combat.

**Expected behavior**
Press Esc key will close spell book even in combat.

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Retail 10.0.0, zhTW game client.

**AdiBags Version**
- v1.9.40

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Comment by Cidan** [comment]
Thanks for the report. Blizzard has changed some of this code to be protected now which makes this tricky to solve cleanly. We'll try to figure out the best way forward here.

**Comment by gygaxX** [comment]
please fix this issue asap.. we want to use adibag again.

**Comment by Cidan** [comment]
Fixed in #865
