### ISSUE TITLE
"S" button missing

### ISSUE THREAD

**Issue by Inosss** [AdiAddons/AdiBags#738]
**Describe the bug**
There is no "S" button on adibags frame, I can't combine multiple items into one stack. For example, I have 2 slots of 5 bandages. It is expected that when the "S" button is pressed, they will merge into one stack.

**To Reproduce**
1. Press "B" to open adibags
2. There is no "S" button

**Expected behavior**
The appearance of the "S" button

**Screenshots**
![OyO6jjdsnD](https://user-images.githubusercontent.com/7766868/198589709-ea5eda26-4b85-4ba6-841a-520bcf94a86f.png)

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - wotlk classic 3.4.0.46248

**AdiBags Version**
- 1.9.40

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Comment by Cidan** [comment]
Wrath of the Lich King has no bag sort API as Blizzard decided to not backport this feature. For the stackable items, make sure you have the "Merge unstackable items" button selected in the Items option menu.
