### ISSUE TITLE
Can't open config

### ISSUE THREAD

**Issue by esgiee** [AdiAddons/AdiBags#74]
When i try to open config for Adibags i get this message:
`9x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-63.lua:376: invalid order function for sorting
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-63.lua:376: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:344>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-63.lua:969: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:965>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-63.lua:988: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:965>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-63.lua:1021: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:999>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-63.lua:1690: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-63.lua:1883: in function `Open'
AdiBags\config\Options-Options.lua:688: in function `OpenOptions'
AdiBags\core\Core.lua:295: in function <AdiBags\core\Core.lua:289>
(tail call): ?

Locals:
(*temporary) = <table> {
 1 = "Equipment"
 2 = "description"
 3 = "Trade Goods"
 4 = "newAssoc"
 5 = "Armor"
 6 = "Junk"
 7 = "Ammunition"
 8 = "Consumable"
 9 = "BoA"
 10 = "Miscellaneous"
}
(*temporary) = <function> defined @ZygorGuidesViewer\Libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:314
(*temporary) = "BoA"
(*temporary) = "BoA"
(*temporary) = "Junk"
`

I'm playing on ElvUI UI.

**Comment by Cidan** [comment]
I'm going to close this unless you can confirm this is still happening.
