### ISSUE TITLE
Font Face and Height Bugs

### ISSUE THREAD

**Issue by nancikennedy** [AdiAddons/AdiBags#740]
**Describe the bug**
When attempting to change the font face or the font size, errors are produced.

**To Reproduce**
1. Go to AdiBags Options Skin tab
2. Change the font via the dropdown in either Bag title or Section header
3. Error 1 is produced
4. The drop down list updates to the new selection, but the bag appearance doesn't update until a reload
5.  Change the font height via the slider (the size field won't take any changes) in either section
6. Error 2 is produced
7. The fonts size field updates to the new selection, but the bag appearance doesn't update until a reload

**Expected behavior**
Font face and height should be updated.

**Screenshots**
- None.

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Retail 10.0.0.46340

**AdiBags Version**
- 1.9.43

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Additional context**

### Error 1

Message: Interface/AddOns/AdiBags/core/Fonts.lua:79: Usage: self:SetFont(fontFile, height, flags)
Time: Fri Oct 28 15:35:48 2022
Count: 4
Stack: Interface/AddOns/AdiBags/core/Fonts.lua:79: Usage: self:SetFont(fontFile, height, flags)
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/AdiBags/core/Fonts.lua"]:79: in function <Interface/AddOns/AdiBags/core/Fonts.lua:65>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/AdiBags/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:822: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:649>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...erface/AddOns/AdiBags/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/AdiBags/libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/AdiBags/libs/AceGUI-3.0-SharedMediaWidgets/FontWidget.lua"]:23: in function <...gs/libs/AceGUI-3.0-SharedMediaWidgets/FontWidget.lua:21>

Locals: <none>

### Error 2

Message: Interface/AddOns/AdiBags/core/Fonts.lua:79: Usage: self:SetFont(fontFile, height, flags)
Time: Fri Oct 28 15:30:16 2022
Count: 1
Stack: Interface/AddOns/AdiBags/core/Fonts.lua:79: Usage: self:SetFont(fontFile, height, flags)
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/AdiBags/core/Fonts.lua"]:79: in function <Interface/AddOns/AdiBags/core/Fonts.lua:65>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/AdiBags/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:822: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:649>
[string "@Interface/AddOns/AdiBags/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:879: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:867>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...erface/AddOns/AdiBags/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/AdiBags/libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/AdiBags/libs/AceGUI-3.0/widgets/AceGUIWidget-Slider.lua"]:65: in function <...Bags/libs/AceGUI-3.0/widgets/AceGUIWidget-Slider.lua:56>

Locals: <none>

**Comment by Cidan** [comment]
This was fixed in #730 and will be in the next release.
