### ISSUE TITLE
Add support for ElvUI Cooldown Text

### ISSUE THREAD

**Issue by MSav93** [AdiAddons/AdiBags#741]
**Please give us a brief overview (1-2 sentences) of what you would like to see added**
Weakauras recently added support for ElvUI Cooldown Text on their auras which prompted me to consolidate some of my addons (i.e., remove OmniCC and use Elv). Upon doing this I realised that AdiBags does not show ElvUI Cooldown Text (turns out only ElvUI bags do, not even default UI).

**Describe how you would like to see this feature implemented**
The changes WA made to add support seemed fairly minimal so I'm hoping the same would apply to AdiBags.
See [first commit](https://github.com/WeakAuras/WeakAuras2/commit/7ea2ac7292b14480788e13c9f5d003a0ee5733f5) and [second commit](https://github.com/WeakAuras/WeakAuras2/commit/9e6fef77ada27ba325150f474b9a4b0ac058738d) for their implementation

**Comment by Cidan** [comment]
This feels like a reasonable request, in particular since I'd like for AdiBags to play nice with the evolved ecosystem of WoW. We likely won't get to this until we finish some other things that need to be done, but if you'd like to send a PR and test it, we'd be happy to review it.

Thanks!
