### ISSUE TITLE
Error when opening my bank and can't switch to reagent bank

### ISSUE THREAD

**Issue by XtroTheArctic** [AdiAddons/AdiBags#745]
Various problems since Dragonflight prepatch.

I have the latest version 1.9.44 and I see this error when opening my bank. Also, Can't switch to reagent bank by clicking the R button on the top.

```
Message: Interface/AddOns/AdiBags/widgets/ItemButton.lua:327: attempt to call method 'UpdateCooldown' (a nil value)
Time: Sat Oct 29 02:27:09 2022
Count: 20
Stack: Interface/AddOns/AdiBags/widgets/ItemButton.lua:327: attempt to call method 'UpdateCooldown' (a nil value)
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:327: in function `Update'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:623: in function `Update'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:578: in function <Interface/AddOns/AdiBags/widgets/ItemButton.lua:571>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1034: in function `PrepareSections'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1155: in function `FullUpdate'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:599: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:585>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:100: in function <Interface/AddOns/AdiBags/core/Utility.lua:92>
[string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119: in function <Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108>

Locals: self = AdiBagsBankItemButton20 {
 0 = <userdata>
 bag = -1
 IconOverlay2 = Texture {
 }
 OnUpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:632
 inventorySlot = 77
 IconOverlay = Texture {
 }
 itemId = 131733
 SetAlpha = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:616
 stack = AdiBagsStackButton77 {
 }
 GetCount = <function> defined @Interface/AddOns/AdiBags/widgets/ItemButton.lua:479
 IconBorder = Texture {
 }
 bagFamily = 0
 GetItemLocation = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:604
 icon = AdiBagsBankItemButton20IconTexture {
 }
 container = AdiBagsContainer2 {
 }
 SetItemButtonTexture = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:655
 acquired = true
 UpdateTooltip = <function> defined @Interface/FrameXML/BankFrame.lua:59
 GetBagID = <function> defined @Interface/FrameXML/BankFrame.lua:151
 SetItem = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:538
 texture = 376832
 showMatchHighlight = true
 OnItemContextChanged = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:404
 itemLink = "[Spear of Rethu]"
 SetItemButtonQuality = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:643
 count = 1
 UpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:444
 SetItemSource = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:522
 SetItemButtonCount = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:608
 Cooldown = AdiBagsBankItemButton20Cooldown {
 }
 SetItemInternal = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:543
 IconTexture = AdiBagsBankItemButton20IconTexture {
 }
 UpdateCraftedProfessionsQualityShown = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:455
 itemContextMatchResult = 3
 NormalTexture = AdiBagsBankItemButton20NormalTexture {
 }
 GetItemButtonBackgroundTexture = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:663
 ItemContextOverlay = Texture {
 }
 PostOnShow = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:408
 UpdateItemContextOverlayTextures = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:493
 GetItemID = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:585
 GetItemButtonCount = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:612
 PostOnHide = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:417
 RegisterBagButtonUpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:638
 IconQuestTexture = Texture {
 }
 hasItem = true
 GetItemContextOverlayMode = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:465
 SetBagID = <function> defined @Interface/FrameXML/Ite
```

**Comment by koolman007** [comment]
**Similar issue with different kind of error.** 

20x Interface/AddOns/AdiBags/widgets/ItemButton.lua:327: attempt to call method 'UpdateCooldown' (a nil value)
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:327: in function `Update'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:623: in function `Update'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:578: in function <Interface/AddOns/AdiBags/widgets/ItemButton.lua:571>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1034: in function `PrepareSections'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1155: in function `FullUpdate'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:599: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:585>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:100: in function <Interface/AddOns/AdiBags/core/Utility.lua:92>
[string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119: in function <Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108>

Locals:
self = AdiBagsBankItemButton1 {
 0 = <userdata>
 bag = -1
 IconOverlay2 = Texture {
 }
 OnUpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:632
 inventorySlot = 70
 IconOverlay = Texture {
 }
 itemId = 171829
 SetAlpha = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:616
 stack = AdiBagsStackButton48 {
 }
 GetCount = <function> defined @Interface/AddOns/AdiBags/widgets/ItemButton.lua:479
 IconBorder = Texture {
 }
 bagFamily = 0
 GetItemLocation = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:604
 icon = AdiBagsBankItemButton1IconTexture {
 }
 container = AdiBagsContainer2 {
 }
 SetItemButtonTexture = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:655
 acquired = true
 UpdateTooltip = <function> defined @Interface/FrameXML/BankFrame.lua:59
 GetBagID = <function> defined @Interface/FrameXML/BankFrame.lua:151
 SetItem = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:538
 texture = 3731242
 showMatchHighlight = true
 OnItemContextChanged = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:404
 itemLink = "|cff1eff00|Hitem:171829::::::::60:253:::::::::|h[Solenium Ore]|h|r"
 SetItemButtonQuality = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:643
 count = 7
 UpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:444
 SetItemSource = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:522
 SetItemButtonCount = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:608
 Cooldown = AdiBagsBankItemButton1Cooldown {
 }
 SetItemInternal = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:543
 IconTexture = AdiBagsBankItemButton1IconTexture {
 }
 UpdateCraftedProfessionsQualityShown = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:455
 itemContextMatchResult = 3
 NormalTexture = AdiBagsBankItemButton1NormalTexture {
 }
 GetItemButtonBackgroundTexture = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:663
 ItemContextOverlay = Texture {
 }
 PostOnShow = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:408
 UpdateItemContextOverlayTextures = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:493
 GetItemID = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:585
 GetItemButtonCount = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:612
 PostOnHide = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:417
 RegisterBagButtonUpdateItemContextMatching = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:638
 IconQuestTexture = Texture {
 }
 hasItem = true
 GetItemContextOverlayMode = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:465
 SetBagID = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:624
 searchOverlay = AdiBagsBankItemButton1SearchOverlay {
 }
 SetMatchesSearch = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:435
 UpdateItemContextOverlay = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:482
 slot = 7
 GetItemButtonIconTexture = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:659
 GetItemLink = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:600
 PostOnEvent = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:421
 GetItemInfo = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:569
 SetItemButtonTextureVertexColor = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:651
 Stock = AdiBagsBankItemButton1Stock {
 }
 Count = AdiBagsBankItemButton1Count {
 }
 SetItemLocation = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:526
 GetItem = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:596
 GetMatchesSearch = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:440
 SetItemButtonBorderVertexColor = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:647
 Reset = <function> defined @Interface/FrameXML/ItemButtonTemplate.lua:504
}
icon = AdiBagsBankItemButton1IconTexture {
 0 = <userdata

**Comment by Cidan** [comment]
Fixed in .45 -- sorry about that, looks like one of the previous fixes was lost when I was switching branches fixing some other things.
