### ISSUE TITLE
Bank Bug persists.  v1.9.45 only fixed 1/2 of the errors. TY for working hard on Adibags though.

### ISSUE THREAD

**Issue by ZINK-ZINK** [AdiAddons/AdiBags#747]
80x Interface/AddOns/AdiBags/widgets/ItemButton.lua:390: attempt to call method 'UpdateCooldown' (a nil value)
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:390: in function `?'
[string "@Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...ker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...ker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function <...ker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:54>
[string "=(tail call)"]: ?

**Comment by Cidan** [comment]
Thanks Zink, fix going out now.

**Comment by ZINK-ZINK** [comment]
Just tested v1.9.45. No bank bugs at all and the reagent bank works properly. I thought you might appreciate a confirmation this version is working since the bug was stubborn.

**Comment by Cidan** [comment]
Thanks, highly appreciate it!
