### ISSUE TITLE
Default Combined Bag Broken When Using Adi to Manage Only Bank

### ISSUE THREAD

**Issue by dtown213** [AdiAddons/AdiBags#749]
NOTE: Bugs can sometimes be caused by conflicts with other addons. Please disable all other addons and try to reproduce your issue. You must answer below that you have tried disabling all your addons before this bug is accepted. If you have not tried disabling all your addons, your bug will be closed.

**Describe the bug**
When setting Adibags to only manage the bank, when using the Blizzard default "combine bags" setting, the bag interface will not close.  If you use the bag hotkey, or manually click on one of the bags on the bag bar, the associated bag will disappear from the combined bag, and display as a separate bag next to the main interface.  when attempting to close any or all bags, the item slots and bag interface stay on the screen.  Issue is not present when using default separate bags.

**To Reproduce**
1. Go to Options-->Addons-->Adibags-->Confgure
2. Uncheck "Backpack" 
3. Hit "B" to open bags
4. Attempt to close bags, by clicking "X" or hitting "B" again.

**Expected behavior**
Default Bag UI should open and close normally when set to have AdiBags manage only the bank.

**Screenshots**
![image](https://user-images.githubusercontent.com/87483652/198845487-c4ecd461-366f-437d-b4e2-e1a656f1417d.png)

**World of Warcraft Release and Version (Retail 9.2.7, etc)**
 - Retail 10.0.0.46340

**AdiBags Version**
- v1.90.44

**Have you tried disabling all your other addons to ensure only this addon causes the issue?**
 - Yes

**Comment by Cidan** [comment]
Confirmed and I'm able to reproduce this, there's definitely a lot of jank going on here. We'll get this fixed soon.

Thanks for the report!

**Comment by Cidan** [comment]
Fixed in #752 and will be in the next release.
