### ISSUE TITLE
Bank UI / store reagents broken

### ISSUE THREAD

**Issue by sthdevilish** [AdiAddons/AdiBags#750]
Got this when talked to bank npc and chose to bank all reagents (option was set to manual mode). Some reagents got moved to bank, but worst thing it also withdrawed some random items from the bank (in my case: sentinax beacons and some very old items from classic era). This is the error:

10x Interface/AddOns/AdiBags/widgets/ItemButton.lua:390: attempt to call method 'UpdateCooldown' (a nil value)
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:390: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:54>
[string "=(tail call)"]: ?

**Comment by Cidan** [comment]
Please refile this bug and use the bug template, and please answer the questions in the bug template, as they greatly aid in getting bugs fixed quickly.

Thanks.
