### ISSUE TITLE
Item price is displaced and not properly displayed (mostly on gear items)

### ISSUE THREAD

**Issue by XtroTheArctic** [AdiAddons/AdiBags#751]
![image](https://user-images.githubusercontent.com/6631429/198847848-cd83a444-1f60-4caa-8a01-fc6acb1197fb.png)

**Comment by Cidan** [comment]
Please refile this bug using the bug template, and please answer the bug template questions, as they are questions I would need to ask you anyway.

Thanks.

**Comment by XtroTheArctic** [comment]
I am sorry. Before I filed this, I tested it by disabling all addons and I still experienced the problem. I forgot to mention this earlier.

On the other hand, I just noticed that the problem is caused by an out-of-date AdiBags plugin: https://www.curseforge.com/wow/addons/adibags_garrison

While disabling all other addons, I think I didn't disable this one because its name starts with AdiBags.

Now I deleted the old plugin and it's working fine now.

Sorry again.
