### ISSUE TITLE
When using Adibags along with the auction house addon Auctionator, alt-clicking an item in the inventory no longer selects the item to sell. 

### ISSUE THREAD

**Issue by Kream** [AdiAddons/AdiBags#757]
### Addon Version

v1.9.46

### World of Warcraft Version

Retail

### Describe the bug

When using Adibags along with the auction house addon Auctionator, alt-clicking an item in the inventory no longer selects the item to sell. This was not the case in Shadowlands. I could alt-click items in the inventory and easily post them using Auctionator. 

I realise that issues that come up during interaction with other addons are fussy and tricky and not entirely in the control of the maintainers of this addon but auctionator is a major addon with 56 million installs and the interaction between Adibags (which is the best bag addon in wow ever) and Auctionator was very convenient. 

the issue does not persist when I disable Adibags - I am able to Alt-click to post the item using Auctionator. 

### Steps to reproduce

1. Install Auctionator v 10.0.3
2. Log into wow and interact with an auctioneer
3. Attempt to post an item by alt-clicking it 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Kream** [comment]
fwiw, I just realised that posting doesn't take place with combined bags in auctionator so this may in fact be an issue with the combined bags logic that I'm hypothesising that adibags shares with the Blizz code? 

cheers and thank you so much for your work in Adibags.

**Comment by Kream** [comment]
[FYI, this is the auctionator issue](https://github.com/Auctionator/Auctionator/issues/1251)

**Comment by Cidan** [comment]
I am unable to reproduce this issue with the Alpha that was linked in the bug fix from Auctionator. Using the latest version of both AdiBags and the Auctionator alpha does seem to fix this.

AdiBags doesn't use any combined bag logic from the Blizzard side at all, and I think this bug was purely an Auctionator bug.

Can you confirm?

**Comment by Kream** [comment]
> I am unable to reproduce this issue with the Alpha that was linked in the bug fix from Auctionator. Using the latest version of both AdiBags and the Auctionator alpha does seem to fix this.
> 
> AdiBags doesn't use any combined bag logic from the Blizzard side at all, and I think this bug was purely an Auctionator bug.
> 
> Can you confirm?

Yes, confirmed fixed - this seems to be purely an Auctionator bug. 🙏🏾
