### ISSUE TITLE
When selecting items, the quality border disappears 

### ISSUE THREAD

**Issue by Mrhgb** [AdiAddons/AdiBags#758]
### Addon Version

1.9.46

### World of Warcraft Version

Retail

### Describe the bug

When you select an item in your bags the quality border disappears from all icons. I have tried with all other addons disabled and it's the same.

https://gfycat.com/blissfulunfortunatehorseshoecrab

### Steps to reproduce

Open the bag
Select an item

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
I am able to reproduce this bug. It will be fixed in the next release.

**Comment by Mrhgb** [comment]
Great news, thanks!
