### ISSUE TITLE
attempt to compare number with nil

### ISSUE THREAD

**Issue by derekengel** [AdiAddons/AdiBags#761]
### Addon Version

v1.9.46

### World of Warcraft Version

Retail

### Describe the bug

When opening the bag I get the following error

Message: Interface/AddOns/AdiBags_Bound/Main.lua:251: attempt to compare number with nil
Time: Mon Oct 31 17:23:03 2022
Count: 7
Stack: Interface/AddOns/AdiBags_Bound/Main.lua:251: attempt to compare number with nil
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:88: in function <Interface/AddOns/AdiBags/core/Utility.lua:84>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/Filters.lua"]:146: in function `Filter'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:789: in function `FilterSlot'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:823: in function `DispatchItem'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:993: in function `RedispatchAllItems'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1151: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:1134>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:483: in function `RefreshContents'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:468: in function `ResumeUpdates'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:451: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:443>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:89: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:112: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: <none>

### Steps to reproduce

Opening bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Hey there,

This error is not an AdiBags error -- it is a third party addon (AdiBags_Bound), which is not run by us. Please reach out to that addon author for the fix.

**Comment by SpareSimian** [comment]
I'm not sure if anyone maintains it, but it's one I use. I've been avoiding the game while addons get fixed and once I return (maybe in another week), I'll take a look and see if I can get it working again. It was not eligible to become a builtin plugin because it depends on tooltip parsing, which the Adibags developers rightly avoid for performance reasons. But the new tooltip info API might make it eligible.

**Comment by SpareSimian** [comment]
AdiBags_Bound was abandoned years ago and reclaimed as AdiBags_BoE_BoA, then abandoned again. But there's a patch here in that addon's comments to make it work with DF: https://www.curseforge.com/wow/addons/adibags-boe-boa

Change the line that creates the tooltip to this (ie. add the addon name as a second argument):
```
local tip, leftside = CreateFrame( "GameTooltip", "AdiBagsBoEBoAScan" ), {} 
```

I'm debating adopting the addon in my own GitHub account and updating it with these changes, along with a release so 3rd party addon managers can use it. (I use Ajour and love it.)

**Comment by derekengel** [comment]
> AdiBags_Bound was abandoned years ago and reclaimed as AdiBags_BoE_BoA, then abandoned again. But there's a patch here in that addon's comments to make it work with DF: https://www.curseforge.com/wow/addons/adibags-boe-boa
> 
> Change the line that creates the tooltip to this (ie. add the addon name as a second argument):
> 
> ```
> local tip, leftside = CreateFrame( "GameTooltip", "AdiBagsBoEBoAScan" ), {} 
> ```
> 
> I'm debating adopting the addon in my own GitHub account and updating it with these changes, along with a release so 3rd party addon managers can use it. (I use Ajour and love it.)

The addon author corrected the error and updated the addon. https://github.com/AvyAddons/AdiBags_Bound/issues/2

**Comment by SpareSimian** [comment]
@derekengel Wow! I just looked at Avy's code and it's very nice. While it still has to scan the tooltip, it maintains a cache so it only does it once, which should address the performance issue that blocks it from being a built-in plugin. Bravo. I just added it to Ajour for automatic updates.
