### ISSUE TITLE
[Feature]: More control over the icon overlay positions

### ISSUE THREAD

**Issue by nancikennedy** [AdiAddons/AdiBags#762]
### Describe the feature

There are a couple of quality of life features that would make the icon overlays work a little more cooperatively with other addons overlays.

ilevel feature: Be able to change font face, font size, and anchor position
upgrade arrow: Ability to change the arrow size & anchor position.

### Describe the implementation

Giving the ilevel and overlay icons the same treatment as the other font and sizing options that other elements in AdiBags already have would work.

**Comment by chilblane** [comment]
I believe the Pawn upgrade arrow currently gets covered by the Can I Mog It? icon, so that would be a nice thing to edit.

**Comment by nancikennedy** [comment]
Can I Mog It has an option to change the anchor of their icon overlay, I believe

**Comment by chilblane** [comment]
Yeah but I wouldn't mind equal flexibility in both pawn-adibags and CIMI

**Comment by Talyrius** [comment]
There are already pending pull requests for these features (see #496 & #499).
