### ISSUE TITLE
UI spitting 1654 errors from Adibags

### ISSUE THREAD

**Issue by Rycia** [AdiAddons/AdiBags#764]
### Addon Version

v1.9.46

### World of Warcraft Version

Retail

### Describe the bug

1654x bad argument #5 to '?' (Usage: self:SetTextColor(color [, a]))
[string "=[C]"]: in function `SetTextColor'
[string "@Interface/AddOns/AdiBags/modules/ItemLevel.lua"]:170: in function `?'
[string "@Interface/AddOns/LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:317: in function `Update'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:577: in function `Update'
[string "@Interface/AddOns/AdiBags/widgets/ItemButton.lua"]:532: in function <Interface/AddOns/AdiBags/widgets/ItemButton.lua:525>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:954: in function `PrepareSections'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:1060: in function `FullUpdate'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:565: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:551>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:89: in function <Interface/AddOns/AdiBags/core/Utility.lua:81>
[string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119: in function <Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108>

### Steps to reproduce

Exist.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Thanks, we'll get this patched for the next major release.

**Comment by Talyrius** [comment]
This should be fixed. If not, please open a new issue.
