### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by MarcLFJ** [AdiAddons/AdiBags#765]
### Addon Version

v1.9.46

### World of Warcraft Version

Retail

### Describe the bug

Getting a LUA error after loading into the game

7x AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "COVENANT_SANCTUM_INTERACTION_STARTED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface/AddOns/LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface/AddOns/DataStore_Covenants/DataStore_Covenants.lua"]:435: in function <...e/AddOns/DataStore_Covenants/DataStore_Covenants.lua:426>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

### Steps to reproduce

1. Install latest addon version
2. Load up the game

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
This is an AceEvent-3.0 error caused by **DataStore_Covenants** which should be deleted from your addons folder according to the changelog for [Altoholic v9.0.003](https://www.curseforge.com/wow/addons/altoholic/files/3167597):

> - The following DataStore modules are no longer part of the project, and are not supported : **DataStore_Rares, DataStore_Keystones, DataStore_Covenants**.

The only reason AdiBags is mentioned at all in the above error is because both addons make use of the same shared library.
