### ISSUE TITLE
[Feature]: Item level threshold for "junk"

### ISSUE THREAD

**Issue by Compleks96** [AdiAddons/AdiBags#766]
### Describe the feature

When doing legacy content I pick up quite a lot of low ilvl equipment that i will vendor. Would be nice with a filter to say "anything below xxx ilvl is junk", so I can easily distuingish between the gear.

### Describe the implementation

I'm thinking a slider to adjust ilvl threshold would be nice, or perhaps just a text field.
Since ilvl and equipment are already accessible within the addon probably it's not too bad?

**Comment by Talyrius** [comment]
This feature is already available via a third-party addon:
[AdiBags_Lowlevel](https://www.curseforge.com/wow/addons/adibags_lowlevel)
