### ISSUE TITLE
bugsac

### ISSUE THREAD

**Issue by Milky063** [AdiAddons/AdiBags#774]
### Addon Version

newest one. 

### World of Warcraft Version

Retail

### Describe the bug

2x ...face/AddOns/AdiBags/libs/AceHook-3.0-9/AceHook-3.0.lua:180: Attempting to rehook already active hook SetGetMinimapShape.
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceHook-3.0-9/AceHook-3.0.lua"]:180: in function <...face/AddOns/AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/AdiBags/libs/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Maps/RectangleMinimap.lua"]:97: in function `SetUpdateHook'
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Maps/RectangleMinimap.lua"]:112: in function `?'
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...vUI/Libraries/Core/Ace/AceEvent-3.0/AceEvent-3.0.lua:119>

### Steps to reproduce

i just zoned into a new area and keeps popping up. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
This is an AceHook-3.0 error caused by **ElvUI_WindTools**. The only reason AdiBags is mentioned at all in the above error is because both addons make use of the same shared library.
