### ISSUE TITLE
[Feature]: ElvUI/Clean Skin

### ISSUE THREAD

**Issue by LiamGBR** [AdiAddons/AdiBags#776]
### Describe the feature

Would a skin option directly in the addon be a possibility? Been relying on https://www.curseforge.com/wow/addons/elvui-adibags for a long time but its rarely updated quick enough to the point where I could be missing features for a while. (author has logged in recently but last update 9.0.5) It also usually has strange behaviour after an update where it may not work correctly without a full reinstall.

### Describe the implementation

Unsure of how much effort would be needed for this but nows probably the best time to ask about it. Implemented with maybe a toggle in the settings somewhere.

**Comment by juntereiner** [comment]
More recently, there is https://www.curseforge.com/wow/addons/elvui-adibags-wrath which works before prepatch. But I agree, if possible it will be much better to have this option here.

**Comment by Zazou49** [comment]
I agree ! Unfortunately https://www.curseforge.com/wow/addons/elvui-adibags seems abandoned.

**Comment by Beet4** [comment]
YES! Please :D built in skin from Elvui Adibags would be awesome

**Comment by ryankhart** [comment]
> I agree ! Unfortunately https://www.curseforge.com/wow/addons/elvui-adibags seems abandoned.

Looks like someone forked the original ElvUI_Adibags addon and there is an alpha branch on this repository, but at this moment is completely untested, but you might get lucky with it.
https://github.com/Bauxite/ElvUI_AdiBags/tree/df_alpha

**Comment by LiamGBR** [comment]
Author of ElvUI plugin WindTools has released https://www.curseforge.com/wow/addons/adibagselvuiskin which doesn't require replacing the actual AdiBags addon so will use that for now.

**Comment by Zazou49** [comment]
Awesome, a bit afraid of the Readme : 

> because the hack of AdiBags is not a very easy thing for me, to avoid blocking the method currently using, I make the core code not easy to read.
> but you can also add some post function for applying more styling things with the apis. check api.lua if you needed.

**Comment by ryankhart** [comment]
> because the hack of AdiBags is not a very easy thing for me, to avoid blocking the method currently using, I make the core code not easy to read.
> but you can also add some post function for applying more styling things with the apis. check api.lua if you needed.

Wut... Is there another possible interpretation of this than, "I don't want people to copy, make changes, and redistribute my code so I'm intentionally obfuscating it."? That's what it sounds like me after looking had the Core.lua file.

**Comment by Zazou49** [comment]
> > because the hack of AdiBags is not a very easy thing for me, to avoid blocking the method currently using, I make the core code not easy to read.
> > but you can also add some post function for applying more styling things with the apis. check api.lua if you needed.
> 
> Wut... Is there another possible interpretation of this than, "I don't want people to copy, make changes, and redistribute my code so I'm intentionally obfuscating it."? That's what it sounds like me after looking had the Core.lua file.

Unfortunately yes, I don’t understand why Adbibags devs here would patch her addon lol
