### ISSUE TITLE
7th Bank Bag inaccessible

### ISSUE THREAD

**Issue by glassleo** [AdiAddons/AdiBags#778]
### Addon Version

1.9.46

### World of Warcraft Version

Retail

### Describe the bug

If you want to equip/swap out the 7th bag in your bank using AdIBags, you just get an error message saying "No equipment slots for that item" and nothing happens.

In AdiBags this looks like the first bank bag (leftmost slot) but in the default UI it's the last bank bag (rightmost slot). The other 6 bag slots work as expected. And if you have a bag equipped, there are no issues accessing the contents using AdiBags. It's just the bag swapping/equipping part that isn't working.

### Steps to reproduce

1. Go to your bank
2. Click the "Equipped Bags" button in the bank frame
3. Try to swap out the first bag slot with a different bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Fixed in .48. Please open another issue if you see this come up again.
