### ISSUE TITLE
Phase 2 Prepatch Errors

### ISSUE THREAD

**Issue by yajinni** [AdiAddons/AdiBags#779]
### Addon Version

1.9.46

### World of Warcraft Version

Retail

### Describe the bug

Bags doesnt work/open. Errors i am getting.

### Error 1
4x Interface/AddOns/AdiBags/widgets/BagSlots.lua:227: attempt to call upvalue 'ContainerIDToInventoryID' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function `Create'
[string "@Interface/AddOns/AdiBags/widgets/BagSlots.lua"]:464: in function `CreateBagSlotPanel'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:172: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:98>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:100: in function <Interface/AddOns/AdiBags/core/Utility.lua:92>
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function <Interface/AddOns/AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:112: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

### Error 2
1x Interface/AddOns/AdiBags/widgets/Section.lua:130: attempt to call upvalue 'BuildSectionKey' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:155: in function <Interface/AddOns/AdiBags/core/OO.lua:142>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:226: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:98>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:100: in function <Interface/AddOns/AdiBags/core/Utility.lua:92>
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function <Interface/AddOns/AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:112: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

### Error 3
1x Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:264: Usage: RegisterMessage("eventname", "methodname"): self was not a table?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/OO.lua"]:60: in function <Interface/AddOns/AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:129: in function `GetFrame'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:83: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:112: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

### Error 4
1x Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:638: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:638: in function `UpdateContent'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:481: in function `RefreshContents'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:468: in function `ResumeUpdates'
[string "@Interface/AddOns/AdiBags/widgets/ContainerFrame.lua"]:451: in function <Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:443>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:89: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:112: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = AdiBagsContainer1 {
 0 = <userdata>
 firstLoad = true
 HeaderLeftRegion = AdiBagsSimpleLayeredRegion1 {
 }
 isBank = false
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 BagSlotButton = CheckButton {
 }
 BottomLeftRegion = AdiBagsSimpleLayeredRegion3 {
 }
 sameChanged = <table> {
 }
 forceLayout = true
 isReagentBank = false
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 paused = false
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 Center = Texture {
 }
 RightEdge = Texture {
 }
 LeftEdge = Texture {
 }
 content = <table> {
 }
 BottomEdge = Texture {
 }
 removed = <table> {
 }
 Anchor = AdiBagsBagAnchor1 {
 }
 itemGUIDtoItem = <table> {
 }
 sections = <table> {
 }
 BottomRightCorner = Texture {
 }
 changed = <table> {
 }
 added = <table> {
 }
 ToSortSection = AdiBagsSection1 {
 }
 BottomLeftCorner = Texture {
 }
 stacks = <table> {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 TopRightCorner = Texture {
 }
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 }
 dirtyLayout = true
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 Content = Frame {
 }
 buttons = <table> {
 }
 TopEdge = Texture {
 }
 HeaderRightRegion = AdiBagsSimpleLayeredRegion2 {
 }
 BottomRightRegion = AdiBagsSimpleLayeredRegion4 {
 }
 widgets = <table> {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 CloseButton = Button {
 }
 Title = AdiBagsContainer1Title {
 }
 bagObject = <table> {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 BagSlotPanel = AdiBagsContainer1Bags {
 }
 name = "Backpack"
}
bag = 1
added = <table> {
}
removed = <table> {
}
changed = <table> {
}
sameChanged = <table> {
}
content = <table> {
 size = 0
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
GetContainerNumSlots = nil
GetContainerNumFreeSlots = nil
GetContainerItemID = nil
GetContainerItemLink = nil
addon = <table> {
 AcquireItemButton = <function> defined @Interface/AddOns/AdiBags/widgets/ItemButton.lua:173
 FAMILY_TAGS = <table> {
 }
 UpdateFilters = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:83
 SecureHook = <function> defined @Interface/AddOns/AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:335
 GetInteractingWindow = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:440
 ConfigChanged = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:360
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 Filter = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:144
 IsEnabled = <function> defined @Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 Reconfigure = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:190
 SetupTooltip = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:125
 RegisterMessage = <function> defined @Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:301
 CreateFont = <function> defined @Interface/AddOns/AdiBags/core/Fonts.lua:122
 isClassic = false
 db = <table> {
 }
 OpenOptions 
 
###  Error 5
 1x Interface/AddOns/AdiBags/core/Layout.lua:62: attempt to index field 'anchor' (a nil value)
[string "@Interface/AddOns/AdiBags/core/Layout.lua"]:62: in function <Interface/AddOns/AdiBags/core/Layout.lua:61>
[string "@Interface/AddOns/AdiBags/core/Layout.lua"]:111: in function `?'
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `SendMessage'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:90: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:112: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

### error 6
1x Interface/AddOns/AdiBags/widgets/ContainerFrame.lua:599: attempt to call method 'FullUpdate' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/AdiBags/widgets/LayeredRegion.lua"]:119: in function <Interface/AddOns/AdiBags/widgets/LayeredRegion.lua:108>

### Steps to reproduce

Trying to open the bags in any way.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
See #732, #782, #788, #790, & #759.
