### ISSUE TITLE
Broken on 10.x 11/15 patch

### ISSUE THREAD

**Issue by rodalpho** [AdiAddons/AdiBags#780]
### Addon Version

latest

### World of Warcraft Version

Retail

### Describe the bug

Message: Interface/AddOns/AdiBags/core/Utility.lua:334: Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
Time: Tue Nov 15 18:38:29 2022
Count: 1
Stack: Interface/AddOns/AdiBags/core/Utility.lua:334: Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
[string "=[C]"]: in function `GetItemSubClassInfo'
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:334: in main chunk

Locals: (*temporary) = nil
(*temporary) = 0

### Steps to reproduce

play game

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Rycia** [comment]
Bags won't even open for me and I have to have Adibags disabled to open my bags at all.

**Comment by Cidan** [comment]
Please see #782 for updates!
