### ISSUE TITLE
Does not work at all with most recent patch

### ISSUE THREAD

**Issue by Wraiven** [AdiAddons/AdiBags#785]
### Addon Version

10.0.2

### World of Warcraft Version

Retail

### Describe the bug

Addon does not work at all, when trying to open gives a weird bar i can move but that's all.

Ty so much for your hard work! This is my favorite addon and a must have for the game. 

### Steps to reproduce

Open bag in game

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cackles** [comment]
Went down on 11/16/2022. Tried almost everything, but does not work (Hit 'B' nothing happens). A possible clue is I did not purchase that new expansion - I'm am still on Shadowlands levelling alts.

**Comment by SpareSimian** [comment]
It's being handled on issue #782. I suggest closing this and using the temporary version found there.

**Comment by Wraiven** [comment]
Closing issue per SpareSimian post above
