### ISSUE TITLE
Bags not displaying.

### ISSUE THREAD

**Issue by maguilu** [AdiAddons/AdiBags#787]
### Addon Version

1.9.46

### World of Warcraft Version

Retail

### Describe the bug

I can access the addon config and other configuration-related items but when trying to open the bags, all that happens is the sound of the bags opening but can't see the bags
 Once I disable the addon the bags display again 

### Steps to reproduce

just open the bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Spinum** [comment]
I can confirm/repeat the above behavior. Disabled all addons except AdiBags v1.9.46.

**Comment by lunamoth** [comment]
I'm also having a problem with the AdiBags bag not opening. (1.9.46)

**Comment by NoahDavidATL** [comment]
Same. Addon doesn't work on 10.0.2

**Comment by Elboufda** [comment]
same for me

**Comment by SpareSimian** [comment]
Duplicate of #782. I recommend closing this and continuing there.
