### ISSUE TITLE
finally broken

### ISSUE THREAD

**Issue by perrins21** [AdiAddons/AdiBags#79]
well i was dreading this bc this is probably one of the best bag addons in existence. but its sad to say this now, i believe its finally broken. the new patch seems to have borked the addon totally. you can load it in the game but when you open your bags nothing appears. if by some miracle it gets updated i will be so extremely happy. i loved the way you could organize EVERYTHING in the specifics you wanted.

**Comment by mpfiv** [comment]
If you look at activity you notice changes were merged.

**Comment by perrins21** [comment]
what does that mean? is there hope for this yet?

**Comment by Cidan** [comment]
@perrins21 Me and a few other people did some simple fixes to AdiBags. If you go back to the main code page on GitHub and download the zip (green button, top right) and extract the contents over your old install (don't delete what's in there), you'll have working AdiBags in Legion.

**Comment by Elpiase** [comment]
I downloaded the zip file, installed but the add on is still broken.
When i open bags i got this error:

Message: ..\AddOns\AdiBags\core\Utility.lua line 168:
   Usage: GetItemInfo(itemID|"name"|"itemlink")
Debug:
   ...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317:
      ...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300
   AdiBags\core\Utility.lua:77:
      AdiBags\core\Utility.lua:73
   (tail call): ?
   AdiBags\widgets\LayeredRegion.lua:119:
      AdiBags\widgets\LayeredRegion.lua:108

**Comment by Debuggernaut** [comment]
Thanks for fixing it, guys!  If I run into any trouble I'll be sure to report back here, hopefully with a fix

**Comment by Cidan** [comment]
@Elpiase That's interesting, I've yet to see that happen to me ever since I excluded invalid item id's. Does line 167 of core\Utility.lua say something like: `if not id then return end` or does it say something different?

Also, feel free to try my fork directly: https://github.com/Cidan/adibags

**Comment by OUGHT** [comment]
Direct fork does not work and throws a bunch of errors:

3x AdiBags\Localization.lua:61: Cannot find a library instance of "LibBabble-Inventory-3.0".
3x AdiBags\core\Utility.lua:196: attempt to index field 'BI' (a nil value)
3x AdiBags\core\Core.lua:47: Cannot find a library instance of "AceAddon-3.0".
3x AdiBags\core\Bags.lua:151: attempt to call method 'Debug' (a nil value)
3x AdiBags\widgets\ContainerFrame.lua:697: attempt to index field 'BI' (a nil value)
3x AdiBags\widgets\ItemButton.lua:159: hooksecurefunc(): OnInitialize is not a function
3x AdiBags\Localization.lua:37: attempt to call method 'Debug' (a nil value)
3x AdiBags\modules\DataSource.lua:38: attempt to call method 'NewModule' (a nil value)
3x AdiBags\core\Filters-Фильтры.lua:126: attempt to call method 'NewModule' (a nil value)
3x AdiBags\modules\MoneyFrame.lua:30: attempt to call method 'NewModule' (a nil value)

**Comment by Cidan** [comment]
@OUGHT You need to make sure you install the dev version on top of the latest release build. The dev build doesn't have all the deps bundled with it. In laymen's terms, install the version from Curse, then extract the github build on top of it, and replace the files in there.

**Comment by OUGHT** [comment]
Yes, I found it myself. I thought your fork do not need 'old' AdiBags =-)

**Comment by Elpiase** [comment]
@Cidan row 167 say exactly `if not id then return end`
I tried your fork but it's still not working.

**Comment by Cidan** [comment]
@Elpiase Interesting! Can you add a line above row 167 that says `print(id)` then tell me what your chat log outputs? It will be in white text.

**Comment by Elpiase** [comment]
It turns out i'm just stupid and I was editing in a back-up folder... i moved the new files in the correct one and now it's working. :)
Thanks anyway for your help

**Comment by Cidan** [comment]
No problem :)

**Comment by Malkom** [comment]
Work nice for me and I don't have any error...

I had one but I changed the line 142 in ChangeHighlight/lua : 

--alpha:SetChange(-1)

and work perfectly ;)
