### ISSUE TITLE
Adibags not working

### ISSUE THREAD

**Issue by Traumalock** [AdiAddons/AdiBags#792]
### Addon Version

v1.9.46

### World of Warcraft Version

Retail

### Describe the bug

After installing Adibags and loading into the retail client, I am unable to access my bags.  If I click on the  bags or hit the B button nothing pops up, no bags show. I do not get any error I just lose access to my bags. I have tried to disable all other add ons and only load Adibags and the same issue occurs.

### Steps to reproduce

Install adibags and log in

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
See #732, #782, #788, #790, & #759.
