### ISSUE TITLE
Adibags display dont work 

### ISSUE THREAD

**Issue by odtheman** [AdiAddons/AdiBags#796]
### Addon Version

v10.00

### World of Warcraft Version

Retail

### Describe the bug

Addon is unusable right now, i cant see any of my things in my bags. 

https://gyazo.com/1cea35fa14fc8862d01c68e512f66d23

This is how it looks since the start of phase 2. 
I have turned all of my other addons off and also tried to reinstall the addon. 

### Steps to reproduce

1. Use the addon.. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by akaRaven** [comment]
I just downloaded this https://github.com/AdiAddons/AdiBags and it worked.

The one from Curseforge or Wowup or wherever is currently doing nothing.

Confirmed that link works with and without a host of other addons, just now setting up my hearthstones and categories.

**Comment by MleveK** [comment]
> I just downloaded this https://github.com/AdiAddons/AdiBags and it worked.
> 
> The one from Curseforge or Wowup or wherever is currently doing nothing.
> 
> Confirmed that link works with and without a host of other addons, just now setting up my hearthstones and categories.
> 
> Confirmed also the reagent bag not working, issue has been raised for this.

See #790 Check for V5.3

**Comment by Cidan** [comment]
Duplicate of #782
