### ISSUE TITLE
[Feature]: Currencies: Select/Deselect All

### ISSUE THREAD

**Issue by monoliith** [AdiAddons/AdiBags#798]
### Describe the feature

Severeal times I've recommended this addon to people, they've uninstalled it because it auto-tracks about 80 currencies from across the game, and they aren't big on customizing addons. 

### Describe the implementation

I'd love a "check all/uncheck all" button for currencies. Also, if, by default, the current expansions were currencies were all that were enabled would probably be a good thing. Just for general users who don't min/max their ui. They just want good, working stuff.
![Screenshot_20221120_101349](https://user-images.githubusercontent.com/65993671/202964287-bcc7c731-0a52-4de3-9696-c5d8c4bc5b62.png)

**Comment by SpareSimian** [comment]
By "current expansion", note which expansion the player has access to. I'm not planning to buy DF any time soon, nor did I buy BFA, so for me, the current expansion is actually the previous one.

**Comment by Talyrius** [comment]
> Severeal times I've recommended this addon to people, they've uninstalled it because it auto-tracks about 80 currencies from across the game, and they aren't big on customizing addons.

Only new currencies are tracked by default, so new users of the addon would only see the currencies they've interacted with since using it. Untracking currencies is a fairly trivial task that most users are able to intuit. 🤔
