### ISSUE TITLE
Reagent bank "blizzard sorting" gives an error

### ISSUE THREAD

**Issue by antedap** [AdiAddons/AdiBags#799]
### Addon Version

v.1.9.47

### World of Warcraft Version

Retail

### Describe the bug

2x AdiBags/core/Bags.lua:298: attempt to call global 'SortReagentBankBags' (a nil value)
[string "@AdiBags/core/Bags.lua"]:298: in function `Sort'
[string "@AdiBags/widgets/ContainerFrame.lua"]:363: in function <AdiBags/widgets/ContainerFrame.lua:361>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 isBank = true
 Enable = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHook = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:335
 defaultModuleLibraries = <table> {
 }
 PostDisable = <function> defined @AdiBags/core/Bags.lua:264
 RawHookScript = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:394
 PostClose = <function> defined @AdiBags/core/Bags.lua:290
 SetDefaultModulePrototype = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 frame = AdiBagsContainer2 {
 }
 name = "AdiBags_Bank"
 baseName = "AdiBags"
 IsEnabled = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 bagIds = <table> {
 }
 DisableModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 BankFrameGetRight = <function> defined @AdiBags/core/Bags.lua:304
 Sort = <function> defined @AdiBags/core/Bags.lua:295
 PreOpen = <function> defined @AdiBags/core/Bags.lua:283
 CanOpen = <function> defined @AdiBags/core/Bags.lua:279
 RegisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 AdiBags_InteractingWindowChanged = <function> defined @AdiBags/core/Bags.lua:271
 GetName = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 IsHooked = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:492
 order = 20
 bagName = "Bank"
 IsModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 hooks = <table> {
 }
 SetDefaultModuleState = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 SendMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 UnhookAll = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:476
 SetEnabledState = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 Unhook = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:417
 RegisterEvent = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 SecureHookScript = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:409
 HookScript = <function> defined @ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:365
 defaultModuleState = true
 IterateModules = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:433
 UnregisterAllEvents = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 RawHook = <func

### Steps to reproduce

1 Open the bank
2 Switch to the reagent bank
3 Click "Blizzard Sorting"

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
I've confirmed and reproduced this. Fix on the way!

**Comment by Cidan** [comment]
Fixed in .48, which is live now.
