### ISSUE TITLE
Updated version missing regeant bag that was in commit build

### ISSUE THREAD

**Issue by picklerick84** [AdiAddons/AdiBags#805]
### Addon Version

v1.9.47

### World of Warcraft Version

Retail

### Describe the bug

The regeant bag is completely missing in this build that worked fine in the v5.3 build that was up here.

Also because the regeant bag doesn't show.  If you have a regeant bag from prepatch event and loot something that goes into it, it disappears because it is in the regeant bag you can't see.

### Steps to reproduce

Loot something that is a regeant.  Open bags and you can't see it or interact with it.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
This is a known issue and was outlined in the release notes. The updated features will come at a later date (next day or so).
