### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Stickumnote** [AdiAddons/AdiBags#807]
### Addon Version

1.9.48

### World of Warcraft Version

Retail

### Describe the bug

Error displaying currency when using the currency plugin

### Steps to reproduce

I am not sure, I Enable currency and the error happens, I am not a programmer.

Message: Interface/AddOns/AdiBags/modules/CurrencyFrame.lua:257: attempt to index local 'cell' (a nil value)
Time: Tue Nov 22 17:57:45 2022
Count: 1
Stack: Interface/AddOns/AdiBags/modules/CurrencyFrame.lua:257: attempt to index local 'cell' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:138: in function `GetFrame'
[string "@Interface/AddOns/AdiBags/core/Bags.lua"]:90: in function `Open'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:112: in function <Interface/AddOns/AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: <none>

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Which currencies do you have enabled?

**Comment by cwwood0322** [comment]
Although you can click configure every setting option is greyed out. Only seeing separate bags.

**Comment by Stickumnote** [comment]
Hello,

I had them all checked and it only gives me the errors when I log into an
account which has a lot of different currencies. I believe I have narrowed
it down to the addon only being able to display a certain amount of types
and I am over that number. I can enable them until I reach the error, back
off by 1 then I am fine. it appears to be around 48-49 types enabled when
the error is generated.

**Comment by Talyrius** [comment]
Closing in favor of #824.
