### ISSUE TITLE
[Feature]: Separate regular bag free space and reagent bag free space

### ISSUE THREAD

**Issue by DoveCannon** [AdiAddons/AdiBags#808]
### Describe the feature

Right now the bag free space and reagent bag free space are being combined into the same space. This makes it hard to tell how much actual free space our bags have left as reagent slots can't hold non-reagents.

### Describe the implementation

Add a check box to have free bag space and free reagent bag space separated into two sections. Personally I use the option to stack free space, and as such I'd prefer to have two stacks. One stack of free bag space and one stack of free reagent bag space.

**Comment by Cidan** [comment]
Thanks for the request -- this is already slated to be done in the next few versions.

**Comment by DoveCannon** [comment]
Excellent, good to know, thanks!

**Comment by Talyrius** [comment]
Fixed via bd25cbb.
