### ISSUE TITLE
Bank bags still not showing correctly, offered for me to buy a slot for 99K gold

### ISSUE THREAD

**Issue by Gnathach** [AdiAddons/AdiBags#809]
### Addon Version

v1.9.48

### World of Warcraft Version

Retail

### Describe the bug

Newest version is showing 7 bag slots but still not working correctly.  The right most bag in the equipped bags display is red, and if I drag the bag out of it and try to put it back, it offers for me to buy a bank slot for 99,999g 99s 99c.

### Steps to reproduce

1. Open bank
2. toggle bag display
3. drag bag out of the right most slot
4. try to put the bag back in the slot

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Gnathach** [comment]
awesome.  I seem to remember it was working in the temporary fix last week that someone did

**Comment by Talyrius** [comment]
Fixed via 84ac7d0.
