### ISSUE TITLE
Masque support

### ISSUE THREAD

**Issue by PINCHO93** [AdiAddons/AdiBags#81]
Now that you have updated the addon for Legion, could you add support for masque?

**Comment by Cidan** [comment]
What parts of the UI would you like to see use Masque?

**Comment by PINCHO93** [comment]
The actual items in my bag. So far the "custom" code is working (minor issue with the empty bag slots) So imo it should be fixed and added.

**Comment by Talyrius** [comment]
For reference, experimental masque support was added in 239ac142fa13f4b66393004e3a22943c8ae74638 and subsequently reverted via 7f88d1369ee029fd339890dfb7d1408042dd7fe9.

**Comment by Cidan** [comment]
This will probably be a longer term project after Legion launches. I'll look into it.

**Comment by Adirelle** [comment]
IIRC, Masque is intended to work with action buttons, which have not the same layers and components than item buttons. Some of the useful features of a bag addon could not work with Masque skinning.

**Comment by Cidan** [comment]
That makes sense; I don't mind taking at the very least a cursory look at Masque support as I'm sure it has changed over the years.

**Comment by SethWilliamson** [comment]
For reference, someone seems to have figured it out for Bagnon. Perhaps a glance at their code might help point you in the right direction.  https://wow.curseforge.com/projects/bagnon-facade

**Comment by Breavyn** [comment]
This really isn't that hard to integrate. I created a basic implementation before I stopped playing in legion. If it's something you would like I can clean the code up and submit a pull request.

![masque image](https://user-images.githubusercontent.com/29270083/43988359-55d4266a-9d77-11e8-89fa-27996563f38b.png)

**Comment by Talyrius** [comment]
@Breavyn
How does your implementation differ from 239ac14? Does it account for the additional layers found in item buttons?

**Comment by altusgerona** [comment]
@Talyrius @Breavyn @Cidan Any updates on this? Happy to help with the PR.

**Comment by hugombu94** [comment]
Hey! Just downloaded AdiBags and I love it! I was wondering how the Masque support is coming along? I saw that a user (Breavyn) was able to get a basic implementation working. Look forward to any updates. Thank you!

**Comment by ppluchon** [comment]
Hello ! 
Any news about this feature ? :)

**Comment by leobolin** [comment]
Has anyone been able to get it to work after 9.0? Quality borders are borked.

**Comment by YWI** [comment]
Any update?

**Comment by Cidan** [comment]
See #631
