### ISSUE TITLE
LUA error when loading into game, trying to open bags via B shortcut and clicking on Bag icon

### ISSUE THREAD

**Issue by InzaneSK** [AdiAddons/AdiBags#811]
### Addon Version

v1.9.48

### World of Warcraft Version

Retail

### Describe the bug

When enter the world with only Adibags and Adibags Config loaded. Get 22 LUA warnings

Message: Interface/AddOns/AdiBags/core/Utility.lua:221: Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
Time: Wed Nov 23 10:38:19 2022
Count: 1
Stack: Interface/AddOns/AdiBags/core/Utility.lua:221: Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
[string "=[C]"]: in function `GetItemSubClassInfo'
[string "@Interface/AddOns/AdiBags/core/Utility.lua"]:221: in main chunk

Locals: (*temporary) = nil
(*temporary) = 0

Can  close the LUA warnings and press ESC to bring up menu and get LUA Error

Message: Interface/AddOns/AdiBags/core/Hooks.lua:56: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
Time: Wed Nov 23 10:39:31 2022
Count: 1
Stack: Interface/AddOns/AdiBags/core/Hooks.lua:56: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:56: in function `(for generator)'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:127: in function <Interface/AddOns/AdiBags/core/Hooks.lua:119>
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/UIParent.lua"]:3372: in function <Interface/FrameXML/UIParent.lua:3371>
[string "=[C]"]: in function `securecall'
[string "@Interface/FrameXML/UIParent.lua"]:4022: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals: maxContainer = 4
id = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
hookedBags = <table> {
}
GetContainerNumSlots = nil

When I press B to open bags, LUA error

Message: Interface/AddOns/AdiBags/core/Hooks.lua:56: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
Time: Wed Nov 23 10:40:07 2022
Count: 1
Stack: Interface/AddOns/AdiBags/core/Hooks.lua:56: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:56: in function `(for generator)'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:96: in function <Interface/AddOns/AdiBags/core/Hooks.lua:86>
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: maxContainer = 4
id = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
hookedBags = <table> {
}
GetContainerNumSlots = nil

If you click the bags icon in lower right corner, LUA error

Message: Interface/AddOns/AdiBags/core/Hooks.lua:78: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
Time: Wed Nov 23 10:41:42 2022
Count: 1
Stack: Interface/AddOns/AdiBags/core/Hooks.lua:78: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:78: in function `GetContainerFrame'
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:161: in function <Interface/AddOns/AdiBags/core/Hooks.lua:156>
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/MainMenuBarBagButtons.lua"]:76: in function <Interface/FrameXML/MainMenuBarBagButtons.lua:66>
[string "=[C]"]: ?

Locals: self = <table> {
 AcquireItemButton = <function> defined @Interface/AddOns/AdiBags/widgets/ItemButton.lua:156
 FAMILY_TAGS = <table> {
 }
 UpdateFilters = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:83
 SecureHook = <function> defined @Interface/AddOns/AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:336
 GetInteractingWindow = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:437
 ConfigChanged = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:357
 GetSlotId = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:57
 Filter = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:144
 IsEnabled = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:451
 Reconfigure = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:190
 SetupTooltip = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:114
 RegisterMessage = <function> defined @Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:188
 CreateFont = <function> defined @Interface/AddOns/AdiBags/core/Fonts.lua:122
 filterProto = <table> {
 }
 db = <table> {
 }
 OpenOptions = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:275
 SetEnabledState = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:424
 Hook = <function> defined @Interface/AddOns/AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:274
 IterateBags = <function> defined @Interface/AddOns/AdiBags/core/Bags.lua:183
 OnEnable = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:122
 HookBagFrameCreation = <function> defined @Interface/AddOns/AdiBags/core/Bags.lua:306
 NewBag = <function> defined @Interface/AddOns/AdiBags/core/Bags.lua:150
 GetClass = <function> defined @Interface/AddOns/AdiBags/core/OO.lua:129
 RegisterFilter = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:120
 BACKDROP = <table> {
 }
 OnInitialize = <function> defined =[C]:-1
 NewModule = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:235
 InitializeFilters = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:64
 IterateFilters = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:116
 ReagentBankUpdated = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:348
 CreateBagSlotPanel = <function> defined @Interface/AddOns/AdiBags/widgets/BagSlots.lua:437
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @Interface/AddOns/AdiBags/core/Hooks.lua:137
 ToggleAllBags = <function> defined @Interface/AddOns/AdiBags/core/Hooks.lua:86
 OnProfileChanged = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:198
 GetName = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:279
 name = "AdiBags"
 OpenBackpack = <function> defined @Interface/AddOns/AdiBags/core/Hooks.lua:168
 LayoutBags = <function> defined @Interface/AddOns/AdiBags/core/Layout.lua:102
 Disable = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:314
 SetGlobalLock = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:405
 Unhook

### Steps to reproduce

1. load into retail with Adibags addon enabled. 
2. Press ESC to bring up system menu
3. press B to open bags
4. Click bag icon in lower right corner
All produce LUA errors

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by medaemon** [comment]
I have the same behavior with the 1.9.50 installed.

**Comment by Cidan** [comment]
This should be fixed now -- can someone verify please?

**Comment by Aitahoof** [comment]
I had the same issues that are listed above. I downloaded v1.10.7 zip file released 01/24/2023. I pressed the keybind "B" and also  manually opening the bag and had no issues, tested at Bank, it opened and I received no Lua Messages.

**Comment by Aitahoof** [comment]
I had an issue at 09:43 MST, again i am unable as I just logged in at that time I tried to gather as much of the Lua Errors , hopefully its something 

1x AdiBags/core/Core.lua:185: attempt to index field 'anchor' (a nil value)
[string "@AdiBags/core/Core.lua"]:185: in function <AdiBags/core/Core.lua:184>
[string "=[C]"]: ?
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:562: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:555>
[string "=(tail call)"]: ?
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?

1x Interface\FrameXML\Bindings.xml:1 AdiBags/widgets/ContainerFrame.lua:1 (null
4x AdiBags/core/Hooks.lua:56: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@AdiBags/core/Hooks.lua"]:56: in function `(for generator)'
[string "@AdiBags/core/Hooks.lua"]:127: in function <AdiBags/core/Hooks.lua:119>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CloseAllBags'
[string "@FrameXML/UIParent.lua"]:3438: in function <FrameXML/UIParent.lua:3437>
[string "=[C]"]: in function `securecall'
[string "@FrameXML/UIParent.lua"]:4088: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
maxContainer = 4
id = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
hookedBags = <table> {
}
5x AdiBags/core/Fonts.lua:99: Usage: self:SetFont(fontFile, height, flags)
[string "=[C]"]: in function `SetFont'
[string "@AdiBags/core/Fonts.lua"]:99: in function `?'
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@AdiBags/libs/LibSharedMedia-3.0-8020003/LibSharedMedia-3.0.lua"]:247: in function `Register'
[string "@ElvUI/Core/Media/SharedMedia.lua"]:72: in function `AddMedia'
[string "@ElvUI/Core/Media/SharedMedia.lua"]:79: in main chunk

1x AdiBags/core/DefaultFilters.lua:44: Usage: GetItemClassInfo(itemClassID)
[string "=[C]"]: in function `GetItemClassInfo'
[string "@AdiBags/core/DefaultFilters.lua"]:44: in function `SetupDefaultFilters'
[string "@AdiBags/core/Filters.lua"]:65: in function `InitializeFilters'
[string "@AdiBags/core/Core.lua"]:97: in function <AdiBags/core/Core.lua:81>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:623: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:615>

1x Frame:UnregisterEvent(): Frame:UnregisterEvent(): Attempt to unregister unknown event "VOID_STORAGE_OPEN"
[string "=[C]"]: in function `UnregisterEvent'
[string "@AdiBags/core/EventHandlers.lua"]:45: in function `OnUnused'
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:197: in function `UnregisterAllEvents'
[string "@AdiBags/core/EventHandlers.lua"]:57: in function <AdiBags/core/EventHandlers.lua:56>
[string "=[C]"]: ?
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:569: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:555>
[string "=(tail call)"]: ?
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?






1x Frame:UnregisterEvent(): Frame:UnregisterEvent(): Attempt to unregister unknown event "VOID_STORAGE_OPEN"
[string "=[C]"]: in function `UnregisterEvent'
[string "@AdiBags/core/EventHandlers.lua"]:45: in function `OnUnused'
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:197: in function `UnregisterAllEvents'
[string "@AdiBags/core/EventHandlers.lua"]:57: in function <AdiBags/core/EventHandlers.lua:56>
[string "=[C]"]: ?
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@AdiBags/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:569: in function <...ceAdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:555>
[string "=(tail call)"]: ?
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Scrap/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function <...rap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?
