### ISSUE TITLE
autoclosing

### ISSUE THREAD

**Issue by jacho981** [AdiAddons/AdiBags#812]
### Addon Version

v1.9.48

### World of Warcraft Version

Retail

### Describe the bug

when i sell an item to a vendor bags auto-close on every sell and i have to re-open the bags to sell another. i guess it's from the last update, didnt happen before.

### Steps to reproduce

just selling any item to the vendor closes the bags.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by KayM1** [comment]
Same error here, since the last prepatch.
I tried to grab the lua error through buggrabber, but strangely enough there doesn't appear to be one.

The bag just closes when vendoring items.

**Comment by davetheaztec** [comment]
Running into the same thing - verified it's adibags by disabling everything else and still encountering the behavior,  (no lua errors either)

**Comment by Talyrius** [comment]
See #800.
