### ISSUE TITLE
Adibags prevents closing of UI Panels in Combat

### ISSUE THREAD

**Issue by Imiona** [AdiAddons/AdiBags#813]
### Addon Version

v1.9.48

### World of Warcraft Version

Retail

### Describe the bug

When in Combat and opening a Interface Panel (LFG, Hero Panel, Toybox etc.)  i cant close the Panels with the ESC Key,

No Errors though, only "Interface action failed because of an Addon" in Chat

### Steps to reproduce

See above

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
See #737.
