### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by dnbarclay** [AdiAddons/AdiBags#814]
### Addon Version

1.9.48

### World of Warcraft Version

Retail

### Describe the bug

LUA Errors:

98x .../AdiBags_PriorExpansions/AdiBags_PriorExpansions.lua:272: attempt to call global 'GetContainerItemEquipmentSetInfo' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags/core/Filters.lua"]:146: in function `Filter'
[string "@AdiBags/widgets/ContainerFrame.lua"]:797: in function `FilterSlot'
[string "@AdiBags/widgets/ContainerFrame.lua"]:831: in function `DispatchItem'
[string "@AdiBags/widgets/ContainerFrame.lua"]:1001: in function `RedispatchAllItems'
[string "@AdiBags/widgets/ContainerFrame.lua"]:1159: in function `FullUpdate'
[string "@AdiBags/widgets/ContainerFrame.lua"]:607: in function <AdiBags/widgets/ContainerFrame.lua:593>
[string "=[C]"]: ?
[string "@AdiBags/core/Utility.lua"]:102: in function <AdiBags/core/Utility.lua:94>
[string "@AdiBags/widgets/LayeredRegion.lua"]:119: in function <AdiBags/widgets/LayeredRegion.lua:108>

### Steps to reproduce

No obvious trigger. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
Your error is from [AdiBags_PriorExpansions](https://curseforge.com/wow/addons/adibags-prior-expansions), a third-party addon. Please open an issue with them.
