### ISSUE TITLE
Bag closes when selling items

### ISSUE THREAD

**Issue by Natervater** [AdiAddons/AdiBags#815]
### Addon Version

1.9.48

### World of Warcraft Version

Retail

### Describe the bug

When selling items to vendors, bag opens as expected, but when right clicking an item to sell to a vendor, the item sells and the bag frame closes automatically. 

### Steps to reproduce

1. Open Vendor UI, bag frame should open
2. right click item to sell
3. item sells, bag frame immediately closes

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by MechaZao** [comment]
I don't have this issue and can't reproduce it myself, but I have a friend that has the problem exactly as described. 

none of my attempts at troubleshooting it for him have helped

**Comment by Talyrius** [comment]
See #800.

**Comment by BastardoX** [comment]
Hey Guys i have the Same Problem, i got the newest Version from 02.12.2022

**Comment by almercie** [comment]
I've also got this problem. To add to the issue above, anytime an item changes locations in my bags, the bag frame force closes. So selling to a vendor, Deleting an item, Posting to an Auction House, Splitting a stack of items. This happens regardless of how the bag is opened (Adibags opens the bag from the vendor/AH window, or I manually open it). It's as if it needs to re-cache the bag and closes the frame to update the cache.

**Comment by Talyrius** [comment]
This issue has been closed as it's a duplicate of #800. If you have anything to add to the discussion, please do so over there. Thank you.

**Comment by Talyrius** [comment]
> I do get one error referencing the AdiBags Currency Frame.

That error has already been reported in issue #824.

**Comment by almercie** [comment]
> This issue has been closed as it's a duplicate of #800. If you have anything to add to the discussion, please do so over there. Thank you.

I resolved my Issue from the comments in [#800](https://github.com/AdiAddons/AdiBags/issues/800). Had to place the professional items for both Fishing and Engineering (Fishing pole, Arclight Spanner, & Gyromatic Micro-Adjuster) in their profession slots.
