### ISSUE TITLE
[Feature]: Add "always visible" option for Junk filter

### ISSUE THREAD

**Issue by BevansDesign** [AdiAddons/AdiBags#817]
### Describe the feature

Would it be possible to add an option to always show the Junk section even when it's empty? Currently you can't add an item to the Junk filter if there's nothing else in it (unless I'm missing something).

Thanks for making such a great mod! I've been using it for a long time.

### Describe the implementation

Either show an empty slot, or something else.

**Comment by Talyrius** [comment]
> Currently you can't add an item to the Junk filter if there's nothing else in it (**_unless I'm missing something_**).

Yes, there's already a way to do this. The dropdown menu shown when pressing `Alt` allows you to quickly assign items to preexisting sections:
![image](https://user-images.githubusercontent.com/1068810/122603182-d8d46700-d028-11eb-8004-b26afe998c96.png)
