### ISSUE TITLE
Error when adding item to category in bags

### ISSUE THREAD

**Issue by nancikennedy** [AdiAddons/AdiBags#82]
I added 'Talisman of True Treasure Tracking" to the Junk category by dropping it on the category title in my bag, which produced the following error:

2x AdiBags\widgets\ContainerFrame.lua:995: AdiBagsSection3:SetPoint(): AdiBagsSection5 is dependent on this
[C](?): in function `SetPoint'
AdiBags\widgets\ContainerFrame.lua:995: in function`LayoutSections'
AdiBags\widgets\ContainerFrame.lua:1064: in function <AdiBags\widgets\ContainerFrame.lua:1040>
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:155: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>

[string "safecall Dispatcher[1]"]:13: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function`SendMessage'
AdiBags\modules\Junk.lua:147: in function `Update'
AdiBags\modules\Junk.lua:141: in function`?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[4]"]:4: in function <[string "safecall Dispatcher[4]"]:4>
...
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `SendMessage'
AdiBags\modules\FilterOverride.lua:141: in function`AssignItems'
AdiBags\modules\FilterOverride.lua:514: in function `OnReceiveDragSectionHeader'
AdiBags\modules\FilterOverride.lua:491: in function`?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[4]"]:4: in function <[string "safecall Dispatcher[4]"]:4>

[string "safecall Dispatcher[4]"]:13: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85>
(tail call): ?

Locals:
nil

**Comment by Cidan** [comment]
Hm, Does this happen every time for you? I can't seem to reproduce it, but I have an idea of what this is. This seems to be a race condition due to sections being read from a local state that is global to the ContainerFrame file. It seems like sections are being modified while it's being iterated on.

I'll take a look at refactoring this bit of code this weekend so state is stored in the containerProto.

**Comment by Cidan** [comment]
@nancikennedy Hey, I've made a change in the way state is handled for layouts. If this is still happening for you, install master from https://github.com/Cidan/AdiBags and let me know if this resolves this issue.

**Comment by nancikennedy** [comment]
I will install and test. It was happening continually until I deleted the talisman from the junk filter

**Comment by Cidan** [comment]
Small update, I just had this bug happen to me. I'll look into it.

**Comment by Cidan** [comment]
I think I have a fix. This is a really hard bug to trigger though. I'll include my possible fix with my next PR.

Thanks.

**Comment by nancikennedy** [comment]
Okay. I haven't been able to recreate the error yet, so I'm relieved you managed to confirm it.

**Comment by nancikennedy** [comment]
I haven't seen this error crop up again, and have been able to add the talisman back to the junk filter. :)
