### ISSUE TITLE
"Do you want to purchase a bank slot for 99,999g99s99c?"

### ISSUE THREAD

**Issue by wheatbread** [AdiAddons/AdiBags#820]
### Addon Version

v1.9.48

### World of Warcraft Version

Retail

### Describe the bug

When I attempted to replace the Burnished Inscription Bag in my 7th bank slot with a Lightless Silk Pouch, it produced this popup message:

![image](https://user-images.githubusercontent.com/548824/204071334-2745fcef-8c49-44b5-b4ce-76f874c82e42.png)

Clicking confirm did not make the replacement go through as my character did not have the requisite 99k.  

I disabled Adibags and was able to replace the bag without this popup about 99k coming up.  

The popup comes up even if the bags are both soulbound.  Also with only Adibags enabled.

### Steps to reproduce

I'm not sure if it's specific to those bags or not.  

1. attempt to replace bag in 7th bank slot with a lightless silk pouch

Note:  Just now tested having a lightless silk pouch in 7th bank slot and tried to replace with another lightless silk pouch with only adibags on.  Still got the popup.  So it happens even without the burnished inscription bag. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Wraiven** [comment]
I came here to say the same is happening to me as well

**Comment by cindynico** [comment]
to me the same is happening aswel

**Comment by Cidan** [comment]
Fixed in .49
