### ISSUE TITLE
[Feature]: Seperate Free Space for Reagent Bag and normal Bags

### ISSUE THREAD

**Issue by Aryaena** [AdiAddons/AdiBags#822]
### Describe the feature

Seperate Free Space for Reagent Bag and normal Bags

### Describe the implementation

Hi,
i'm sorry for asking for more while AdiBags is already super awesome, but i noticed that the free bag slots for reagent bags and alround bags are all merged together when using the "merge free space" option. I think it would be great to seperate them into two different slots. It would feel strange if your normal bags are full, but there is still space in your reagent bag, in that case you couldnt loot gear and stuff, even though it looks like you have free space available. Same problem if the option is not used, since reagent slots and normal slots look the same. (or is it just me, and i messed up with some other options?)
Thank you and have a great day.

**Comment by Talyrius** [comment]
See #808.
