### ISSUE TITLE
Bags Closes Automatically

### ISSUE THREAD

**Issue by nweht** [AdiAddons/AdiBags#823]
### Addon Version

v1.9.48

### World of Warcraft Version

Retail

### Describe the bug

In 2 of my characters the bags automatically closes when i equip, use, sell or put an item on my bank. 
I disabled all my addons and this still happening.
This only happen in 2 of my characters even i use the same profile in all of them.

### Steps to reproduce

Open the Bag
Equipe an item // Sell an Item // Put an Item on the Auction House // Put an item on the Bank // Use an item.
The bag closes.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Ormal1708** [comment]
I'm having the same issue, also when depositing or removing an item from the bank etc.

**Comment by drinkeboer** [comment]
Yep, same issue.

**Comment by Talyrius** [comment]
See #800.
