### ISSUE TITLE
Currency broken on some characters

### ISSUE THREAD

**Issue by PeterRenaertsPXL** [AdiAddons/AdiBags#824]
### Addon Version

1.9.48

### World of Warcraft Version

Retail

### Describe the bug

No currencies are shown on certain characters, and when opening the bag after a reload/login the following error comes up:
```
AdiBags/modules/CurrencyFrame.lua:257: attempt to index local 'cell' (a nil value)
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@AdiBags/core/Bags.lua"]:138: in function `GetFrame'
[string "@AdiBags/core/Bags.lua"]:90: in function `Open'
[string "@AdiBags/core/Hooks.lua"]:112: in function <AdiBags/core/Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>
```

All characters are using the same profile.

### Steps to reproduce

1. Log in / reload UI
2. Open bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Can you give me the exact settings you have for your currency panel, including the amount for your currencies? For example:

* I have X Y Z checked
* Layout width for currencies is set to 4
* Hide Zeros is on
* X has 11
* Y has ...

Thanks!

**Comment by PeterRenaertsPXL** [comment]
I have everything checked (I hadn't bothered changing those settings)
Hide zeroes is on
Arial Narrow size 16
4 per row

I have a lot of currencies... Is that the issue? I assume it defaulted to all currencies on since I hadn't touched the plugin settings at all.

I turned off most of the options and now it's working and I don't get the error.
Tried adding some currencies that I have at 0 but they don't get shown at all, but also no error, even after a reload.

**Comment by Cidan** [comment]
Hm, I can't reproduce this error, but I do see some currencies just don't show up anymore, even when checked. I'm willing to bet that's the issue. I'll debug this and let you know when it's fixed.

**Comment by Talyrius** [comment]
Pertinent information from #807:
> I had them all checked and it only gives me the errors when I log into an account which has a lot of different currencies. I believe I have narrowed it down to the addon only being able to display a certain amount of types and I am over that number. I can enable them until I reach the error, back off by 1 then I am fine. it appears to be around 48-49 types enabled when the error is generated.
