### ISSUE TITLE
[Feature]: Support for ConsolePort

### ISSUE THREAD

**Issue by Mysuki-twitch** [AdiAddons/AdiBags#825]
### Describe the feature

Support to use the controller inside the bags like all other bag addons

### Describe the implementation

You can play WoW with a controller now and you can use a keybind to open the bag like normal. With ConsolePort addon, you can use the D-Pad to move around the itens inside the bag to choose w/e you want and need. Plenty other bag addons have the support for that, but not AdiBags :(  The controller does not work at all.
[![](https://iili.io/HKEGtn9.jpg)](https://freeimage.host/i/HKEGtn9)

**Comment by Cidan** [comment]
I've been meaning to test this/try this on my SteamDeck actually. AdiBags doesn't reuse any of the Blizzard bag frames, and instead draws its own frames. I'm not sure what the level of effort is involved here, but I'd like to eventually get to this.

We'll add it at some point, once we have some other, more critical bits done.

**Comment by class2u** [comment]
I need this feature badly. Thanks!

**Comment by darroshi** [comment]
Hi,
Please try my addon that tries to fix this https://www.curseforge.com/wow/addons/adibags-console-port-support
It's not perfect, but i've been using it since DF launch and for simple operations in bags it's perfectly enough.
Any feedback is very welcome :)
