### ISSUE TITLE
Opening bag causes WoW client crash

### ISSUE THREAD

**Issue by Rokonen** [AdiAddons/AdiBags#828]
### Addon Version

v1.9.48

### World of Warcraft Version

Classic

### Describe the bug

When opening either my bag or bank, the WoW client immediately crashes. This only happens on one particular character and when AdiBags is enabled, regardless of whether any other addons are enabled. I tried doing a full UI reset and reinstalling the add-on but the issue persists on this character.

### Steps to reproduce

I'm not sure if it's reproducible. It seems unique to a particular character on my account. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
Is this with an Apple M1 or M2 Mac?

**Comment by Rokonen** [comment]
Hello, this is with Apple M1. I am using WoW natively.

**Comment by Talyrius** [comment]
See #731.
