### ISSUE TITLE
Error with Magneto, Titan Panel and Adibags...?

### ISSUE THREAD

**Issue by nancikennedy** [AdiAddons/AdiBags#83]
Installed the new version of Magneto, and now getting the following error. Not sure who the culprit is:
 
1x Titan\TitanPanelTemplate.lua:1022: Usage: TitanPanelMagnetletButtonIcon:SetTexCoord(minX, maxX, minY, maxY) or SetTexCoord(ULx, ULy, LLx, LLy, URx, URy, LRx, LRy)
[C]: in function `SetTexCoord'
Titan\TitanPanelTemplate.lua:1022: in function `TitanPanelButton_SetButtonIcon'
Titan\TitanPanelTemplate.lua:977: in function `TitanPanelButton_UpdateButton'
Titan\LDBToTitan.lua:401: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[5]"]:4: in function <[string "safecall Dispatcher[5]"]:4>
[C]: ?
[string "safecall Dispatcher[5]"]:13: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
...AdiBags\libs\LibDataBroker-1.1\LibDataBroker-1.1-4.lua:30: in function <...AdiBags\libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:22>
Magneto\Outlets\DataBroker.lua:128: in function `Clear'
Magneto\Outlets.lua:51: in function `?'
...
Magneto\Magneto-1.0 r007.lua:747: in function `UpdateData'
Magneto\Magneto-1.0 r007.lua:727: in function `Update'
Magneto\Magneto-1.0 r007.lua:810: in function `UpdateState'
Magneto\Magneto-1.0 r007.lua:967: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
...s\AckisRecipeList\libs\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <...s\AckisRecipeList\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
Locals:
nil

**Comment by Cidan** [comment]
This doesn't seem to be like a problem with AdiBags directly, but I'm not sure. LDB makes stack debugging very difficult. I'll try to see if I can get an updated version of all required deps merged in to eliminate out of date deps as an issue.
