### ISSUE TITLE
Cannot close any UI elements except bags while in combat

### ISSUE THREAD

**Issue by Booggg** [AdiAddons/AdiBags#831]
### Addon Version

1.9.48

### World of Warcraft Version

Retail

### Describe the bug

We used to be able to clear all menus (like spellbook, map, lfg ect) with esc key, but since the new ui change this does not work while in combat. If you are mid pull on a raid boss and fat finger one of these, you can not clear it unless you fumble about to click the little x.

I initally though this was an issue with blizzard ui, but people say they have no issue so I toggled off my addons one by one and found disabling adibags fixed the issue. I then only enabled adibag to confirm it is causing the issue.

THIS IS A VERY ANNOYING BUG.

Thanks.

there is no error in bug sack, but an error msg thrown in chat. "interface action failed because of an addon"

### Steps to reproduce

Enable Adibags, get in combat, open any UI elements like spellbook or lfg ect they cannont be closed pressing esc key.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
I think I know what this bug is, and it's going to be tricky to fix. Blizzard has a ton of new mechanisms that taint the user UI, and I ran into this while testing as well. Let me see if I can figure out a solid fix for this over the next few days.

**Comment by Booggg** [comment]
Thanks, I never realized how often I open these by mistake mid pull until now haha.

**Comment by TomCats** [comment]
Confirmed for me as happening while the world map is open.  I can close the world map by clicking the X, but attempting to  close via escape key while in combat will produce the same issue.

**Comment by mnejing** [comment]
Can confirm this is still happening as of today.

**Comment by quatu** [comment]
In Core.lua if you change
```
self:RawHook("CloseAllBags", true)
self:RawHook("CloseBag", true)
self:RawHook("CloseBackpack", true)
```
to
```
self:SecureHook("CloseAllBags")
self:SecureHook("CloseBag")
self:SecureHook("CloseBackpack")
```
it seems to work.

**Comment by Mavvi87** [comment]
> In Core.lua if you change
> 
> ```
> self:RawHook("CloseAllBags", true)
> self:RawHook("CloseBag", true)
> self:RawHook("CloseBackpack", true)
> ```
> 
> to
> 
> ```
> self:SecureHook("CloseAllBags")
> self:SecureHook("CloseBag")
> self:SecureHook("CloseBackpack")
> ```
> 
> it seems to work.

This works, but I noticed something important worth mentioning; Its important that your bag keybind (normally B) must be set to "Toggle Backpack" and not "Open All Bags", or it wont be able to close the bag.

Thank you, Quatu

**Comment by Cidan** [comment]
Hi everyone,

This is fixed, and works regardless of your keybindings now. The fix will go out with the next bugfix version (this week). Thanks, and sorry for the wait!
