### ISSUE TITLE
Window closes upon any item right-click

### ISSUE THREAD

**Issue by sMteX** [AdiAddons/AdiBags#832]
### Addon Version

v1.9.49

### World of Warcraft Version

Retail

### Describe the bug

Right clicking any item (equipping, eating, selling) and also batch selling junk closes the Adibags window. The action actually happens, but closes the window in the process. Nothing related to Adibags in BugSack from this time, no visible Lua error or anything in console/chat.

### Steps to reproduce

1. Install version 1.9.49 on current 10.0.2 retail
2. Open bags
3. Try to click any item in the bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by drocks** [comment]
also having this problem in addition to ilvl throwing errors and not showing now

**Comment by Cidan** [comment]
Please update to .50 to fix the ilvl problem. We're looking at this bag closing bug now.

Thanks!

**Comment by Talyrius** [comment]
See #800.
