### ISSUE TITLE
WOTLK Currency

### ISSUE THREAD

**Issue by kimura64** [AdiAddons/AdiBags#833]
### Addon Version

1.9.49

### World of Warcraft Version

Wrath

### Describe the bug

Hello everyone, 

As you can see on screenshots below, I don't have currency listed on the bag : 
![image](https://user-images.githubusercontent.com/47465584/204548952-69204d6a-7996-4e79-acd0-32a5578db575.png)
![image](https://user-images.githubusercontent.com/47465584/204549321-239da529-114b-4d36-a7ba-2fdfe2f6229b.png)
![image](https://user-images.githubusercontent.com/47465584/204549598-90db5af0-f32f-4b24-9e93-b56bf176012e.png)
Even if I check them on the Wow Currency

Someone can help me ?

### Steps to reproduce

Open the bag and check the currency

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
See #707.
