### ISSUE TITLE
Bag background broken

### ISSUE THREAD

**Issue by karmalegend** [AdiAddons/AdiBags#839]
### Addon Version

v1.9.50

### World of Warcraft Version

Retail

### Describe the bug

Changing the bag background texture does absolutely nothing

### Steps to reproduce

Open adibags settings ->skin -> bag background

change it

Nothing happens, Reload?

Nothing happens

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by karmalegend** [comment]
It seems like the texture is never intended to actually apply the texture as the "background" but merely as a texture for the color to be laid over by height mapping?? or smth. If this is the case consider closed.

**Comment by Cidan** [comment]
That is correct, and this is the way textures work in WoW.
