### ISSUE TITLE
Icons in inventory don't update when you equip item

### ISSUE THREAD

**Issue by tempest420** [AdiAddons/AdiBags#84]
So when I equip a newly looted item, the icon in my inventory shows the new item despite the fact that if I check my character sheet, the item is equipped. I have to close and reopen inventory for the icon in bag to update.

**Comment by RomanMezentsev** [comment]
+1
The same problem.

**Comment by Cidan** [comment]
I noticed this problem earlier today on an instance run. I'll get this fixed asap.

**Comment by Cidan** [comment]
Okay, fixed. I'll include it in my next PR.

**Comment by tempest420** [comment]
Thanks!
