### ISSUE TITLE
[Feature]: Quality depiction on icon 

### ISSUE THREAD

**Issue by MechaZao** [AdiAddons/AdiBags#840]
### Describe the feature

In the normal blizz bags (and other bag addons such as elvui's) icons for reagents in DF have quality indicators on them like so -

![image](https://user-images.githubusercontent.com/20646520/205140724-461f4b19-4676-442f-b0ad-ebdafb3f8999.png)

It would be great if this were possible on AdiBags as well!

### Describe the implementation

find a different way to depict the item is in the Reagent bag, and place the quality indicators in the top left position as it is in other addons/blizz bags.

**Comment by Talyrius** [comment]
Possibly resolvable via #701.

**Comment by jukx** [comment]
Want to second this request. This feature is pretty crucial now with dragonflight.

**Comment by Jaidy88** [comment]
Unfortunately, my English is very poor, so I don't understand the post from #701 (https://github.com/AdiAddons/AdiBags/pull/701). What and where should I change something?

It would be really great if you could see the quality level directly in the bag and not have to hover over it with the mouse.

**Comment by ThomasCox42** [comment]
Also bumping this feature request so it stays relevant. Thanks for all the work everyone puts into this :)

**Comment by Bakamaka11** [comment]
Agree, very important thing, implement please

**Comment by voyvoy** [comment]
I was wondering, if I had missed something in the addon options. Please consider implementing these quality indicators. Thank you!

**Comment by Cidan** [comment]
Fixed in #865
