### ISSUE TITLE
"You've obtained a reagent bag"-box stuck

### ISSUE THREAD

**Issue by GibsonSWE** [AdiAddons/AdiBags#841]
### Addon Version

1.9.50

### World of Warcraft Version

Retail

### Describe the bug

I have a yellow box stuck in the bottom right of the screen saying "You've obtained a reagent bag! Open your bag."

If I disable adibags the box goes away, but comes back when I re enable adibags.
The reagent bag I have equipped is "Gatherer's Reagent Pouch"

### Steps to reproduce

![image](https://user-images.githubusercontent.com/33501602/205324324-3b17f4cf-c88b-411c-b8dc-f29a9fabf52d.png)

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by lfmnovaes** [comment]
Any work around for this?

**Comment by GibsonSWE** [comment]
> 

The issue seem to be related to this reagent bag specifically, as its a reward from a quest. Equipping a different reagent bag solved the issue for me.

**Comment by Cidan** [comment]
Fixed in #865
