### ISSUE TITLE
Can't separate stacks

### ISSUE THREAD

**Issue by Pamboo1** [AdiAddons/AdiBags#844]
### Addon Version

v1.9.50

### World of Warcraft Version

Retail

### Describe the bug

When want to separate a stack, for example 30 into a set of 10 and 20, it will not separate the stacks.  It just goes back to the original amount.  I have to disable the addon to do this. 
Thanks

### Steps to reproduce

Open the bag.  Find a stack of mats that have more than 1. Shift R-Click to set the amount to take.  Then nothing happens to make the separate set.  I disabled all addons except Adibags and it still does not work. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by kcoderhere** [comment]
Prior to Dragonflight, you could just drag a split item anywhere in the empty bag background to split it. Now you have to drag your split item into the Free Space box for it to work.

**Comment by Talyrius** [comment]
In the settings, make sure you've selected either of the last two options from this dropdown to make it easier to identify the actual state of your stacked items when interacting with merchant, auction house, bank, mailbox, and trade windows:
![image](https://cloud.githubusercontent.com/assets/1068810/19857669/c50ba620-9f3b-11e6-890b-d22363bc2f12.png)

Now, shift-click the stack you'd like to split, choose an amount, click "Okay," and then drop the partial stack in a free bag slot or trade/mail/merchant window.

> **_Prior to Dragonflight,_** you could just drag a split item anywhere in the empty bag background to split it. Now you have to drag your split item into the Free Space box for it to work.

No, this is inaccurate. This functionality has remained unchanged. If you have any feedback regarding how this works, you're welcome to add to the discussion taking place in #711.
