### ISSUE TITLE
[Feature]: Separate Reagent bag from the UI.

### ISSUE THREAD

**Issue by Zxkarie** [AdiAddons/AdiBags#849]
### Describe the feature

Would it be possible to add an option to section the reagent bag? kinda like how the default UI does with combined bags.
I have to keep emptying it into my bank because it makes me feel cluttered AF.

I would be happy if there was such an option to force sort items in my reagent bag to the bottom of my adibags.

### Describe the implementation

Add an option to split or force the sort location not mixed with my normal bag items.

**Comment by YetAnotherDevWannabe** [comment]
That would indeed be a great feature :)

**Comment by Cidan** [comment]
This will be implemented in the new layout engine. Specifically, you'll be able to sort individual sections manually, however you please.

**Comment by Zxkarie** [comment]
Lucky timing, I was jus checking my emails and saw you replied.
That sounds perfect, thank you. What are your plans for the new layout engine?

**Comment by Cidan** [comment]
Check out #675 for more info! :)
