### ISSUE TITLE
Entire game freezes for 2 seconds every time I open bags

### ISSUE THREAD

**Issue by wrightling** [AdiAddons/AdiBags#852]
### Addon Version

v1.9.50

### World of Warcraft Version

Retail

### Describe the bug

Each time I open bags (whether I do it or they open automatically because of talking to a vendor or a player initiating a trade), the entire game freezes for around 2 seconds before the bags finally open.

This happens with every open.

There are no errors captured in buggragger/bugsack.

### Steps to reproduce

Open bags and notice long game freeze.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by alipc09** [comment]
Also experiencing the same issue

**Comment by Cidan** [comment]
Are you using any of the unofficial AdiBags plugins/addons? Some of the older addon plugins (i.e. anything that isn't `AdiBags` and `AdiBags_Config`) use tooltip scanning that causes freezes like this.

**Comment by kcoderhere** [comment]
This happened to me with "AdiBags BoE & BoA" until I downloaded the community fix.

**Comment by wrightling** [comment]
I disabled any unofficial adibags plugins and it works fine. I'll close this issue as it's not a core Adibags problem.
