### ISSUE TITLE
Issue with opening/closing bank bag slots when Adibags not set to apply to bank.

### ISSUE THREAD

**Issue by Mrunderwonder** [AdiAddons/AdiBags#858]
### Addon Version

1.9.50

### World of Warcraft Version

Retail

### Describe the bug

I guess I may be one of the few who like Adibags for my bags but not my bank. I noticed some odd behavior when you use it this way. When you have Adibags set so it does not apply to your bank. When opening the bank, you then shift-click the backpack to open all the ban bags or you have to open them individually. If you open your bags with shift-click on your backpack, the last bank bag is not opened. You must click on this bag to open it. When closing your bank with the X button in the right corner, none of the bank bag slots are closed. You must use ESC to close your bank/bags, or the bags get stuck on screen and can't be closed. When you close your bank/bags using ESC the last bank bag does not close at all, you must click on it again to close it before you close the bank, or it get stuck on screen and can't be closed with the X button in the corner.

### Steps to reproduce

1. Set Adibags to not apply to the bank.
2. Open bank.
3. Shift-click on backpack. (All bank bags slot should open except the final one.)
4. Click on final bag that did not open to open the bag.
5. Close bank using X button in corner. (All bags should be stuck on screen and will not close if X button is used.)
6. Open bank again and hit the ESC button. (All bags/bank should close except the bag we had to open manually.)
7. Open bank again and click on the final bank bag to close it.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Thanks for the comprehensive bug report! I believe this bug is due to addon taint issues, but there are two bugs here:

1) All bags don't open when shift-clicking the bag icon
2) The stuck bags when hitting escape.

The second bug is fixed by #865 and will be released this week, such that hitting "Esc" will work as expected. The first bug I also just fixed, and will also be released with #865.

Thank you again!

**Comment by Mrunderwonder** [comment]
Thanks and happy new year.
