### ISSUE TITLE
You can not separate items in the bag

### ISSUE THREAD

**Issue by AlexMecker** [AdiAddons/AdiBags#859]
### Addon Version

v1.9.50

### World of Warcraft Version

Retail

### Describe the bug

Items such as potions, food, infusions, etc. are not separated (Shift + LMB), it is very annoying if you want to share something with another player, you have to turn off the addon.

### Steps to reproduce

You open the bag, hold down the shift and click on the desired item with LMB, trying to separate it into parts, poke into an empty place in the bag and nothing happens

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
In the settings, make sure you've selected either of the last two options from this dropdown to make it easier to identify the actual state of your stacked items when interacting with merchant, auction house, bank, mailbox, and trade windows:
![image](https://cloud.githubusercontent.com/assets/1068810/19857669/c50ba620-9f3b-11e6-890b-d22363bc2f12.png)

Now, shift-click the stack you'd like to split, choose an amount, click "Okay," and then drop the partial stack in a free bag slot or trade/mail/merchant window.

If you have any feedback regarding how this works, you're welcome to add to the discussion taking place in #711.

**Comment by AlexMecker** [comment]
Thank you, it worked

**Comment by AlexMecker** [comment]
Thank you, it worked
