### ISSUE TITLE
Need help with Duplicate filters undoing existing filter

### ISSUE THREAD

**Issue by N6REJ** [AdiAddons/AdiBags#862]
### Addon Version

1.9.50

### World of Warcraft Version

Retail

### Describe the bug

I'm having an issue where in professions where we have duplicate filter names ( on purpose ) something is happening where it kills the filter completely.
What I want to happen is, in a profession like "tailoring" & "Jewelcrafting" where they both have SOME of the same items, it should skip the duplicate items and reuse the filter name, uiname, & desc if they are the same.  I don't know what needs to change in my code.
https://github.com/N6REJ/.wow-settings/blob/main/wow/core.lua is my "engine" which is the same for all addons.
https://github.com/N6REJ/Adibags_Bears_Jewelcrafting is the jewelcrafting addon
https://github.com/N6REJ/AdiBags_Bears_Tailoring/blob/main/DF-db.lua is tailoring.

### Steps to reproduce

create duplicate filters with only partial items in one of the filters.
if the filter exists it actually disables the filter

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by N6REJ** [comment]
Any chance on getting this resolved?

**Comment by N6REJ** [comment]
I'm not sure if this is the proper fix or not https://github.com/N6REJ/Adibags_Bears_Jewelcrafting

**Comment by Cidan** [comment]
Unfortunately, we don't provide support for third party addons. If you have a specific feature ask for us to implement in the core addon to better support you, we'd be happy to take a look, but debugging others code is outside our scope.

Thanks!

**Comment by N6REJ** [comment]
> Unfortunately, we don't provide support for third party addons. If you have a specific feature ask for us to implement in the core addon to better support you, we'd be happy to take a look, but debugging others code is outside our scope.
> 
> Thanks!

is there some document that explains how we would implement a filter?  For example, how do we tell adibags to process the "items" array without creating a new filter?
