### ISSUE TITLE
[Feature]: sort reagents pls

### ISSUE THREAD

**Issue by fai1337** [AdiAddons/AdiBags#864]
### Describe the feature

I seem to recall that the reagents bank used to be sorted. Now it's all just lumped together under "tradeskill" and well, yes, I KNOW that they're tradeskill items, that's why they're in the reagents bank. Now it's hard for me to see if it's an item I need to keep for my engineering, or if it's an item to send over to my tailor.

### Describe the implementation

Please re-enable crafting/gathering item sorting.

**Comment by Cidan** [comment]
We pull the categories directly from the Blizzard API for every item, and it's not something we manually control. I don't think we ever broke down items in the bank bag by crafting profession.

**Comment by Talyrius** [comment]
It can definitely be done with [AdiBags_PT3Filter](https://github.com/AdiAddons/AdiBags_PT3Filter).

**Comment by Cidan** [comment]
Just a heads up, I'm working on a feature built into AdiBags for this. Here's a screenshot of what I have as a WIP:

![image](https://user-images.githubusercontent.com/1133628/211493335-e325aa99-cdce-4bb5-913a-f8a6670e226c.png)

Right now it shows both expansion and tradeskill, but the final version will let you configure how you want bags to be split/sorted, i.e. ignore expansion, or only have expansion, or both.
