### ISSUE TITLE
1.9.51 bug grabber going off like crazy.

### ISSUE THREAD

**Issue by Trogdor666** [AdiAddons/AdiBags#866]
### Addon Version

1.9.51

### World of Warcraft Version

Retail

### Describe the bug

Since the newest update buggrabber is constantly going off with the following:

22x AdiBags/core/Hooks.lua:216: attempt to call field 'CloseSpecialWindows' (a nil value)
[string "@AdiBags/core/Hooks.lua"]:216: in function <AdiBags/core/Hooks.lua:215>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `securecall'
[string "@FrameXML/UIParent.lua"]:3393: in function `CloseWindows'
[string "@FrameXML/UIParent.lua"]:3410: in function <FrameXML/UIParent.lua:3408>
[string "=[C]"]: in function `securecall'
[string "@FrameXML/UIParent.lua"]:4059: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
self = <table> {
 AcquireItemButton = <function> defined @AdiBags/widgets/ItemButton.lua:176
 modules = <table> {
 }
 UpdateFilters = <function> defined @AdiBags/core/Filters.lua:83
 SecureHook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:335
 GetInteractingWindow = <function> defined @AdiBags/core/Core.lua:461
 GetContainerItemTexture = <function> defined @AdiBags/core/Utility.lua:438
 ConfigChanged = <function> defined @AdiBags/core/Core.lua:381
 GetSlotId = <function> defined @AdiBags/core/Utility.lua:70
 Filter = <function> defined @AdiBags/core/Filters.lua:144
 IsEnabled = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 Reconfigure = <function> defined @AdiBags/core/Core.lua:211
 SetupTooltip = <function> defined @AdiBags/core/Utility.lua:127
 RegisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @AdiBags/core/Utility.lua:303
 CreateFont = <function> defined @AdiBags/core/Fonts.lua:122
 isClassic = false
 db = <table> {
 }
 OpenOptions = <function> defined @AdiBags/core/Core.lua:296
 SetEnabledState = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:273
 IterateBags = <function> defined @AdiBags/core/Bags.lua:190
 AcquireColumn = <function> defined @AdiBags/core/OO.lua:215
 OnEnable = <function> defined @AdiBags/core/Core.lua:128
 HookBagFrameCreation = <function> defined @AdiBags/core/Bags.lua:318
 NewBag = <function> defined @AdiBags/core/Bags.lua:157
 GetClass = <function> defined @AdiBags/core/OO.lua:129
 RegisterFilter = <function> defined @AdiBags/core/Filters.lua:120
 BACKDROP = <table> {
 }
 RemoveTooltip = <function> defined @AdiBags/core/Utility.lua:160
 UnregisterAllEvents = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 isBCC = false
 GetContainerItemStackCount = <function> defined @AdiBags/core/Utility.lua:434
 IterateFilters = <function> defined @AdiBags/core/Filters.lua:116
 ReagentBankUpdated = <function> defined @AdiBags/core/Core.lua:372
 CreateBagSlotPanel = <function> defined @AdiBags/widgets/BagSlots.lua:448
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @AdiBags/core/Hooks.lua:144
 AcquireDropzone = <function> defined @AdiBags/core/OO.lua:215
 ToggleAllBags = <function> defined @AdiBags/core/Hooks.lua:93
 OnProfileChanged = <function> defined @AdiBags/core/Core.lua:219
 GetName = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "AdiBags"
 OpenBackpack = <function> defined @AdiBags/core/Hooks.lua:175
 LayoutBags = <function> defined @AdiBags/core/Layout.lua:103
 Disable = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 SetGlobalLock = <function> defined @AdiBags/core/Core.lua:429
 ParseItemLink = <function> defined @AdiBags/core/Utility.lua:178
 DisableHooks = <function> defined @AdiBags/core/Core.lua:198
 UpdateInteractingWindow = <function> defined @AdiBags/core/Core.lua:447
 Print = <function> defined @AdiBags/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 OpenAllBags = <function> defined @AdiBags/core/Hooks.lua

### Steps to reproduce

Have the addon enabled and buggrabber constantly spams with FATALITY sound.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by chilblane** [comment]
Pretty easy to spam the CloseSpecialWindows is nil error by repeatedly opening and closing the main menu with Escape. Probably because there are... no special windows.

**Comment by asymptotic1** [comment]
New line in core.lua in 1.9.51

self:SecureHook('CloseSpecialWindows')

There's your problem.

**Comment by Cidan** [comment]
@asymptotic1 This isn't the problem, it's related, but not quite right.

Emergency release going out shortly with the fix.

**Comment by Cidan** [comment]
Fixed with 1.9.52, which is going out in a few minutes.

**Comment by asymptotic1** [comment]
Thanks for rapid response!
