### ISSUE TITLE
Lua when hitting the ESC key. 

### ISSUE THREAD

**Issue by SenpaiBankai** [AdiAddons/AdiBags#870]
### Addon Version

v1.9.51

### World of Warcraft Version

Retail

### Describe the bug

Was working fine until the update about an hour ago. Now everytime I hit the ESC key. no matter what menu I am in, I get an LUA error for the addon. 
Here is the error I receive. 

31x AdiBags/core/Hooks.lua:216: attempt to call field 'CloseSpecialWindows' (a nil value)
[string "@AdiBags/core/Hooks.lua"]:216: in function <AdiBags/core/Hooks.lua:215>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `securecall'
[string "@FrameXML/UIParent.lua"]:3393: in function `CloseWindows'
[string "@FrameXML/UIParent.lua"]:3410: in function <FrameXML/UIParent.lua:3408>
[string "=[C]"]: in function `securecall'
[string "@FrameXML/UIParent.lua"]:4059: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
self = <table> {
 AcquireItemButton = <function> defined @AdiBags/widgets/ItemButton.lua:176
 modules = <table> {
 }
 UpdateFilters = <function> defined @AdiBags/core/Filters.lua:83
 SecureHook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:335
 GetInteractingWindow = <function> defined @AdiBags/core/Core.lua:461
 GetContainerItemTexture = <function> defined @AdiBags/core/Utility.lua:438
 ConfigChanged = <function> defined @AdiBags/core/Core.lua:381
 GetSlotId = <function> defined @AdiBags/core/Utility.lua:70
 Filter = <function> defined @AdiBags/core/Filters.lua:144
 IsEnabled = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 Reconfigure = <function> defined @AdiBags/core/Core.lua:211
 SetupTooltip = <function> defined @AdiBags/core/Utility.lua:127
 RegisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @AdiBags/core/Utility.lua:303
 CreateFont = <function> defined @AdiBags/core/Fonts.lua:122
 isClassic = false
 db = <table> {
 }
 OpenOptions = <function> defined @AdiBags/core/Core.lua:296
 SetEnabledState = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:273
 IterateBags = <function> defined @AdiBags/core/Bags.lua:190
 AcquireColumn = <function> defined @AdiBags/core/OO.lua:215
 OnEnable = <function> defined @AdiBags/core/Core.lua:128
 HookBagFrameCreation = <function> defined @AdiBags/core/Bags.lua:318
 NewBag = <function> defined @AdiBags/core/Bags.lua:157
 GetClass = <function> defined @AdiBags/core/OO.lua:129
 RegisterFilter = <function> defined @AdiBags/core/Filters.lua:120
 BACKDROP = <table> {
 }
 RemoveTooltip = <function> defined @AdiBags/core/Utility.lua:160
 UnregisterAllEvents = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 isBCC = false
 GetContainerItemStackCount = <function> defined @AdiBags/core/Utility.lua:434
 IterateFilters = <function> defined @AdiBags/core/Filters.lua:116
 ReagentBankUpdated = <function> defined @AdiBags/core/Core.lua:372
 CreateBagSlotPanel = <function> defined @AdiBags/widgets/BagSlots.lua:448
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @AdiBags/core/Hooks.lua:144
 AcquireDropzone = <function> defined @AdiBags/core/OO.lua:215
 ToggleAllBags = <function> defined @AdiBags/core/Hooks.lua:93
 OnProfileChanged = <function> defined @AdiBags/core/Core.lua:219
 GetName = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "AdiBags"
 OpenBackpack = <function> defined @AdiBags/core/Hooks.lua:175
 LayoutBags = <function> defined @AdiBags/core/Layout.lua:103
 Disable = <function> defined @AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 SetGlobalLock = <function> defined @AdiBags/core/Core.lua:429
 ParseItemLink = <function> defined @AdiBags/core/Utility.lua:178
 DisableHooks = <function> defined @AdiBags/core/Core.lua:198
 UpdateInteractingWindow = <function> defined @AdiBags/core/Core.lua:447
 Print = <function> defined @AdiBags/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 OpenAllBags = <function> defined @AdiBags/core/Hooks.lua

### Steps to reproduce

If I'm doing anything, and hit the ESC key, this error pops up. Doesn't matter if the bag is open or not. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Fixed in 1.9.52 -- please update :)

**Comment by SenpaiBankai** [comment]
Okay, where can I get that? Because curseforge only has 1.9.51.

**Comment by SenpaiBankai** [comment]
Tried to update via this; 
![image](https://user-images.githubusercontent.com/122000314/210715722-dd1c3623-ef44-4a19-a663-a21f0d87579e.png)

and get this; 
![image](https://user-images.githubusercontent.com/122000314/210715787-139541b4-16e0-4f1c-b504-06ac4cfdfafd.png)

**Comment by Cidan** [comment]
That looks like a curse updater error -- I do not know what that error is. Try relaunching the curseforge app.

**Comment by SenpaiBankai** [comment]
Got it going, thank you!
