### ISSUE TITLE
Frequent Lua Error popup

### ISSUE THREAD

**Issue by insanum** [AdiAddons/AdiBags#871]
### Addon Version

v1.9.51

### World of Warcraft Version

Retail

### Describe the bug

Message: Interface/AddOns/AdiBags/core/Hooks.lua:216: attempt to call field 'CloseSpecialWindows' (a nil value)
Time: Wed Jan  4 21:55:02 2023
Count: 6
Stack: Interface/AddOns/AdiBags/core/Hooks.lua:216: attempt to call field 'CloseSpecialWindows' (a nil value)
[string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:216: in function <Interface/AddOns/AdiBags/core/Hooks.lua:215>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `securecall'
[string "@Interface/FrameXML/UIParent.lua"]:3393: in function `CloseWindows'
[string "@Interface/FrameXML/UIParent.lua"]:3410: in function <Interface/FrameXML/UIParent.lua:3408>
[string "=[C]"]: in function `securecall'
[string "@Interface/FrameXML/UIParent.lua"]:4059: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals: self = <table> {
 AcquireItemButton = <function> defined @Interface/AddOns/AdiBags/widgets/ItemButton.lua:176
 modules = <table> {
 }
 UpdateFilters = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:83
 SecureHook = <function> defined @Interface/AddOns/AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:335
 GetInteractingWindow = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:461
 GetContainerItemTexture = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:438
 ConfigChanged = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:381
 GetSlotId = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:70
 Filter = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:144
 IsEnabled = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 Reconfigure = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:211
 SetupTooltip = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:127
 RegisterMessage = <function> defined @Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:303
 CreateFont = <function> defined @Interface/AddOns/AdiBags/core/Fonts.lua:122
 isClassic = false
 db = <table> {
 }
 OpenOptions = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:296
 SetEnabledState = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/AdiBags/libs/AceHook-3.0/AceHook-3.0.lua:273
 IterateBags = <function> defined @Interface/AddOns/AdiBags/core/Bags.lua:190
 AcquireColumn = <function> defined @Interface/AddOns/AdiBags/core/OO.lua:215
 OnEnable = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:128
 HookBagFrameCreation = <function> defined @Interface/AddOns/AdiBags/core/Bags.lua:318
 NewBag = <function> defined @Interface/AddOns/AdiBags/core/Bags.lua:157
 GetClass = <function> defined @Interface/AddOns/AdiBags/core/OO.lua:129
 RegisterFilter = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:120
 BACKDROP = <table> {
 }
 RemoveTooltip = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:160
 UnregisterAllEvents = <function> defined @Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 isBCC = false
 GetContainerItemStackCount = <function> defined @Interface/AddOns/AdiBags/core/Utility.lua:434
 IterateFilters = <function> defined @Interface/AddOns/AdiBags/core/Filters.lua:116
 ReagentBankUpdated = <function> defined @Interface/AddOns/AdiBags/core/Core.lua:372
 CreateBagSlotPanel = <function> defined @Interface/AddOns/AdiBags/widgets/BagSlots.lua:448
 TOP_PADDING = 32
 hookedBags = <table> {
 }
 OpenBag = <function> defined @Interface/AddOns/AdiBags/core/Hooks.lua:144
 AcquireDropzone = <function> defined @Interface/AddOns/AdiBags/core/OO.lua:215
 ToggleAllBags = <function> defined @Interface/AddOns/AdiBags/core/Hooks.lua:93
 OnProfileCha

### Steps to reproduce

Occurs during game initial load and every time I hit the Escape button.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Fixed in 1.9.52

**Comment by insanum** [comment]
Yeah... was just going reply that the problem is gone in v1.9.52.
Thanks for your hard work and sorry for the noise. :-)

**Comment by Cidan** [comment]
No worries, my fault -- for whatever reason, I forgot to include changes I had locally in the release. Sigh.
