### ISSUE TITLE
new error since last update

### ISSUE THREAD

**Issue by Giftiger** [AdiAddons/AdiBags#873]
### Addon Version

v1.9.51

### World of Warcraft Version

Retail

### Describe the bug

When log in or after a reload

its my first error reporting here and english is not my main language, hope its ok like this

### Steps to reproduce

Message: Interface/AddOns/AdiBags/core/Core.lua:122: attempt to call field 'SetCVarBool' (a nil value)
Time: Thu Jan  5 08:01:10 2023
Count: 1
Stack: Interface/AddOns/AdiBags/core/Core.lua:122: attempt to call field 'SetCVarBool' (a nil value)
[string "@Interface/AddOns/AdiBags/core/Core.lua"]:122: in function <Interface/AddOns/AdiBags/core/Core.lua:82>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Fixed in 1.9.52

**Comment by Giftiger** [comment]
nice thx
