### ISSUE TITLE
BUG: Bank shows random items as part of Gear Sets

### ISSUE THREAD

**Issue by ZINK-ZINK** [AdiAddons/AdiBags#876]
### Addon Version

1.9.52

### World of Warcraft Version

Retail

### Describe the bug

As shown in the pic all kinds of totally random items are being counted as part of my Gear Sets. They only show like this while in the Bank, if I right-click the category so the items move to my Bags they switch to the correct categories, but in the bank they go right back to being wrong. 

No idea how to reproduce it at all.
![adibags set bug 1](https://user-images.githubusercontent.com/96964163/210829448-5712e8c2-f867-4d70-96f4-ee4165262f5e.jpg)

### Steps to reproduce

.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Oh interesting, I'll try to reproduce this. Thanks for the report!

**Comment by ZINK-ZINK** [comment]
I ended up doing spring-cleaning on my bank to make space and in the process figured out how to reproduce it.

It only happens to Gear Sets in the Bank and only when there are items in that specific Set that aren't in that Container. Make a Gear Set, keep wearing half, but put the other half in the Bank; that should make it happen. The bug doesnt come and go, it's just that way permanently, and as far as I can remember it's been around a good while.
