### ISSUE TITLE
WotLK v1.9.52 - log on bug

### ISSUE THREAD

**Issue by Stefen74** [AdiAddons/AdiBags#877]
### Addon Version

v1.9.52

### World of Warcraft Version

Wrath

### Describe the bug

Message: Usage: local success = C_CVar.SetCVarBitfield(name, index, value [, scriptCVar])
Time: Thu Jan  5 18:09:48 2023
Count: 1
Stack: Usage: local success = C_CVar.SetCVarBitfield(name, index, value [, scriptCVar])
[string "=[C]"]: in function `SetCVarBitfield'
[string "@Interface\AddOns\AdiBags\core\Core.lua"]:121: in function <Interface\AddOns\AdiBags\core\Core.lua:82>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua"]:66: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua"]:619: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:611>

Locals: <none>

### Steps to reproduce

When logging on.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
This will be fixed in the next release -- the WotLK code path has a few bugs that need to be fixed.
