### ISSUE TITLE
Gold count font

### ISSUE THREAD

**Issue by tempest420** [AdiAddons/AdiBags#88]
More of a request than a bug, I hope that's ok. The currency widget allows you to change font/font size/color etc. The same is true of the text on the inventory pane (category names). Can you add this feature to the gold count? It is the only one that stays as the wow default.

**Comment by Cidan** [comment]
Once things settle down and I can get most show stopper bugs fixed, I'll look into adding more features like this.

**Comment by tempest420** [comment]
Thanks Cidan, appreciate it.

**Comment by kalbert312** [comment]
https://github.com/AdiAddons/AdiBags/pull/466
