### ISSUE TITLE
[Feature]: Toggle Recent Item Catagory

### ISSUE THREAD

**Issue by griddark** [AdiAddons/AdiBags#882]
### Describe the feature

Normally I just manually remove the Recent Item category in the module/widget lua, but due to all the updates the addon is having recently this has become time consuming.
It would be great if we could have new items highlight without having them have their own category.

### Describe the implementation

In options under Track new items, have a toggle to disable recent item category.

**Comment by kirk56k** [comment]
I'd love to see this feature as well. +1 Please and thank you.
