### ISSUE TITLE
Reagent Bank Deposit Issue

### ISSUE THREAD

**Issue by MechaZao** [AdiAddons/AdiBags#885]
### Addon Version

v1.9.54

### World of Warcraft Version

Retail

### Describe the bug

Items in the Reagent Bag do not go into the Reagent Bank when pressing Deposit All Reagents.

I have to either move them to a normal bag first, or place them in the reagent bank manually.

### Steps to reproduce

1. Have reagents in player Reagent Bag

2. Press Deposit All Reagents (with Reagent Bank open)

3. nothing happens

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
I can't reproduce this -- I just emptied out my reagent bank, loaded up by reagent bag, closed the bank, opened it back up, hit the deposit button, and items from the reagent bag deposited into the reagent bank.

This function isn't something AdiBags actually does manually. There's an API call we make to the Blizzard API that handles the depositing of reagents and all logic as to what to deposit and where. Addon authors have no control over this. Are you sure your reagent bank isn't full? If not, can you install bugsack and buggrabber, and see if you get any errors?

**Comment by MechaZao** [comment]
I have no errors at all coming from it - but here is a short clip of the issue. I emptied my reagent bank into my bags, pressed deposit, and *only* the items that were not in my reagent bag went into the bank. 

https://streamable.com/sc329x

here are the remaining items after pressing deposit and confirming there is still space (40 slots) in the reagent bank 

![image](https://user-images.githubusercontent.com/20646520/211237725-6b8967b9-c5b8-4ba0-970d-38a7df8fe55f.png)

that is with adibags as the only enabled addon.

**Comment by MechaZao** [comment]
Upon further investigation, this only seems to be happening on a couple of characters (that I know of) - and persisted through a complete reinstall.

So I did some further research and some more digging and it turns out that at some point on those characters, (though I'm not sure how since I've only ever used AdiBags), "Ignore This Bag" was checked for the reagent slot.

![image](https://user-images.githubusercontent.com/20646520/211387164-9beeeead-0bd9-4390-9e7c-e57150f58990.png)

Unchecking this in the default UI and then re-enabling AdiBags, the deposit function now works as intended.

sorry for the mistaken bug report! hopefully it helps somebody else who may be having the same issue though.

**Comment by Cidan** [comment]
Oh interesting. Thanks for reporting this. I think we need to check for this in AdiBags and make sure ignore is off, or otherwise give users the option to toggle this setting.
