### ISSUE TITLE
Reagents with Quality Sorting Issue

### ISSUE THREAD

**Issue by MechaZao** [AdiAddons/AdiBags#886]
### Addon Version

v1.9.54

### World of Warcraft Version

Retail

### Describe the bug

Within their own category, reagents seem to be sorted in seemingly random orders. For example - 

![image](https://user-images.githubusercontent.com/20646520/211227036-3ee6fffa-3e9e-4c7f-b755-e1bf081fc2a3.png)

I would expect this to either go T1-T2-T3 or T3-T2-T1

not all reagents follow the same order, but none of them seem to be in a sensible one.

this happens regardless of my item sort settings, and with no third party category addons enabled.

### Steps to reproduce

1. Have two or three of the same reagent in your bank or bag, with different quality tiers

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Sorting isn't done by AdiBags and is done by Blizzard's sort method. Sub-sorting by quality is not something on our radar at the moment.
