### ISSUE TITLE
Bags randomly resetting to default

### ISSUE THREAD

**Issue by MechaZao** [AdiAddons/AdiBags#89]
For some reason, my adibags will randomly reset to default settings. I can't reproduce the reset, but I can fix it SOMETIMES by hitting the blizzard sort button. If that doesn't work, I have to go into config and reselect the profile. Note: profile didn't change throughout. There are no LUA errors.  Edit: reset seems to happen the most after looting or changing zones. Not every time.

**Comment by Cidan** [comment]
Can you define what you mean by "reset to default settings?" Do you mean that literally, any options that you set in the config window will randomly snap back to their defaults? Does this happen mid-game, or only when you login? If you re-login, do your settings load back up to what they were, or are they saved to the default state?

When do you first notice it? Does it happen randomly while you have the bag open, or does it happen right when you open your bag?

Thanks.

**Comment by MechaZao** [comment]
I can explain with some screenshots. This is what it looks like when it resets. http://puu.sh/qe1cb/4703be9350.jpg This doesn't happen with the bag actually open, but when I open the bag it looks this way. I can close it and reopen it several times and it stays  like that. If I hit the blizzard sort button, it will usually go back to my selected filters. When logging out and back in, it's set to my normal settings.

http://puu.sh/qe1ip/026c9f1d38.jpg is what it looks like with my settings.

**Comment by Cidan** [comment]
Ah, okay. I actually fixed this bug on my branch as I ran into it as well. It'll be fixed in the next version.

Thanks for the screenshots :)

**Comment by MechaZao** [comment]
Thanks! and no problem
