### ISSUE TITLE
Anchor Option Missing

### ISSUE THREAD

**Issue by ThePrez0Dent** [AdiAddons/AdiBags#890]
### Addon Version

v1.10.1

### World of Warcraft Version

Retail

### Describe the bug

Maybe you are already aware but the option to move the bags anchor is missing (or I am absolutely blind)

### Steps to reproduce

Not sure if it has anything to with it but I had previously disabled the option to show/move the anchor without opening the options menu

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
The anchor option has been removed from AdiBags, as it was a rarely used option. Virtually everyone dragged the bags by dragging the titlebar handle.

**Comment by ThePrez0Dent** [comment]
Thank you for your quick response... didn't know this was an option (I'll see my dumb self out)

**Comment by Cidan** [comment]
Not at all dumb! This is actually exactly why I removed the option -- it's a really bad user experience in 2023 and very non-standard.

**Comment by ThePrez0Dent** [comment]
Personally I am more of a fan of having the options to put in the exact coordinates to precisely align stuff but then again also a very OCD persona about this stuff :)

**Comment by Cidan** [comment]
I can understand that. I think I'll circle back at some point and offer something that will aid in this, just not as intrusive/opinionated as the anchor.

**Comment by Talyrius** [comment]
> Personally I am more of a fan of having the options to put in the exact coordinates to precisely align stuff but then again also a very OCD persona about this stuff :)

Yes, me too! 😆

**Comment by Cidan** [comment]
See #891 for thoughts on this. Thank you for the feedback!

**Comment by Tzarynn** [comment]
The few people that I play with and I actually hate that this feature is gone.  We are constantly moving our bags unintentionally. Having the locked bags feature was great, we could play the way we wanted to without having to worry about dragging our bags. Please, for the love of all that is holy, bring back this feature.

**Comment by Talyrius** [comment]
This issue has been closed. Please direct your feedback to #891.
