### ISSUE TITLE
[Feature]: Anchor reworked implementation

### ISSUE THREAD

**Issue by Cidan** [AdiAddons/AdiBags#891]
### Describe the feature

With the elimination of the Anchor positioning, users are left without a means to set the exact position of the bag. AdiBags will implement a coordinate overlay for bags, such that, if enabled, coordinates are displayed in an overlay when the bag is dragged, and disappears once the bag stops dragging.

With this, the return of locking a bag's position should come back.

The key difference between this proposal and anchors is there should be no option for changing how a bag is positioned. All options should be informational in nature.

### Describe the implementation

- A checkbox option in the options screen that when enabled, will overlay bags with a coordinates panel, telling you where all four corners of the bag are at any given moment.
- The ability to lock the bag using alt + click like previously possible in Anchor mode.

Other considerations:

It might make more sense that instead of using an option, the user simply has to ctrl + drag the header for the overlay to appear, eliminating "option fatigue". We'll test this out and gather feedback.

**Comment by Talyrius** [comment]
The overlay for the anchors could also be unlocked/displayed in the default UI's new Edit Mode. As an example, Bartender4 does this in addition to offering its own options.

My preference is always for precise control over each point and offset. However, I'm not the average user. ¯\\_(ツ)_/¯

**Comment by Cidan** [comment]
Also, I don't see bags in the edit mode window as an option, do we have to add it? ergh.

**Comment by Cidan** [comment]
quote AcidWeb: "Don't." lol

**Comment by Dmeister406** [comment]
Hi Cidan,

Is there any expected timeframe for adding back in a feature to lock the windows in place now that the anchor option has been removed? Many thanks for your work on this addon.

**Comment by Cidan** [comment]
Hi there,

I'm working on two different features right now that I'd like to get done this week. The first is the ability to automatically split reagents by expansion pack, and the second being some desperately needed internal cleanup around type annotations and renaming some internal fields.

I'll probably target window locking first, as it's a very easy add, later this week. I'll then add the anchor overlay either next week, or in Feb, as I'm taking some time off of work towards the end of Jan for travel.

**Comment by Dmeister406** [comment]
OK awesome! Thanks a million!

**Comment by glassleo** [comment]
An option to choose how the window grows, would be nice while waiting for the anchor to come back. I always used to have the window in my bottom right corner and it'd grow upwards+left, but now since I accidentally moved it it has started to grow downwards which is super annoying.

**Comment by glassleo** [comment]
> Also, I don't see bags in the edit mode window as an option, do we have to add it? ergh.

It's coming in 10.0.5 (you will be able to move the bag bar). I don't think the bag windows themselves are moveable in Edit Mode at all.

I don't think AdiBags needs to be involved in Edit Mode at all.

**Comment by Cidan** [comment]
@glassleo Yeah, we're not going to integrate with edit mode, as it's a complete and total disaster that breaks addons at random.

There are enough thoughts around this, that I may bring the anchor back, but have it turned off by default for a more natural user experience for new users, and allow people to turn it on if they'd like.

**Comment by glassleo** [comment]
Hmm, the window growing bug seems to only happen right after you have moved the window without closing it. If I move it, then re-open, it grows as I would expect.

**Comment by Dmeister406** [comment]
> There are enough thoughts around this, that I may bring the anchor back, but have it turned off by default for a more natural user experience for new users, and allow people to turn it on if they'd like.

I actually really like this idea. I must say as a new user of Adibags, when I first installed it I was a little confused by the way the anchor system worked. However, after a little time I came to understand it and then really like it!

**Comment by silverhawke249** [comment]
so this was a recent change? i feel like older versions of AdiBags would anchor the bank window position relative to the bag window position... now that this feature is gone, my bank window would either be too far away from the bag window or they would overlap, depending on how the addon decides to layout the bag. i would love for an option to anchor the bank relative to the bag again.

**Comment by yajinni** [comment]
Any update on this?
I sorely miss being able to have the ancho set to the bottom right and have it grow out from there.
My bad sometimes overlap with other elements from my UI since this change.

**Comment by Dmeister406** [comment]
> Any update on this?

I've been following this on the AB Discord. Cidan has said on a number of occasions over the last 3 or 4 months that the anchor feature would be reinstated but defaulted to "off". It hasn't happened yet as he has said he is busy with RL. Perhaps it will happen with an update for 10.1, as I'm sure that will break a lot of addons again...

**Comment by Cidan** [comment]
The old anchor system has now been restored and released. Sorry for the delay folks, really really busy last few months for me!

Anchor mode is off by default, it can be enabled by alt-clicking on the bag, or using the options menu to turn it on.
