### ISSUE TITLE
Quest Icon Color and Marker

### ISSUE THREAD

**Issue by ThePrez0Dent** [AdiAddons/AdiBags#892]
### Addon Version

v1.10.1

### World of Warcraft Version

Retail

### Describe the bug

Quest Icon Color is blue and Marker is missing if Masque is not enabled/adibags skinning is disabled

**Masque Disabled/Skinning Disabled**
![grafik](https://user-images.githubusercontent.com/118535256/211411671-36bd1bfd-fd59-4dc2-84bc-c45dba48a314.png)

**Masque Enabled/Skinning Enabled**
![grafik](https://user-images.githubusercontent.com/118535256/211412103-b2471ffb-6b25-4db5-97f3-a31384ca758b.png)

### Steps to reproduce

Run Adibags with/without Masque enabled/Skinning enabled

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Oh, interesting. I'll take a look at this. Thanks :)

**Comment by Cidan** [comment]
Fixed in the next release. Thanks for the report!

**Comment by ThePrez0Dent** [comment]
Not the same issue but I'll just add this here.
There seems to be some layering issue with the Azerite Gear Regardless of skinning
**Without**
![grafik](https://user-images.githubusercontent.com/118535256/211416003-d2480906-eaff-4b85-8cfa-cd8ce6a2d9bc.png)
**With**
![grafik](https://user-images.githubusercontent.com/118535256/211416252-a4bc20d1-4b3c-41ea-a45d-eefd0bc2c892.png)

**Comment by Cidan** [comment]
I skipped BfA and I have no Azerite gear to test with. I'm also not entirely sure what I'm supposed to be looking for. I spot some differences, but I don't understand what you're trying to say.

**Comment by ThePrez0Dent** [comment]
I am pretty sure the colored border was above the "corner icons" on versions <1.10.x but as it is bfa I am not sure if I wanna install a old version just to check that

**Comment by ThePrez0Dent** [comment]
Also:
1. Are Bank/Reagent Bags supposed to not be anchored to the Inventory anymore?
2. Bank/Reagent using set color only for border 
![grafik](https://user-images.githubusercontent.com/118535256/211417260-9cfdd8a4-92e7-4f60-8924-2656015c7275.png)

**Comment by Cidan** [comment]
I don't think I changed anything with regard to ordering or layering that would have caused this. Besides, I think the border icons should be on top anyway.

**Comment by Cidan** [comment]
@ThePrez0Dent

1. No, Anchoring has been removed as it was a weird and non-standard paradigm. A revised psuedo-anchoring system will return at a later date.
2. What texture are you using for the bank? It works here:

![image](https://user-images.githubusercontent.com/1133628/211417917-c7bbd5b5-1dda-4560-b1a5-0280909cc501.png)

**Comment by ThePrez0Dent** [comment]
Blizzard Dialog Ba.... 1. (second from Top)
Pretty sure I never changed that as I only recently completely redid my interface but maybe that's some relic when I was messing aroung or just something that changed with then updating to the new version

Blizzard Tooltip works fine though thank you
