### ISSUE TITLE
Small lag spike when opening bag

### ISSUE THREAD

**Issue by Illusionarygod** [AdiAddons/AdiBags#894]
### Addon Version

1.10.0

### World of Warcraft Version

Retail

### Describe the bug

There's a small lag spike each time I open my bags. It's definitely subtle, but it's something I notice and I was hoping there could be a fix.

### Steps to reproduce

Opening bag, much more noticeable if you repeatedly open and close.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
I noticed this too, actually! There are some parts of the drawing code that I know are inefficient. Unfortunately, that part of the code is very, very involved and it's going to take a while to get to the root of this. It's something I've had in mind for a while, and a part of my plan to tackle for v2.0.0
