### ISSUE TITLE
Junk not desaturated when skinned by Masque

### ISSUE THREAD

**Issue by ThePrez0Dent** [AdiAddons/AdiBags#896]
### Addon Version

v1.10.1

### World of Warcraft Version

Retail

### Describe the bug

Junk not desaturated when skinned by Masque
not sure if that is a bug or just an effect of Masque taking over the look but hey there you go
Happens on all the Skins I have tried (Blizzard Classic/Modern, Caith, Hex, Raeli)

**Disabled**
![grafik](https://user-images.githubusercontent.com/118535256/211452751-4f9b29a0-414c-4590-963a-56a7124b31c4.png)

**Enabled**
![grafik](https://user-images.githubusercontent.com/118535256/211453413-073ce85c-4a2e-4d5d-8b03-961b2fa3313f.png)
![grafik](https://user-images.githubusercontent.com/118535256/211452955-1009929b-651a-4746-bb7f-b9ecbcb79bf8.png)

### Steps to reproduce

Enable Masque Skinning

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

PS: Sorry for adding to your workload so much today

**Comment by Cidan** [comment]
I noticed this as well. I'm pretty sure this is an effect Masque has on the button's. I'll see if there's something I can do about it.
