### ISSUE TITLE
[Feature]: Reimplement Bag/Bank background colour change

### ISSUE THREAD

**Issue by Dmeister406** [AdiAddons/AdiBags#897]
### Describe the feature

In previous versions, bank and bag window background colour could be changed. In version 1.10.2 this option has been removed:

https://iili.io/H7Wr6s1.jpg

### Describe the implementation

A simple option as before would be the best implementation.

**Comment by Cidan** [comment]
You can still set the background color. In the screenshot you pasted, there's just one box now that says Color. Make sure you select the correct texture as well.
