### ISSUE TITLE
Transparent background - can't change

### ISSUE THREAD

**Issue by Dahhhaka** [AdiAddons/AdiBags#900]
### Addon Version

v1.10.2

### World of Warcraft Version

Retail

### Describe the bug

For a few days, the background of my AdiBags has become transparent. 

[https://i.imgur.com/yuUxB4X.png](url)

Disabled all addons, opened up settings, and all the theming options are greyed out:
[https://i.imgur.com/NC3QCbU.png](url)

### Steps to reproduce

Open adibags

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
If you click on the "Theme" option on the left (not one of the sub menus), you'll see:

![image](https://user-images.githubusercontent.com/1133628/211687443-1a5c8f99-2c2b-46a2-a35c-5a45373f7e87.png)

The instructions there state that if you have the "default" theme selected, you can't edit or update the theme, as the default theme can not be changed. Type in a new theme into the box labeled "New Theme Name". This will create a new theme, select it, and all the controls will be enabled for you to edit.
