### ISSUE TITLE
Pawn Upgrade Arrow Compatiblity with Masque

### ISSUE THREAD

**Issue by ThePrez0Dent** [AdiAddons/AdiBags#901]
### Addon Version

v1.10.2

### World of Warcraft Version

Retail

### Describe the bug

Pawn Upgrade Arrow missaligned when skinned by Masque (I would assume it would also happen with the normal ilvl arrow if it wasn't afaik removed in 10.0 (unintentionally or not who knows))
not sure if this is something you can do something about

**Unskinned**
![grafik](https://user-images.githubusercontent.com/118535256/211736044-9872c30b-fbee-40bc-996a-a2f486080138.png)

**Skinned**
![grafik](https://user-images.githubusercontent.com/118535256/211736122-dae4e124-5661-4dc2-a7d7-d9df97c866a0.png)
![grafik](https://user-images.githubusercontent.com/118535256/211736180-fbc45ce1-1e20-4b9d-8895-170f2ec39483.png)

### Steps to reproduce

See above

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
I don't think we can change the arrow alignment, but the ilevel one I think we can change. I think answer here is to allow users to adjust the location of the ilevel.

**Comment by juntereiner** [comment]
> I don't think we can change the arrow alignment, but the ilevel one I think we can change. I think answer here is to allow users to adjust the location of the ilevel.

OMG yes please, I always need to change the ilvl position when there is a new update.

**Comment by ThePrez0Dent** [comment]
Though I have literally no idea why the arrow moves up when skinned

**Comment by Cidan** [comment]
Nor do I -- I haven't dug very deep into Masque tbh. Some of what it does is ✨magic✨.

**Comment by ThePrez0Dent** [comment]
my first thought was that it was messing up text placement because I changed icon scaling to prevent other problems with border size but as its happening with other skins too I have no idea

**Comment by swaj** [comment]
How are you getting the quality border to align with the Masque icon edges?  For me, no matter which skin I pick in Masque, the quality border either doesn't show at all, or it's always a rounded square.
