### ISSUE TITLE
[Feature]: Change Scale increments

### ISSUE THREAD

**Issue by KatyPurry** [AdiAddons/AdiBags#903]
### Describe the feature

By default bag's scale can only be changed by 10% increments. Would it be possible to set the increments to 5% or 1%? 

![image](https://user-images.githubusercontent.com/89610869/211874916-aa790ad0-9783-47ef-8eb0-e74f63c3be41.png)

Max height size can be changed 1 by 1.

### Describe the implementation

Review code

**Comment by Cidan** [comment]
Yeah, I think this should be doable. We'll add it.

**Comment by glassleo** [comment]
I'd like decimals, even. I like to set my scale to a pixel perfect value, which happens to be 83.33%. It would be nice to not have to edit the SavedVariables manually!

**Comment by Cidan** [comment]
Unfortunately, the smallest unit we can support is a single decimal point, i.e. 83.3%

I have two concerns here:

1) Upon testing 1% stepping, it seems like the slider skips digits, i.e. you can slide from 99% to 101%. Typing 100% into the box works.

2) The smallest unit we can support is one decimal point, i.e. 83.3%. However, setting the increments this small, it makes the slider more or less completely useless.

Let me think about the best way to go about this for a bit.

**Comment by glassleo** [comment]
> The smallest unit we can support is one decimal point, i.e. 83.3%. However, setting the increments this small, it makes the slider more or less completely useless.

Yeah, those AceGUI widgets are not the best... if only it didn't reformat the step value when entering a value manually it would be fine. Not sure if that's possible with the way the widget works.

**Comment by eleanoryeung** [comment]
Is it possible to make the actual icon size editable? I don't think scale is very useful as most other elements are already customizable. The only reason for me to change the scale is to shrink the icons, but i think it makes colored quality borders hard to see, which i notice after the masque support.

**Comment by Cidan** [comment]
@eleanoryeung Can you describe this a bit more? Do you mean to scale the item buttons down, but keep the extra whitespace around the bag?

**Comment by eleanoryeung** [comment]
> @eleanoryeung Can you describe this a bit more? Do you mean to scale the item buttons down, but keep the extra whitespace around the bag?

Basically yes. I am accustomed to change the actual button size like 14, 16 or so.
I did not actually notice the whitespace. It's not a problem for me.
