### ISSUE TITLE
Missing textures will break bags on open

### ISSUE THREAD

**Issue by Cidan** [AdiAddons/AdiBags#905]
### Addon Version

v1.10.0 - v1.10.4

### World of Warcraft Version

Retail

### Describe the bug

When setting up a theme, textures for the background and border of the bag are pulled from LibSharedMedia. If a bag sets a texture via LSM, and the texture later disappears (i.e. addon providing that texture is uninstalled), the bag will error on open until the theme or texture is changed in the options. This prevents the bag from working smoothly if textures disappear.

We need to check if a texture exists when doing a render of the bag, and default to a safe texture if not found.

### Steps to reproduce

Install an addon with a texture, i.e. GW2_UI

Use a provided texture with AdiBags in the theme window

Disable the addon that provides the texture

Try to open the bag, and the error will happen.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Zxkarie** [comment]
Have a similar issue #908 
I have my bags/bank using the Blizzard Tooltip texture but it keeps defaulting back to the 2nd option down from the list "Blizzard Dialog Ba..." can't see what it says. 

Never had this issue before updating to v1.10.5
LUA error also.

1x SharedXML/Backdrop.lua:296: attempt to index field 'backdropInfo' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags/core/OO.lua"]:60: in function <AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@AdiBags/core/Bags.lua"]:136: in function GetFrame' [string "@AdiBags/core/Bags.lua"]:90: in function Open'
[string "@AdiBags/core/Hooks.lua"]:119: in function <AdiBags/core/Hooks.lua:116>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>
