### ISSUE TITLE
Addon broken with new update

### ISSUE THREAD

**Issue by Nabohs** [AdiAddons/AdiBags#907]
### Addon Version

v1.10.4

### World of Warcraft Version

Wrath

### Describe the bug

Unable to use addon, only has default bag space

### Steps to reproduce

5x Interface\AddOns\AdiBags\core\Constants.lua:92: table index is nil
[string "@Interface\AddOns\AdiBags\core\Constants.lua"]:92: in main chunk

Locals:
addonName = "AdiBags"
addon = <table> {
 isWrath = true
 isClassic = false
 GetFontDefaults = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:132
 isRetail = false
 CreateFontOptions = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:141
 L = <table> {
 }
 isBCC = false
 CreateFont = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:122
}
L = <table> {
 Reset new items = "Reset new items"
 Use SyLevel = "Use SyLevel"
 Bags = "Bags"
 Bag background = "Bag background"
 Use this section to define any item-section association. = "Use this section to define any item-section association."
 Alt-right-click to configure manual filtering. = "Alt-right-click to configure manual filtering."
 AMMO_TAG = "Am"
 auto-sort = "auto-sort"
 Let SyLevel handle the the display. = "Let SyLevel handle the the display."
 Never = "Never"
 Consider gems as a subcategory of trade goods = "Consider gems as a subcategory of trade goods"
 ... including incomplete stacks = "... including incomplete stacks"
 Filter = "Filter"
 Change stacking at merchants', auction house, bank, mailboxes or when trading. = "Change stacking at merchants', auction house, bank, mailboxes or when trading."
 Same as InventoryItemLevels = "Same as InventoryItemLevels"
 Bind type = "Bind type"
 Recent Items = "Recent Items"
 Size = "Size"
 Track new items in each bag, displaying a glowing aura over them and putting them in a special section. "New" status can be reset by clicking on the small "N" button at top left of bags. = "Track new items in each bag, displaying a glowing aura over them and putting them in a special section. "New" status can be reset by clicking on the small "N" button at top left of bags."
 Display the level of equippable item in the top left corner of the button. = "Display the level of equippable item in the top left corner of the button."
 Font = "Font"
 Press Alt while doing so to open a dropdown menu. = "Press Alt while doing so to open a dropdown menu."
 None = "None"
 Lock anchor = "Lock anchor"
 Opacity = "Opacity"
 Show filtering information... = "Show filtering information..."
 Texture = "Texture"
 Select which first-level categories should be split by sub-categories. = "Select which first-level categories should be split by sub-categories."
 Mininum level = "Mininum level"
 Show only one free slot for each kind of bags. = "Show only one free slot for each kind of bags."
 Split by subcategories = "Split by subcategories"
 When checked, right-clicking on an empty space of a bag opens the configuration panel. = "When checked, right-clicking on an empty space of a bag opens the configuration panel."
 Click to reset item status. = "Click to reset item status."
 Container information = "Container information"
 ENCHANTING_BAG_TAG = "En"
 Filtering information = "Filtering information"
 Item category = "Item category"
 Merge free space = "Merge free space"
 Select how the bags are positionned. = "Select how the bags are positionned."
 Remove = "Remove"
 Toggle and configure item filters. = "Toggle and configure item filters."
 Small = "Small"
 Check this to display one individual section per set. If this is disabled, there will be one big "Sets" section. = "Check this to display one individual section per set. If this is disabled, there will be one big "Sets" section."
 Mining = "Mining"
 Allow you manually redefine the section in which an item should be put. Simply drag an item on the section title. = "Allow you manually redefine the section in which an item should be put. Simply drag an item on the section title."
 Merge stackable items = "Merge stackable items"
 Drop your item there to add it to this section. = "Drop your item there to add it to this section."
 disabled = "disabled"
 Right-click to (un)lock the bag anchor. = "Right-click to (un)lock the bag anchor."
 Check this to show space at your bank in the plugin. = "Check this to show space at your bank in the plugin."
 Bank color = "Bank color"
 Virtual stacks display in one place items that actually spread over several bag slots. = "Virtual stacks display in

3x Interface\AddOns\AdiBags\core\Bags.lua:161: attempt to index field 'BAG_IDS' (a nil value)
[string "@Interface\AddOns\AdiBags\core\Bags.lua"]:161: in function `NewBag'
[string "@Interface\AddOns\AdiBags\core\Bags.lua"]:205: in main chunk

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 CloseBag = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:156
 CloseBackpack = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:187
 EnableModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:328
 modules = <table> {
 }
 IterateEmbeds = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:438
 SecureHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:335
 IterateDefinedBags = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:195
 IterateBags = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:190
 NewBag = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:157
 bagProto = <table> {
 }
 RawHookScript = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:394
 CloseSpecialWindows = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:215
 defaultModulePrototype = <table> {
 }
 GetContainerItemTexture = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:438
 ConfigChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:395
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:405
 UpsertTheme = <function> defined @Interface\AddOns\AdiBags\core\Theme.lua:30
 hooks = <table> {
 }
 OpenBackpack = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:175
 defaultModuleState = false
 ThemeExists = <function> defined @Interface\AddOns\AdiBags\core\Theme.lua:86
 IsEnabled = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:447
 SplitSectionKey = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:356
 GetArgs = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:140
 DisableModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:346
 CloseAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:126
 SetupTooltip = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:127
 Reconfigure = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:226
 isRetail = false
 GetContainerItemTextureCountLocked = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:442
 DeleteTheme = <function> defined @Interface\AddOns\AdiBags\core\Theme.lua:90
 RegisterBucketEvent = <function> defined @Interface\AddOns\AdiBags\core\EventHandlers.lua:119
 Printf = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:65
 BuildSectionKey = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:346
 GetDistinctItemID = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:303
 CreateFont = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:122
 isClassic = false
 GetContainerFrame = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:78
 Debug = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:62
 OpenOptions = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:310
 GetContainerSkin = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:520
 SetEnabledState = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:420
 Hook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:273
 enabledState = true
 ShouldStack = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:484
 RegisterEvent = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:80
 GetInteractingWindow = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:475
 UpdateInteractingWindow = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:461
 BankUpdated = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:377
 SecureHookScript = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:409
 IterateModules = <function> defined @Interface\AddOns\AdiBags\libs

3x Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:1116: attempt to perform arithmetic on local 'ITEM_SIZE' (a nil value)
[string "@Interface\AddOns\AdiBags\widgets\ContainerFrame.lua"]:1116: in main chunk

Locals:
addonName = "AdiBags"
addon = <table> {
 modules = <table> {
 }
 UpdateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:335
 GetInteractingWindow = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:475
 GetContainerItemTexture = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:438
 ConfigChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:395
 GetSlotId = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:70
 Filter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:447
 Reconfigure = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:226
 isRetail = false
 RegisterMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:143
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:303
 CreateFont = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:122
 isClassic = false
 OpenOptions = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:310
 GetFamilyTag = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:394
 Hook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:273
 IterateBags = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:190
 OnEnable = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:140
 NewBag = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:157
 GetClass = <function> defined @Interface\AddOns\AdiBags\core\OO.lua:129
 RegisterFilter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:120
 RemoveTooltip = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:160
 NewModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:231
 isBCC = false
 GetContainerItemStackCount = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:434
 IterateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:386
 hookedBags = <table> {
 }
 OpenBag = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:144
 ToggleAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:93
 NewTheme = <function> defined @Interface\AddOns\AdiBags\core\Theme.lua:66
 GetName = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:275
 name = "AdiBags"
 OpenBackpack = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:175
 LayoutBags = <function> defined @Interface\AddOns\AdiBags\core\Layout.lua:67
 Disable = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 SetGlobalLock = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:443
 ParseItemLink = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:178
 DisableHooks = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:213
 Unhook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:417
 Print = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:50
 OpenAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:116
 L = <table> {
 }
 safecall = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:94
 Debug = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:62
 SaveTheme = <function> defined @Interface\AddOns\AdiBags\core\Theme.lua:76
 CompareSectionKeys = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:364
 UnregisterEvent = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:143
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 CloseBag = <functio

3x Interface\AddOns\AdiBags\widgets\ItemButton.lua:229: attempt to index field 'BAG_IDS' (a nil value)
[string "@Interface\AddOns\AdiBags\widgets\ItemButton.lua"]:229: in main chunk

Locals:
addonName = "AdiBags"
addon = <table> {
 AcquireItemButton = <function> defined @Interface\AddOns\AdiBags\widgets\ItemButton.lua:179
 modules = <table> {
 }
 UpdateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:335
 GetInteractingWindow = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:475
 GetContainerItemTexture = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:438
 ConfigChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:395
 GetSlotId = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:70
 Filter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:447
 Reconfigure = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:226
 isRetail = false
 RegisterMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:143
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:303
 CreateFont = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:122
 isClassic = false
 OpenOptions = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:310
 GetFamilyTag = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:394
 Hook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:273
 IterateBags = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:190
 OnEnable = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:140
 NewBag = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:157
 GetClass = <function> defined @Interface\AddOns\AdiBags\core\OO.lua:129
 RegisterFilter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:120
 RemoveTooltip = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:160
 NewModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:231
 isBCC = false
 GetContainerItemStackCount = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:434
 IterateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:386
 CreateBagSlotPanel = <function> defined @Interface\AddOns\AdiBags\widgets\BagSlots.lua:448
 hookedBags = <table> {
 }
 OpenBag = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:144
 ToggleAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:93
 NewTheme = <function> defined @Interface\AddOns\AdiBags\core\Theme.lua:66
 GetName = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:275
 name = "AdiBags"
 OpenBackpack = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:175
 LayoutBags = <function> defined @Interface\AddOns\AdiBags\core\Layout.lua:67
 Disable = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 SetGlobalLock = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:443
 ParseItemLink = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:178
 DisableHooks = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:213
 Unhook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:417
 Print = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:50
 OpenAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:116
 L = <table> {
 }
 safecall = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:94
 Debug = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:62
 SaveTheme = <function> defined @Interface\AddOns\AdiBags\core\Theme.lua:76
 CompareSectionKeys = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:364
 UnregisterEvent = <function> defined @Interface\AddOns\AdiBags\l

3x Interface\AddOns\AdiBags\widgets\Section.lua:52: attempt to perform arithmetic on local 'ITEM_SIZE' (a nil value)
[string "@Interface\AddOns\AdiBags\widgets\Section.lua"]:52: in main chunk

Locals:
addonName = "AdiBags"
addon = <table> {
 AcquireItemButton = <function> defined @Interface\AddOns\AdiBags\widgets\ItemButton.lua:179
 modules = <table> {
 }
 UpdateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:83
 SecureHook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:335
 GetInteractingWindow = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:475
 GetContainerItemTexture = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:438
 ConfigChanged = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:395
 GetSlotId = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:70
 Filter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:144
 IsEnabled = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:447
 Reconfigure = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:226
 isRetail = false
 RegisterMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface\AddOns\AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:143
 hooks = <table> {
 }
 GetDistinctItemID = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:303
 CreateFont = <function> defined @Interface\AddOns\AdiBags\core\Fonts.lua:122
 isClassic = false
 OpenOptions = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:310
 GetFamilyTag = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:394
 Hook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:273
 IterateBags = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:190
 OnEnable = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:140
 NewBag = <function> defined @Interface\AddOns\AdiBags\core\Bags.lua:157
 GetClass = <function> defined @Interface\AddOns\AdiBags\core\OO.lua:129
 RegisterFilter = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:120
 RemoveTooltip = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:160
 NewModule = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:231
 isBCC = false
 GetContainerItemStackCount = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:434
 IterateFilters = <function> defined @Interface\AddOns\AdiBags\core\Filters.lua:116
 ReagentBankUpdated = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:386
 CreateBagSlotPanel = <function> defined @Interface\AddOns\AdiBags\widgets\BagSlots.lua:448
 hookedBags = <table> {
 }
 OpenBag = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:144
 ToggleAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:93
 NewTheme = <function> defined @Interface\AddOns\AdiBags\core\Theme.lua:66
 GetName = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:275
 name = "AdiBags"
 OpenBackpack = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:175
 LayoutBags = <function> defined @Interface\AddOns\AdiBags\core\Layout.lua:67
 Disable = <function> defined @Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 SetGlobalLock = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:443
 ParseItemLink = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:178
 DisableHooks = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:213
 Unhook = <function> defined @Interface\AddOns\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:417
 Print = <function> defined @Interface\AddOns\AdiBags\libs\AceConsole-3.0\AceConsole-3.0.lua:50
 OpenAllBags = <function> defined @Interface\AddOns\AdiBags\core\Hooks.lua:116
 L = <table> {
 }
 safecall = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:94
 Debug = <function> defined @Interface\AddOns\AdiBags\core\Core.lua:62
 SaveTheme = <function> defined @Interface\AddOns\AdiBags\core\Theme.lua:76
 CompareSectionKeys = <function> defined @Interface\AddOns\AdiBags\core\Utility.lua:364
 UnregisterEvent = <function> defined @Interface\AddOns\AdiBags\l

3x Interface\AddOns\AdiBags\core\Core.lua:88: attempt to index field 'DEFAULT_SETTINGS' (a nil value)
[string "@Interface\AddOns\AdiBags\core\Core.lua"]:88: in function <Interface\AddOns\AdiBags\core\Core.lua:83>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:66: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:494: in function `InitializeAddon'
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:619: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:611>

3x Interface\AddOns\AdiBags\modules\DataSource.lua:59: attempt to index field 'db' (a nil value)
[string "@Interface\AddOns\AdiBags\modules\DataSource.lua"]:59: in function <Interface\AddOns\AdiBags\modules\DataSource.lua:58>
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:66: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:494: in function `InitializeAddon'
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:619: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:611>

3x Interface\AddOns\AdiBags\modules\NewItemTracking.lua:61: attempt to index field 'db' (a nil value)
[string "@Interface\AddOns\AdiBags\modules\NewItemTracking.lua"]:61: in function <Interface\AddOns\AdiBags\modules\NewItemTracking.lua:60>
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:66: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:494: in function `InitializeAddon'
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:619: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:611>

3x Interface\AddOns\AdiBags\modules\MoneyFrame.lua:35: attempt to index field 'db' (a nil value)
[string "@Interface\AddOns\AdiBags\modules\MoneyFrame.lua"]:35: in function <Interface\AddOns\AdiBags\modules\MoneyFrame.lua:34>
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:66: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:494: in function `InitializeAddon'
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:619: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:611>

3x Interface\AddOns\AdiBags\modules\FilterOverride.lua:67: attempt to index field 'db' (a nil value)
[string "@Interface\AddOns\AdiBags\modules\FilterOverride.lua"]:67: in function <Interface\AddOns\AdiBags\modules\FilterOverride.lua:64>
[string "=[C]"]: ?
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:66: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:494: in function `InitializeAddon'
[string "@Interface\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:619: in function <...ce\AddOns\AdiBags\libs\AceAddon-3.0\AceAddon-3.0.lua:611>

11x Interface_Wrath\FrameXML\Bindings.xml:1 Interface\AddOns\AdiBags\libs\LibSharedMedia-3.0\lib.xml:1 (null)

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Fixed in 1.10.5, which is building and going out now. You can get it from the release page on GitHub right away, or from Curse in a few minutes.

Thanks for the report!
