### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Zxkarie** [AdiAddons/AdiBags#908]
### Addon Version

v.1.10.5

### World of Warcraft Version

Retail

### Describe the bug

When opening the bag sometimes the background will be invisible. I literally just updated today. A reload fixes it but my bag opacity is lowered/more transparent than it was set at before.

1x SharedXML/Backdrop.lua:296: attempt to index field 'backdropInfo' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags/core/OO.lua"]:60: in function <AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@AdiBags/core/Bags.lua"]:136: in function `GetFrame'
[string "@AdiBags/core/Bags.lua"]:90: in function `Open'
[string "@AdiBags/core/Hooks.lua"]:119: in function <AdiBags/core/Hooks.lua:116>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

### Steps to reproduce

The only thing I did before the lua error popped up was I clicked edit mode and backed out of it, since I meant to click options.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Zxkarie** [comment]
nvm ignore the opacity thing, it changed my texture to dialogue box from tooltip, which is why the opacity was lower than it was before. Unsure what properly triggered the error, can't reproduce it.

**Comment by Cidan** [comment]
I believe this is related to #905. I'll close this in favor of that one.
