### ISSUE TITLE
Bank Bag 1 is always considered as reagent bag

### ISSUE THREAD

**Issue by sotheray** [AdiAddons/AdiBags#909]
### Addon Version

v1.10.5

### World of Warcraft Version

Wrath

### Describe the bug

Everything in bank bag 1 has a "re" tag.

### Steps to reproduce

put a bag in bank bag slot 1

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
I believe this is due to the new WotLK update that broke some events, and is fixed in the latest release of AdiBags. Can you verify?

**Comment by sotheray** [comment]
Still exists in the newest version 1.10.6 :(

**Comment by stu177** [comment]
Still broken for me with v1.10.7.
