### ISSUE TITLE
AdiBags Does Not Properly Reflect Inventory When Opening Mailbox

### ISSUE THREAD

**Issue by Nouser** [AdiAddons/AdiBags#910]
### Addon Version

1.10.5

### World of Warcraft Version

Wrath

### Describe the bug

When I open my mailbox and loot items to my inventory, the correct item stack quantities and free bagspaces are not properly shown. No errors are caught in Bugsack or Buggrabber.

### Steps to reproduce

0. Disable all addons except AdiBags, AdiBags Config, and BugSack/BugGrabber
1. Open bag
2. Go to mailbox
3. Open mail containing 12 items (I used 12 stacks of herbs)
4. Open mail containing some other item (I used a random green BoE)
5. Note that the item stack count may be off for these looted items (my herb count went up when I looted the BoE, free space wasn't correct)
6. Close the bag
7. Reopen the bag and see all matches as you expect

I have also repro'd this by looting one stackable item first and then some different item. The stack shows the wrong count and combines different looted items (ie I opened a stack of goldclover and a stack of lichbloom, it shows as goldclover with a quantity != goldclover count, lichbloom count, and goldclover + lichbloom count)

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
A few questions:

1) What are your virtual stack settings set to? i.e. which "Merge" options are enabled in the options?
2) When you collect those herbs from the mail, do you already have some of those same herbs? Are they all the same set of herbs, or different items?
3) Are you clicking on each item one by one when looting from the mail, or using an open all button?
