### ISSUE TITLE
[Feature]: Configure button

### ISSUE THREAD

**Issue by SpareSimian** [AdiAddons/AdiBags#912]
### Describe the feature

I disabled the right-click configure option in combat because I was always accidentally opening the config when I missed the rarely-used item in my bag that I was trying to use. Instead, I've been typing "/adibags config" when I need to add a new custom filter. My most common use case is when I want to add a toy to my "Consumable/Toy" section, a pet-related item to my "Consumable/Pet" section, or containers to my "Consumable/Container" section (so I'll remember to open them later). 

### Describe the implementation

I'd prefer to have a specific button in the upper right button cluster for configuration. Perhaps a "C" to the left of the "X" button, While you're at it, I'd love to have another button to quickly jump to the manual filter section of the config. "F", perhaps?

**Comment by Cidan** [comment]
We're planning on doing some new configuration options in the short term, including some new hotkeys. We'll actually be reducing the number of buttons on the top right and instead adding a menu button.

I do want to expand the hotkeys available to be bound, some of the current ones I have in mind are:

* Tri-state toggle between bag split of expansion + tradegood, just tradegood, just expansion
* Open your bank bag when you're not at the bank
* Configuration window

Thanks for the suggestions :)
