### ISSUE TITLE
[Feature]: Import String for Profiles from other people

### ISSUE THREAD

**Issue by Hyrulien** [AdiAddons/AdiBags#914]
### Describe the feature

Basically a feature like its present in the wow's talent tree or many other addons, where u can import & export the setup in the case of adibags this would mean like the sizing, layout, fonts, black/whitelisted items etc etc.

### Describe the implementation

In the profiles tab would be awesome to see an import & export button for your current profile. Perhaps a separate website where people post their adibag profiles would be nice but that might just be overkill. Posting it like people do on wago.io with other addon import strings should be good enough.

**Comment by SpareSimian** [comment]
Note that you can copy your AdiBags.lua file from the WTF directory. Pull it up in Notepad and check it out. The main issue with that is that it exposes your list of characters, which is a privacy issue. 

For me, the main item of value to share is the filter. Mine is about 90% of my config file. It might be nice to have some way of merging filters from others. But you'd want a way to back it up, as that's the fastest way to mess up a working filter set.
