### ISSUE TITLE
Quality highlight is much thinner when Masque is enabled

### ISSUE THREAD

**Issue by StragaSevera** [AdiAddons/AdiBags#917]
### Addon Version

v1.10.6

### World of Warcraft Version

Retail

### Describe the bug

When the setting "Quality highlight" is enabled (with full opacity and "dim junk" turned off), and Masque addon is on (and not turned off masking AdiBags specifically), the highlight is barely noticeable:

https://i.imgur.com/PjuOxjH.png

(The verification requires me to say I disabled all other addons, but this bug is because of interactions between two addons).

### Steps to reproduce

1. Install Masque;
2. Open the bags

### Verification

- [ ] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Masque is responsible for all aspects of the button, including the glow. The glow comes from whatever Masque theme is active, and is not something we can control.
