### ISSUE TITLE
Error when clicking the "N" button (reset new items)

### ISSUE THREAD

**Issue by tempest420** [AdiAddons/AdiBags#92]
Weird thing is, reloading ui makes it go away until something else triggers it.

Here's the error message:

Error in AdiBags: Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:995: AdiBagsSection4:SetPoint(): AdiBagsSection5 is dependent on this -- details: [Error 000001E4461ECB80]
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:995: AdiBagsSection4:SetPoint(): AdiBagsSection5 is dependent on this
[C]: in function `SetPoint'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:995: in function `LayoutSections'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:1064: in function <Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:1040>
(tail call): ?
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:447: in function `RefreshContents'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:432: in function `ResumeUpdates'
Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:415: in function <Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:407>
[C]: in function `Show'
Interface\AddOns\AdiBags\core\Bags.lua:89: in function `Open'
Interface\AddOns\AdiBags\core\Bags.lua:209: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
...
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `SendMessage'
Interface\AddOns\AdiBags\core\Core.lua:447: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85>
(tail call): ?
[C]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>
(*temporary) = AdiBagsSection4 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 4
 count = 4
 total = 4
 name = "Consumable"
 category = "Consumable"
 height = 1
 key = "Consumable#Consumable"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = AdiBagsSection5 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 2
 count = 2
 total = 2
 name = "Armor"
 category = "Equipment"
 height = 1
 key = "Equipment#Armor"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPRIGHT"
(*temporary) = 10.5
(*temporary) = 0

**Comment by Cidan** [comment]
This is fixed in the next version.
