### ISSUE TITLE
Bags not updating when items are sold or deleted (etc.)

### ISSUE THREAD

**Issue by Wevah** [AdiAddons/AdiBags#920]
### Addon Version

v1.10.6

### World of Warcraft Version

Retail

### Describe the bug

When selling/trashing/whatever items, the bags don't update to reflect the items no longer being there.

### Steps to reproduce

1. Open AdiBags
2. Sell something
3. Item is sold, but bags don't update

Making the code added in https://github.com/AdiAddons/AdiBags/commit/a4ba03dbff7baa51eefd6b8eb771c26d0b04a96b apply to retail also (commenting out/removing the `if addon.isWrath` and its corresponding `end`) makes the bags update properly.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Fixed in 1.10.7
