### ISSUE TITLE
Adibags anchor gone

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [AdiAddons/AdiBags#922]
### Addon Version

1.10.7

### World of Warcraft Version

Retail

### Describe the bug

Can no longer lock the bag window to a specific location and is very annoying when you have your ui set up exactly how you want and you accidentally drag the window slightly

### Steps to reproduce

Right click at the top no longer shows or hides the anchor point.. very vexing change

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Tealc-1899** [comment]
It seems to have also effected the overall scaling of the bags and everything is larger than what it should be now.

**Comment by SpareSimian** [comment]
Duplicate of #890. See #891 for the new implementation under construction.
