### ISSUE TITLE
Bank doesn't open

### ISSUE THREAD

**Issue by Meilinn** [AdiAddons/AdiBags#925]
### Addon Version

v1.0.7

### World of Warcraft Version

Retail

### Describe the bug

When I open the bank for the first time after login the bags open very narrow and tall and half of them are out of the screen. When I open them a second time the bags open normal, but the bank doesn't open. The only fix is to reload, but again the bank opens tall out of screen the first time and I cannot open it again. 

### Steps to reproduce

Open the bank

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
It sounds like it may be opening completely off screen. When you first open it, drag it away from the edge. I'd also advise adjusting your bank's column width, the overall maximum bag height, and/or scale options in the configuration interface.

**Comment by Meilinn** [comment]
Thank you, I was opening outside the screen. I don't know why the first time I open it, it doesn't open with the setting I set, the second time it does. Thank you.

**Comment by Talyrius** [comment]
When it first opens, it doesn't know what's in your bank, so it doesn't know how to categorize everything. Subsequent openings for that session are sorted correctly. If possible, this is something we'd like to resolve in the future.
