### ISSUE TITLE
[Feature]: Hide Bag Bar

### ISSUE THREAD

**Issue by Denadazlir** [AdiAddons/AdiBags#927]
### Describe the feature

I'd really love it if AdiBags had the option to hide the Bag Bar because I use the addon GW2 UI and up until recently, the default blizzard bag bar has always been hidden by GW2. GW2 has it's own "bag bar" or button to open the bags when clicked. I don't need more than one button on screen to open the bag and would like to hide the bag bar. The default bag bar doesn't go with the GW2 appearance which is another reason I want to hide it. I'm also sure there would be other players out there who would like to have it hidden; whether it be because it would be one less item on screen or for reason like mine or something else.

### Describe the implementation

When I go to config, I should be able to enable/disable "Hide Bag Bar"

**Comment by Cidan** [comment]
Amusingly enough, I also use GW2 UI and noticed this today as well. I will fix this in the next version.

**Comment by SpareSimian** [comment]
If you're messing with the bag bar, I'd love an option to display the free space for non-reagent bags separately. I rarely fill my reagent bag but I'm always running out of space in the regular bags, and the display of the free space including the reagent bag leaves me "holding the bag" sometimes, so to speak.
