### ISSUE TITLE
Strange filter issue

### ISSUE THREAD

**Issue by N6REJ** [AdiAddons/AdiBags#930]
### Addon Version

1.10.7

### World of Warcraft Version

Retail

### Describe the bug

There is a strange filtering issue where its creating 2 filters named "Enchanting" and another called "Elemental"
There is already a pre-existing filter named "Enchanting" and "Elemental" so I don't understand why its not being reused.
I searched the entire addon folder and neither item shows up.
<img width="413" alt="image" src="https://user-images.githubusercontent.com/1850089/217673883-73a1ec62-b041-4cde-afd0-abc5670dae79.png">

### Steps to reproduce

have dragon shard of knowledge in bank.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
In the tooltip, look at the AH categories under "item information." You'll find that they differ and this is why they're kept separate.

**Comment by N6REJ** [comment]
please reopen this, I don't think your answer is quite correct.  Using the item shown there is no "ah category" since It can't be sold in the AH and even if it could why the duplicate filter names?  There should ever only be ONE filter by name xyz.
Why doesn't the ID &/OR name show up in adibags code?

**Comment by Cidan** [comment]
Hi there.

AdiBags does not maintain a list of items and categories, which is why you can't find it in the code. For each item, we call the WoW API and get its auction house category, which is how we filter items. Even items that can not be sold on the auction house have an item category for the auction house. We have known for at least a decade or so that Blizzard sometimes does put items in the wrong category.

Can you do me a favor, and show me a screenshot without the popup that shows both categories, then show me the extended popup information for each item? That should be three screenshots total: one for the bag, and one for each item.

**Comment by N6REJ** [comment]
Hi and ty for responding.  I've only been playing wow a couple of years so there's ton's I don't know.
I already added the one I showed above to one of my categories https://github.com/N6REJ/AdiBags_Bears_Ultimate/blob/3d2819156d5d2be3f813d8069f135bd8ebd4c3fc/DF-db.lua#L585-L603

per @Talyrius I look at the item tooltip and discovered one of these is for legion the other for draenor.  I don't know how much that has to do with it.

![WoWScrnShot_020923_054504](https://user-images.githubusercontent.com/1850089/217804110-a280f3e6-411a-4b55-810a-04e442fa14e8.jpg)
![WoWScrnShot_020923_054502](https://user-images.githubusercontent.com/1850089/217804120-aff73de7-2c6e-490d-9c93-179c633b8bd1.jpg)
![WoWScrnShot_020923_054443](https://user-images.githubusercontent.com/1850089/217804123-75e572e7-2b5c-4374-ba79-e52e04ac67eb.jpg)


My addon for enchanting is https://github.com/N6REJ/Adibags_Bears_Enchanting.
Elemental items are used by so many classes I put them in a "DF-Global" file that is shared by all my adibag addons.
I'm not going to pretend my code might not have errors.  I've done my best to check for pre-existing filters and such.

Thanks for taking the time.

**Comment by Talyrius** [comment]
To see how classifications are obtained, please see [GetItemInfo](https://wowpedia.fandom.com/wiki/API_GetItemInfo).

For example, using the items you've referenced above:
```
/run local _, itemLink, _, _, _, itemType, itemSubType = GetItemInfo(191784); print(format("%s:\nitemType = %q\nitemSubType = %q", itemLink, itemType, itemSubType)) -- Dragon Shard of Knowledge
/run local _, itemLink, _, _, _, itemType, itemSubType = GetItemInfo(124124); print(format("%s:\nitemType = %q\nitemSubType = %q", itemLink, itemType, itemSubType)) -- Blood of Sargeras
/run local _, itemLink, _, _, _, itemType, itemSubType = GetItemInfo(190326); print(format("%s:\nitemType = %q\nitemSubType = %q", itemLink, itemType, itemSubType)) -- Rousing Air
/run local _, itemLink, _, _, _, itemType, itemSubType = GetItemInfo(109693); print(format("%s:\nitemType = %q\nitemSubType = %q", itemLink, itemType, itemSubType)) -- Draenic Dust
```

```
[Dragon Shard of Knowledge]:
  itemType = "Tradeskill"
  itemSubType = "Elemental"
[Blood of Sargeras]:
  itemType = "Tradeskill"
  itemSubType = "Elemental"
[Rousing Air]:
  itemType = "Tradeskill"
  itemSubType = "Elemental"
[Draenic Dust]:
  itemType = "Tradeskill"
  itemSubType = "Enchanting"
```

Yes, sometimes Blizzard miscategorizes or subcategorizes items with the same name under separate categories. However, that doesn't appear to be what's at play here.

It would have been helpful context to add that you were using custom filters in addition to those toggleable from the "item category" options. AdiBags places these items into sections named `"itemType#itemSubType"` or, in the case of the above examples, `"Tradeskill#Elemental"` and `"Tradeskill#Enchanting"`.
