### ISSUE TITLE
Item in wrong category?

### ISSUE THREAD

**Issue by N6REJ** [AdiAddons/AdiBags#931]
### Addon Version

1.10.7

### World of Warcraft Version

Retail

### Describe the bug

Glimmer of Fire ( I assume all glimmers ) are falling under miscellaneous instead of "Disenchant"
![WoWScrnShot_020923_171347](https://user-images.githubusercontent.com/1850089/217961131-8f9bc84a-41c2-49e3-9979-9221174a4535.jpg)

### Steps to reproduce

check bag for glimmer of fire

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
AdiBags gets its item categories from the Blizzard API, and we do not have any way to change this. Blizzard has, for whatever reason, categorized this item as miscellaneous.
