### ISSUE TITLE
Lost my bag

### ISSUE THREAD

**Issue by Hexan666** [AdiAddons/AdiBags#932]
### Addon Version

1.10.7

### World of Warcraft Version

Retail

### Describe the bug

On some of my chars the adibags window is missing. I think this has something to do with the anchors not being usable. Is there a command to reset or recenter the bags. Thank you!

### Steps to reproduce

Open bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Wevah** [comment]
Happened to me too, once. I had to go into the saved variables file for AdiBags and manually change the position.
