### ISSUE TITLE
[Feature]: Grey/White gear as equipment category

### ISSUE THREAD

**Issue by Duranna144** [AdiAddons/AdiBags#933]
### Describe the feature

With 10.0.5 adding white and grey gear to transmog, they have slightly more value than normal junk. If possible, I would like to have an option to sort all white/grey equipment into a separate category so they are not grouped with junk. If it would not be possible to have white/grey equipment in its own category, to have them group with equipment.

### Describe the implementation

When going into config, in the Junk screen, have a third category option as "Equipment is not junk" or "Separate low quality equipment". This would then add another category for filtering of low quality gear OR would would put low quality equipment into the normal equipment category (whichever could be done).

**Comment by SpareSimian** [comment]
Interesting point. I use junk cloth gloves enchanted with +fishing on my toons that are still leveling fishing. When they cap fishing, they pass the gloves to an alt. I just noticed this week that they'd gone soulbound!
