### ISSUE TITLE
Forced reagents labels

### ISSUE THREAD

**Issue by gitHabbe** [AdiAddons/AdiBags#936]
### Addon Version

v1.10.7

### World of Warcraft Version

Wrath

### Describe the bug

The items in the first bag slot in the bank are always marked with "Re" for reagent. Even tho no settings enabled or disabled this kind of behavior. Bags used are normal ones, such as Traveler's, Mooncloth, Panther Hide, and Frostweave bags.

Freshly deleted settings (saved variables)

### Steps to reproduce

1. Open bank
2. Have "Bag type" enabled (enabled by default)

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Stidnoob** [comment]
I have the same bug on Classic Era Hardcore, but there is no reagent bank on era.
AdiBags-v1.10.21

The first bag slot unlocked, gives the "Re" flag on all the slots associated with it empty or not.
