### ISSUE TITLE
Changes to money amount keeps resizing the window

### ISSUE THREAD

**Issue by milan-stojanovic** [AdiAddons/AdiBags#938]
### Addon Version

v1.10.7

### World of Warcraft Version

Retail

### Describe the bug

Whenever you are at a vendor and selling items from your bag, as your money amount keeps changing, it keeps changing the width of the bag and can cause you to miss-click items (for example if you're spam selling a stack of items). GIF example below:

![resize-bug](https://user-images.githubusercontent.com/10252583/222988002-e5bc1506-889f-46ff-958a-2bbd7c946def.gif)

### Steps to reproduce

1. Make sure you have a stack of something to sell to vendor
2. Go to a nearby vendor
3. Start selling the items in the bag and pay attention to the width of the bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Bronski** [comment]
It seems to happen whenever I'm selling a bunch of items from the recent section, say after a transmog run. It's always disconcerting and makes me think I may have sold something by accident. Also, I lose my place.

I would an option to only resize on-open or something.

Thanks.
