### ISSUE TITLE
Adibads error 

### ISSUE THREAD

**Issue by MilchoThePrince** [AdiAddons/AdiBags#940]
### Addon Version

10.00.7

### World of Warcraft Version

Retail

### Describe the bug

i open bag it show normal when i install adibags after error 

### Steps to reproduce

cannot open it 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Can you please provide a stack track or some sort of description as to what you're seeing?
