### ISSUE TITLE
Cant Open Bags

### ISSUE THREAD

**Issue by sizeablerainbow** [AdiAddons/AdiBags#941]
### Addon Version

AdiBags-v1.10.7.zip

### World of Warcraft Version

Retail

### Describe the bug

when pressing B hotkey to open bags just doesn't open, disabled all addons except list below

Addons enabled

Adibags
Adibags configuration
BugGrabber
Bugsack

when trying to open bag i get this error from bugsack

1x AdiBags/core/Hooks.lua:56: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@AdiBags/core/Hooks.lua"]:56: in function `(for generator)'
[string "@AdiBags/core/Hooks.lua"]:96: in function <AdiBags/core/Hooks.lua:86>
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
maxContainer = 4
id = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
hookedBags = <table> {
}
GetContainerNumSlots = nil

### Steps to reproduce

happens when i launch the game with all addons or just those enabled 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by xulander20** [comment]
I have the same problem and error.

**Comment by Cidan** [comment]
Is everyone who has this issue playing on official Blizzard servers?

**Comment by stingah** [comment]
I have the same problem, disabled all other addons and it does not open. I play on official servers (EU).

**Comment by Weirdei** [comment]
Same problem, but error is different

`Date: 2023-06-08 18:54:18
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/AdiBags/core/Utility.lua line 221:
   Usage: GetItemSubClassInfo(itemClassID, itemSubClassID)
Debug:
   [string "=[C]"]: GetItemSubClassInfo()
   [string "@Interface/AddOns/AdiBags/core/Utility.lua"]:221: in main chunk
Locals:
(*temporary) = nil
(*temporary) = 0

AddOns:
  Swatter, v9.1.BETA.5.12 (OneMawTime)
  ACU, v
  AddOnSkins, v4.68
  AdiBags, vBuild 17
  ElvUI, v13.33
  ElvUILibraries, v13.33
  BlizRuntimeLib_ruRU v10.1.0.100100 <none>
  (ck=ae)

`

**Comment by Weirdei** [comment]
Now I am started to geting same error

Date: 2023-06-14 11:03:29
ID: 9
Error occured in: Global
Count: 1
Message: Interface/AddOns/AdiBags/core/Hooks.lua line 78:
   attempt to call upvalue 'GetContainerNumSlots' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:78: GetContainerFrame()
   [string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:174: OpenBackpack()
   [string "@Interface/AddOns/AdiBags/core/Hooks.lua"]:204:
      Interface/AddOns/AdiBags/core/Hooks.lua:195
   [string "=(tail call)"]: ?
   [string "TOGGLEBACKPACK"]:1:
      [string "TOGGLEBACKPACK"]:1
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v9.1.BETA.5.12 (OneMawTime)
  ACU, v
  AddOnSkins, v4.68
  AdiBags, vBuild 17
  AdiBagsDFCrafting, vv2.2.1
  AdiBagsDragonflight, v2.3.12
  AdiBagsHearthstones, v2.10
  Auctionator, v10.1.6
  BigWigs, vv284.1
  Details, v#Details.20230520.11023.151
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v13.33
  ElvUIEnhancedCursorTooltip, v1.0
  ElvUILibraries, v13.33
  ElvUIWindTools, v3.32
  GTFO, v5.3.1
  HidingBar, vv10.1.0
  Informant, v9.1.BETA.5.12 (OneMawTime)
  InteractiveWormholes, v100100.37-Release
  MRT, v4740
  MythicDungeonTools, v4.0.4.4
  NameplateAuras, v100100.1-release
  NameplateCooldowns, v100100.1-release
  OmniCD, v10.0.2.2741
  Plater, vPlater-v560.4-Retail
  ProfessionShoppingList, vv10.1.0-008
  RaiderIO, v10.1.0 (v202306112115)
  RaiderIODBEUF, v
  RaiderIODBEUM, v
  RaiderIODBEUR, v
  RCLootCouncil, v3.8.1
  SharedMediaNaowh, v
  Simulationcraft, v10.1.0-06
  SlideBar, v9.1.BETA.5.12 (OneMawTime)
  Stubby, v9.1.BETA.5.12 (OneMawTime)
  WagoAppCompanion, v1.0.0
  WarpDeplete, v2.4.0
  WeakAuras, v5.5.4
  BlizRuntimeLib_ruRU v10.1.0.100100 <none>
  (ck=4a8)

**Comment by Talyrius** [comment]
Through a [Discord conversation](https://discord.com/channels/1063213796845428876/1063218345614262282/1123915661538775081), this was determined to be caused by a conflicting installation of [ElvUI AdiBags](https://www.curseforge.com/wow/addons/elvui-adibags). Uninstall that and **_reinstall_** the official release of [AdiBags](https://www.curseforge.com/wow/addons/adibags) instead (the old installation must be overwritten as they share the same file directory structure).
