### ISSUE TITLE
Adibags Tooltip Error

### ISSUE THREAD

**Issue by jkemouse11** [AdiAddons/AdiBags#945]
### Addon Version

1.10.7

### World of Warcraft Version

Retail

### Describe the bug

I am not sure when the errors come, just going to the bank and AH and selling gear I noticed in bug sack I get:

381x SharedXML/Tooltip/TooltipUtil.lua:8: attempt to index local 'tbl' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags/core/Filters.lua"]:146: in function `Filter'
[string "@AdiBags/widgets/ContainerFrame.lua"]:849: in function `FilterSlot'
[string "@AdiBags/widgets/ContainerFrame.lua"]:883: in function `DispatchItem'
[string "@AdiBags/widgets/ContainerFrame.lua"]:1052: in function `RedispatchAllItems'
[string "@AdiBags/widgets/ContainerFrame.lua"]:1211: in function <AdiBags/widgets/ContainerFrame.lua:1194>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@AdiBags/core/Core.lua"]:476: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49>
[string "=(tail call)"]: ?

--------------------------------------------

The other Adibags addons I have:
AdiBags - Bound
AdiBags - Dragonflight (includes Crafting)
AdiBags - Low Level (Dragonflight Compatible)
AdiBags - Primordial Stones
AdiBags Bears Herbs

All are updated to game version 10.0.7 except Low Level which is 10.0.5 (and AdiBags which is also 10.0.5)

### Steps to reproduce

I am not sure when the errors come, just going to the bank and AH and selling gear

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by SpareSimian** [comment]
This is coming from the filter plugin. I'm trying to debug it but no luck so far. Details:

https://github.com/AvyAddons/AdiBags_Bound/issues/5
