### ISSUE TITLE
[Feature]: 10.1

### ISSUE THREAD

**Issue by Milky063** [AdiAddons/AdiBags#951]
### Describe the feature

Need a update for 10.1 please. Thank you very much. 

### Describe the implementation

Still having glitches with the addon.

**Comment by doublej42** [comment]
Will not let me open some of the new container types for 10.1.

**Comment by SpareSimian** [comment]
Which container types? A Wowhead link to one would be nice. Can you open them if you turn off AdiBags handling for your bags? Or if you just click the icon at top left of the AdiBags frame to switch it to raw bag view.

**Comment by doublej42** [comment]
I'm pretty sure it was https://www.wowhead.com/item=205423/shadowflame-residue-sack  and https://www.wowhead.com/item=205682/large-shadowflame-residue-sack

**Comment by Talyrius** [comment]
> Still having glitches with the addon.

That's not very helpful. What glitches?

**Comment by doublej42** [comment]
Seems to be stable now. Thank you.
