### ISSUE TITLE
Quick Filter Bar[Feature]: 

### ISSUE THREAD

**Issue by Sharandra** [AdiAddons/AdiBags#953]
### Describe the feature

Have quickfilters that you can toggle on and off for categories, that if toggled, only show items in bag for those categories, like gear, crafting mats, recipes, junk etc. 
Wouldn´t have to be the most detailed list of categories, just the most common would be enough.
For example if you click on the icon for gear, it would show only armor, weapon and jewellery (and gear sets if they are filtered) and the window would shrink to fit the selection. would make finding things/managing bagspace a bit less painfull (yes, I use the search option IF I know the name of the item I´m looking for). 
There is just too much stuff the game puts in our bags in recent expansions. Even with categories it´s become a bit too much, can´t see at a glance what I´m looking for anymore.

Been using AdiBags for years and love it, thanks for keeping it updated!

Additionally or alternatively, collapsible bag categories would be nice to have too.

### Describe the implementation

A bar at the top, between title and bags, with icons for a bunch of common categories, the icons would have a tooltip, if toggled the icon glows and only the items from the category in the bags are shown.

**Comment by Cidan** [comment]
This is already implemented -- click the "V" on the top right of the bag:

![image](https://user-images.githubusercontent.com/1133628/236699941-7abd1ada-8e7b-4f4e-b5df-a69a1e6d856e.png)

**Comment by Sharandra** [comment]
That´s not the same. Having to uncheck a ton of categories to show only items of one category to find one item and then having to check them all again and go through that whole process every time is a hassle. sorry.
