### ISSUE TITLE
Bank Bags not opening

### ISSUE THREAD

**Issue by Kirrawr** [AdiAddons/AdiBags#954]
### Addon Version

7.076.883

### World of Warcraft Version

Retail

### Describe the bug

After WoW 10.1 went live I dont recall going to my bank but yesterday on multiple toons I tried to open my bank tabs and nothing pops up?

### Steps to reproduce

clicking on the banker in Val

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
I can't reproduce this issue, and I also don't know what that addon version, `7.076.883` is, as it's not ours.

Are you sure you disabled all your other addons, as required before a bug report?
