### ISSUE TITLE
[Feature]: BoP/BoA/BoE labels on icons

### ISSUE THREAD

**Issue by KevinFelix** [AdiAddons/AdiBags#955]
### Describe the feature

Please add an option to display a little BoA, BoP, BoE label on items.

### Describe the implementation

Analogue to how ilvl is displayed top left, potentially add the option to display a "bound" status message bottom left. Ideally also make it so the bop, boa, boe labels can be used as a search parameter to highlight said items. Basically what https://www.curseforge.com/wow/addons/bagnon-iteminfo does for Bagnon, but for Adibags.

**Comment by SpareSimian** [comment]
Try this plugin. https://github.com/AvyAddons/AdiBags_Bound
