### ISSUE TITLE
Reagents Not Depositing

### ISSUE THREAD

**Issue by jeffguy77** [AdiAddons/AdiBags#96]
Only since the last update, the reagents are no longer depositing automatically or manually when you click the button.

**Comment by jeffguy77** [comment]
This was not AdiBags. It was actually the game and happened without any addons.

This fixed it for me:
us.battle.net/forums/en/wow/topic/14928982829

i had the same issue. 
opened bank, click reagent bank tab, click deposit all reagents and nothing happens. 

disabled all addons. tried again. no joy. 

i then took all sorting off of all bags (where you click on the bag icons and set the assignment to equipment/consumables\trade goods and took the ignore this bag option off as well. 

tried depositing all reagents.... and it worked. 

for me, it was the ignore this bag option that was stuffing me up. removed that, and the deposit all reagents button on the reagent bank worked.

**Comment by zarevucky** [comment]
Even if it's not AdiBags' fault, it might be helpful if it detected such settings on bags and provided a dialog with warning and ability to reset it.
