### ISSUE TITLE
Can't Open Reagent Bank: Dragonflight

### ISSUE THREAD

**Issue by Kaoskitty** [AdiAddons/AdiBags#960]
### Addon Version

1.10.9

### World of Warcraft Version

Retail

### Describe the bug

Just downloaded and installed the latest version (1.10.9) and now I can no longer open the bank reagent tab. The text in upper left corner changes from "Bank" to "Reagent Bank" but it's still only showing the items from the main bank. 

Error:

1x AdiBags/modules/TooltipInfo.lua:134: attempt to index local 'slotData' (a nil value)
[string "@AdiBags/modules/TooltipInfo.lua"]:134: in function <AdiBags/modules/TooltipInfo.lua:119>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML/ContainerFrame.lua"]:1498: in function `OnUpdate'
[string "@FrameXML/ContainerFrame.lua"]:1465: in function `OnEnter'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1460>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:335
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:394
 hooked = true
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 GetOptions = <function> defined @AdiBags/modules/TooltipInfo.lua:74
 name = "AdiBags_TooltipInfo"
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 hooks = <table> {
 }
 baseName = "AdiBags"
 OnTooltipSetItem = <function> defined @AdiBags/modules/TooltipInfo.lua:119
 RegisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 OnEnable = <function> defined @AdiBags/modules/TooltipInfo.lua:54
 OnInitialize = <function> defined @AdiBags/modules/TooltipInfo.lua:46
 IsHooked = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:492
 uiDesc = "Add more information in tooltips related to items in your bags."
 uiName = "Tooltip information"
 IsModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 SendMessage = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 UnhookAll = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:476
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 Unhook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:417
 RegisterEvent = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 SecureHookScript = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:409
 HookScript = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:365
 defaultModuleState = true
 IterateModules = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:433
 UnregisterAllEvents = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 RawHook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:312
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 moduleName = "TooltipInfo"
 UnregisterEvent = <function> defined @AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
}
tt = GameTooltip {
 0 = <userdata>
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:539
 SetVoidDepositItem = <function> defined =[C]:-1
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:53

### Steps to reproduce

Press "R" upper right to try to swap between bank and reagent bank

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Checking this now, please hold.

**Comment by Cidan** [comment]
Fixed in v1.10.10, which is going out right now. Thanks for catching this!
