### ISSUE TITLE
Opening Vault results in nil bagFamily

### ISSUE THREAD

**Issue by SpareSimian** [AdiAddons/AdiBags#962]
### Addon Version

v1.10.11

### World of Warcraft Version

Retail

### Describe the bug

```
Message: Interface/AddOns/AdiBags/modules/DataSource.lua line 140:
   table index is nil
...
Locals:
bag = -3
bagSize = 98
bagFree = 0
bagFamily = nil
```

Looks like GetContainerNumSlots is returning an unexpected value nil for the reagent bank when looking at the vault.

### Steps to reproduce

Open the guild vault. Repeatable. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Thanks, fixed in v1.10.12.
