### ISSUE TITLE
lua error new update today 5/22/2023

### ISSUE THREAD

**Issue by Milky063** [AdiAddons/AdiBags#967]
### Addon Version

AdiBags-v1.10.13.zip

### World of Warcraft Version

Retail

### Describe the bug

28x FrameXML/ContainerFrame.lua:1583: attempt to index a nil value
[string "@FrameXML/ContainerFrame.lua"]:1583: in function `GetBagID'
[string "@FrameXML/ContainerFrame.lua"]:1687: in function `UpdateCooldown'
[string "@AdiBags/widgets/ItemButton.lua"]:366: in function `Update'
[string "@AdiBags/widgets/ItemButton.lua"]:328: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@AdiBags/modules/NewItemTracking.lua"]:176: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49>
[string "=(tail call)"]: ?

Locals:
self = AdiBagsItemButton56 {
 0 = <userdata>
 OnLeave = <function> defined @FrameXML/ContainerFrame.lua:1472
 SetItem = <function> defined @FrameXML/ItemButtonTemplate.lua:544
 IconOverlay = Texture {
 }
 SetAlpha = <function> defined @FrameXML/ItemButtonTemplate.lua:631
 UpdateCooldown = <function> defined @FrameXML/ContainerFrame.lua:1683
 showMatchHighlight = true
 OnDragStart = <function> defined @FrameXML/ContainerFrame.lua:1570
 OnReceiveDrag = <function> defined @FrameXML/ContainerFrame.lua:1574
 icon = AdiBagsItemButton56IconTexture {
 }
 itemId = 194898
 UpdateTooltip = <function> defined @FrameXML/ContainerFrame.lua:1483
 SetReadable = <function> defined @FrameXML/ContainerFrame.lua:1675
 CheckUpdateTooltip = <function> defined @FrameXML/ContainerFrame.lua:1699
 UpdateNewItem = <function> defined @FrameXML/ContainerFrame.lua:1621
 IsReadable = <function> defined @FrameXML/ContainerFrame.lua:1679
 count = 1
 UpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:450
 SetItemButtonCount = <function> defined @FrameXML/ItemButtonTemplate.lua:614
 SetItemInternal = <function> defined @FrameXML/ItemButtonTemplate.lua:549
 UpdateCraftedProfessionsQualityShown = <function> defined @FrameXML/ItemButtonTemplate.lua:461
 HighlightTexture = Texture {
 }
 bagFamily = 0
 PostOnShow = <function> defined @FrameXML/ItemButtonTemplate.lua:414
 UpdateItemContextOverlayTextures = <function> defined @FrameXML/ItemButtonTemplate.lua:499
 texture = 4636980
 SetItemSource = <function> defined @FrameXML/ItemButtonTemplate.lua:528
 itemLink = "|cffa335ee|Hitem:194898:6643:::::::70:257::13:9:8836:8840:8902:9405:8791:9376:8913:8960:9366:9:28:2164:29:40:30:36:38:8:40:676:48:194578:49:204697:50:198258:51:204440::::Player-60-0E61B4BD:|h[Illuminating Pillar of the Isles |A:Professions-ChatIcon-Quality-Tier5:17:17::1|a]|h|r"
 IconQuestTexture = AdiBagsItemButton56IconQuestTexture {
 }
 hasItem = 1
 EmptySlotTextureFile = "Interface\BUTTONS\UI-EmptySlot"
 SetBagID = <function> defined @FrameXML/ContainerFrame.lua:1578
 IsExtended = <function> defined @FrameXML/ContainerFrame.lua:1713
 UpdateItemContextOverlay = <function> defined @FrameXML/ItemButtonTemplate.lua:488
 CheckForTutorials = <function> defined @FrameXML/ContainerFrame.lua:1742
 PushedTexture = Texture {
 }
 itemContextMatchResult = 3
 filterName = "Gear manager item sets"
 emptyBackgroundAtlas = "bags-item-slot64"
 ExtendedSlot = Texture {
 }
 Count = AdiBagsItemButton56Count {
 }
 isProfessionItem = false
 SetItemButtonAnchorPoint = <function> defined @FrameXML/ItemButtonTemplate.lua:618
 searchOverlay = AdiBagsItemButton56SearchOverlay {
 }
 GetItemLocation = <function> defined @FrameXML/ItemButtonTemplate.lua:610
 bag = 0
 IconOverlay2 = Texture {
 }
 OnModifiedClick = <function> defined @FrameXML/ContainerFrame.lua:1529
 JunkIcon = Texture {
 }
 slot = 5
 OnItemContextChanged = <function> defined @FrameXML/ItemButtonTemplate.lua:410
 UpdateExtended = <function> defined @FrameXML/ContainerFrame.lua:1717
 GetDebugReportInfo = <function> defined @FrameXML/ContainerFrame.lua:1221
 UpdateJunkItem = <function> defined @FrameXML/ContainerFrame.lua:1653
 HasItem = <function> defined @FrameXML/ContainerFrame.lua:1671
 OnClick = <function> defined @FrameXML/ContainerFrame.lua:1442
 IconTexture = AdiBagsItemButton56IconTexture {
 }
 timeSinceUpgradeCheck = 0
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 NormalTexture = AdiBagsItemButton56NormalTexture {
 }
 SetItemButtonScale = <function> defined @FrameXML/ItemButtonTemplate.lua:623
 dirty = false
 isCraftedItem = false
 PostOnHide = <function> defined @FrameXML/ItemButtonTemplate.lua:423
 UpgradeIcon = Texture {
 }
 BattlepayItemTexture = Texture {
 }
 NewItemTex

### Steps to reproduce

I was just using blizzards standard Equipment manager to switch gears and this error started to happen. This all started with the latest update. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Can you show me what your stacking settings are like? For example:

![image](https://github.com/AdiAddons/AdiBags/assets/1133628/3deea964-7d75-476c-b921-561b51c6ef3b)

**Comment by Milky063** [comment]
give me 20 mins at dinner right now 👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Milky063** [comment]
[cid:021b8fba-ef31-49f3-a413-b74bc2b62e65]
________________________________

**Comment by Marvin10193** [comment]
![image](https://github.com/AdiAddons/AdiBags/assets/84191617/0375513c-8251-4761-9713-8350d29c37f0)

These are my settings and im seeing a similiar/same lua error. 

15x FrameXML/ContainerFrame.lua:1583: attempt to index a nil value
[string "@FrameXML/ContainerFrame.lua"]:1583: in function `GetBagID'
[string "@FrameXML/ContainerFrame.lua"]:1687: in function `UpdateCooldown'
[string "@AdiBags/widgets/ItemButton.lua"]:366: in function `Update'
[string "@AdiBags/widgets/ItemButton.lua"]:328: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49>
[string "=(tail call)"]: ?

Locals:
self = AdiBagsItemButton16 {
 0 = <userdata>
 OnLeave = <function> defined @FrameXML/ContainerFrame.lua:1472
 SetItem = <function> defined @FrameXML/ItemButtonTemplate.lua:544
 IconOverlay = Texture {
 }
 SetAlpha = <function> defined @FrameXML/ItemButtonTemplate.lua:631
 UpdateCooldown = <function> defined @FrameXML/ContainerFrame.lua:1683
 showMatchHighlight = true
 OnDragStart = <function> defined @FrameXML/ContainerFrame.lua:1570
 OnReceiveDrag = <function> defined @FrameXML/ContainerFrame.lua:1574
 icon = AdiBagsItemButton16IconTexture {
 }
 itemId = 185053
 UpdateTooltip = <function> defined @FrameXML/ContainerFrame.lua:1483
 SetReadable = <function> defined @FrameXML/ContainerFrame.lua:1675
 CheckUpdateTooltip = <function> defined @FrameXML/ContainerFrame.lua:1699
 UpdateNewItem = <function> defined @FrameXML/ContainerFrame.lua:1621
 IsReadable = <function> defined @FrameXML/ContainerFrame.lua:1679
 count = 1
 UpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:450
 SetItemButtonCount = <function> defined @FrameXML/ItemButtonTemplate.lua:614
 SetItemInternal = <function> defined @FrameXML/ItemButtonTemplate.lua:549
 UpdateCraftedProfessionsQualityShown = <function> defined @FrameXML/ItemButtonTemplate.lua:461
 HighlightTexture = Texture {
 }
 PostOnShow = <function> defined @FrameXML/ItemButtonTemplate.lua:414
 UpdateItemContextOverlayTextures = <function> defined @FrameXML/ItemButtonTemplate.lua:499
 SetItemSource = <function> defined @FrameXML/ItemButtonTemplate.lua:528
 texture = 132243
 IconQuestTexture = AdiBagsItemButton16IconQuestTexture {
 }
 hasItem = 1
 EmptySlotTextureFile = "Interface\BUTTONS\UI-EmptySlot"
 SetBagID = <function> defined @FrameXML/ContainerFrame.lua:1578
 IsExtended = <function> defined @FrameXML/ContainerFrame.lua:1713
 itemLink = "|cff1eff00|Hitem:185053::::::::70:1467:::::::::|h[Kodo Soul]|h|r"
 UpdateItemContextOverlay = <function> defined @FrameXML/ItemButtonTemplate.lua:488
 CheckForTutorials = <function> defined @FrameXML/ContainerFrame.lua:1742
 PushedTexture = Texture {
 }
 itemContextMatchResult = 3
 filterName = "Equipment"
 emptyBackgroundAtlas = "bags-item-slot64"
 ExtendedSlot = Texture {
 }
 Count = AdiBagsItemButton16Count {
 }
 isProfessionItem = false
 SetItemButtonAnchorPoint = <function> defined @FrameXML/ItemButtonTemplate.lua:618
 searchOverlay = AdiBagsItemButton16SearchOverlay {
 }
 bagFamily = 0
 GetItemLocation = <function> defined @FrameXML/ItemButtonTemplate.lua:610
 bag = 2
 IconOverlay2 = Texture {
 }
 OnModifiedClick = <function> defined @FrameXML/ContainerFrame.lua:1529
 JunkIcon = Texture {
 }
 slot = 14
 OnItemContextChanged = <function> defined @FrameXML/ItemButtonTemplate.lua:410
 UpdateExtended = <function> defined @FrameXML/ContainerFrame.lua:1717
 GetDebugReportInfo = <function> defined @FrameXML/ContainerFrame.lua:1221
 UpdateJunkItem = <function> defined @FrameXML/ContainerFrame.lua:1653
 HasItem = <function> defined @FrameXML/ContainerFrame.lua:1671
 OnClick = <function> defined @FrameXML/ContainerFrame.lua:1442
 IconTexture = AdiBagsItemButton16IconTexture {
 }
 timeSinceUpgradeCheck = 0
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 NormalTexture = AdiBagsItemButton16NormalTexture {
 }
 SetItemButtonScale = <function> defined @FrameXML/ItemButtonTemplate.lua:623
 dirty = false
 isCraftedItem = false
 PostOnHide = <function> defined @FrameXML/ItemButtonTemplate.lua:423
 UpgradeIcon = Texture {
 }
 BattlepayItemTexture = Texture {
 }
 NewItemTexture = Texture {
 }
 flash = Texture {
 }
 Cooldown = AdiBagsItemButton16Cooldown {
 }
 IconBorder = Texture {
 }
 OnUpdate = <function> defined @FrameXML/ContainerFrame.lua:1483
 GetItemContextOverlayMode = <function

**Comment by salamisami** [comment]
Bump same issue

**Comment by Milky063** [comment]
Got this lua error today,

66x FrameXML/ContainerFrame.lua:1583: attempt to index a nil value
[string "@FrameXML/ContainerFrame.lua"]:1583: in function `GetBagID'
[string "@FrameXML/ContainerFrame.lua"]:1687: in function `UpdateCooldown'
[string "@AdiBags/widgets/ItemButton.lua"]:366: in function `Update'
[string "@AdiBags/widgets/ItemButton.lua"]:328: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@AdiBags/modules/NewItemTracking.lua"]:176: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49>
[string "=(tail call)"]: ?

Locals:
self = AdiBagsItemButton56 {
 0 = <userdata>
 OnLeave = <function> defined @FrameXML/ContainerFrame.lua:1472
 SetItem = <function> defined @FrameXML/ItemButtonTemplate.lua:544
 IconOverlay = Texture {
 }
 SetAlpha = <function> defined @FrameXML/ItemButtonTemplate.lua:631
 UpdateCooldown = <function> defined @FrameXML/ContainerFrame.lua:1683
 showMatchHighlight = true
 OnDragStart = <function> defined @FrameXML/ContainerFrame.lua:1570
 OnReceiveDrag = <function> defined @FrameXML/ContainerFrame.lua:1574
 icon = AdiBagsItemButton56IconTexture {
 }
 itemId = 194898
 UpdateTooltip = <function> defined @FrameXML/ContainerFrame.lua:1483
 SetReadable = <function> defined @FrameXML/ContainerFrame.lua:1675
 CheckUpdateTooltip = <function> defined @FrameXML/ContainerFrame.lua:1699
 UpdateNewItem = <function> defined @FrameXML/ContainerFrame.lua:1621
 IsReadable = <function> defined @FrameXML/ContainerFrame.lua:1679
 count = 1
 UpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:450
 SetItemButtonCount = <function> defined @FrameXML/ItemButtonTemplate.lua:614
 SetItemInternal = <function> defined @FrameXML/ItemButtonTemplate.lua:549
 UpdateCraftedProfessionsQualityShown = <function> defined @FrameXML/ItemButtonTemplate.lua:461
 HighlightTexture = Texture {
 }
 bagFamily = 0
 PostOnShow = <function> defined @FrameXML/ItemButtonTemplate.lua:414
 UpdateItemContextOverlayTextures = <function> defined @FrameXML/ItemButtonTemplate.lua:499
 texture = 4636980
 SetItemSource = <function> defined @FrameXML/ItemButtonTemplate.lua:528
 itemLink = "|cffa335ee|Hitem:194898:6643:::::::70:257::13:9:8836:8840:8902:9405:8791:9376:8913:8960:9366:9:28:2164:29:40:30:36:38:8:40:676:48:194578:49:204697:50:198258:51:204440::::Player-60-0E61B4BD:|h[Illuminating Pillar of the Isles |A:Professions-ChatIcon-Quality-Tier5:17:17::1|a]|h|r"
 IconQuestTexture = AdiBagsItemButton56IconQuestTexture {
 }
 hasItem = 1
 EmptySlotTextureFile = "Interface\BUTTONS\UI-EmptySlot"
 SetBagID = <function> defined @FrameXML/ContainerFrame.lua:1578
 IsExtended = <function> defined @FrameXML/ContainerFrame.lua:1713
 UpdateItemContextOverlay = <function> defined @FrameXML/ItemButtonTemplate.lua:488
 CheckForTutorials = <function> defined @FrameXML/ContainerFrame.lua:1742
 PushedTexture = Texture {
 }
 itemContextMatchResult = 3
 filterName = "Gear manager item sets"
 emptyBackgroundAtlas = "bags-item-slot64"
 ExtendedSlot = Texture {
 }
 Count = AdiBagsItemButton56Count {
 }
 isProfessionItem = false
 SetItemButtonAnchorPoint = <function> defined @FrameXML/ItemButtonTemplate.lua:618
 searchOverlay = AdiBagsItemButton56SearchOverlay {
 }
 GetItemLocation = <function> defined @FrameXML/ItemButtonTemplate.lua:610
 bag = 0
 IconOverlay2 = Texture {
 }
 OnModifiedClick = <function> defined @FrameXML/ContainerFrame.lua:1529
 JunkIcon = Texture {
 }
 slot = 5
 OnItemContextChanged = <function> defined @FrameXML/ItemButtonTemplate.lua:410
 UpdateExtended = <function> defined @FrameXML/ContainerFrame.lua:1717
 GetDebugReportInfo = <function> defined @FrameXML/ContainerFrame.lua:1221
 UpdateJunkItem = <function> defined @FrameXML/ContainerFrame.lua:1653
 HasItem = <function> defined @FrameXML/ContainerFrame.lua:1671
 OnClick = <function> defined @FrameXML/ContainerFrame.lua:1442
 IconTexture = AdiBagsItemButton56IconTexture {
 }
 timeSinceUpgradeCheck = 0
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 NormalTexture = AdiBagsItemButton56NormalTexture {
 }
 SetItemButtonScale = <function> defined @FrameXML/ItemButtonTemplate.lua:623
 dirty = false
 isCraftedItem = false
 PostOnHide = <function> defined @FrameXML/ItemButtonTemplate.lua:423
 UpgradeIcon = Texture {
 }
 BattlepayItemTexture = Texture {
 }
 NewItemTex

**Comment by Milky063** [comment]
![image](https://github.com/AdiAddons/AdiBags/assets/50210970/cab1f970-38d6-4e73-bd9c-b051d4be230c)
