### ISSUE TITLE
Config TOC out of date

### ISSUE THREAD

**Issue by cmleininger** [AdiAddons/AdiBags#97]
The AdiBags_Config.toc file is out of date. The game refuses to load the config interface, say it is out of date, even if you check "Load out of Date Addons". However, if you change the top line of the file to read ## Interface: 70000 instead of ## Interface: 60000, the config loads just fine and seems to work just fine also.

This was probably just an oversight but I imagine there are people who have tried to use this and given up, so it would be good to change the version on Curse and other addon sites.

**Comment by Talyrius** [comment]
This has already been fixed (f9db11f) in the [latest alpha](https://www.wowace.com/addons/adibags/files/).
