### ISSUE TITLE
error lua

### ISSUE THREAD

**Issue by GnomeTW** [AdiAddons/AdiBags#975]
### Addon Version

v1.10.17

### World of Warcraft Version

Retail

### Describe the bug

error report

1x [ADDON_ACTION_FORBIDDEN] 插件 'AdiBags' 嘗試調用保護功能 'SetTab()'。
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetTab'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:2486: in function `EJ_ContentTab_OnClick'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:464: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:310>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:715: in function `EncounterJournal_LoadUI'
[string "@FrameXML/UIParent.lua"]:1147: in function `ToggleEncounterJournal'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1162: in function <FrameXML/MainMenuBarMicroButtons.lua:1160>
[string "=[C]"]: ?

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}

### Steps to reproduce

This error occurs intermittently and usually happens when I have ADIBAG open while also opening other built-in interfaces.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by N6REJ** [comment]
can confirm... happens randomly with bug grabber and bug sack active but closed
```
2x [ADDON_ACTION_BLOCKED] AddOn 'AdiBags' tried to call the protected function 'Frame:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@SilverDragon_Overlay/pins.lua"]:30: in function `OnAcquired'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:201: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:158>
[string "=[C]"]: in function `AcquirePin'
[string "@SilverDragon_Overlay/worldmap.lua"]:52: in function `RefreshAllData'
[string "@SilverDragon_Overlay/worldmap.lua"]:190: in function `UpdateWorldMapIcons'
[string "@SilverDragon_Overlay/module.lua"]:201: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bears_Audio_Switcher/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...rs_Audio_Switcher/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/Misc/Loot.lua"]:119: in function <ElvUI/Core/Modules/Misc/Loot.lua:117>
[string "=[C]"]: in function `Hide'
[string "@ElvUI/Core/Modules/Misc/Loot.lua"]:214: in function `?'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bears_Audio_Switcher/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...rs_Audio_Switcher/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```
