### ISSUE TITLE
AdiBags won't open bank window, only bags

### ISSUE THREAD

**Issue by rickvdwetering** [AdiAddons/AdiBags#976]
### Addon Version

v1.10.17

### World of Warcraft Version

Retail

### Describe the bug

The bank window will not open.

BugSack Error message:
string "=(tail call)"]: ?
[string "@AdiBags/core/OO.lua"]:60: in function <AdiBags/core/OO.lua:52>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@AdiBags/core/Bags.lua"]:136: in function `GetFrame'
[string "@AdiBags/core/Bags.lua"]:90: in function `Open'
[string "@AdiBags/core/Bags.lua"]:275: in function `?'
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@AdiBags/core/Core.lua"]:447: in function `?'
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:49>
[string "=(tail call)"]: ?

Locals:
(*temporary) = <function> defined =[C]:-1

### Steps to reproduce

Open the bank window. It doesn't open.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Talyrius** [comment]
> * [x]  I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

This isn't the case as your error specifically calls out the use of callback handler from `ElvUI_Libraries`.

**Comment by rickvdwetering** [comment]
Well then adibags is calling it itself as I'm a 100% certain all addons
were disabled.

**Comment by Cidan** [comment]
Hi there,

You are misinterpreting what a stack trace is and how the World of Warcraft addon system works. The folder, in this case `ElvUI_Libraries` has to be loaded by the WoW client in order for it to show up in the stack trace. The WoW client explicitly has no way to view or load code from other addon folders outside of the addon's own folder.

This stack trace does show that you have `ElvUI_Libraries` enabled -- this is not an opinion, it's a fact that is irrefutable.

No worries though! Can you double check and retry with that addon disabled?

Thanks :)

**Comment by rickvdwetering** [comment]
I am pretty sure I unchecked all addons including the Elvui libraries,
maybe it still loads outside of the addons list, I don't know. Maybe
Adibags has some hardcoded call to it in the code. I will check again today
but I'm not expecting a different result.

**Comment by rickvdwetering** [comment]
You closed it? Wtf, I said I'd get back to it, but no, just ignore ppl
trying to fix your broken ass addon. It's nothing to do with elvui. You
need to check your broken code.
