### ISSUE TITLE
Currency Value Bug

### ISSUE THREAD

**Issue by Squimbert** [AdiAddons/AdiBags#979]
### Addon Version

v1.10.17

### World of Warcraft Version

Retail

### Describe the bug

When tracking conquest with the currency plugin, spending or gaining conquest (in my test case by buying a conquest item from vendor then selling it back) causes the value of conquest pinned on the bags to jump to incredibly high and inaccurate numbers. it resets to the real value when i open the blizzard currency tab. 

My test example:

i have 1115 conquest. i purchase an item from the vendor for 450 conquest. the value of conquest on my bags now says 66,500. i sell it back and now the value of conquest on my bags says 111,500.  i open the blizzard currency tab and it resets my conquest value on the bags to the true value of 1115.

### Steps to reproduce

buy any conquest item from the vendor while tracking conquest on the adibags currency plugin.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Squimbert** [comment]
i guess the addon is mostly abandoned. rip

**Comment by Cidan** [comment]
It's not abandoned -- I've been on medical leave and haven't been able to
work on this for a while. Expect some updates soon.
