### ISSUE TITLE
Item icons incorrect when replacing previous item / items not appearing in bag

### ISSUE THREAD

**Issue by VikingSven82** [AdiAddons/AdiBags#98]
2 bugs:
If you have your bag open, and you add an item to the bag that replaces another item, the new item has the icon for the old item.
Example:
Solve an archaeology artifact, using a keystone - the artifact goes into your bag in the spot the keystone was in, and has the icon for the keystone. 

Sometimes an item just doesn't appear in the bag, I've noticed it most when doing archaeology recently. The only way to get it to appear is to sort the bag, then close and re-open.

**Comment by Cidan** [comment]
This has been fixed in the latest beta.
