### ISSUE TITLE
Adibags - error pops up when opening bags on retail

### ISSUE THREAD

**Issue by putladin** [AdiAddons/AdiBags#980]
### Addon Version

v1.10.17

### World of Warcraft Version

Retail

### Describe the bug

When oopening the bag the following error pops up:

245x .../AdiBags_PriorExpansions/AdiBags_PriorExpansions.lua:272: attempt to call global 'GetContainerItemEquipmentSetInfo' (a nil value)
[string "=(tail call)"]: ?
[string "@AdiBags/core/Filters.lua"]:148: in function `Filter'
[string "@AdiBags/widgets/ContainerFrame.lua"]:848: in function `FilterSlot'
[string "@AdiBags/widgets/ContainerFrame.lua"]:882: in function `DispatchItem'
[string "@AdiBags/widgets/ContainerFrame.lua"]:1042: in function `RedispatchAllItems'
[string "@AdiBags/widgets/ContainerFrame.lua"]:1201: in function `FullUpdate'
[string "@AdiBags/widgets/ContainerFrame.lua"]:642: in function <AdiBags/widgets/ContainerFrame.lua:628>
[string "=[C]"]: ?
[string "@AdiBags/core/Utility.lua"]:108: in function <AdiBags/core/Utility.lua:100>
[string "@AdiBags/widgets/LayeredRegion.lua"]:119: in function <AdiBags/widgets/LayeredRegion.lua:108>

Locals:
(*temporary) = 0.013000
(*temporary) = <function> defined =[C]:-1

This makes the game lag.

### Steps to reproduce

Not sure, that you can. But I have reinstallled the addon multiple times, which did not fix the issue.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
This bug is caused by AdiBags_PriorExpansions, which is not written by the AdiBags team. In the future when submitting bugs, please be sure to follow the instructions and disable all addons except AdiBags.

Thanks!

**Comment by putladin** [comment]
Hello,

Thank you for the swift response.

Did not realise, that it is a diferrent addon.

Regards,
Mira
