### ISSUE TITLE
Frame:RegisterEvent(): Frame:RegisterEvent(): Attempt to register unknown event "CURSOR_UPDATE"

### ISSUE THREAD

**Issue by d4kir92** [AdiAddons/AdiBags#983]
### Addon Version

1.10.19

### World of Warcraft Version

Classic PTR

### Describe the bug

1x Frame:RegisterEvent(): Frame:RegisterEvent(): Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@AdiBags/core/EventHandlers.lua"]:45: in function `OnUsed'
[string "@AdiBags/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:66: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49>
[string "=(tail call)"]: ?

### Steps to reproduce

log into "classic era ptr"

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by aglarcz** [comment]
Can confirm, also hapenning to  me.
