### ISSUE TITLE
wrong item displayed

### ISSUE THREAD

**Issue by waytoomuchgaming** [AdiAddons/AdiBags#986]
### Addon Version

1.10.19

### World of Warcraft Version

Classic

### Describe the bug

The bag display non existent items, like copper ore and copper bars, after i transformed them in bronze bars. Closing and reopening bags don't make the bug disapear. Reloading UI neither. Only loging out makes the bug disapear.

### Steps to reproduce

No idea, it just happen from time to time.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by waytoomuchgaming** [comment]
image of the problem : https://imgur.com/a/vz9t2YJ

**Comment by SpareSimian** [comment]
Just to debug the problem, try switching to raw bag view and also disabling AdiBags to see if the underlying Blizzard bag code is doing the same thing.

**Comment by waytoomuchgaming** [comment]
disabling adibag make the problem disapear, the blizzard bag don't have the bug.
