### ISSUE TITLE
[Feature]: ilevel text options

### ISSUE THREAD

**Issue by nancikennedy** [AdiAddons/AdiBags#988]
### Describe the feature

I would like to be able to make the level text on icons smaller, and change with corner it's anchored to.

### Describe the implementation

In the Item Level options, I would like a checkbox to make the text smaller and a pop menu to choose which corner to pin the text to.

**Comment by nancikennedy** [comment]
I really like [Simple Item Level](https://www.curseforge.com/wow/addons/simple-item-level) the way that Simple Item Level does this.

**Comment by Talyrius** [comment]
See #303 & #496.
