### ISSUE TITLE
ContainerFrame.lua error

### ISSUE THREAD

**Issue by FlesHBoX** [AdiAddons/AdiBags#99]
Since the last update, I've had two characters so far who have experienced this issue.  As far as I can tell it seems to be associated with reagents possibly.  This just happened on my JC after crafting two gems;
http://imgur.com/tfPt0Pi

And here is my enchanter's reagent bank, displaying the same visual issue;
http://imgur.com/3ZQAlsm

In both cases, when opening my bags (or reagent bank in the case of my enchanter) the following error is output ;

Error in AdiBags: Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:1008: AdiBagsSection13:SetPoint(): AdiBagsSection7 is dependent on this -- details: [Error 0000021C5A996B20]

**Comment by Cidan** [comment]
This is a known issue that I thought I had resolved in the dev version, but I absolutely just ran into it again last night. I'll take a look at it some more, but if I can't fix the current iteration of the code, I'll likely rewrite this part of AdiBags from scratch.

**Comment by Cidan** [comment]
Also, you can prevent this bug from happening for the moment by disabling compact layous.

**Comment by FlesHBoX** [comment]
Aha! Thanks for the tip to prevent it.

**Comment by als30334** [comment]
yup I got that error on my NE priest like 5 times. I was coming here to report the bug, but looks like I don't have to.

**Comment by Talyrius** [comment]
Is this still occurring?
