### ISSUE TITLE
[Feature]: Blacklist for excluding user-specified reagents from "Deposit All Reagents"

### ISSUE THREAD

**Issue by burntorangejedi** [AdiAddons/AdiBags#990]
### Describe the feature

WOW is really inconsistent in how it treats reagents - sometimes you can spend them if they're in your bank, and sometimes you can not. We need a way to create a blacklist for reagents so that when we click the "Deposit All Reagents" button, we don't have to go back into our bank and pull out our crests and fragments.

### Describe the implementation

Add a new list parameter in the Options window that allows us to enter, by name or by ID, the items we want excluded from any request to "Deposit All Reagents". We'd need to see what items are specified in that list and be able to add/remove items as we see fit. If the item is on the list it should NOT be auto deposited in the bag when we click "Deposit All Reagents".

**Comment by Cidan** [comment]
Unfortunately, this is not possible. AdiBags does not implement this function, the WoW client does -- all we do is call it, and there is no way to instruct the client what to deposit and what not to.
