### ISSUE TITLE
error lua

### ISSUE THREAD

**Issue by Missratata** [AdiAddons/AdiBags#991]
### Addon Version

10.1.7

### World of Warcraft Version

Retail

### Describe the bug

I clicked on ESC, and this messenger kept popping up, even after I disabled the other addons in my game

28x AdiBags/core/Hooks.lua:56: attempt to call upvalue 'GetContainerNumSlots' (a nil value)
[string "@AdiBags/core/Hooks.lua"]:56: in function `(for generator)'
[string "@AdiBags/core/Hooks.lua"]:127: in function <AdiBags/core/Hooks.lua:119>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CloseAllBags'
[string "@FrameXML/UIParent.lua"]:3465: in function `CloseAllWindows'
[string "@FrameXML/UIParent.lua"]:1732: in function <FrameXML/UIParent.lua:1416>
[string "=[C]"]: ?

Locals:
maxContainer = 4
id = 0
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call upvalue 'GetContainerNumSlots' (a nil value)"
hookedBags = <table> {
}
GetContainerNumSlots = nil

### Steps to reproduce

I just clicked on ESC

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by SpareSimian** [comment]
What did you do _before_ you clicked on ESC? Did you just start the game and then hit it, or did you do other things?

**Comment by Missratata** [comment]
sorry for the late answer, but yeah I just started the game and hit it
