### ISSUE TITLE
10.2 Minor Error

### ISSUE THREAD

**Issue by Kyreaper** [AdiAddons/AdiBags#996]
### Addon Version

1.10.22

### World of Warcraft Version

Retail
Game Version: 10.2.0.52188, US, English 

### Describe the bug

When the "The War Within" module is selected & loaded the following error is thrown out:

34x AdiBags_ByExpansion_WarWithin/categories/reputation.lua:1 Error loading AdiBags_ByExpansion_WarWithin/categories/reputation.lua

~

Screenshot from BugGrabber / BugSack:
![11-25-2023 AdiBag TWW Module Error](https://github.com/AdiAddons/AdiBags/assets/12869693/ea02d0c6-e2a9-476e-b151-8c2603f58fa2)

### Steps to reproduce

Enable "The War Within" module, then load the game normally. I get the error whenever I login to a character with the TWW module enabled. 

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
That addon is not written by the AdiBags authors. Please reach out to the authors of that module.
